### ISSUE TITLE
Icon size is incorrect

### ISSUE THREAD

**Issue by OoguroxRyuuya** [lwouis/alt-tab-macos#2431] opened 2023-03-24 02:50 UTC
**Describe the bug**

Icon size is incorrect

**Screenshots / video**

![CleanShot 2023-03-24 at 10 51 28](https://user-images.githubusercontent.com/61595521/227411962-1f0322d9-94c2-429c-b3c9-cb0b1e6e583f.png)

**Steps to reproduce the bug**

1. CMD + TAB

**Your environment**

* AltTab version: 6.56.0
* macOS version: 13.2.1
* Other relevant info: e.g. using external keyboard, multiple monitors, etc

![CleanShot 2023-03-24 at 10 49 51](https://user-images.githubusercontent.com/61595521/227411791-30220af2-367a-4488-987b-a9b0a1f18ec0.png)

**Comment by lwouis** [comment] 2023-03-24 08:21
Duplicate of https://github.com/lwouis/alt-tab-macos/issues/1279

**Closed by lwouis** 2023-03-24 08:21 UTC
Labels: bug
