### ISSUE TITLE
Malposition of Controls shortcuts placeholder

### ISSUE THREAD

**Issue by jukrb0x** [lwouis/alt-tab-macos#828] opened 2021-02-17 16:53 UTC
**Describe the bug**
The position of shortcuts placeholder in the section _While open, press:_ are different in Shortcut 1 and Shortcut 2.
Check the video below.

**Screenshots / video**

https://user-images.githubusercontent.com/15688641/108237470-e6fd9e00-7182-11eb-8e5a-b4d78dbe1bc8.mp4

**Steps to reproduce the bug**

1. Go to AltTab Controls
2. Switch between Shortcut 1 and Shortcut 2
3. Observe the position of shortcuts placeholders in the section after _While open, press:_

**Comment by lwouis** [comment] 2021-02-17 17:34
Duplicate of https://github.com/lwouis/alt-tab-macos/issues/808

**Closed by lwouis** 2021-02-17 17:34 UTC
Labels: bug
