### ISSUE TITLE
emojis in title of window on alttab are all cut off

### ISSUE THREAD

**Issue by ComfortableMilk4454** [lwouis/alt-tab-macos#3329] opened 2024-04-28 16:29 UTC
**Describe the bug**
emojis in title of window on alttab are all cut off

**Screenshots / video**
<img width="434" alt="image" src="https://github.com/lwouis/alt-tab-macos/assets/43555540/4de18679-895c-42e4-92a1-375fd05c8476">

**Steps to reproduce the bug**

1. alt tab when you have a window open with an emoji in its name

**Your environment**

* AltTab version: 6.67.0
* macOS version: 14.4.1 (23E224)

**Comment by lwouis** [comment] 2024-04-28 18:36
Duplicate of https://github.com/lwouis/alt-tab-macos/issues/814

**Closed by lwouis** 2024-04-28 18:36 UTC
Labels: bug
