### ISSUE TITLE
Thumbnails with `Stage Manager` mode

### ISSUE THREAD

**Issue by lipa44** [lwouis/alt-tab-macos#2485] opened 2023-04-15 13:12 UTC
**Describe the bug**

When Stage Manager mode enabled _(which is new `MacOS` workspace mode)_, app thumbnails are looking weird

They're alike stage manager's app preview...

Is it possible to fix and make thumbnails for stage manager's apps plain like regular ones?

**Screenshots / video**

<img width="892" alt="Screenshot 2023-04-15 at 16 02 58" src="https://user-images.githubusercontent.com/82240296/232225463-5fe9ee5d-571e-4e68-9023-6ad4fe7c8da9.png">

<img width="175" alt="image" src="https://user-images.githubusercontent.com/82240296/232225519-9ea3af2e-8c56-40eb-a539-79f7d0b0a3bd.png">

**Steps to reproduce the bug**

1. Enable stage manager mode
2. Open AltTab window

**Your environment**

* AltTab version: 6.56.0
* macOS version: Ventura 13.2.1

**Comment by lwouis** [comment] 2023-04-15 16:22
Duplicate of https://github.com/lwouis/alt-tab-macos/issues/1731

**Closed by lwouis** 2023-04-15 16:22 UTC
Labels: bug
