### ISSUE TITLE
App icons sometimes shown at wrong size (layout issue)

### ISSUE THREAD

**Issue by phattrance** [lwouis/alt-tab-macos#1279] opened 2021-12-09 06:51 UTC
Hi, why does the ALTTAB iclons look small vs the other icons? This started to happen 2-3 releases ago and it really annoying. The icons gets smaller seems to be random and sometimes there are like 5 of 8 icons looking smaller etc

![IMG_7126](https://user-images.githubusercontent.com/5632780/145347932-d3e8ca5c-d8fc-44bc-a4fd-23b5435e7fbe.jpg)

![IMG_7127](https://user-images.githubusercontent.com/5632780/145348230-fe5053a4-acba-4c62-afd5-5d112a7f0351.jpg)

**Comment by lwouis** [comment] 2021-12-10 03:10
Yes, this is a layout issue that I've noticed as well sometimes when using customized Appearance preferences, as you are doing here (hiding screenshot, hiding title, etc).

Could you please share your preferences on that tab?

![image](https://user-images.githubusercontent.com/106195/145510842-6ede2f25-d8ec-434f-a09b-24d1cba3e6d1.png)

**Comment by phattrance** [comment] 2021-12-10 07:20
Here are my settings. The small icons seems to be random. sometimes they work fine, sometimes they are small.

![image](https://user-images.githubusercontent.com/5632780/145533570-e939346a-c941-4ed6-a62a-b3ad9824b320.png)

**Comment by phattrance** [comment] 2021-12-10 07:27
Any ideas on how to fix this? Its so annoying!

**Comment by lwouis** [comment] 2021-12-10 10:41
Well you could look into the layout code and share a PR which addresses the issue. That would be the best way to fix this of course.

As a workaround if you don't have time for the real fix, you could tweak your preferences in Appearance to slightly different values and see if it goes away.

i'll try your settings later on my laptop to see if i can reproduce with those, but i can't volunteer much time on this project these days. See the pinned ticket about me looking for someone to take over this project

**Comment by phattrance** [comment] 2021-12-10 20:01
yea, ive already tried tons of different combinations of settings to try to solve this, but they all seem to randomly get smaller somehow.  I would say that icons get smaller like 80% of all the time i use alt tab and 20% of the times the icons seems normal sized. I think the problem started showing up when i switched to monterey, i did not have this problem when i used big sur.

**Comment by teenjuna** [comment] 2022-01-08 05:37
I experience the same issue and it is indeed very annoying

**Comment by brain0verfl0w** [comment] 2022-01-08 10:44
I have the same issue too.

**Comment by metacodes** [comment] 2022-06-01 12:02
The root cause is that `hStackView.fittingSize.width` sometimes is different. For those smaller icons, `hStackView.fittingSize.width` is smaller than others. I try to play sliders `windowMaxWidthInRow`, `windowMinWidthInRow` and `iconSize`, it can solve this problem.

<img width="1727" alt="image" src="https://user-images.githubusercontent.com/3339872/171397477-5e5ac404-d9d9-4f1e-9e7c-dbb8ffad4e9e.png">

<img width="1193" alt="image" src="https://user-images.githubusercontent.com/3339872/171397272-bcda75a2-be38-4f7d-bbda-d0b66cef2c6e.png">

<img width="494" alt="image" src="https://user-images.githubusercontent.com/3339872/171399217-ad40c0c3-6ef1-4b3f-9758-f4cfd648b3d7.png">

Make `windowMinWidthInRow` less than 10% and adjust `iconSize` can reproduce this problem.

**Comment by franco-ruggeri** [comment] 2022-09-15 07:12
I'm having the same issue but I manage to fix it by adjusting "Window min width row". To me, it happens when this parameter is too small.

It is still annoying because the good value yielding square icons (see picture in the OP) depends on the screen resolution. Since I change screen resolution during the day (work, home, relax on the sofa), I need to change this value several times per day (6% on UQHD screen or laptop screen, 10% on QHD screen). 

It would be great to add a feature like a checkbox to trim the icons to the smallest width not causing the problem, which would automatically be adjusted depending on the screen resolution.

**Comment by educbraga** [comment] 2024-02-06 15:15
This seems to happen if 'Window min width in row' is set to 1%. This issue doesn't seem to happen when it's set to 2% or higher.

**Comment by Bones526** [comment] 2024-03-22 07:42
When I have a monitor, I can avoid this situation by adjusting the slider, but when I have an external monitor, a set of settings cannot be better applied to two monitors, so can you detect whether there are multiple monitors, Then set the adjustment slider separately for each monitor, thank you for this application, he is great （Translate from Google）

**Comment by DarkMikey** [comment] 2024-05-16 08:03
> This seems to happen if 'Window min width in row' is set to 1%. This issue doesn't seem to happen when it's set to 2% or higher.

Cannot confirm this. I guess this is randomly true in your scenario but with my screen it does happen with 2% but goes away with 8%. 

Hope this will be fixed, it annoys me more than it should.

**Comment by Allsochen** [comment] 2024-08-03 07:07
This issue will be fixed at this [post](https://github.com/lwouis/alt-tab-macos/pull/3468)

**Comment by Allsochen** [comment] 2024-08-03 07:08
feat: refactor the appearance preferences for simplification. #3468

**Comment by lwouis** [comment] 2024-10-09 22:44
This issue will probably be gone with the revamp from v7.0.0. I'm closing this issue. Please share here if anyone still faces it 👍

**Closed by lwouis** 2024-10-09 22:44 UTC
Labels: bug
