### ISSUE TITLE
AltTab breaks some OS animations from Big Sur

### ISSUE THREAD

**Issue by vwh** [lwouis/alt-tab-macos#718] opened 2020-12-09 06:57 UTC
**Describe the bug**
ATM will break pop up window transmition animation in Big Sur.

**Screenshots / video**

With ATM Quit:
![With ATM Quit](https://user-images.githubusercontent.com/7691760/101595443-4ece9480-3a2e-11eb-8409-fedf8a805b1d.gif)

With ATM Open:
![With ATM Open](https://user-images.githubusercontent.com/7691760/101595477-5beb8380-3a2e-11eb-8d9c-c2e890349356.gif)

**Steps to reproduce the bug**

1. Open ATM
2. Open any pop up window(Touch ID authentication, Save as, etc.)

**Comment by lwouis** [comment] 2021-08-29 08:03
To clarify the status of this ticket:

* I was able to reproduce the original issue with window animations on BigSur
* I wasn't able to reproduce the new discussion about AltTab potentially crashing QuickLook or finder. It seems like this one could be due to Apple Silicon, due to Big Sur, a bug in macOS with PDF or RAW files, and potentially completely unrelated to AltTab

**Comment by lwouis** [comment] 2021-09-25 11:33
I narrowed down the issue: it doesn't happen if I comment out the code which subscribes to a particular accessibility event (`AXObserverAddNotification` with `kAXFocusedUIElementChangedNotification`). It's an issue we have seen in the past with specific apps (see https://github.com/lwouis/alt-tab-macos/blob/5cd7b4458041b7164ca8aeeccda299fa188dde35/src/logic/Application.swift#L29).

We subscribe to this Accessibility event so we can notice when tabs are changed (e.g. 2 windows are merged into 1 with 2 tabs).

I don't know what can be done here really. It seems like a clear bug from macOS here. Observing accessibility events should not influence the observed apps. Yet it does here.

Either we have these broken animations if we subscribe, or we lose knowledge of tabs if we don't. Losing knowledge of tabs means AltTab will start showing incorrect windows when tabs are involved.

**Comment by lwouis** [comment] 2021-11-28 05:16
I worked on this today. I tried to see if there is a specific process in macOS for which we could avoid listening to its `kAXFocusedUIElementChangedNotification` event, to prevent the issue from this ticket.

It seems that each app process is involved. For instance, I can prevent the problem happening for `Safari` (cmd+s in Safari to test) by not listening to the event for process `com.apple.Safari`. Similarly, to prevent the issue in `System Preferences > Software Update`, I need to not listen to the event in `com.apple.systempreferences`.

This is bad news because apps like Safari can have native tabs. So we need to listen to the event.

The bug is present in Monterey as well, so Apple hasn't fixed this bug in their latest OS.

I don't know how to deal with this.

**Comment by nnemkin** [comment] 2021-11-28 08:20
How bad is the breakage if you disable tab tracking? Could you perhaps add an option to turn it off?

I can live without tabs, but laggy file dialogs are very painful.

**Comment by lwouis** [comment] 2021-11-28 09:07
> How bad is the breakage if you disable tab tracking?

AltTab would fail to show some windows made into tabs. It would show windows that are now closed since it didn't notice their closure. Other issues of that nature.

> Could you perhaps add an option to turn it off?

There are already too many options (see #351). Plus, how would we even explain that one to users? It would look pretty bad as well. It would be macOS version specific as well, so another problem for QA/support.

Overall I think we'll keep status quo for now until someone finds a breakthrough

**Comment by yossizahn** [comment] 2022-04-07 10:53
This seems to have fixed itself lately. The problem doesn't occur by me nowadays.

**Comment by lwouis** [comment] 2022-05-26 15:35
With the fix from #1540, this ticket should be fixed. The latest release should work fine on any version of Big Sur 👍

**Closed by lwouis** 2022-05-26 15:35 UTC
Labels: bug, need breakthrough, macOS 11, macOS 12
