### ISSUE TITLE
Center the switching 

### ISSUE THREAD

**Issue by kayc7** [lwouis/alt-tab-macos#1059] opened 2021-07-29 11:08 UTC
**Is your feature suggestion related to a problem? Please describe.**
The switcher is centered towards the top of the screen

**Describe the solution you'd like**
Center it vertically on the screen

I really love this program and I find the default settings to be nearly perfect. I've seen the other topics listed about this and how additional settings in the settings menu may cause even more confusion for the end-user. My question is this: why is the app switcher even centered near the top as a default? Both the built-in app switcher for MacOS and Windows (and many linux distros) are centered vertically.

If there won't be an additional settings menu to prevent confusion, I think it makes more sense for this "set-in-stone" configuration of this program be centered vertically, to follow the configuration of default app-switchers as well as Windows App switcher (which is what it's trying to mimic, right?)

**Comment by lwouis** [comment] 2021-07-29 15:16
Duplicate of https://github.com/lwouis/alt-tab-macos/issues/585

**Closed by lwouis** 2021-07-29 15:16 UTC
Labels: enhancement
