### ISSUE TITLE
Alt-Tab window switcher suddenly not start anymore (but the default MacOS window switcher) 

### ISSUE THREAD

**Issue by stidch** [lwouis/alt-tab-macos#528] opened 2020-08-13 06:44 UTC
**Describe the bug**

When I initially start AltTab the AltTab window switcher starts successfully when pressing CMD+tab on my external Magic Keyboard.

Suddenly (I don't know what causes AltTab to not work anymore) the AltTab window switcher is not opened anymore, but the MacOS default window switcher.

What I've tried in this situation:
- Restarting AltTab - does not help
- Using the MacBookPro internal keyboard - does not help
- Restarting MacOS helps

Setup:
- MacBookPro 2019
- MacOS Catalina 10.15.6
- AltTab 4.19.0

**Screenshots / video**

Configuration

![image](https://user-images.githubusercontent.com/14352675/90102151-4bf1ba80-dd40-11ea-8f79-fbdc1a408396.png)

**Steps to reproduce the bug**

Unfortunately I don't know how to reproduce it. But I can see it quite often and I don't know how to fix it.

**Comment by lwouis** [comment] 2020-08-13 06:52
Hi @stidch! Thanks for sharing this issue!

Based on the symptoms, I think you are experiencing #157. Could you please run this command in Terminal and share the result?

`ioreg -l -w 0 | grep SecureInput | awk 'BEGIN {FS="[^a-zA-Z0-9]+"} {print $8}' | uniq | xargs -n 1 ps aux`

It should show you which app on your machine is enabling Secure Input, which prevents AltTab from accessing your keyboard inputs.

**Comment by stidch** [comment] 2020-08-13 08:13
Hey @lwouis 

Thanks for the very quick response.

I've executed the command, but I get an error 🤔 
```
$ ioreg -l -w 0 | grep SecureInput | awk 'BEGIN {FS="[^a-zA-Z0-9]+"} {print $8}' | uniq | xargs -n 1 ps aux
ps: illegal argument: Yes
usage: ps [-AaCcEefhjlMmrSTvwXx] [-O fmt | -o fmt] [-G gid[,gid...]]
          [-u]
          [-p pid[,pid...]] [-t tty[,tty...]] [-U user[,user...]]
       ps [-L]
```

If I call the commands separately I see the following:

```
ioreg -l -w 0 | grep SecureInput
  |   "IOConsoleUsers" = ({"kCGSSessionOnConsoleKey"=Yes,"kSCSecuritySessionID"=100008,"kCGSessionLoginDoneKey"=Yes,"kCGSSessionGroupIDKey"=672444324,"kCGSSessionSystemSafeBoot"=No,"kCGSSessionUserNameKey"="11sgrimm","kCGSSessionIDKey"=257,"kCGSSessionSecureInputPID"=251,"kCGSessionLongUserNameKey"="Grimm, Stephan","kCGSSessionAuditIDKey"=100008,"kCGSSessionLoginwindowSafeLogin"=No,"kCGSSessionUserIDKey"=1443202911})
    | |   "IOConsoleUsers" = ({"kCGSSessionOnConsoleKey"=Yes,"kSCSecuritySessionID"=100008,"kCGSessionLoginDoneKey"=Yes,"kCGSSessionGroupIDKey"=672444324,"kCGSSessionSystemSafeBoot"=No,"kCGSSessionUserNameKey"="MYUSER","kCGSSessionIDKey"=257,"kCGSSessionSecureInputPID"=251,"kCGSessionLongUserNameKey"="MYNAME","kCGSSessionAuditIDKey"=100008,"kCGSSessionLoginwindowSafeLogin"=No,"kCGSSessionUserIDKey"=1443202911})
```

If I look for a process with PID 251 I see
```
ps aux | grep 251
myuser         53572   0.0  0.0  5251536      8   ??  Ss   10:05PM   0:00.10 /System/Library/Frameworks/Metal.framework/Versions/A/XPCServices/MTLCompilerService.xpc/Contents/MacOS/MTLCompilerService
myuser         22352   0.0  0.0  5125192   1124   ??  S    Tue02PM   0:00.69 /System/Library/Frameworks/CoreServices.framework/Frameworks/Metadata.framework/Versions/A/Support/mdwrite
root            1441   0.0  0.0  5125120   1032   ??  S    Tue02PM   0:00.21 /usr/libexec/secinitd
myuser           914   0.0  0.0  4600148   2512   ??  S    Tue02PM   0:00.16 /System/Library/PrivateFrameworks/CommunicationsFilter.framework/CMFSyncAgent
myuser         57259   0.0  0.0  4408572    816 s000  S+   10:09AM   0:00.00 grep --color 251
_coreaudiod      283   0.0  0.1  5791456  25184   ??  Ss   Tue02PM   2:26.28 /usr/sbin/coreaudiod
myuser           251   0.0  0.1  6518400  38744   ??  Ss   Tue02PM   0:25.83 /System/Library/CoreServices/loginwindow.app/Contents/MacOS/loginwindow console
```

Does this help?

**Comment by lwouis** [comment] 2020-08-13 08:30
Thank you for the breakdown! I can see on the last line that you're being affected by the bug in macOS `loginwindow`. See more explanations on [this comment](https://github.com/lwouis/alt-tab-macos/issues/157#issuecomment-672563979) on the ticket I mentioned above.

I'm closing this ticket as a duplicate of #157. Hopefully enough people test the new build, and I can release the new AltTab which is unaffected by Secure Input 👍

**Closed by lwouis** 2020-08-13 08:30 UTC
Labels: bug, duplicate
