### ISSUE TITLE
Navigate windows using vim bindings

### ISSUE THREAD

**Issue by goldlil** [lwouis/alt-tab-macos#1994] opened 2022-10-07 13:52 UTC
**Is your feature suggestion related to a problem? Please describe.**
It's not related to specific problem, I just think it would be nice to be able navigate windows with custom bindings, eg. vim style hjkl. Arrows are ok, but sometimes it would be easier to customise our own keys for navigation,

**Describe the solution you'd like**
I would like to be able to assigne any key to left, right, up, down. Arrows are cool, but this would be level up, especially for us used to vim bindings.

**Describe alternatives you've considered**
RIght now arrows are doing job.

**Comment by lwouis** [comment] 2022-10-07 14:24
Duplicate of https://github.com/lwouis/alt-tab-macos/issues/1229

**Closed by lwouis** 2022-10-07 14:24 UTC
Labels: enhancement
