### ISSUE TITLE
Separate blacklists for window-less apps, and windowed apps.

### ISSUE THREAD

**Issue by SoPat712** [lwouis/alt-tab-macos#648] opened 2020-10-11 15:24 UTC
I use an app called airmessage that allows my Android phone to use iMessage through a server run on my computer. It also means that iMessage has to constantly be running in the background. While this is just one use case in which the window-less app feature is inconvenient, it would in fact be helpful if it were possible to blacklists apps not from both, but from one or the other. Another thing is that I would not like finder to be able to show up in the window-less apps area when I blacklist it, but it also means that when I unzip DMG's, I have to use mission control to be able to see the windows, as dmgs always open in Finder.

Anyway, thanks for any help in advance.

**Comment by SoPat712** [comment] 2020-10-19 19:39
An update to this enhancement: Another app that also has this odd behavior is tooth fairy, an app I use to connect and disconnect by bluetooth headphones. In alt-tab it shows up as a windowless app, even though it is 100% not necessary to create new windows, as it simply opens the preference pane. I have blacklisted toothfairy altogether, including preferences, but I would still like to be able to only blacklist the app in windowless apps.

**Comment by lwouis** [comment] 2020-10-20 14:53
This ticket can't be my priority at the moment given the other open tickets. For anyone who would be interested in moving this ticket forward faster, I explained how the UI should look like in #539.

**Comment by lwouis** [comment] 2022-06-10 16:23
Closing as duplicate of https://github.com/lwouis/alt-tab-macos/issues/763

**Closed by lwouis** 2022-06-10 16:23 UTC
Labels: enhancement
