### ISSUE TITLE
Missing window preview sometimes

### ISSUE THREAD

**Issue by comonadd** [lwouis/alt-tab-macos#2025] opened 2022-10-18 12:24 UTC
Sometimes, AltTab stops showing window preview for certains apps.

If I turn on the checkbox in appearance settings "hide apps with no open window", those elements that have no preview are not shown. I think this is because AltTab doesn't recognize them as having any open windows for some reason. I have tried restarting AltTab but it doesn't help. The only thing that helps is restarting the apps, but it's not really convenient.

![missing previews](https://user-images.githubusercontent.com/15632950/196428348-652f63a9-e637-4563-922e-909a1147e8ee.png)

**Steps to reproduce the bug**

1. Open AltTab
2. See missing previews

**Comment by lwouis** [comment] 2022-10-18 16:56
Duplicate of #1324

**Closed by lwouis** 2022-10-18 16:56 UTC
Labels: bug
