### ISSUE TITLE
Finder isn't shown amongst running apps after initial installation

### ISSUE THREAD

**Issue by Stokestack** [lwouis/alt-tab-macos#3350] opened 2024-05-10 18:32 UTC
**Describe the bug**

Finder is not blacklisted, and I don't have "Hide apps with no open window" checked. But immediately after installing Alt-Tab (and restarting it after granting permissions), it did not show Finder among running applications.

So I created a Finder window, and then checked Alt-Tab; it was shown. I then closed the Finder window, and checked Alt-Tab; now a large Finder icon appeared at the end of the open-apps grid.

**Steps to reproduce the bug**

Do a fresh installation of Alt-Tab and grant all permissions.
Make sure Finder isn't blacklisted in Alt-Tab preferences.
Make sure Alt-Tab isn't hiding apps with no windows.
Make sure Finder has no windows.
Invoke Alt-Tab.

**Your environment**

* AltTab version: 6.68.0
* macOS version: 14.4.1 (Apple Silicon)
* Other relevant info: e.g. using external keyboard, multiple monitors, etc
Using external monitor in clamshell mode, but I doubt this is a factor.

**Comment by lwouis** [comment] 2024-05-10 20:14
Hi,

On a fresh install, Finder is blacklisted partially. Only windows are shown, not the app itself in the case where there is no open window. This is what it looks like:

<img width="700" alt="image" src="https://github.com/lwouis/alt-tab-macos/assets/106195/9ff3d1ca-d033-4504-8b44-8c8c9065b32f">

When you say that Finder is not blacklisted, do you mean that you removed the row from the blacklist table?

Thank you 🙇

**Comment by Stokestack** [comment] 2024-05-10 23:09
Sure! First I set the drop-down to the blank entry. This didn't do anything. Then I removed the entry altogether.

On a side note: I think it would be better _not_ to hide Finder by default. Doing so hides one of Alt-Tab's coolest features: creating a window if you tab to an app that lacks one.

**Comment by lwouis** [comment] 2024-05-11 15:06
Could you please share a video of the issue? Showing the preferences and the behavior?

Thank you

**Comment by Stokestack** [comment] 2024-05-11 19:39
Well, it only occurred _on initial installation_. How do I fully remove AltTab and all of its preferences?

**Comment by lwouis** [comment] 2024-05-11 21:07
There is a button for that in the preferences:

<img width="700" alt="image" src="https://github.com/lwouis/alt-tab-macos/assets/106195/04149106-c485-4d53-9a3a-f72e2cc3c895">

**Comment by Stokestack** [comment] 2024-05-13 19:42
OK, deleting preferences did reproduce the problem. In fact, now it doesn't show Finder even when it has a window. Screen grab and shot of preferences attached.

https://github.com/lwouis/alt-tab-macos/assets/196304/a00d48c1-d9e7-47cb-b120-afb0ed0fcb52

![Screenshot 2024-05-13 at 12 34 41 PM](https://github.com/lwouis/alt-tab-macos/assets/196304/68a3d98d-9e33-4f84-8a1c-3db13307715d)

**Comment by lwouis** [comment] 2024-05-13 20:31
Could you please show the Blacklist tab?
Also, if you press command+tab, the default app-switcher shows the Finder icon, right?

Thank you

**Comment by Stokestack** [comment] 2024-05-14 00:37
Right, I forgot that Finder was blacklisted by default (which I don't understand; it defeats one of the best features of Alt-Tab).

After resetting preferences and removing Finder from the blacklist, it still doesn't show up in Alt-Tab at first. You have to create a Finder window and then invoke Alt-Tab. After that, Finder will show up without a window. [Here's a screen grab of the sequence](https://youtu.be/KHrlHodhdz0).

**Comment by ShaiAvr** [comment] 2024-08-31 11:42
I am also having this issue. When alt-tab starts, if there are no finder windows, then finder doesn't show at all, despite removing it from the black list and disabling "hide apps without windows". Only after opening a finder window and closing it, the finder app is shown in alt-tab as expected. It's really annoying since I am used to finder always being available in the apps list of Cmd+Tab.

I also agree with @Stokestack that it shouldn't be blacklisted (even partially) by default. In addition to being able to create a new window when tabbing to an app without a window (which I admit is cool since if you tab into an app without a window, you were probably going to make a new window so it's a nice shortcut), most Mac users like me are used to having finder always available in the apps list and while I can understand why some people don't like it, I think MacOS standard behavior should be followed by default.

Another point I should mention is that for me, this issue is totally reproducible. Just start alt-tab without having any finder windows open, and you won't see the finder app icon at all. Opening a finder window fixes this and makes the finder app available even without any windows open.

**Comment by lwouis** [comment] 2024-08-31 16:06
Hi,

I was able to reproduce the issue. After investigating, I think it must be due to a change in macOS, at some point in the new releases.

The reason AltTab is not showing the Finder is that it detects that Finder has 1 open window. However, that window is bogus, and is later filtered. So we see neither the window nor the app-with-no-open-window.

<img width="979" alt="image" src="https://github.com/user-attachments/assets/7c4e0d7e-faeb-4c4b-9b55-1f1ef6639cdf">

It's a logic bug in our code technically. It hasn't happened before with other apps because it only happens if the window has no `CGWindowID`. Windows should always have an ID. Except in that case, for some reason, the OS API doesn't return, so we have `nil`.

I've made a fix for this. It will be shipped in the next release 👍 

Thank you 🙇

**Closed** 2024-10-08 19:46 UTC
Labels: bug, unreproducible
