### ISSUE TITLE
Cannot assign ` key to shortcuts on Monterrey

### ISSUE THREAD

**Issue by mpr1255** [lwouis/alt-tab-macos#1425] opened 2022-03-09 01:00 UTC
**Describe the bug**

Shortcuts that use the \` character as part do not seem to work on Mac OSX Monterrey 12.2.0 and 12.2.1. I typically use alt+tab for toggling between apps and  alt+` for toggling between windows in the Active App, but this does not work on Monterrey. 

**Steps to reproduce the bug**

I believe the bug can be reproduced by trying to use \` as part of a shortcut on Monterrey. The steps I took to isolate this as an alleged bug were: 

1. Used \` key as part of shortcut on Big Sur. 
2. Used \` as part of shortcut on Monterrey. 
3. Upon finding 2 did not work, I closed every open application to confirm nothing was hijacking the \` key. I disabled the default assignment of the \` key in the Mac keyboard settings. And I assigned the same functionality in Alt-Tab (Shortcut 2, 'show windows from Active App') to alt+1 and a range of other keyboards. It worked in all cases. Shortcut 1 also did not work when using \`.

**Comment by phao5814** [comment] 2022-03-09 08:34
I was thinking it was just me for a moment....confirming this is the case for MacOS Monteray 12.2.1 .

**Comment by lwouis** [comment] 2022-03-09 13:56
Duplicate of #1190 #1278

**Closed by lwouis** 2022-03-09 13:56 UTC
Labels: bug
