### ISSUE TITLE
Don't ask for Screen Recording permission if it's not necessary

### ISSUE THREAD

**Issue by ris58h** [lwouis/alt-tab-macos#2369] opened 2023-02-23 19:33 UTC
**Is your feature suggestion related to a problem? Please describe.**
AltTab requires both Accessibility and Screen Recording permissions being granted to start using the app. It seems like Screen Recording is needed only to show window thumbnails and the app could work just fine without it if user has `Hide window thumbnails` setting turned on.

**Describe the solution you'd like**
I would like to be able to use the app without Screen Recording permission granted if it's not necessary. For example [HyperSwitch](https://bahoom.com/hyperswitch) shows blurred gray rectangles instead of thumbnails if Screen Recording permission isn't granted.

**Comment by lwouis** [comment] 2023-02-23 19:48
Duplicate of #1082

**Closed by lwouis** 2023-02-23 19:48 UTC
Labels: enhancement
