### ISSUE TITLE
Keyboard shortcut  ⌥ + ` doesn't work on macOS Monterey

### ISSUE THREAD

**Issue by GrimDemon** [lwouis/alt-tab-macos#1854] opened 2022-08-10 10:12 UTC
**Describe the bug**

I tried setting ⌥ + ` as "Shortcut 2" for switching between windows from the active app. The keyboard shortcut is not being used by any other app. Nothing happens when I do the shortcut. When I change it to something else e.g. ⌥ + F12 it works. Additionally, "Shortcut 2" defaults to an empty character that I don't recognize. I am using macOS Monterey on an Apple M1 Pro. The physical keyboard is English International and the software keyboard language is Polish.

**Screenshots / video**

<img width="686" alt="Screenshot 2022-08-10 at 11 48 24" src="https://user-images.githubusercontent.com/7392904/183872583-fb938035-2717-4ac2-8ce7-a7b36d7edf6b.png">
<img width="686" alt="Screenshot 2022-08-10 at 11 49 17" src="https://user-images.githubusercontent.com/7392904/183872601-100f72c8-b4b3-4ca0-a7c4-d279590cae60.png">

**Steps to reproduce the bug**

1. Go to AltTab preferences.
2. Set character for "Shortcut 2".
3. Use it with whatever application you want.
4. Nothing happens. Instead of the expected window switching, I start typing this character into the text field (if the application is a text editor).

**Comment by GrimDemon** [comment] 2022-08-10 10:15
I suspect this is a duplicate of #1190.

**Comment by lwouis** [comment] 2022-08-10 12:39
I use the US English built-in keyboard of my macbook pro. I use US English as software input.

I tried to add Polish as the input source (software):

<img width="780" alt="image" src="https://user-images.githubusercontent.com/106195/183902456-4a210508-7bf9-4657-ba36-6aad49f3e259.png">

When I opened AltTab, it had automatically adapted the ``` ` ``` key into `<`:

<img width="686" alt="image" src="https://user-images.githubusercontent.com/106195/183902622-ac691b7b-057d-4eaf-91e2-a8c37b6d8dce.png">

In addition, if I still click the key to change it, and press the same key on my keyboard (the key above `tab`, which in my case is physically labeled ``` ` ```), it sets the key to `<` correctly again.

I'm wondering why this is not working on your setup. Do you use an external / non-Apple keyboard? Do you use another input source than me? (I got offered `Polish` and `Polish - Pro` for example in the input sources). Maybe the issue is because you have an M1 mac somehow? Have you seen this issue on an Intel mac? Etc. Anything that could be noteworthy to investigate the issue.

**Comment by lwouis** [comment] 2022-08-10 12:47
I'll close this ticket to keep the conversation focused in #1190

**Closed by lwouis** 2022-08-10 12:47 UTC
Labels: bug
