### ISSUE TITLE
AltTab 4.16.0 crashing on launch after update

### ISSUE THREAD

**Issue by nathang21** [lwouis/alt-tab-macos#495] opened 2020-08-07 02:25 UTC
## Summary
After updating AltTab and relaunching the app, I opened the preferences menu and started to customize keyboard shortcuts and it crashed. 

## Reproduce
Relaunch app. 
Since then, I have not been able to re-open it, it crashes on launch. No UI is visible, but sometimes the windows jump around for a split second (which from reading other issues is WAI on startup).

I confirmed the processing is not running, and Console logs show crash report being generated. 

See attached zip for crash reports
[Archive.zip](https://github.com/lwouis/alt-tab-macos/files/5038977/Archive.zip)

**Comment by lwouis** [comment] 2020-08-07 03:17
Hey @nathang21! Sorry about the crash loop! That's unfortunate.

I checked the crash report, especially the ones in AppCenter (they are easier to handle as the symbols are resolved). I think you clicked to send crash reports, right?

In the report, i see the app preferences, and I see that the `holdShortcut` is empty! That's why the app crashes. It should normally be impossible to remove that shortcut. The UI doesn't provide any way to do it.

> I opened the preferences menu and started to customize keyboard shortcuts

Do you remember what you did exactly? I don't know how you managed to empty the hold part of the shortcut.

To be fix the app, please just delete your preferences by running `defaults delete com.lwouis.alt-tab-macos`

**Comment by nathang21** [comment] 2020-08-07 04:15
Hi @lwouis , thanks for the quick response, that fix did the trick.

I believe the app crashed while I was editing that keyboard shortcut, which makes sense that it would be empty. I was actually trying to figure out a way to unmap the 2nd preset in AltTab, and just use the Primary, as I was playing around with the native macos keyboard shortcuts for switching spaces. 

Hope that helps, I can get more logs if that would be helpful. 

P.S. Lots of apps have a little small x on the right side on however, to remove/un-asssign a keyboard shortcut, without being required to choose a new one immediately. Consider that a FR / nice to have, as I am planning on only using 1 shortcut.

**Comment by lwouis** [comment] 2020-08-07 04:44
>  I was actually trying to figure out a way to unmap the 2nd preset in AltTab, and just use the Primary

Do you remember the exact UI actions you took? To disable a shortcut, you need to press the little cross icon on the right:

![image](https://user-images.githubusercontent.com/106195/89609741-b1165d80-d8b3-11ea-9cd6-29227fa3ea28.png)

After you press it, it should look like this:

![image](https://user-images.githubusercontent.com/106195/89609792-d30fe000-d8b3-11ea-9747-4ce715681af0.png)

Importantly, I disabled this cross for the main hold shortcut part:

![image](https://user-images.githubusercontent.com/106195/89609869-07839c00-d8b4-11ea-8c21-3da145ca027a.png)

That's why I'm so puzzled at how you managed to clear it, and get it to be the empty string in your preferences

**Comment by nathang21** [comment] 2020-08-07 04:54
Unfortunately I don't remember exactly, the app crashed very suddenly though, while I was in the process of recording the shortcut.

Whoops I must have missed the little X button when I first clicked it because I never saw it show "Record Shortcut".

So the way it got in that state I assume, was It didn't clear it, but also didn't finish recording it. Pretty sure it crashed somewhere in that small window.

**Comment by nathang21** [comment] 2020-08-07 04:55
FWIW, I'm not able to reproduce it either.

**Comment by lwouis** [comment] 2020-08-07 04:58
@nathang21 A bit more explanations for clarity: https://www.loom.com/share/bc250efdb6134059879381d6b94c0c7b

**Comment by nathang21** [comment] 2020-08-07 05:19
Very helpful. Made a follow-up, not sure how helpful this will be to you though.
https://www.loom.com/share/c76f5474611e4fd888bc32bb38ab352e

**Comment by nathang21** [comment] 2020-08-07 05:37
Confirmed after a restart things are working as expected again. Still can't reproduce though how that happened.

**Comment by lwouis** [comment] 2020-08-07 06:49
**The empty hold shortcut**

I'm really not sure how that happened. Maybe its the Space switching shortcut that conflicted, like changing a Space in the middle of setting the shortcut? In my test, the shortcut recording UI is really robust, and will just cancel and use the previous shortcut if you do things like click on another UI element, lose focus, etc. Really not sure what's happening. Anyway, if I see more crash reports in AppCenter this week, I'll just put some code to clear the `holdShortcut` in the preferences if it's in this bogus state. Or maybe i'll change the button to be clearable, and rework the code to allow for that to be possible.

**The shortcut not working**

When you used Alfred, it flashed "AltTab 1", "AltTab 2", like up to "AltTab 6". It could be that you had multiple versions of AltTab running at the same time. Especially since you disable showing in the menubar, you could have a few different versions running at the same time, and messing with each other.

Next time it happens you can check in Activity Monitor if there is really only 1 AltTab running. You may also want to check in your Login Items that there is not multiple AltTab versions set to start on login.

**Bonus discovery**

You use dark mode on your system, and that video made me realize I haven't adapted the new icons to dark mode! I'll fix that!

**Comment by nathang21** [comment] 2020-08-07 14:46
1. Yeah something super weird was going on in my system, I wouldn't worry too much about it, thanks though! Would be nice if there was an easy way to backup preferences, or avoid them from getting in a valid state. Maybe the app could still open but show an error if the preferences are invalid, instead of crashing on launch? Not sure how feasible that is though. 

2. Yeah those are from all the tests builds I have downloaded. I made sure to use the primary one (AltTab) which is in my Applications folder that updates automatically. All the others you saw, were in my Downloads folder. I checked Activity Monitor and terminal `ps aux | grep AltTab` and did not see any instances running. Anytime I opened it, they would crash instantly, I even tryied downloading an older release from Github and had the same result. I didn't show this in my recording sorry. 

3. Ah very nice!

**Comment by lwouis** [comment] 2020-08-08 16:04
Regarding the preferences being corrupted and crashing the app on launch, it's quite a difficult problem.

First, preferences can crash on launch, but they can also crash later, like when trying to trigger the app. The problem being that these crashes are not from reading the preference from disk or something systematic like this. No the crashes are from the app having a functional crash like the app needs a value to do some action, and suddenly the expected value is not here, or has a value that makes no sense in this context.

I'm not sure how I would improve this. I could imagine at boot, doing a pass on the existing preferences, and seeing that they are within some constraints, like a dropdown menu should be between 0 and 4, for all 5 possible options, for example. However now I have this extra validation code to maintain, and potentially it can itself be the cause of future crashes if I forget to update it when a preference is updated in the future.

I'll think about and see if I can think of a clever way to reduce this crashes. These are indeed the worst crashes as the user is completely locked out, and can't even use the feedback back to write about it. At least now I added a crash report, and it initialise before anything else, so the user can now click a button to send a report, and I will review these in AppCenter frequently. I have been reading many already, and fixed a dozen exotic rate crashes already thanks to that crash reporter.

Closing the ticket. Thanks for your support!

**Comment by OmryAr** [comment] 2020-08-30 23:26
Hi! I found a way to reproduce this crash: When modifying the first (shift key?) I go to the left box (just right of the "Hold" text) and click it. It then grays out the current key and shows the u-turn arrow, as expected. Clicking **a few pixels just to the right of the arrow** makes the application hard crash!
Following this crash the setting is blank and the app won't start. Only removing this setting allows it to launch again.
Hope this helps :-)

**Comment by lwouis** [comment] 2020-08-31 02:08
Thank you so much @OmryAr! I tried so hard to find this issue in the past, but failed. You found it! I was able to reproduce it.

I'll fix this asap!

**Closed** 2020-08-31 05:41 UTC
Labels: bug, unreproducible

**Comment by OmryAr** [comment] 2020-08-31 10:12
Hurray! :-) Thank you for the great support and wonderful app!
