### ISSUE TITLE
Preferences window is cut off

### ISSUE THREAD

**Issue by MKGitHub** [lwouis/alt-tab-macos#1226] opened 2021-11-13 16:09 UTC
**Describe the bug**

Preferences window is cut off.

**Screenshots / video**
![Screenshot  2021-11-13 at 17 06 49](https://user-images.githubusercontent.com/535550/141650815-7ff2c382-be25-48ae-aa2a-37b4c9298782.png)

**Comment by lwouis** [comment] 2021-11-14 02:27
Duplicate of https://github.com/lwouis/alt-tab-macos/issues/1062

**Closed by lwouis** 2021-11-14 02:27 UTC
Labels: bug
