### ISSUE TITLE
Total finder have 2 window while use Alt-Tab

### ISSUE THREAD

**Issue by Eden-tran** [lwouis/alt-tab-macos#2373] opened 2023-02-27 08:15 UTC
Hi
First i just  want to say that your product is amazing and i want to thank you for that. It helps me a lot at work.
The second is to ask you about the problem i am using Total Finder on my MAC Mojave and i see that have 2 window on it.I have read the issue same with this one but i don't know how to fix it. Maybe my english not good to fully understand that issue. But i hope that you can help me to fix it. 

I'm using 
-MAC mojave 10.14.6
-Total Finder 1.12.3
-Alt-Tab Version 6.55.0

Thank you and hope you reply

![CleanShot 2023-02-27 at 15 07 08](https://user-images.githubusercontent.com/58251640/221509052-e207d89d-3320-49de-9130-afe1d3d70a43.png)

**Comment by lwouis** [comment] 2023-02-27 08:28
Duplicate of #84

**Closed by lwouis** 2023-02-27 08:28 UTC
