### ISSUE TITLE
Alt tab windows on all available monitor screens, only showing the apps for each monitor

### ISSUE THREAD

**Issue by dilirity** [lwouis/alt-tab-macos#2607] opened 2023-06-23 07:01 UTC
**Is your feature suggestion related to a problem? Please describe.**
Currently, having multiple monitors and alt tabbing, shows only one alt tab overlay on one monitor (where, depends on the settings). Having apps on separate monitors and showing them all in the same ovelray, makes it hard to figure out which app is showing on which monitor.

**Describe the solution you'd like**
Have an option, that when toggled, would show the Alt Tab overlay on each monitor screen, only showing the apps running on that monitor. That would greatly help declutter the alt tab overlay windows.

Another idea would be to color the apps (or tag them in some way) to differentiate between the monitors they are on.

**Describe alternatives you've considered**
Maybe there is such an option, but I couldn't find it in the settings.

Just realized, that the "Preview selected window" works in helping you find the app you need! (oh I really like this option!)

**Comment by lwouis** [comment] 2023-06-23 07:03
Duplicate of https://github.com/lwouis/alt-tab-macos/issues/535#issuecomment-674921293

**Closed by lwouis** 2023-06-23 07:03 UTC
Labels: enhancement
