### ISSUE TITLE
When pressing command tab, it loops throgh every window every once in a while.

### ISSUE THREAD

**Issue by malkhazidartsmelidze** [lwouis/alt-tab-macos#3196] opened 2024-02-22 11:10 UTC
**Describe the bug**

I am usually switching using CMD+Tab between 5-10 open windows. Somethimes (maybe after 3-7 normal switch) when I press CMD+TAB it stays and loops through every window.

Also sometimes it stays open when even when I get my fingers of both keys. (seen in video when I use mouse to switch between videos, I have not pressed any keys)

<img width="597" alt="image" src="https://github.com/lwouis/alt-tab-macos/assets/34204206/7b01a19b-1aeb-4ba5-8f0c-8a8c10df88b6">
<img width="611" alt="image" src="https://github.com/lwouis/alt-tab-macos/assets/34204206/9cffecd4-cbd4-4d60-b57d-c1dd4697c132">

**Screenshots / video**

Add screenshots to help explain your problem. You can also record your screen to show the bug in action. That is *really* helpful!

https://github.com/lwouis/alt-tab-macos/assets/34204206/73af1958-bae7-436a-8137-c28c6f9dd9ca

**Steps to reproduce the bug**

1. Press CMD+Tab
5. See error sometimes

**Your environment**

* AltTab version: 6.64.0
* macOS version: 14.2 sonoma
* Macbook pro 14, + ultrawide 4k monitor connected via DP

**Comment by malkhazidartsmelidze** [comment] 2024-02-22 11:20
It's not key/hardware issue, I have checked if either shortcut or arrow keys are sticky in multiple keyboard checker apps

**Comment by arya1106** [comment] 2024-02-22 14:03
Adding on to this issue, I can also recreate it, and am open to help fix it,

**Comment by lwouis** [comment] 2024-02-22 16:25
Hi everyone,

Could you please test [this build of the app](https://github.com/lwouis/alt-tab-macos/issues/3117#issuecomment-1952171420), and share if the issue persist with it or not?

Thank you 🙇

**Comment by arya1106** [comment] 2024-02-23 00:55
Based on one day's use, it seems like the issue doesn't persist. Although, I do appreciate the quality of life improvement that exists in the usual build of AltTab.

I'll update this comment if I encounter the issue again.

**Comment by kosciolek** [comment] 2024-02-23 11:29
Suddenly started happening for me as well. This is the most frequent issue (it rapidly cycles to the last window), but there are some other things that started happening around the same time:
* cycling forward just a few windows, but not necessarily until the end
* cycling backwards
* hovering the mouse over the switcher makes it cycle forwards and backwards, seemingly randomly

**Comment by eyalroth** [comment] 2024-02-23 11:43
This happens to me constantly on MBP 2019 with Karabiner elements. Has been like that for about a month.

**Comment by lwouis** [comment] 2024-02-23 19:02
This seems to be a duplicate of https://github.com/lwouis/alt-tab-macos/issues/3196. Closing this to focus on 1 ticket/place.

**Closed by lwouis** 2024-02-23 19:02 UTC
Labels: bug

**Comment by mistermantas** [comment] 2024-03-22 11:16
> This seems to be a duplicate of #3196. Closing this to focus on 1 ticket/place.

Are you sure you linked the right issue number? Surely this issue is not a duplicate of itself?

**Comment by arya1106** [comment] 2024-03-22 16:49
See #3117 for discussion on this issue.
