### ISSUE TITLE
Possible to center the application UI

### ISSUE THREAD

**Issue by huyhoang8398** [lwouis/alt-tab-macos#3331] opened 2024-04-30 20:39 UTC
**Is your feature suggestion related to a problem? Please describe.**

Is it possible to center the UI in the screen, for me i think it a bit high on top comparing to the default macOS altab

<img width="2048" alt="Screenshot 2024-04-30 at 22 38 26" src="https://github.com/lwouis/alt-tab-macos/assets/25379882/5576101c-a07f-40e7-a5b3-eda1eacb07ec">

**Comment by azhongzl** [comment] 2024-05-03 06:32
+1, a bit high

**Comment by JohnnyFireOne** [comment] 2024-05-08 14:43
+1000 for me will be awesome!

**Comment by alexaldearroyo** [comment] 2024-06-14 10:34
Also talked [here](https://github.com/lwouis/alt-tab-macos/issues/585). The issue was created 4 years ago but it seems no developer is working on that right now.

**Comment by lwouis** [comment] 2024-07-06 10:59
Duplicate of https://github.com/lwouis/alt-tab-macos/issues/585

**Closed by lwouis** 2024-07-06 10:59 UTC
Labels: enhancement
