### ISSUE TITLE
"Login Item Added" notification on every startup

### ISSUE THREAD

**Issue by SenseiMarv** [lwouis/alt-tab-macos#2247] opened 2023-01-09 08:54 UTC
**Describe the bug**

After upgrading to macOS 13 Ventura, there is a notification "Login Item Added - "AltTab.app" will open automatically when you log in. You can manage this in Login Items Settings." on each startup when I have enabled autostart for AltTab. This notification has to be dismissed each time manually.
Every startup should have no notification about added login items when the autostart option is enabled in the AltTab settings.

**Screenshots / video**

![SCR-20230106-bdo](https://user-images.githubusercontent.com/41735601/211268483-1aa4107f-16c3-4ba4-a26e-dd36312f0a79.png)
(The screenshot is in German since this is my OS language setting - sorry if that causes any inconvenience. I put the translated sentence into the description)

**Steps to reproduce the bug**

1. Make sure that you are on macOS 13 Ventura
2. Enable autostart in the AltTab settings
3. Restart your machine and examine the notification

**Your environment**

* AltTab version: 6.26.0
* macOS version: 13.1
* Other relevant info: e.g. using external keyboard, multiple monitors, etc: -

**Comment by lwouis** [comment] 2023-01-09 10:54
I can't reproduce on my machine. I'll close this for now. If other people have the issue, I'll re-open the ticket.

**Closed by lwouis** 2023-01-09 10:54 UTC
Labels: bug

**Comment by trestent2** [comment] 2023-01-09 18:13
Try updating AltTab.
