### ISSUE TITLE
[Feature] Possibility to center switcher on screen 

### ISSUE THREAD

**Issue by cmalex23** [lwouis/alt-tab-macos#1024] opened 2021-07-03 18:40 UTC
Hi. Amazing work. Only thing missing is the ability to center the switcher on the screen. Maybe a Y-position adjustment, or some other way.

Thanks a lot!

**Comment by lwouis** [comment] 2021-07-04 01:22
Duplicate of https://github.com/lwouis/alt-tab-macos/issues/585

**Closed by lwouis** 2021-07-04 01:22 UTC
Labels: enhancement
