### ISSUE TITLE
Close silently

### ISSUE THREAD

**Issue by weqopy** [lwouis/alt-tab-macos#766] opened 2021-01-08 10:50 UTC
There are no screenshots or videos because of it close  silently.

macOS 11.1
MacBook Pro (Retina, 13-inch, Early 2015)

**Comment by lwouis** [comment] 2021-01-09 09:30
Duplicate of https://github.com/lwouis/alt-tab-macos/issues/704

**Closed by lwouis** 2021-01-09 09:30 UTC
Labels: bug, duplicate
