### ISSUE TITLE
Vertical list without window preview and shortcuts for selection

### ISSUE THREAD

**Issue by EmilCataranciuc** [lwouis/alt-tab-macos#338] opened 2020-05-16 19:59 UTC
Are there any chances to add an option for a vertical list with shortcuts to select specific window? For example, each selection would get assigned a number for a shortcut, like 1, 2, 3... 11, 12... Numbers should never be composed of characters which are too far away from each other on the keyboard, like 10. I propose the following list of shortcuts:
1...0, 11, 12, 22, 21, 23, 33, 32, 34, 44, 43, 45, 55, 54, 56, 66, 65, 67, 77, 76, 78, 88, 87, 89, 99, 98, 90, 00, 09. So shortcuts for 38 windows probably should be enough. Also, the shortcuts should be static. Like once 1 is assigned to one window it stays assigned to it. For example, once 1 is assigned to XCode for a given project it will stay assigned to it until the project is closed or the system rebooted.
But I find the window preview to be confusing since I have to adapt a dynamic view. I would rather show the following in the list: the shortcut, icon, app name, document name. So, for example, if we have Chrome in the list then the list will include the following (as an example):
3 chrome-icon "Chrome - Google.com"

https://contexts.co seems to implement similar functionalities but I wasn't able to get it to show all the open windows. And it is closed source. I would rather support an open source project (donation and translation).

**Comment by lwouis** [comment] 2020-05-17 02:13
Hi @EmilCataranciuc! Thanks for sharing this idea!

I think this is overlapping with #210. I encourage you to read the conversation in that ticket, and the ticket it links to also. There are interesting discussions around ergonomics of such shortcuts, and the vision for AltTab.

Overall, I would say that what you describe is a big departure from the current AltTab. Such a departure that I feel it could be a separate app at this point. AltTab is all about: visual memory/recognition of the windows, and chronological navigation. Both of these defining features are absent in your proposed UX, and are replaced with: memory mapping of windows to numbers, and direct navigation.

I'll close this ticket as a duplicate of #210. We can focus the conversation there.

**Closed by lwouis** 2020-05-17 02:13 UTC
Labels: duplicate, enhancement
