### ISSUE TITLE
Navigate between fullscreen apps with assigned keys

### ISSUE THREAD

**Issue by xbladesub** [lwouis/alt-tab-macos#1601] opened 2022-05-21 02:33 UTC
There is no any way to navigate between fullscreen apps in macOS using shortcuts. I mean directly navigation like from app 'a' to app 'z' escaping all other desktops and fullscreen apps. Maximum what can we do - navigate between desktops.

It would be really nice to be able to assign specific shortcuts to apps which run in fullscreen mode. So the result will be like this:

1) Choose the apps from menu and assign shortcuts to them like <Ctrl-1/2/3>
2) Navigate between those apps running in fullscreen mode using those shortcuts

Not sure if apple allow to do it, but would be really nice. (New MacBook forelock is sucks)

**Comment by lwouis** [comment] 2022-05-21 02:49
Duplicate of #210

**Closed by lwouis** 2022-05-21 02:49 UTC
Labels: enhancement
