### ISSUE TITLE
6.31.0 not showing other windows when not on first space

### ISSUE THREAD

**Issue by michael-gratton** [lwouis/alt-tab-macos#1424] opened 2022-03-08 23:25 UTC
**Describe the bug**

On my MacOS 12.2.1 machine, I just upgraded to 6.31.0, and now when I'm not on the first space, invoking AltTab only shows the active window, or in some cases, only shows the active window and the last one or two previously focused windows. It never shows all windows in subsequent spaces, however.

To reproduce:

1. Configure AltTab to show windows from visible spaces only
2. Invoke AltTab on the first space - note all windows are shown
3. Change to a different space and invoke AltTab

Expected: all windows on the space are shown

Actual: only the active window is shown

This may be application specific in some way - Firefox windows usually show up, the AltTab preferences seems to always show up. Terminal and GitUp windows only show up after being first focused. Postgres.app and Emacs windows never seem to show up?

**Comment by stevetodd** [comment] 2022-03-14 21:33
Probably the same as #1324

**Comment by paul-nameless** [comment] 2022-03-15 11:34
Not working for me as well :(

**Comment by Perlence** [comment] 2022-04-08 08:45
Currently, I work around this by restarting the apps from the other desktops that were started before AltTab. Is there a better way?

**Comment by lwouis** [comment] 2022-04-08 10:05
Closing as duplicate of https://github.com/lwouis/alt-tab-macos/issues/1324

**Closed by lwouis** 2022-04-08 10:05 UTC
Labels: bug, macOS 12
