### ISSUE TITLE
6.3.0 bugs

### ISSUE THREAD

**Issue by MrBaseMax** [lwouis/alt-tab-macos#587] opened 2020-09-08 14:26 UTC
1) The app started to hang for a couple of seconds to open the switching menu. Not always, but sometimes.
2) And this menu behaves like the option "do nothing" turned on (stays and waits for a click). Which is not. (Also "sometimes").

Seems like appeared with 6.3.0

**Comment by MrBaseMax** [comment] 2020-09-08 14:33
Combination 1. Set for current app windows

**Comment by mfn** [comment] 2020-09-08 14:44
>     1. The app started to hang for a couple of seconds to open the switching menu. Not always, but sometimes

This sounds like https://github.com/lwouis/alt-tab-macos/issues/563

**Comment by MrBaseMax** [comment] 2020-09-08 14:47
> > ```
> > 1. The app started to hang for a couple of seconds to open the switching menu. Not always, but sometimes
> > ```
> 
> 
> This sounds like #563

nope. hangs before **appear**. and stucks instead of disappear

**Comment by mfn** [comment] 2020-09-08 14:47
> nope. hangs before **appear**

Yes, the issue is unfortunately a mixup…

I do report "hang before appear" there.

**Comment by lwouis** [comment] 2020-09-08 15:09
#563 had *a lot* of discussion about performance issues and graphical glitches. Some of it have changed over the past few days as I have investigated, and updated the code in all sorts of way, not only for performance, but also to add new features.

The next release is currently being built by the CI. It will be release in a few minutes. It contains [this improvement](https://github.com/lwouis/alt-tab-macos/issues/563#issuecomment-688852964) which I suspect to be the root cause of various bad behaviors.

Could you please try out the next release, and let us know if some issues persist there?

**Comment by MrBaseMax** [comment] 2020-09-08 15:11
sure. thank you

**Comment by lwouis** [comment] 2020-09-08 15:12
Actually let's close this ticket and focus the conversation on #563. It has more people, and a rich history of discussions/investigations already.

**Closed by lwouis** 2020-09-08 15:12 UTC
Labels: bug
