### ISSUE TITLE
Better support for vertical desktops

### ISSUE THREAD

**Issue by jackbravo** [lwouis/alt-tab-macos#165] opened 2020-02-28 16:47 UTC
I tried using alt tab while rotating my main monitor, but seems like this is not supported:

It seems to try to show all the windows in the same row. For the following screenshot I had more windows opened in my desktop but they were not showing in alt-tab.

![image](https://user-images.githubusercontent.com/15214/75567758-a78ced80-5a17-11ea-8f91-7a99b5e5b654.png)

**Comment by lwouis** [comment] 2020-03-01 23:57
Hi @jackbravo! Thank you for sharing this feedback!

There was a similar discussion in #32. At the time, I tried to reproduce the issue, but couldn't, and the author of #32 didn't follow-up with more info, so the issue kind of went nowhere unfortunately.

Could you please have a look at the ticket? It would be very useful if you could go in more details about the monitor you are using (i.e. brand, size, resolution, etc) as well as generic info such as OS version, alt-tab version, etc.

Then if you're on the technical side, if would be very useful if you could print some debug info in the source code to show us what the `screen` object contains on [that line](https://github.com/lwouis/alt-tab-macos/blob/v3-poc/src/ui/main-window/ThumbnailsPanel.swift#L111).

alt-tab simply asks the OS for the screen size, and define the size of its own window as a percentage of that size, so the issue you experience and the issue experienced in #32 *have* to be that the OS API is returning that the screen is still horizontal basically. Sounds like the screen/os is failing here. We have to implement a workaround this bug, and for that, we need a way to detect that the screen *actual* size, so we need to know what the `screen` object holds. The issue being that I can't reproduce this, so I need someone who experiences this issue to help share some info.

**Comment by lwouis** [comment] 2020-03-06 05:39
Actually, I will close this ticket as duplicate, and re-open #32. There is more material in the other, especially [specific instructions](https://github.com/lwouis/alt-tab-macos/issues/32#issuecomment-558606368) on how we could make progress to fix the issue.

**Closed** 2020-03-06 05:39 UTC
Labels: bug, duplicate
