### ISSUE TITLE
Wrong size when window is minimized 

### ISSUE THREAD

**Issue by simplerick** [lwouis/alt-tab-macos#3924] opened 2024-11-30 10:41 UTC
**Describe the bug**

When I minimize the window and open alt-tab immediately after the minimized window has wrong size and bad quality

**Screenshots / video**

<img width="1352" alt="image" src="https://github.com/user-attachments/assets/b79e454a-c185-4488-bb40-a3f553b80250">

How it should be. It renders normally if wait for second after minimizing
<img width="1352" alt="image" src="https://github.com/user-attachments/assets/30c830d7-6786-4783-b403-f22039e4f422">

**Steps to reproduce the bug**

1. Open a tall window for more noticeable scaling effect
2. Click on yellow button 
3. Press cmd+tab to open AltTab right after step 2. I'm not sure, but the problem may be related to the macos animation when the window moves down and shrinks, so maybe you need to open AltTab before the window disappears completely and when it is significantly shrinked.

**Your environment**

* AltTab version: 7.5.0
* macOS version: Monterey 12.7.6

**Comment by lwouis** [comment] 2024-11-30 11:41
Hi,

Indeed, macOS animation technically distorts the window. So if you open AltTab during that time, we will show the window how it is: distorted. Normally, once the animation is over, AltTab will refresh the thumbnail and it will be crisp. Isn't that happening to you?

If not, could you please share a video? I can't reproduce locally.

Thank you 🙇

**Comment by simplerick** [comment] 2024-12-01 15:02
Hi, thank you for answer. Do you mean it should update while the AltTab window is still open? For me thumbnails stay the same way until I reopen AltTab.

https://github.com/user-attachments/assets/c74f4ac0-b42b-4313-9b7d-ac83677c7eee


No problem, here's the video. Don't hesitate to ask for more info

**Comment by lwouis** [comment] 2024-12-01 16:16
Thank you for this video

What happens if you re-open AltTab? Is it still blurry?

I reproduced your setup: Dock at the bottom, and Scale Minimizing effect. I can't reproduce your issue.

See [this video](https://youtube.com/shorts/WPXX7IypUog)

**Comment by simplerick** [comment] 2024-12-02 07:02
No, if I open it up again, it's fine. I recently updated AltTab for the first time in several months, never had this happen before. 

Try making the box less square in shape and enable the "auto-hide" and "minimize into application icon" options in dock settings. 
Here are my dock settings:
<img width="427" alt="image" src="https://github.com/user-attachments/assets/c32301e2-1ddf-460a-a1fa-ec5573439880">

**Comment by lwouis** [comment] 2024-12-02 23:25
I tried again with the same settings, and different window shapes, but couldn't reproduce.

I think it may be a bug with the particular old version of macOS you're using. Since it's a bug that's only been happening on your setup, and since it's not critical but just a bit ugly, and finally since it goes away after re-opening the switcher, I'll close this ticket for now.

Thank you 🙇

**Closed by lwouis** 2024-12-02 23:25 UTC
Labels: bug, unreproducible
