### ISSUE TITLE
Weird represenatation of apps without an open instance in v6.46.0

### ISSUE THREAD

**Issue by DeEskalator** [lwouis/alt-tab-macos#1749] opened 2022-06-29 21:36 UTC
In v6.45.0 apps without an open instance were displayed like this:
<img width="1094" alt="v6 45 0" src="https://user-images.githubusercontent.com/47759580/176548852-b778014e-f641-4613-ba2e-3cd5327b29c2.png">

In v6.46.0 it looks like this:
<img width="1054" alt="v6 46 0" src="https://user-images.githubusercontent.com/47759580/176549005-13646879-7039-44a9-9f25-f2caf96752dc.png">

The white box is kinda ugly. I personally much preferred them having this transparent look. The transparent effect is not visible  in the screenshots but it always looked gorgeous when the wallpaper blended through AltTab. I would love if you changed this to the old behaviour.

**Comment by lwouis** [comment] 2022-06-30 22:13
I experimented with translucent background and gradient background there. They look aesthetic but they have bad usability: it's easy to have colors behind AltTab that make AltTab contents hard to see. Numerous users have complained about AltTab being not visually accessible enough. This is why i improved the visuals to make the app-with-no-icon "thumbnails" clearer.

i won't revert to the old look, but i'll provide a Dark Mode design so if you use Dark Mode you'll see it instead, and it will be closer to the old design.

Closing as duplicate of https://github.com/lwouis/alt-tab-macos/issues/1752

**Closed by lwouis** 2022-06-30 22:13 UTC
Labels: bug
