### ISSUE TITLE
LibreOffice windows not appearing in Alt-tab list

### ISSUE THREAD

**Issue by mjog** [lwouis/alt-tab-macos#809] opened 2021-02-07 23:17 UTC
**Describe the bug**

LibreOffice windows not appearing in Alt-tab list

**Steps to reproduce the bug**

1. Open a document in LibreOffice
2. Press shortcut to invoke AltTab window
3. Notice LibreOffice window is not present

**Comment by lwouis** [comment] 2021-02-08 14:17
I downloaded LibreOffice, opened it, and it shows all its windows in AltTab correctly.

Could you please help me with reproduction steps, a video recording, screenshots, anything that could help me understand and reproduce so I can fix the issue?

Thank you!

**Comment by mjog** [comment] 2021-02-09 03:40
I can't currently reproduce this either, may be inttermittent? I restarted AltTab yesterday.

**Comment by lwouis** [comment] 2021-02-09 03:53
I'm going to close this ticket as a duplicate of #639. It's another example of the issue that may be useful to try to get reproduction steps

**Closed by lwouis** 2021-02-09 03:53 UTC
Labels: bug, unreproducible
