### ISSUE TITLE
Alttab causes the animation of some bullet frames to be stiff and stuck

### ISSUE THREAD

**Issue by vaf714** [lwouis/alt-tab-macos#1293] opened 2021-12-19 17:10 UTC
**Describe the bug**

If you turn on alttab, some pop-up animations will become blunt and lagging, such as all pop-up boxes in the settings, such as settings->battery->battery health, word save box, etc.

**Steps to reproduce the bug**

1. Open alt-tab
1. Go to 'system setting'
2. Click on 'battery'
3. Click on 'battery'
4. Click on 'battery health'
5. Pay attention to the animation
6. There are many other places like this

**Comment by vaf714** [comment] 2021-12-19 17:14
and, my computer is macbookpro 2021, macos is montery12.1

**Comment by lwouis** [comment] 2021-12-19 17:16
Duplicate of #718

**Closed by lwouis** 2021-12-19 17:16 UTC
Labels: bug
