### ISSUE TITLE
Infrequent macOS Sonoma showing "AltTab is sharing your screen" even when thumbnails are disabled

### ISSUE THREAD

**Issue by xconverge** [lwouis/alt-tab-macos#2881] opened 2023-10-13 03:56 UTC
**Describe the bug**

Every hour or so I still see this pop up, I cannot figure out what I am pressing or doing to trigger it, but it does seem correlated with some alt-tab keypress activity I am doing.

Continued discussion from https://github.com/lwouis/alt-tab-macos/issues/2606#issuecomment-1760210354

**Screenshots / video**

My current settings:
<img width="576" alt="image" src="https://github.com/lwouis/alt-tab-macos/assets/4219348/13aacc02-f30f-4440-90fd-fd5b0adc9da9">

**Steps to reproduce the bug**

Really unsure so far, will add information if I can come up with something repeatable. I had alttab disabled for a week due to this but will use it to try and isolate what I am pressing. 

I really only use Cmd+Tab, I dont click or hover with the mouse/touchpad too often I don't think

**Your environment**

* AltTab version: 6.62.0
* macOS version: 14.0
* Other relevant info: just a standalone M1 macbook air

**Comment by xconverge** [comment] 2023-10-13 03:57
@wookayin please feel free to add anything if you can come up with any repro steps

**Comment by Duc-NSH** [comment] 2023-10-13 04:45
I also faced this issue, I have disabled the thumbnail but sometimes the system still indicates the screen recording, I cannot reproduce the bug, it seems random occurrence...

**Comment by xconverge** [comment] 2023-10-13 07:02
Just a shot in the dark @lwouis but is this one missing the `Preferences.hideThumbnails` guard and might be it? https://github.com/lwouis/alt-tab-macos/blob/master/src/ui/App.swift#L260C25-L260C25

**Comment by lwouis** [comment] 2023-10-13 07:26
I realized that the `Preview selected window` will screenshot to show the preview. So that feature too will trigger the purple indicator.

However, it's unchecked on the OP's preferences, so it's not the root cause here, I imagine.

**Comment by victor08rdz** [comment] 2023-10-15 00:31
MacBook Air M1 2020
Sonoma 14.0 (23A344)

Appears a message of recording screen, that´s a big issue of privacy.

<img width="283" alt="image" src="https://github.com/lwouis/alt-tab-macos/assets/60049763/74f3683c-a308-49e4-b227-e850c765c240">
![Recording ALT TAB APP](https://github.com/lwouis/alt-tab-macos/assets/60049763/14b537e8-cd08-4409-a602-532605ee6742)

**Comment by xconverge** [comment] 2023-10-20 20:21
6.63.0 should have this fixed, will update/continue to investigate if it doesn't fix this

**Comment by lwouis** [comment] 2023-10-20 21:00
Indeed! I'll close this ticket. Let's re-open if the issue still happens 👍

**Closed by lwouis** 2023-10-20 21:00 UTC
Labels: bug
