### ISSUE TITLE
Focusing the wrong window with multiple displays

### ISSUE THREAD

**Issue by JakeCoxon** [lwouis/alt-tab-macos#26] opened 2019-10-15 11:45 UTC
If i have two displays setup like like
DIsplay 1: Chrome1
Display 2: Spotify Chrome2

If i control-tab from Spotify to Chrome1 then Chrome2 is focussed instead. It doesn't happen if I swap Chrome1 and Chrome2 so I have a feeling it depends on the order of the two windows being opened

**Comment by lwouis** [comment] 2019-10-17 10:25
I tested and could not reproduce.

I assumed by "Chrome 1" and "Chrome 2" you meant 2 windows of a single Chrome app. Is that the case? I tried to switch my 2 chrome windows from 1 monitor to the other, but it always focuses the right window in all scenarios, even when I try to mix up everything.

Does it happen only with Spotify, or with any other app btw?

I understand that a recording of multi screen can be hard. Could you maybe provide a step-by-step scenario to help reproduce this bug? Something like:

* Launch Spotifyapp
* Put Spotifywindow on display 2
* Launch Chrome
* Open another Chrome window
* Move the second window on display 2
* Focus Spotify with the mouse
* control-tab to chrome first window
* it focuses chrome second window

Thank you!

**Comment by JakeCoxon** [comment] 2019-10-17 11:11
Hi I determined that it only happened with Chrome windows, not Finder, Safari or iTerm, and the second app didn't matter whether it was Spotify iTerm etc. I had karabiner elements running but I closed that incase that had something to do with it.

Here's a video https://i.imgur.com/6oY1u24.mp4 As you can see I control tab to the Google window, and the Bing window has the keyboard focus. After a but of testing I determined that the Google window *is* focused but the Bing window is focussed immediately after

Your scenario basically matches mine and it didn't matter if I first focused spotify with the mouse, control tab, or command tab. Unfortunately I tried quitting everything and starting from scratch but now I can't reproduce it. Will let you know if I run into it again

**Comment by lwouis** [comment] 2019-10-17 14:45
> Unfortunately I tried quitting everything and starting from scratch but now I can't reproduce it

That's why I asked for a step-by-step because I was thinking that somehow the order **the apps** and the windows are opened may matter here. Actually even alt-tab-macos itself. If you start it in the middle of an app opening for example there may be a desync like we see on the video.

For now I'll flag the issue as unreproducible and close it. Please open it again if you stumble upon it again. Hopefully it was a fluke that's extremely unlikely to happen :)

**Closed by lwouis** 2019-10-17 14:45 UTC
Labels: unreproducible
