### ISSUE TITLE
When no current window Alt-tab goes too far back

### ISSUE THREAD

**Issue by leenapps** [lwouis/alt-tab-macos#1044] opened 2021-07-21 07:45 UTC
**Is your feature suggestion related to a problem? Please describe.**
When I close the last window of an application then press alt-tab for quick switch or hold alt-tab down, the window that it switches back to is two windows back.

**Describe the solution you'd like**
If the current application has zero windows or no windows are active then alt tab should go to the first item on the list

**Describe alternatives you've considered**
Switching back to the previous window first then closing the window with the red x. That's quite inconvenient

**Comment by leenapps** [comment] 2021-07-21 08:33
I've added this to showUiOrCycleSelection that is triggered on command tab It's having the desired effect.
Is this kind of behaviour desirable for others? Does the implementation fit into the app correctly? I noticed that Windows.list.first?.application.dockLabel was nil I am fetching the titles directly from NSWorkspace.

Windows.list.first?.application.dockLabel is nil at this point.  I'm not sure why
`    func showUiOrCycleSelection(_ shortcutIndex: Int) {
   ...
   ...
   ...
			
			let dln = Windows.list.first?.application.runningApplication.localizedName
			
			let fman = NSWorkspace.shared.frontmostApplication?.localizedName
			
			if fman == dln{
				Windows.cycleFocusedWindowIndex(1)
			}`

**Comment by lwouis** [comment] 2021-07-22 01:17
I was able to reproduce the issue. It seems like a bug with the thumbnails index not being updated in that particular use-case. It normally gets updated because when you close a window, another will get focus, but here this event is not happening. A piece of code to update indexes is missing for that use-case.

I'll look into it

**Comment by lwouis** [comment] 2021-08-11 17:16
This issue turned out to be pretty complex. There are other scenarios than the OP which are a problem. Overall, the situation that's not correctly handled is: no window is focused.

This can happen from:

* Closing the last window of an app (when the app stays open)
* Clicking on the Desktop, which focuses Finder but doesn't focus any Finder window (if any exist)
* Switching to an app which doesn't create a new window on switch
* Etc

To handle this, AltTab now keeps track of the focused window of each app (if any), and if the currently active app has none, it will highlight the left-most thumbnail, instead of the second one as it usually does.

This UX is also what Windows 10 does, I double-checked.

**Closed** 2021-08-30 15:15 UTC
Labels: bug
