### ISSUE TITLE
Webex in-call window doesn't focus when selected

### ISSUE THREAD

**Issue by gordon8214** [lwouis/alt-tab-macos#921] opened 2021-04-16 22:26 UTC
In the [Cisco Webex Meetings](https://www.webex.com/video-conferencing) app, switching to the in-meeting view works maybe 1 in 10 attempts. The Webex app is foregrounded (menubar appears) but the meeting window stays in the background.

## Setup
- Cisco Webex Meetings 41.4.4.10
- AltTab 6.20.0

## Steps
1. Install Cisco Webex Meetings
2. Create a new meeting (doesn't need any participants).
3. Switch away from Webex app.
4. Switch back to Webex with AltTab.

**Comment by lwouis** [comment] 2021-04-17 06:51
I installed the app, and was able to reproduce the issue. It's very indeterministic though. I got it to happen 3 times in maybe 50 switch.

**Comment by lwouis** [comment] 2021-04-17 07:11
Closing in favor of https://github.com/lwouis/alt-tab-macos/issues/922 where the overarching issue can be addressed

**Closed by lwouis** 2021-04-17 07:11 UTC
Labels: bug

**Comment by keaukraine** [comment] 2022-07-08 09:01
I still am able to reproduce it 100% with Webex call window.

**Comment by lwouis** [comment] 2022-07-08 13:46
@keaukraine could you please open a new ticket with steps to reproduce and a video?

**Comment by keaukraine** [comment] 2022-07-14 09:00
@lwouis Sorry I cannot record video because it is not my own computer but the one provided for work by my employer.

I can only say that I use Mac OS 12.4 and issue happens 100% times I switch to Webex video meeting window using Alttab app.

**Comment by citruz** [comment] 2022-07-21 08:42
Happens for me also 100% of the time, even without an external display.

**Comment by citruz** [comment] 2022-07-21 20:55
Done #1803
