### ISSUE TITLE
XQuartz windows do not appear in altTab

### ISSUE THREAD

**Issue by PLanB2008** [lwouis/alt-tab-macos#2214] opened 2022-12-20 09:11 UTC
**Describe the bug**

When running a X11 application like xeyes via xquartz the application window does not appear.

**Screenshots / video**

![grafik](https://user-images.githubusercontent.com/26460239/208628787-88e836c1-2a4c-4d39-a9a1-4f3876133fba.png)

**Steps to reproduce the bug**

1. Install Xquartz (eg. via brew)
2. start xeyes or every other X application
3. Use AltTab

**Your environment**

* AltTab version:  6.51.0
* macOS version: 13.0.1 (22A400)
* Other relevant info: e.g. using external keyboard, multiple monitors, etc

Update: Provided more clear screenshot

**Comment by lwouis** [comment] 2022-12-20 10:15
I downloaded Xeyes [here](https://langui.net/xeyes/), and was able to reproduce the issue.

After debugging it, I can confirm that it's an issue from the app itself. It was 99% chance, but I can confirm. The app does 2 things wrong:

* It doesn't trigger "new window" AX events. This may be a flow in the tech behind Quartz, or it may just be some issue in the Xeyes app. Not sure, but the end result is that AltTab is not notified by the OS that Xeyes spawned a window, thus it doesn't see it
* When AltTab is spawn and Xeyes is already opened, AltTab doesn't rely on the event discussed above, but instead asks for the app's windows through another AX API call. That call fails in the case of the main Xeyes window because that window is set to the `CGWindowLevel` of `1`. This level is how "high" the window is on the stack of other windows on screen. The value of `1` is undocumented, and created issues in the past, so AltTab considers it a bug.

There is nothing much AltTab could do. This app has issue. I wonder if it's the same for "every other X application" as you wrote, or more of a case-by-case basis, with some apps actually behaving properly and being listed in AltTab.

Closing the ticket as unactionable on our end.

**Closed by lwouis** 2022-12-20 10:15 UTC
Labels: bug
