### ISSUE TITLE
When the shortcut key triggers the display, it will be white for a moment.(Included video)

### ISSUE THREAD

**Issue by lowking** [lwouis/alt-tab-macos#3148] opened 2024-01-31 11:07 UTC
**Describe the bug**

When the shortcut key triggers the display, it will be white for a moment.

**Screenshots / video**

https://github.com/lwouis/alt-tab-macos/assets/33308659/7ff611a1-c666-4ec5-9a57-383b38ae79b0

**Steps to reproduce the bug**

Wait for more than 5 seconds and press the shortcut key.
Please note that the interval between the two shortcut keys should be longer.

**Your environment**

* AltTab version: 6.65.0
* macOS version: macOS 13.5 (22G74)
* Other relevant info: e.g. using external keyboard, multiple monitors, etc
using external keyboard and monitor
The recording screen can not be seen, and the mobile phone shooting needs to be slow to see accurately.

**Comment by lowking** [comment] 2024-01-31 11:11
Two frames from the video:
![image](https://github.com/lwouis/alt-tab-macos/assets/33308659/8ee1a902-e117-42a2-a929-8d7dd6f0d86f)
![image](https://github.com/lwouis/alt-tab-macos/assets/33308659/da5fd431-c651-492c-8971-1741900748ee)

By the way, there is a problem with the steam icon display

**Comment by lwouis** [comment] 2024-01-31 13:24
Duplicate of https://github.com/lwouis/alt-tab-macos/issues/2342

**Closed by lwouis** 2024-01-31 13:24 UTC
Labels: bug
