### ISSUE TITLE
app doesn't work when a resolution changing video is played

### ISSUE THREAD

**Issue by alucardontop** [lwouis/alt-tab-macos#2084] opened 2022-11-05 18:24 UTC
**Describe the bug**

Play a resolution changing video like the one attached and try to use the app
[cat.webm](https://user-images.githubusercontent.com/89560393/200135231-1a5b764b-fa7c-4162-84a4-0418f3b2257f.webm)

**Comment by lwouis** [comment] 2022-11-05 20:50
Hi,

First of all, please use the template that's provided when filling a bug. It helps produce a clear, understandable, reproducable bug report. You didn't use the template, so your report suffers from it.

You mention "doesn't work". What do you mean? It crashes? It doesn't display what you would expect? Etc
You mention to "Play a resolution changing video". With which video player? Chrome doesn't resize its window for instance.

In any case, I opened the video with VLC, which resizes the video dynamically. AltTab handled this remarkably well:

https://user-images.githubusercontent.com/106195/200140621-58698890-30a4-4bc7-9abb-3d7f5d6166d4.mov

I'll close this ticket since it seems like the use-case is correctly supported. Please feel free to bring further details regarding the issue, showing that indeed there is an issue with AltTab. If it's actionable, I'll re-open the ticket so we can look further into it.

**Closed by lwouis** 2022-11-05 20:50 UTC
Labels: bug, unreproducible
