### ISSUE TITLE
`,` shortcut to open preferences

### ISSUE THREAD

**Issue by probablykasper** [lwouis/alt-tab-macos#1983] opened 2022-09-29 22:16 UTC
**Is your feature suggestion related to a problem? Please describe.**

I'd like to more quickly access the AltTab settings

**Describe the solution you'd like**

Pressing `,` when the AltTab menu is open would open the preferences

**Comment by lwouis** [comment] 2022-09-30 00:10
Duplicate of https://github.com/lwouis/alt-tab-macos/issues/1813

**Closed by lwouis** 2022-09-30 00:10 UTC
Labels: enhancement

**Comment by probablykasper** [comment] 2022-09-30 02:07
Sorry for not looking thoroughly enough - and thanks for making AltTab! ❤️
