### ISSUE TITLE
app ignores windows opened via shell script in applescript

### ISSUE THREAD

**Issue by mvaculciak** [lwouis/alt-tab-macos#1202] opened 2021-11-03 15:00 UTC
**Describe the bug**

When a window is opened using a shell script in applescript, the window gets ignored by the alttab switcher.

**Steps to reproduce the bug**

running the following script should reproduce the bug (one can't get to the newly opened Finder window by alttab) 

tell application "Finder"
	do shell script "open -n /Applications/"
end tell

**Comment by lwouis** [comment] 2021-11-05 11:22
I tried to reproduce, and the window shows correctly on my machine. That is, after I changed `open -n` to `open`. Before that, the script doesn't even open a window for me. After I removed the `-n`, it opens the window, and I see it in AltTab.

What's your macOS version, and AltTab version?\
How are you running the AppleScript?

I ran the script from:
* Script Editor
* Terminal.app by running `osascript -e 'tell application "Finder"' -e 'do shell script "open /Applications/"' -e 'end tell'`
* Terminal.app by running `osascript ~/Desktop/alttab-issue1202.scpt` with the scpt file containing the snippet

**Comment by mvaculciak** [comment] 2021-11-06 16:20
Hi, thanks for the response! 
Sorry for not providing the full description - I'm running on m1 macbook pro with Big Sur 11.5.2 (20G95). The AltTab version is 6.26.0. 

The -n should force opening a new app window, which is crucial for me. I have tried your way (executing `osascript -e 'tell application "Finder"' -e 'do shell script "open /Applications/"' -e 'end tell'` in terminal) and it works fine. Unfortunately opening new finder window was just poorly chosen minimal working example. 
What I need at the end is the following: when pressing cmd+down (opening a file in finder) an applescript is executed to check whether the filename is “CMakeLists.txt” in which case a new QtCreator window should be opened. Otherwise all works just like cmd+down.

To bind the script to the cmd+down shortcut I use BetterTouchTool (the option is "Launch Application / Open File / Start AppleScript”). However, seeing your answer I have tried to narrow the problem down a bit and simply run the shell command 
`open CMakeLists.txt -n -a /Applications/Qt\ Creator.app`.
This opens the CMakeLists.txt in a new Qt Creator (Qt Creator 4.15.2) app as desired, however it is not visible in AltTab. At the same time HyperSwitch sees it normally (but I’d like to keep using AltTab as it allows one to cycle through minimised windows and is overall prettier). Could you please try to reproduce this?

Sorry for the very confusing bug description. Just in case I’m also attaching the script, probably written in a very non-elegant way, but I’m new to applescript and so far it’s been almost nothing but pain.

>tell application "Finder"
	set picked to selection as alias list
	set picked_item to picked’s item 1
	set picked_item_path to POSIX path of picked_item
	set picked_item_name to name of picked_item
end tell
>
>if picked_item_name = "CMakeLists.txt" then
	do shell script "open " & quoted form of picked_item_path & " -a /Applications/Qt\\ Creator.app -n"
else
	try —check if picked_item is a folder and if so, open it (not in a new window)
		do shell script "cd " & quoted form of picked_item_path
		tell application "Finder" to set target of front Finder window to picked_item
	on error —if picked item is not a folder, it’s a file -> open it
		tell application "Finder" to open picked_item_path
	end try
end if

**Comment by lwouis** [comment] 2021-11-07 09:02
I downloaded QT Creator, and could reproduce the issue using the shell command you shared (i.e. `open CMakeLists.txt -n -a /Applications/Qt\ Creator.app `).

After debugging the issue, it seems to be specific to QT Creator. As you've seen, Finder works well. I also tried `open CMakeLists.txt -n -a /System/Applications/TextEdit.app` and it works fine as well.

QT Creator seems to have a bug. Let me try to explain how it goes step by step in AltTab:

* QT Creator is launched (i.e. new process in the OS)
* AltTab notices that, and:
  * Starts observing to Accessibility Events from QT Creator
  * Uses the Accessibility API to ask for QT Creator windows. **At this point, it returns 0**
* QT Creator continues to boot, and opens its first window. At this point, AltTab should receive an Accessibility Event with the new window info. It doesn't.
* Later, if I pause the debugger, and manually use the Accessibility API to ask for QT Creator windows, it returns the one window.

Thus, the issue is that QT Creator doesn't have the window ready when it's asked for windows very early. That's normally no problem for most apps, as they will open windows later, and emit an Accessibility Event (i.e. `AXWindowCreated`) which AltTab will use to notice the window. Here QT Creator doesn't emit that event.

I'm afraid I can't see any workaround AltTab can do about this. This QT Creator must affect other accessibility apps like screen readers for blind people for instance. The only thing to do is file a ticket with QT Creator maker company, and ask them to fix this. You can share my investigation info above.

I'll close this ticket as I don't see any possible action from AltTab side to deal with this issue.

**Closed by lwouis** 2021-11-07 09:02 UTC
Labels: bug, unreproducible
