### ISSUE TITLE
blank white space instead of menubar icon showing since installing v5.0.0

### ISSUE THREAD

**Issue by foss-** [lwouis/alt-tab-macos#542] opened 2020-08-18 16:41 UTC
**Describe the bug**

Problem was introduced with v5 update.

**Screenshots / video**

![menubar icon](https://user-images.githubusercontent.com/5708172/90540165-19512300-e181-11ea-846c-05ac62cf5e9d.png)

**Steps to reproduce the bug**

update to v5.0.0

There are a few other issues I am seeing since the update: alt-tab UI is not showing at all on macOS 10.15.6 (supplement update). Also when clicking the white menubar space the menu options do show, but settings won't open.

Feels like all those problems are related. Let me know if you need additional information / want anything specific tested. Console does not show any errors when searching for "alt-tab". All issues mentioned are persisting after restarting the mac.

**Comment by mparry** [comment] 2020-08-19 09:10
FWIW, I see this white icon when I start AT but it is replaced by the correct icon after a second or two

**Comment by lwouis** [comment] 2020-08-19 09:36
Hey @foss-! Thanks for sharing this issue!

I'm not sure what I'm looking at on the screenshot. Did you add a white rectangles on the screenshot yourself to cover parts of it? I think on the top left I see the white menubar section you mentioned, but what about the white bar under it? And on the right?

Could someone share a screenshot with a bit more context like where I can see the icons next to it to ground myself when trying to understand the visuals I'm looking at? 🙇

**Comment by mfn** [comment] 2020-08-19 09:39
> Did you add a white rectangles on the screenshot yourself to cover parts of it? I

No, that's how it looks, same to me:
![image](https://user-images.githubusercontent.com/87493/90618575-7fd15200-e210-11ea-8163-837f6f017f1f.png)

(but then it disappears, because https://github.com/lwouis/alt-tab-macos/issues/544 )

**Comment by mfn** [comment] 2020-08-19 09:39
The command on my system:
```
~ $ defaults read com.lwouis.alt-tab-macos
{
    MSAppCenter310AppCenterUserDefaultsMigratedKey = 1;
    MSAppCenter310CrashesUserDefaultsMigratedKey = 1;
    MSAppCenterInstallId = "C0173104-8752-42C1-88B3-B4096060FC22";
    MSAppCenterPastDevices = {length = 2195, bytes = 0x62706c69 73743030 d4010203 04050607 ... 00000000 00000685 };
    MSAppCenterSessionIdHistory = {length = 804, bytes = 0x62706c69 73743030 d4010203 04050607 ... 00000000 0000023e };
    MSAppCenterUserIdHistory = {length = 799, bytes = 0x62706c69 73743030 d4010203 04050607 ... 00000000 00000239 };
    "NSStatusItem Preferred Position Item-0" = "759.5";
    "NSWindow Frame SUStatusFrame" = "760 696 400 129 1920 240 1344 840 ";
    "NSWindow Frame SUUpdateAlert" = "615 360 690 577 0 0 1920 1057 ";
    "NSWindow Frame com.sindresorhus.Preferences.FrameAutosaveName" = "767 469 386 174 0 0 1920 1057 ";
    SUAutomaticallyUpdate = 0;
    SUEnableAutomaticChecks = 1;
    SUHasLaunchedBefore = 1;
    SULastCheckTime = "2020-08-19 06:48:20 +0000";
    SUUpdateGroupIdentifier = 1934599494;
    SUUpdateRelaunchingMarker = 1;
    arrowKeysEnabled = true;
    cancelShortcut = "\\U238b";
    closeWindowShortcut = W;
    hideShowAppShortcut = H;
    hideSpaceNumberLabels = true;
    holdShortcut = "\\U2318";
    maxScreenUsage = 80;
    metaKey = "\\U2318 command";
    minCellsPerRow = 7;
    minDeminWindowShortcut = M;
    nextWindowShortcut = "\\U21e5";
    preferencesVersion = "5.0.0";
    previousWindowShortcut = "\\U21e7\\U21e5";
    quitAppShortcut = Q;
    showOnScreen = 1;
    startAtLogin = false;
    tabKeyCode = 48;
    theme = 1;
    updatePolicy = 1;
    windowDisplayDelay = 0;
}
```

**Comment by lwouis** [comment] 2020-08-19 10:18
I made a local build from @akx quick-fix PR: [AltTab.app.zip](https://github.com/lwouis/alt-tab-macos/files/5095670/AltTab.app.zip)

@foss- can you try it and see if it fixes the issue for you?

**Comment by foss-** [comment] 2020-08-19 11:47
`defaults read com.lwouis.alt-tab-macos`

https://bin.disroot.org/?345f360639742405#534KWr8o8XE8XAnkfWmAQSE55LKqtQFPXhtk4kwJXL52

Your testbuild from 1h ago opens fine and all issues are gone:

- [x] icon is displayed correct in menubar

- [x] settings open as expected

- [x] alt-tab window shows as expected

**Comment by lwouis** [comment] 2020-08-20 10:47
Closing this as duplicate of #543. Let's keep the conversation in one place 👍

**Closed by lwouis** 2020-08-20 10:47 UTC
Labels: bug
