### ISSUE TITLE
Sometimes firefox is hidden in tab switcher

### ISSUE THREAD

**Issue by nrjais** [lwouis/alt-tab-macos#1079] opened 2021-08-19 07:29 UTC
**Describe the bug**

Sometimes(Faced it 3-4 time over a span of 2 months) firefox window is not shown in the tab switcher and the only way to get it back is to restart alt-tab

**Screenshots / video**
<img width="1680" alt="Screenshot 2021-08-19 at 12 55 28 PM" src="https://user-images.githubusercontent.com/20153307/130026207-3ca99efa-a038-4e03-9972-b64d5b89b50a.png">

**Steps to reproduce the bug**

I haven't been able to reproduce this, It randomly happens, but if you need anything in the current state I can provide, But once I restart alt-tab the issue will go away and re-appear after 2-3 weeks

**Comment by lwouis** [comment] 2021-08-19 10:35
Is there any chance that this window on your screenshot started fullscreen, or was set fullscreen at some point in time? There are known issues with fullscreen windows, so i'm wondering if this is within that scope or if it's another root cause

**Comment by nrjais** [comment] 2021-08-19 11:04
No, The Zoom window is full-screen. It has always happened with Firefox only, and it randomly happens, but I think whenever this has occurred a full-screen zoom window was open, but I don't remember if it is always the case.

**Comment by lwouis** [comment] 2021-08-19 11:34
I need steps to reproduce if we want any chance to fix this 😅

Which version of macOS are you on?

**Comment by nrjais** [comment] 2021-08-19 11:50
Mojave
I will be changing my laptop after two days, Then if it happens again will try to reproduce.
It is just very rare that I can't get the steps to reach to this state knowingly.

**Comment by fredless** [comment] 2021-09-26 16:56
Volunteering that I'm seeing similar behavior with Microsoft Edge, using multiple desktops and Show Windows from Visible Desktops selected for the shortcut.  Sometimes none of the Edge windows on the active desktop are shown... after manually clicking through the open windows, and then trying again, they show up in the switcher. Happening frequently, but not precisely sure how to reproduce reliably yet.  When I figure it out I will open a new issue. Big Sure 11.5.2 and Edge v95

**Comment by lwouis** [comment] 2022-04-08 03:07
Should be fixed in v6.32.0

**Closed by lwouis** 2022-04-08 03:07 UTC
Labels: bug, unreproducible
