### ISSUE TITLE
Group by space

### ISSUE THREAD

**Issue by maciej-skurznica** [lwouis/alt-tab-macos#2526] opened 2023-05-12 08:50 UTC
**Is your feature suggestion related to a problem? Please describe.**
No

**Describe the solution you'd like**
I would love to see the ability to choose an option to display windows grouped by space and the ability to rename the spaces. This would be great as there is no other (good) alternative app that can handle spaces renaming. The user should be able to choose or not for the specific shortcut (not global setting).

**Comment by lwouis** [comment] 2023-05-12 09:09
Duplicate of #337

**Closed by lwouis** 2023-05-12 09:09 UTC
Labels: enhancement
