### ISSUE TITLE
Visible Spaces Not Working when Alt-Tab Starts Up

### ISSUE THREAD

**Issue by williamhCode** [lwouis/alt-tab-macos#1504] opened 2022-04-20 04:35 UTC
## Bug Description

If I startup AltTab with other apps opened, AltTab (with visible spaces option) not only detects just the windows on the current desktop, but also all apps that are open. The other apps that are opened however, are displayed with the +icon which is normally for apps when no windows are opened. If I reopen or open an app while AltTab is running, or make any changes to the app (closing and opening windows), this bug does not occur/ goes away.

## Screenshots

When AltTabbing -

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/83525937/164149878-53b8b3c1-3f1b-4727-b7da-34302ad4ed1e.png">

Actual Opened Windows on my Current Desktop -

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/83525937/164149973-172bf621-f470-486f-ba3d-f760e389c3b3.png">

**NOTE**: I am aware that if an app if running and has no windows, the +icons will show, but all the other apps shown in the first screenshot (except for finder) have an active window opened.

## Steps to Reproduce

1. Make sure AltTab is not running.
2. Have more than one desktop opened.
3. Have windows and apps opened on the desktop other than the current one.
4. Startup AltTab.
5. Run the AltTab shortcut that shows windows from **All Apps** and **Visible Spaces**.

## Additional Info
**Specs**
- AltTab Version 6.33.0
- MacBook Pro (13-inch, M1, 2020)
- macOS Monterey 12.2.1 (21D62)

**Comment by lwouis** [comment] 2022-04-20 06:40
I think this is a duplicate of #1324

**Closed by lwouis** 2022-04-20 06:40 UTC
Labels: bug
