### ISSUE TITLE
chrome window loss after alttab restart

### ISSUE THREAD

**Issue by Eyesfront-ZJG** [lwouis/alt-tab-macos#2893] opened 2023-10-17 11:53 UTC
**Describe the bug**

1. before alttab restart  chrome have 3  windows
<img width="1072" alt="image" src="https://github.com/lwouis/alt-tab-macos/assets/3964945/a4e79e2a-8801-4522-b7bd-959d8a87f574">

2. after alttab restart, altab only have  on chrome  window
<img width="1157" alt="image" src="https://github.com/lwouis/alt-tab-macos/assets/3964945/ecf1836a-60ff-49fd-9722-2efe69481bf1">

3.  to swith chrome  3 windows,  i need  to click another 2 window  manually first time

**Your environment**

* AltTab version: 6.61.0 +
* macOS version: 13.0 +
* Other relevant info: e.g. using external keyboard, multiple monitors, etc

**Comment by lwouis** [comment] 2023-10-17 12:16
Hi @Eyesfront-ZJG,

I think you're witnessing #1324. I'm closing this ticket as it's a duplicate of the other.

Thank you

**Closed by lwouis** 2023-10-17 12:16 UTC
Labels: bug
