### ISSUE TITLE
Missing window when using Arc Browser

### ISSUE THREAD

**Issue by sascharucks** [lwouis/alt-tab-macos#2257] opened 2023-01-13 13:05 UTC
**Describe the bug**
The Arc Browser has a feature to open links from other apps (like Mail) in a small window ("Little Arc"). This window is missing from the list of windows. When I tab between an app and back to Arc I get the main window not the small one.

**Screenshots / video**

<img width="1728" alt="SCR-20230113-jey" src="https://user-images.githubusercontent.com/670855/212326676-a95b0a48-44bd-4ff8-901b-d1c752524f81.png">

**Steps to reproduce the bug**

1. Open Arc Browser.
2. Open a little Arc window
3. Alt Tab back and forth

**Your environment**

* AltTab version: 6.52.1
* macOS version: 16.1
* Other relevant info: MBP 16" 2021

**Comment by sascharucks** [comment] 2023-01-13 13:06
I also sent this ticket as feedback to Arc.

**Comment by lwouis** [comment] 2023-01-13 13:20
Hi,

AltTab reports windows as they are. It doesn't report windows, if those windows are not detectable as windows, at the technical levels. This means that it's highly likely that Arc has an incorrect implementation of their windows. This is the reference check for a window to be considered an actual window, and be displayed by AltTab. You may want to refer the Arc customer support to this, so that they can forward to the developpers, who may fix their implementation to comply with it.

Nothing to do on AltTab's side, so closing this ticket.

**Closed by lwouis** 2023-01-13 13:20 UTC
Labels: bug

**Comment by sascharucks** [comment] 2023-01-13 16:31
Thanks for the feedback!

**Comment by lwouis** [comment] 2023-05-11 16:44
@metya the behavior you describe seems like it could be due to #1324

**Comment by metya** [comment] 2023-05-11 17:23
It seems like that. Will follow this issue. Do you have any ideas on how to fix it?) or is it an unknown behavior?

**Comment by sascharucks** [comment] 2023-06-07 07:09
I did not receive any feedback from Arc so far.

**Comment by kbakk** [comment] 2023-11-09 19:03
Has any Arc users found a workaround for this? 

@sascharucks any feedback from Arc?

**Comment by metya** [comment] 2023-11-10 00:11
@kbakk No( 
I haven't found the solution. 
Until the developers of the alt-tab do anything with that. And I think it probably would be a special hack for Arc.

**Comment by sascharucks** [comment] 2023-12-29 09:55
Didn't here back from them. I am not sure if they even answer feedback.

**Comment by Herrner** [comment] 2024-01-12 08:56
I gave feedback as well, let's see...

**Comment by oscaromsn** [comment] 2024-02-27 00:19
facing the same problem here

that's odd, because I like arc and alt-tab so much

**Comment by metya** [comment] 2024-02-28 22:57
let's reopen this issue?

**Comment by oscaromsn** [comment] 2024-04-06 20:14
since the last arc update little arc is finally showing on AltTab 🥳

**Comment by metya** [comment] 2024-04-09 22:42
That's very awesome!
I don't think so though :) In my case, the problem is still here :)

**Comment by sascharucks** [comment] 2024-04-10 09:38
I can confirm that it is working now for me as well with this version:
Version 1.37.0 (48361)
Chromium Engine Version 123.0.6312.106

🎉

**Comment by metya** [comment] 2024-04-11 13:07
ok! maybe at that time it wasn't working, but now seems to work fine. 
hooray!

**Comment by mattiacerutti** [comment] 2024-05-01 12:15
Still not working here.

**Comment by oscaromsn** [comment] 2024-05-01 13:56
yes, here sometimes it works and sometimes it don't :(

**Comment by shpodg** [comment] 2024-05-23 03:25
Still not working with arc 1.43.1

**Comment by oscaromsn** [comment] 2024-05-23 04:41
yes, it worked for a few releases, but then it stopped working again :(

**Comment by iwex** [comment] 2024-07-22 12:58
Hello! +1 - can't switch Little Arc window
@lwouis could you please take a look?

**Comment by iwex** [comment] 2024-07-22 13:31
@lwouis it's strange, because macos default cmd+` is working fine

**Comment by metya** [comment] 2024-07-22 13:55
Yeah, it's a problem on the alt-tab side, or just a happy combination of alt-tab + arc browser :)

**Comment by lwouis** [comment] 2024-07-22 16:04
Please see my [previous comment explaining why the issue is likely not on AltTab's side](https://github.com/lwouis/alt-tab-macos/issues/2257#issuecomment-1381843156).
