### ISSUE TITLE
Feature suggestion: allow app-level switching

### ISSUE THREAD

**Issue by zzamboni** [lwouis/alt-tab-macos#532] opened 2020-08-16 11:42 UTC
**Describe the solution you'd like**

It would be nice to have a way to trigger application-level switching, like the built-in macOS app switcher. This would be very useful, particularly when AltTab has been mapped to the Cmd-Tab shortcut, which renders the built-in switcher inaccessible (there seems to be no easy way to map it to a different keyboard shortcut).

This could be mapped to a different user-selectable modifier.

**Describe alternatives you've considered**

I have played a bit with Karabiner Elements and BetterTouchTool, but could not find a satisfactory solution. In BTT there is an "Application Switcher" action which can be bound to an arbitrary key, but all it seems to do is emit the Cmd-Tab key, so it triggers AltTab anyway. A similar mapping can be done in Karabiner Elements, with the same result.

**Comment by lwouis** [comment] 2020-08-16 13:46
Closing this as duplicate of #337. Let's keep the conversation in one thread

**Closed by lwouis** 2020-08-16 13:46 UTC
Labels: enhancement
