### ISSUE TITLE
Large part of an icon appears

### ISSUE THREAD

**Issue by michaelcushing** [lwouis/alt-tab-macos#2693] opened 2023-07-24 17:59 UTC
I am running Alt/Tab 6.61.0 and MacOS 13.4.1.  

Sometimes a part of an icon appears covering the alt/tab window.   See attached screen shot.  I also attach shots of my set up.

<img width="1725" alt="Screenshot 2023-07-24 at 1 56 54 PM" src="https://github.com/lwouis/alt-tab-macos/assets/7904798/91150291-a501-486e-83e6-759d052002d4">

<img width="581" alt="Screenshot 2023-07-24 at 1 54 32 PM" src="https://github.com/lwouis/alt-tab-macos/assets/7904798/81c57d97-6f5f-4dff-9e75-aa6692b33394">

<img width="581" alt="Screenshot 2023-07-24 at 1 54 25 PM" src="https://github.com/lwouis/alt-tab-macos/assets/7904798/f7c3deb1-1120-434d-9662-452dd29b918e">

**Comment by lwouis** [comment] 2023-07-24 18:04
Hi @michaelcushing,

Do you think the giant red rounded-square is an app icon? Could it be an app badge? Like the red badge you get when you have unread emails. If it's an app icon, do you know which app it is? How often does this happen? Everytime, once in a while?

Any additional info like this could help diagnoze/reproduce the issue.

Thank you

**Comment by michaelcushing** [comment] 2023-07-24 18:48
It is definitely an icon.  But I cannot figure out the pattern of why one appears when it does.  First it was just the music icon.  Now it is the Skim (pdf viewer) icon, but there are two of them.  As a test, I just killed Skim, the two disappeared, but now the Preview one is showing.  Oddly, the two Skim ones were on the left side and the Preview one is now on the right side.

I will try and keep looking for a pattern.

**Comment by aicayzer** [comment] 2024-01-09 10:50
Hello! @michaelcushing did you ever manage to identify the pattern? I too am struggling with the same issue... 

When it started happening I assumed I would be one of many and was v. surprised when it transpired only one person, you, had flagged this bug (and c. 6 months ago). Reading through this thread a few things came clear:

~~1. If niche-mac app configuration was the great variable of love, you and I would be match made in heaven 😍~~
1. We have similar Alt-Tab config ! 
2. The problem must relate to either one of them, or more likely given how few people have had this issue, a combination of them

I spent a while trying to diagnose the issue and couldn't figure it out. I first read this thread a couple of days ago and was hoping I'd identify the bug and return back within a couple of days to highlight it.... skip forward to today and I'd accepted defeat. As I was restoring my settings, in a moment of drama fit for a "Mac App Config Settings Love Story" like ours, I managed to reproduce the issue. I don't know whether there are other ways you can induce this problem but I can say this is certainly one! 

**Reproduction of the Problem**
As it turns out I was wrong to think it was likely a combination of settings and instead it is as simple as: 
If `Window app icon size` = `0px` (aka it doesn't have a value), then all hell breaks loose with App Icons. Example screenshots of this where you can see the difference made by having 1px (or any value > 0px) vs 0px set.

![Alt-Tab Bug](https://github.com/lwouis/alt-tab-macos/assets/22304629/9fe1f16f-bb6b-4466-8b24-dd3e90d8bb74)

Now I'm a little rushed atm but, hopefully later today or at worst sometime this week I will open an PR with the fix. 

@lwouis would be remiss not to end this message with thanking you for building a wonderful app! I am a new, very happy, user.

**Comment by lwouis** [comment] 2024-01-09 10:55
Thank you @aicayzer for the follow-up.

It's definitely a bug in the layout logic. That logic is quite complex because:

* AltTab allows complex customs layouts
* AppKit (macOS library we use to display our UI) has messy layout APIs stacked on top of each other over decades. It's very hard to debug such issues.

Going forward, I think #351 is the key. We will reduce the amount of layout customization users can do. That will probably eliminate this bug, as well as others like:

* https://github.com/lwouis/alt-tab-macos/issues/814
* #525

**Comment by lwouis** [comment] 2024-10-09 22:38
This issue will probably be gone with the revamp from v7.0.0. I'm closing this issue. Please share here if anyone still faces it 👍

**Closed by lwouis** 2024-10-09 22:38 UTC
Labels: bug
