### ISSUE TITLE
MacOS app Books doesn't show open book

### ISSUE THREAD

**Issue by matthijsbro** [lwouis/alt-tab-macos#748] opened 2020-12-27 09:55 UTC
**Describe the bug**

When opening a book in the Books app it does not show the reading window with the open book

**Steps to reproduce the bug**

1. Go to Books
2. Click on > Open a book
3. Option+tab to alt-tab

**Comment by mixe3y** [comment] 2020-12-29 09:02
Try enable the following setting:
Appearance -> Show standard tabs as windows ✅

**Comment by matthijsbro** [comment] 2020-12-29 10:44
That didn't do it. Although I did just see the open book window in alt-tab,
it disappeared now that I put this 'show standard tabs as windows' on (and
off again too). I restarted the app, to no avail.


Op di 29 dec. 2020 om 10:02 schreef Janos Miko <notifications@github.com>:

**Comment by lwouis** [comment] 2021-01-02 02:36
Duplicate of https://github.com/lwouis/alt-tab-macos/issues/627

**Closed by lwouis** 2021-01-02 02:36 UTC
Labels: bug
