### ISSUE TITLE
AltTab will greatly impact speed of invoking "Go to the folder" in opanpanel or savepanel

### ISSUE THREAD

**Issue by RoadToDream** [lwouis/alt-tab-macos#788] opened 2021-01-28 04:48 UTC
**Describe the bug**

I know it's a pretty weird bug, and have no ideas what may cause that. When AltTab is running, invoking "Go to the folder" by Cmd+Shift+G is noticeable slower than not running. 

**Screenshots / video**

Add screenshots to help explain your problem. You can also use Loom to easily record your screen to show the bug in action. That is *really* helpful!

**Steps to reproduce the bug**

https://user-images.githubusercontent.com/8088354/106091268-e4a6a780-60e0-11eb-8f69-fee1a5c4ae9b.mp4

**Comment by lwouis** [comment] 2021-01-28 06:17
Duplicate of #718

**Closed by lwouis** 2021-01-28 06:17 UTC
Labels: bug
