### ISSUE TITLE
AltTab Window doesn't hide at times on MacOS 12.5 (M1)

### ISSUE THREAD

**Issue by sarthikg** [lwouis/alt-tab-macos#1811] opened 2022-07-24 16:28 UTC
**Describe the bug**

At times when using Alt + Tab action on the keyboard, the AltTab Window showing the currently opened tabs does not hide automatically. I have to manually press Esc key in order to hide it.

Do note, even after disengaging the Alt & the Tab key, the window does not hide.

**Screenshots / video**

https://user-images.githubusercontent.com/38561148/180656790-d651176b-2079-4643-827b-519d01200b46.mov

**Steps to reproduce the bug**

1. Open any application, or be at home screen.
2. Press Alt & Tab keys simultaneously to get the AltTab engaged.
3. Press Tab a couple of times (or even do not press it).
4. Disengage the Alt and Tab keys
5. The AltTab window does not disappear
6. Press the Esc key to disengage it.

**Comment by vpatel-dev** [comment] 2022-07-28 14:46
Any updates on this? It has been bugging me a lot lately.

**Comment by lwouis** [comment] 2022-07-28 16:10
I can't reproduce this issue.

Some questions that may help find why it happens on your machine:

* What keyboard are you using? If not the one from the laptop, what's the physical layout (photo would help)?
* Did you change the language (macOS calls this Input Source) in macOS?
* Do you have any software interacting with keyboard inputs (e.g. karabineer, BTT, etc)?
* macOS version?
* AltTab version?
* Intel CPU or Apple Silicon (e.g. M1, M2)?

**Comment by hexedpackets** [comment] 2022-08-06 18:17
I've been running into this issue as well. I have an external keyboard and use Karabiner, which both seem to be requirements for the bug. I've swapped option and command on my external keyboard, did not change the language. Its an ANSI keyboard (Kinesis Freestyle Edge). The only thing I've changed in Karabiner is function keys on the internal keyboard, nothing on the external one.

This is what I've found:

- AltTab stays open if I move my mouse at all when I hit tab it on my external keyboard and Karabiner running
- AltTab always closes when my keyboard is disconnected (with or without Karabiner)
- If Karabiner is not running, AltTab closes when triggering from my external keyboard
- With my external keyboard and Karabiner running, if my mouse is perfectly still AltTab will close

A related behavior I'm seeing is if I don't move my mouse, trigger AltTab, release tab but keep holding command before moving my mouse then whatever window is highlighted in AltTab will be switched to as if I had released the command key.

This is on an M1 Macbook Pro running 12.4
Karabiner 14.6.0
AltTab 6.46.1

**Comment by lwouis** [comment] 2022-08-06 19:02
@sarthikg @vpatel-dev do you also use Karabineer like @hexedpackets?

**Comment by sarthikg** [comment] 2022-08-06 19:09
@lwouis , I am not using any keyboard modifier app.

**Comment by sarthikg** [comment] 2022-08-06 19:21
@lwouis Additional glitches happening....

https://user-images.githubusercontent.com/38561148/183263280-1311124c-564e-4d4c-b13c-f700afbc2eee.mp4

**Comment by vpatel-dev** [comment] 2022-08-06 19:25
> @sarthikg @vpatel-dev do you also use Karabineer like @hexedpackets?

No.

**Comment by lwouis** [comment] 2022-08-06 19:37
@sarthikg it looks like you have multiple AltTab running at once. What shows in Activity Monitor if you search "AltTab" when such behavior happens?

**Comment by sarthikg** [comment] 2022-08-06 19:40
@lwouis You are not wrong.
<img width="1201" alt="image" src="https://user-images.githubusercontent.com/38561148/183263875-19b11a82-b517-4da5-85c5-0021ca762b02.png">

**Comment by vpatel-dev** [comment] 2022-08-06 19:44
> @lwouis You are not wrong. <img alt="image" width="1201" src="https://user-images.githubusercontent.com/38561148/183263875-19b11a82-b517-4da5-85c5-0021ca762b02.png">
> 
> Quitting one of them solved all the issues for me. Can you folks also confirm once @vpatel-dev , @hexedpackets ? Will close the issue after your confirmations.

Sure. The weird thing is, this is not a constant issue. It happens only sometimes. If it ever happens, I will quit one of the AltTab processes, come back here, and let you know what happens.

**Comment by lwouis** [comment] 2022-08-06 19:47
Could you try these steps here to try and confirm the root cause? https://github.com/lwouis/alt-tab-macos/issues/1840#issuecomment-1205481275

**Comment by sarthikg** [comment] 2022-08-06 19:50
@lwouis Should there be a restriction to prevent multiple processes of AltTab from running? I dont see a use-case where multiple processes for it should be required.

**Comment by hexedpackets** [comment] 2022-08-06 19:58
> @lwouis You are not wrong. <img alt="image" width="1201" src="https://user-images.githubusercontent.com/38561148/183263875-19b11a82-b517-4da5-85c5-0021ca762b02.png">
> 
> Quitting one of them solved all the issues for me. Can you folks also confirm once @vpatel-dev , @hexedpackets ? Will close the issue after your confirmations.

Nope, just one instance running for me.

**Comment by lwouis** [comment] 2022-08-06 23:16
> @lwouis Should there be a restriction to prevent multiple processes of AltTab from running? I dont see a use-case where multiple processes for it should be required.

A use-case for having multiple processes running at the same time is when you restart AltTab (e.g. in Preferences > General > Reset preferences and restart). The app will start a new instance of itself, then the first instance will quit. For a brief moment, both apps will co-exist. It has never been an issue so far on my machine. I wonder if this restart, or other restart (like what Sparkle does after an auto-update), could be the cause of the multiple instances of AltTab on some people's computer. Though I think it's more likely people have multiple versions installed.

**Comment by veerpatel-dev** [comment] 2022-08-23 10:09
> > @lwouis You are not wrong. <img alt="image" width="1201" src="https://user-images.githubusercontent.com/38561148/183263875-19b11a82-b517-4da5-85c5-0021ca762b02.png">
> > Quitting one of them solved all the issues for me. Can you folks also confirm once @vpatel-dev , @hexedpackets ? Will close the issue after your confirmations.
> 
> Sure. The weird thing is, this is not a constant issue. It happens only sometimes. If it ever happens, I will quit one of the AltTab processes, come back here, and let you know what happens.

OK so it turns out quitting one of the processes solves the issue.

**Comment by lwouis** [comment] 2022-11-06 23:10
Closing this issue as I believe there is nothing to change on AltTab side. The multiple versions of AltTab is discussed in #1840, and seems to come from the OS, but will be discussed more.

The other issues of complex keyboard/software setups are very likely to be issues external to AltTab. AltTab shortcuts are quite mature at this point, so issues with them represent, for 9 tickets out of 10 that I work on, issues on the author's machine, with software or hardware interfering.

**Closed by lwouis** 2022-11-06 23:10 UTC
Labels: bug, unreproducible
