### ISSUE TITLE
Thunderbird and Skim window now showing up in list of windows in AltTab

### ISSUE THREAD

**Issue by AgilentGCMS** [lwouis/alt-tab-macos#772] opened 2021-01-12 17:15 UTC
**Describe the bug**

I have three windows from three different apps open on my current workspace, geany (a code editor), iTerm2 (terminal), and thunderbird (email client). I have AltTab set up to [display all apps from visible spaces](https://drive.google.com/file/d/1k7xNJMSa8lhLyRO8uSE44AmZhGbtMJs0/view?usp=sharing) upon Cmd+Tab. However, when I hit Cmd+Tab, thunderbird does not show in the thumbnails. I've [taken a screenshot](https://drive.google.com/file/d/1s0KLc56lgO0Oyup7xClZWWBvnrh63zY6/view?usp=sharing) right after hitting Cmd+Tab and before releasing Cmd. You can see all three windows, i.e., none of them are hidden or minimized, yet the AltTab thumbnails on top only contain two.

**Steps to reproduce the bug**

1. Open several apps, including Thunderbird.
2. Hit Cmd+Tab to switch between them.

**Note:** This is not 100% reproducible. Sometimes AltTab [does show a thumbnail for thunderbird](https://drive.google.com/file/d/1xeV4U674paivamecg4dVchtwOoBiwPxD/view?usp=sharing). However, once it starts to *not* show the thunderbird thumbnail, *the only fix is to quit and restart thunderbird*. I have not checked if this bug exists for other apps, I'm reporting for thunderbird because that's where I first noticed it.

**Comment by mfn** [comment] 2021-01-13 06:19
> This is not 100% reproducible

I can confirm that I've seen this behavour in recent times too, but it's not clearly reproducible (and happened really rarely to me).

**Comment by lwouis** [comment] 2021-01-13 15:21
I downloaded Thunderbird, but it always shows in AltTab in my tests.

Could you please find steps that reproduce the issue more frequently? I can't reproduce the issue unfortunately

**Comment by AgilentGCMS** [comment] 2021-01-13 17:53
It might well be a duplicate of #639. I have not found a way to reproduce this behavior reliably, it remains stubbornly intermittent. When I submitted this bug, the thunderbird window was in the workspace where it was opened (I use multiple workspaces), I was not connected to an external monitor, and no window was fullscreen. 

I understand it's hard to debug an issue you can't reproduce. The next time this happens, I will try to trace back what I was doing in or to the missing window before. Since this is not reproducible, is there something I/we can do to help debug *once this behavior starts*?

**Comment by AgilentGCMS** [comment] 2021-01-13 19:35
Just saw this behavior for a different app, Skim, the PDF reader. This time the behavior is repeatable, and here's how:

1. I started with two apps open on my workspace, Thunderbird with two windows, and Skim with one document open in one window. At this point, AltTab shows me three thumbnails, as expected. 
2. In Skim, I opened another document, which opens in a new window. This new window is now on top of all other windows.
3. However, at this point AltTab does not show the new Skim window. It still shows the two thunderbird windows and the earlier Skim window.
4. If I now select another window, and then click on the new Skim window to bring it *back* to the foreground, this causes AltTab to learn about the new Skim window. From this point on, AltTab shows four windows, as expected.
5. I can close the new Skim window, then repeat step 2, which reproduces steps 3 and 4 every time.

**Comment by lwouis** [comment] 2021-01-14 04:25
@AgilentGCMS I installed Skim, and tried to reproduce, but [it's not happening for me](https://youtu.be/bwwLnjDEBqs).

**Comment by AgilentGCMS** [comment] 2021-01-15 17:20
@lwouis I just tried doing what you did, i.e., open both files from Finder > Open with > Skim, and indeed AltTab shows both windows. However, can you do the following instead:

1. After opening the first file, close the finder window.
2. Open the second file file by hitting Cmd+O in Skim, then selecting the second file from the file selector that pops up.

On my computer, I'm noticing that this way reproduces the problem, while opening both from Finder does not.

**Comment by AgilentGCMS** [comment] 2021-01-19 21:30
@lwouis Could you reproduce the behavior?

**Comment by lwouis** [comment] 2021-01-20 03:30
@AgilentGCMS I was able to reproduce! That's great! I'll investigate further now on what's happening. Here are the repro steps:

* Open a PDF with Skim
* `Cmd+o` > select another PDF
* The second PDF window opens, but is not listed in AltTab

**Comment by lwouis** [comment] 2021-01-20 03:41
The issue seems to be detecting that the window is on the normal level:

![image](https://user-images.githubusercontent.com/106195/105123958-6fedcf00-5b1c-11eb-98d4-bb4df3a79606.png)

It seems that the window is initially not on the normal level, right when it spawns, probably due to some macOS animation that's slightly different when opening it from the `Open file...` menu compared to double clicking in the Finder. Quickly after, the boolean flips from `false` to `true`.

The reason we look at "is the window on the normal level" is encapsulated in this comment: `helps filter out iStats Pro and other top-level pop-overs, and floating windows`.

We need to change the heuristic to handle this better. Either observing changes of that value, as we do for other things like this that change in the first milliseconds of an app launching, or a window opening. Alternatively, we could use a different clever heuristic to help filter out the floating windows.

**Comment by lwouis** [comment] 2021-01-25 16:56
Possible duplicate of #639

**Comment by lwouis** [comment] 2021-01-25 17:23
I've spend some time trying to find a good heuristic. I can't find anything that could be a proxy to "this window is floating on top of other windows". Especially since it may actually not be true for a few frames during the window creation. The OS is giving us an "incorrect" level for the window for a very short time, before we would get the actual level, but this may reflect an animation or OS glitch where windows spawn at a different level than they end up at.

I could see adding a delay before reading the level, but that has obvious downsides. Best would be to observe, but it's a private API, so no way to do that. We could retry on a quick loop (few ms) for a few hundred ms. It has also obvious downsides.

**Comment by AgilentGCMS** [comment] 2021-02-07 01:20
I should say that while the thunderbird issue is not as easily reproducible, when it does occur it's fairly stubborn in staying. E.g., right now I have Brave browser and thunderbird open (two windows), and even though Thunderbird is in the foreground and above Brave, [AltTab is not showing Thunderbird](https://drive.google.com/file/d/15ecsh5tfxZ3qIkLHsrcPmo0W6kfpiC06/view?usp=sharing). I can even minimize Brave at this point, and AltTab will still not show Thunderbird. The only fix I've found is to quit and then restart AltTab, then the thunderbird windows show up.

**Comment by lwouis** [comment] 2021-02-07 05:38
I can't reproduce the issue with Thunderbird, and same goes for other reports in #639.

The holy thing i could reproduce and thus investigate is with Skim. It may be that every other case is stemming from the same root cause: window level (windows being on top of others) changing right when a window is created. It would explain why AltTab recognizes missing windows after a restart, as these would then be stable with the correct level.

it could also be that these other scenarios have other root causes. No way to know until i can reproduce and investigate them.

For now, the only thing i could investigate is tricky. I've written above how i don't have a way right now to avoid the issue.

**Closed** 2021-02-16 06:08 UTC
Labels: bug, need breakthrough

**Comment by lwouis** [comment] 2021-03-08 14:55
@AgilentGCMS @mfn This ticket was closed automatically when I tagged it in some commits. I'd like to clarify the status to you: the bug in Skim should be fixed. I can no longer reproduce it locally.

Could you please let me know if it's fixed for you as well? Regarding Thunderbird, please also let me know. I couldn't reproduce the issue previously, so I rely on you to tell me if the issue is indeed gone or not 👍

**Comment by mfn** [comment] 2021-03-11 08:41
Thanks for the ping, don't recall having seen this recently 🤞
