### ISSUE TITLE
ATM will cause the system window to appear delayed

### ISSUE THREAD

**Issue by Lijinyu3** [lwouis/alt-tab-macos#782] opened 2021-01-23 08:46 UTC
**Describe the bug**

My device: MacBookPro13 AppleSilicon, OS version: Big Sur 11.1
AltTab version: the latest, 6.12.0
When I running ATM, the system windows will be stuck, and then appear, I can't explain what "system window" exactly is, maybe you can understand it after watch the video below. And I can be sure the problem is caused by AltTab, since there is no such problem after I quit AltTab. It's a strange problem, I don't know how it happened.

**Screenshots / video**

https://user-images.githubusercontent.com/51511895/105573589-a1270300-5d99-11eb-9acf-f38c9451d5c0.mov

https://user-images.githubusercontent.com/51511895/105573591-a3895d00-5d99-11eb-9269-c061dcbc10b7.mov

Add screenshots to help explain your problem. You can also use Loom to easily record your screen to show the bug in action. That is *really* helpful!

**Steps to reproduce the bug**

1. Open Alt-Tab.app
2. Open a system windows, e.g., click "save page as" in "File" bar of browser like Chrome or Safari
4. See error, i.e., it stuck for about 5 secs

**Comment by lwouis** [comment] 2021-01-24 10:54
Hey @Lijinyu3! Thanks a lot for sharing this issue with nice useful videos!

I believe this is a duplicate of the existing issue https://github.com/lwouis/alt-tab-macos/issues/782

Please follow that issue for updates 👍

Note that macOS 11 is not officially supported yet, as indicated on the website and on homebrew.

**Closed by lwouis** 2021-01-24 10:54 UTC
Labels: bug

**Comment by Lijinyu3** [comment] 2021-01-24 11:18
> Hey @Lijinyu3! Thanks a lot for sharing this issue with nice useful videos!
> 
> I believe this is a duplicate of the existing issue #782
> 
> Please follow that issue for updates 👍
> 
> Note that macOS 11 is not officially supported yet, as indicated on the website and on homebrew.

Thanks for your reply @lwouis , I'm looking forward to the update. But I don't know which issue I should to follow for updates, the issue you mentioned is the same as this one, #782

**Comment by lwouis** [comment] 2021-01-24 14:00
I'm sorry @Lijinyu3, I copy-pasted the wrong ticket. Here is the one I was talking about: #718
