### ISSUE TITLE
Apple Books app doesn't show up in Alt-Tab

### ISSUE THREAD

**Issue by Stokestack** [lwouis/alt-tab-macos#856] opened 2021-03-03 02:49 UTC
**Describe the bug**
Books isn't listed among running apps in Alt-Tab. We've seen this before with other apps. There's probably something weird about the window.

**Steps to reproduce the bug**

1. Open a book in Books.
2. With Alt-Tab running, press Command-Tab.

It's a bit more annoying than some apps being missing, because if you're bouncing back and forth between a programming book and your IDE... yeah, you get the picture.

**Comment by lwouis** [comment] 2021-03-03 16:57
Duplicate of #481. See also #627 #748

**Closed by lwouis** 2021-03-03 16:57 UTC
Labels: bug

**Comment by Stokestack** [comment] 2021-03-03 22:40
Search failure on my part.

**Comment by lwouis** [comment] 2021-03-04 02:06
@Stokestack No worries 👍
