### ISSUE TITLE
Add a number to each window to allow jumping to it directly

### ISSUE THREAD

**Issue by thimplicity** [lwouis/alt-tab-macos#2344] opened 2023-02-17 14:02 UTC
Hi,
I really like the app, so thanks for working on this!

I am missing one feature: It would be great, if we could add a number to each window (at least up to 9), so that I do not need to keep pressing tab nine times to get to the ninth window, but rather keep holding cmd after pressing alt+tab and then press 9 to directly jump to that window.

I hope I explained that properly. Thanks for considering!

**Comment by lwouis** [comment] 2023-02-17 17:21
Duplicate of #210

**Closed by lwouis** 2023-02-17 17:21 UTC
Labels: enhancement
