### ISSUE TITLE
Add option to vertically center the app-switcher

### ISSUE THREAD

**Issue by mlubej** [lwouis/alt-tab-macos#968] opened 2021-05-24 15:37 UTC
**Is your feature suggestion related to a problem? Please describe.**

Currently the app-switcher is too high above for my taste

![image](https://user-images.githubusercontent.com/37869250/119371382-aac46700-bcb6-11eb-8a51-369d9c0190e6.png)

**Describe the solution you'd like**
I would appreciate some ability to customize this, either vertical alignment or positioning option

**Comment by lwouis** [comment] 2021-05-25 02:29
Duplicate of https://github.com/lwouis/alt-tab-macos/issues/585

**Closed by lwouis** 2021-05-25 02:29 UTC
Labels: enhancement
