### ISSUE TITLE
Cursor moving over the app-card with a duration to prevent false switching when using a mouse

### ISSUE THREAD

**Issue by jukrb0x** [lwouis/alt-tab-macos#827] opened 2021-02-17 16:17 UTC
**Is your feature suggestion related to a problem? Please describe.**
As we know, the cursor will move around the screen(whatever the scale of movement) with just a slight displacement of the mouse. When AltTab is activated and the cursor is hovering the center of the screen with a mistouch of the mouse, the AltTab act like switching to the application which cursor is hovering. In this case the convience casued, I just want a quick switch to the last app instead.

**Describe the solution you'd like**
**Set a duration after _Shortcut 1_ is pressed.** AltTab await for 0.5 or 1 sec if user chooses to mouse hover a app-card to switch. User needs a certain time to respond to the app which they want to switch, so I guess 0.5/1 sec should be fine. (Also, can be user defiend)

**Describe alternatives you've considered**
Any thoughts?

**Comment by lwouis** [comment] 2021-02-17 17:37
Duplicate of https://github.com/lwouis/alt-tab-macos/issues/286. Please have a look at my [conclusions after a first implementation](https://github.com/lwouis/alt-tab-macos/issues/286#issuecomment-658685978). The topic is interesting, but I wasn't able to find an implementation that doesn't have downsides, so I marked the ticket as `breakthrough needed`. Maybe you can have that breakthrough? ;)

**Closed by lwouis** 2021-02-17 17:37 UTC
Labels: enhancement
