### ISSUE TITLE
Group by spaces/desktops

### ISSUE THREAD

**Issue by damat** [lwouis/alt-tab-macos#2038] opened 2022-10-25 08:56 UTC
**Is your feature suggestion related to a problem? Please describe.**

I use several desktops for different activities. With modern days trends everything is pretty much browser based, so I have multiple Chrome windows spread across multiple spaces. So I find it's really frustrating when I need to switch to a specific Chrome on a specific desktop, using Alt-tab. 

**Describe the solution you'd like**
Ideally I'd like to see windows grouped by Desktops/Spaces they are on. E.g. a separate row for every Desktop I have. That would allow to understand where to navigate. 

**Describe alternatives you've considered**
Now I'm using Mission Control to switch to the desktop I need first, and then switch to the Chrome window. Which is slow and annoying to be honest.

**Comment by lwouis** [comment] 2022-10-25 11:32
Duplicate of #337

**Closed by lwouis** 2022-10-25 11:32 UTC
Labels: enhancement
