### ISSUE TITLE
Consider centering AltTab to match CmdTab

### ISSUE THREAD

**Issue by joostin81** [lwouis/alt-tab-macos#1516] opened 2022-04-23 17:34 UTC
Hello! Just want to suggest that an option be given for AltTab to be centered on the screen rather than the upper part. It could then match CmdTab's location and be more uniform.

**Comment by TitanBlast** [comment] 2022-04-26 20:05
> Hello! Just want to suggest that an option be given for AltTab to be centered on the screen rather than the upper part. It could then match CmdTab's location and be more uniform.

I like this idea :)

**Comment by lwouis** [comment] 2022-04-28 14:47
Duplicate of https://github.com/lwouis/alt-tab-macos/issues/585

**Closed by lwouis** 2022-04-28 14:47 UTC
Labels: enhancement
