### ISSUE TITLE
arrow keys not working in sonoma?

### ISSUE THREAD

**Issue by Quickshadoww** [lwouis/alt-tab-macos#2999] opened 2023-11-20 14:35 UTC
i tried 

"also select windows using -> arrow keys" 

it seems it is not working in sonoma? during the active switcher i am trying to toggle thru using arrow left and rigt key's on my keyboard, but its not reactive, or am i doing something wrong ? this is the only last missing feature for me :D otherwise very nice addon for macos.

**Comment by lwouis** [comment] 2023-11-21 08:06
Hi,

I can't reproduce the issue. Do you have the `Arrow keys` checkbox checked in Preferences > Control?

Thank you

**Comment by Quickshadoww** [comment] 2023-11-21 13:18
![ 2023-11-21 at 14 16 55](https://github.com/lwouis/alt-tab-macos/assets/18103189/d818aba6-0478-4899-845d-271e1f741ec2)
hi yes, i check it, and during the app switcher active i press arrow key left/right but nothing happens ?

**Comment by lwouis** [comment] 2023-11-21 13:20
It was a shortcut conflict with Magnet. Good news, you found the root cause 👍 

I'll close this issue since there is nothing to be done on AltTab's side. Thank you

**Closed by lwouis** 2023-11-21 13:20 UTC
Labels: bug, unreproducible
