### ISSUE TITLE
OpenBoard shows up as a window-less app in Alt-Tab.

### ISSUE THREAD

**Issue by SoPat712** [lwouis/alt-tab-macos#621] opened 2020-09-21 23:05 UTC
**Describe the bug**

OpenBoard, an open source whiteboard app shows up as a window-less app in alt-tab

**Steps to reproduce the bug**

1. Download OpenBoard
2. Run alt-tab
3. Notice the lack of icon for OpenBoard
4. Also notice that it is inconveniently at the end of the list

I'm not sure if this is a problem with OpenBoard, but thanks for the help in advance.

**Comment by lwouis** [comment] 2020-09-23 09:52
I downloaded and opened OpenBoard, and clearly it's not a native macOS app. It has one maximized window with no titlebar, and which obscures the top menubar. Weird stuff.

Have you tried discussing this issue with them before bringing the issue here? I'm fairly sure that the issue is on their side, and they should fix it for other reasons that the app not showing in AltTab. For example, the app doesn't show its window when you right-click the Dock icon:

![image](https://user-images.githubusercontent.com/106195/93996724-8c2b6a80-fdcd-11ea-95e9-895ab47f23fb.png)

A normal app with normal windows shows them at the top, as such:

![image](https://user-images.githubusercontent.com/106195/93996817-aa916600-fdcd-11ea-833d-d46dc72d37c4.png)

Normal window management shortcuts are also disabled, such as `cmd`+`m` which doesn't minimize the window.

I will hardcode an exception and the app will show in AltTab, but I think you should [open an issue on their github](https://github.com/OpenBoard-org/OpenBoard/issues) as their macOS integration has issues.

**Comment by lwouis** [comment] 2020-09-23 09:58
Edit: I implemented the hardcoded whitelisting, and interesting enough, the app window, when sent minimize and close events through AltTab, ignores them. The app can only be hidden apparently, which is what they show in the top right menu. So you can only hide or quit the app. No window manipulation at all.

That's really not a usual macOS experience, and definitely could be made more native to the platform with some extra work on their side.

**Comment by SoPat712** [comment] 2020-09-23 13:18
I'm not sure the problem with the app. I can talk to the developers, but it will be inconvenient, as forums are not very moderator active, and the whole userbase is French.

**Comment by SoPat712** [comment] 2020-09-23 13:39
Ok, it turns out that OpenBoard is basically the most recent whiteboard app with a decent amount of features, so I guess I'm stuck with OpenBoard for the time being.

**Comment by lwouis** [comment] 2020-09-23 13:49
> it will be inconvenient, as forums are not very moderator active, and the whole user base is French

And yet here you are talking to a French guy, and making things move ;p

That being said, I noticed they have a large amount of open issues so it may take a while, but first look if there is already an open issue regarding the mac client, and if not open a ticket, you never know, and it is useful feedback for them that the app is not well integrated on mac.

Also note that as soon I can release #556, the app will appear in AltTab properly for you.

**Comment by SoPat712** [comment] 2020-09-23 15:14
Yeah, I guess that would be perfectly fine, but the lack of activity is more the problem rather than the language barrier. Google Translate has come a long way!

I've opened an issue regarding the major Mac issues, and I'm hoping that'll be fixed if possible. I believe the app is forked from Linux, and not even intended for Mac in the first place, but I think I might try and fork the repo and see if I can't take on that daunting challenge myself.

And once again, thanks for the help with the app so far!

**Comment by SoPat712** [comment] 2020-09-25 00:35
Is there any particular ETA on this issue? It's getting annoying having to Cmd+tab and then Cmd+shift tab because openboard is shown as a window-less app and is 2nd in the list

Once again, thanks for all the help on this issue!

**Comment by lwouis** [comment] 2020-09-25 04:05
I'm afraid there are usually no ETAs on volunteer work 😅 I would plan and commit more if I was working in a group with others, but currently I'm the only developer on this project.

That being said, this update will ship soon. As soon as I get enough feedback from testers that [this build](https://github.com/lwouis/alt-tab-macos/issues/556#issuecomment-698347321) is good. Could you please help and test it too? This build has a PR open and everything is ready. It's just a matter off quality control then I press the button and the release goes live.

**Comment by SoPat712** [comment] 2020-09-25 04:14
I am having an issue, while the app switch while holding tab works going backwards(meaning hold shift), it doesn't work the other way(going forward). Not sure why this is?

**Comment by SoPat712** [comment] 2020-09-25 04:16
Nevermind, the problem is beyond that. The trigger is apparently touching shift, and then going forward and backwards works.

**Comment by SoPat712** [comment] 2020-09-25 04:16
I can screenshare or record my screen if you'd like?

**Comment by lwouis** [comment] 2020-09-25 06:31
Please share of video of the issue. That will help explain it for sure. Let's continue this in the other ticket please

**Comment by lwouis** [comment] 2020-09-25 10:30
The [new release 6.7.0](https://github.com/lwouis/alt-tab-macos/releases/download/v6.7.0/AltTab-6.7.0.zip) should fix this issue. Closing this ticket. Let me know if the issue is not gone and I'll re-open it 👍

**Closed by lwouis** 2020-09-25 10:30 UTC
Labels: bug
