### ISSUE TITLE
Layout default preferences should depend on screen ratio

### ISSUE THREAD

**Issue by gingerbeardman** [lwouis/alt-tab-macos#436] opened 2020-07-17 12:38 UTC
**Describe the bug**

- Thumbnail area is much larger than a full screen window when using portrait display

I use a portrait display and when I use AltTab it allocates more area than expected for each window thumbnail.

In the screenshot below, the highlighted window is a full screen Safari but you can see a lot of space below it.

**Screenshot**

![Screen shot 2020-07-17 at 13 29 11-0001](https://user-images.githubusercontent.com/49612/87786656-3e750d80-c832-11ea-9997-53c1132763a3.png)

**Steps to reproduce the bug**

1. Use a portrait display
2. Run AltTab
3. Invoke AltTab

**Expected**

- thumbnail area should only be as big as full screen window

**Actual**

- thumbnail area is larger than full screen window

**Comment by lwouis** [comment] 2020-07-17 15:53
Hi! Thanks for sharing this feedback!

I think the app is working properly. I think the issue is that your expectation is not matching the reality of the layout logic in the app. I think if you I asked you to actually draw what you think the app should present, you would start questioning your own position.

There are many ways to tile pictures on a screen. You can do what Mission Control does, and have very big differences in size. You can have very big thumbnails when the user only has a few windows open like 2 thumbnails would fill the whole space.

The way AltTab does it is to first fix things, so that position and sizes of thumbnails are dynamic, yet not too much. Your eyes can expect were the rows are going to be roughly, and where the 3rd thumbnail will appear for instance. First it fixes the size of the black background. That's a percentage of the screen, that you can customize in the preferences. Then it fixes the number of rows of thumbnails. That's also customizable. Then it will allocate more of less width for thumbnails according to the min and max number of thumbnails you set, while always preserving the ratio of images, so they are not distorted.

I suggest you play a bit with the preferences, and find a setup that you enjoy more. People have different tastes, and there is no way to ship a one-size-fits-all default. Someone who has a vertical display and 7 windows open like you will want quite different layout settings that someone with an ultra-wide monitor, that frequently works with 20+ windows at a time.

<img width="603" alt="Screen Shot 2020-07-18 at 0 26 56" src="https://user-images.githubusercontent.com/106195/87803537-8f661f80-c88d-11ea-8ce3-2f8caf61aeb3.png">

I'm closing this ticket as I can't see a bug here. If you think there are ways to improve the layout logic, please open a new improvement suggestion ticket, and specify in details how that new system would work 👍

**Comment by gingerbeardman** [comment] 2020-07-17 16:10
Thanks, I had played about with the settings but I cannot make the area outlined in red shrink or disappear. 

What is this space marked in red? Why would the thumbnail of a full screen need so much empty space underneath it?

![Screen shot 2020-07-17 at 17 04 37](https://user-images.githubusercontent.com/49612/87807105-c1589100-c84f-11ea-879c-6d7b75996082.png)

I would expect the layout to be more like this:

![Screen shot 2020-07-17 at 17 04 37 2](https://user-images.githubusercontent.com/49612/87807371-14324880-c850-11ea-8186-3ffd5ea415ae.png)

On the official website, 2 rows does not have this extra space:

![Screen shot 2020-07-17 at 17 08 47](https://user-images.githubusercontent.com/49612/87807528-404dc980-c850-11ea-8b5d-5e1fc5b2970a.png)

**Comment by gingerbeardman** [comment] 2020-07-17 16:20
> First it fixes the size of the black background. That's a percentage of the screen, that you can customize in the preferences.

I think this is the issue, you define the vertical size of things based on the dimensions of the screen. This makes a nice layout on a landscape display but on portrait display everything is stretched vertically.

So, I understand and agree that this is by your design. 

However, I would say that this method of layout size calculation is not ideal for portrait displays.

**Comment by lwouis** [comment] 2020-07-17 17:01
What if you put 2 windows side by side, splitting the screen 50% left and 50% right on your display? How does that look like in AltTab? Their ratio is going to be taller, and it may make use of the vertical space in red.

> However, I would say that this method of layout size calculation is not ideal for portrait displays.

I have put hundred of hours in the current layout logic. That being said it doesn't mean it's the best it could be. It means that i'm not sure what could be done to improve. I need a clear algo/spec that mappable to an implementation, or better yet a PR to actually directly implement your vision

**Comment by gingerbeardman** [comment] 2020-07-17 17:12
Here's what I see with to windows of 50% width and 2 rows

![Screen shot 2020-07-17 at 18 11 36](https://user-images.githubusercontent.com/49612/87813039-07feb900-c859-11ea-86c0-e4977a0046bf.png)

**Comment by gingerbeardman** [comment] 2020-07-17 17:14
And here is with 3 per row

![Screen shot 2020-07-17 at 18 13 23](https://user-images.githubusercontent.com/49612/87813132-37adc100-c859-11ea-9d45-78867b029a76.png)

**Comment by lwouis** [comment] 2020-07-17 17:21
Yes, see, it all matches what I said. Now it's on you to decide your preferences based on the typical size of your windows. For instance, if you often have fullscreen windows, you may want more rows, so less tall, less of the empty space you highlighted in red. Note that that space is only empty because you have these window ratio. If you had slimmer windows as you have shown after, they would make use of the space.

It's all about the workflow you *prefer*. I, or any algo, can't make this decision for you ;) Based the screenshot you seemed to want, I think you want 4-5 rows, with 3-4 column each?

**Comment by gingerbeardman** [comment] 2020-07-17 17:26
Yes, changing the values for "windows per row" and "rows of windows" I can reduce the space we are talking about.

So I think the defaults are great for landscape, but not great for portrait display. It's up to you what you do with this information, I guess.

Thanks for helping me with this. Feel free too close.

**Comment by lwouis** [comment] 2020-07-17 17:38
Glad to hear you find preferences that work better for you! Btw I have been thinking on how to improve the complexity of the Preference UI for a while now. Maybe providing some presets like S, M, L, XL shirt sizes, but then there will always be people with specific hardware and preferences, and I don't want to remove customization from them. It's really tricky to not expose all the pipes, but still keep enabling all workflows.

I'll keep the ticket open because the idea to adapt the defaults depending on the main display ratio is a clear go I think. Note that I said *main* display. Currently AltTab shares the Appearance preference across all displays. Someone with a vertical *and* a horizontal monitor will have the same settings on both. Very complex scenario to handle. I don't even know where to start to support that! 🙉

**Closed** 2020-07-20 22:10 UTC
Labels: bug
