### ISSUE TITLE
Alt-tab randomly gets stuck on select screen for unknown reason

### ISSUE THREAD

**Issue by pawelkontek** [lwouis/alt-tab-macos#3567] opened 2024-08-25 19:17 UTC
**Describe the bug**

The Alt-tab randomly gets stuck on the select screen for an unknown reason. Please see video.

**Screenshots / video**

(It is best to watch with sound to understand when I am pressing cmd+tab to switch tabs)
https://github.com/user-attachments/assets/645529ef-be38-4d88-b1d4-214abe82b09b

**Steps to reproduce the bug**

1. Just use alt tab.

**Your environment**

* AltTab version: Version 6.72.0
* macOS version: Sonoma 14.5 (23F79)
* Other relevant info: Using MBP 14". Using Karabiner.

**Comment by qvanphong** [comment] 2024-08-27 13:43
I'm facing same problem, sometime if I press Alt Tab too fast, the tab select automatically move from left to right until end of list of windows

**Comment by lwouis** [comment] 2024-08-27 14:04
Hi,

Thank you for sharing this issue.

I can't reproduce it. I reproduced your exact inputs as well, and it doesn't get stuck.

Only idea I have is that you may have other apps on your setup which intercept events, and absorb the keyUp event. This would mean AltTab doesn't see them, thus never goes away.

Do you use BTT, Karabineer, external keyboards, logitech things, etc?

Thank you 🙇 

@qvanphong what you describe sounds more like https://github.com/lwouis/alt-tab-macos/issues/3117

**Comment by pawelkontek** [comment] 2024-08-29 14:54
> Do you use BTT, Karabineer, external keyboards, logitech things, etc?

I use Karabiner, but I was also able to reproduce this bug with Karabiner completely turned off.
I use BTT 🤡
No external keyboards or Logitech (as of recording this bug) – it is possible that the Apple keyboard and trackpad were connected via Bluetooth but not active.

> Only idea I have is that you may have other apps on your setup which intercept events, and absorb the keyUp event
Isn't karabiner elements showing what the _computer_ (?) is recording?

**Comment by lwouis** [comment] 2024-08-29 15:50
Karabiner and BTT both listen to keyboard events, and do things with it. In some cases, they may absorb the event.

For instance, if you set Karabiner to remap `E` to `L`, when you press `E`, it will create keyUp event for the letter `E`. Karabiner will absorb it, and re-emit a new event for the letter `L`. At least I believe they do something like this. I know for a fact that these apps can absorb events, then AltTab doesn't receive them. Many users have shared issues with AltTab that were actually due to their setup.

Could you please test with BTT and Karabiner not running, and no external keyboard? I think that should confirm if they were the cause, which is the most likely explanation.

Thank you 🙇

**Comment by nasedil** [comment] 2024-09-05 07:59
I had the problem when updated to Sonoma.  Then I disabled the blue capslock indicator popup in macos and now it seems working normal as before.

**Comment by scriptogre** [comment] 2024-09-05 09:07
I had the exact same issue for months, but have not found anyone else facing it. Finally there's someone else. I am also using Karabiner, but I can confirm that this also happens with Karabiner stopped.

**Comment by ctrl-cheeb-del** [comment] 2024-09-07 12:51
I have also experienced this issue on a brand new macbook also on Sonoma

**Comment by ILIAink** [comment] 2024-09-08 00:52
I unfortunately don't have a solution, but just bumping this since I am facing the same issue.

**Comment by pawelkontek** [comment] 2024-09-09 15:12
@ILIAink I downgraded to 6.63.0. Unfortunately, it didn't fix the issue for me.

**Comment by aoli-al** [comment] 2024-09-10 23:12
I also had this issue for a while. After some debugging, I noticed that the bug went away after I disabled Chrome's input monitoring permission. 

<img width="484" alt="image" src="https://github.com/user-attachments/assets/16f8b864-2886-4b37-af5a-844156a17752">

**Comment by lwouis** [comment] 2024-09-11 07:00
Thank you @aoli-al
Anyone else gets the issue to go away by removing Chrome's Input Monitoring permissions? If yes, that would indicate that it was Chrome stealing inputs in some cases.

**Comment by Yazi27** [comment] 2024-09-11 11:55
No, I use Brave and it is not doing any input monitoring, this issue is really annoying I find myself constantly switching between Brave and VSC, I may have to find an alternative since it seems they are sleeping on this issue

**Comment by AfzalivE** [comment] 2024-09-12 17:49
For me, disabling Karabiner's 3 input monitoring applications fixed it, re-enabling them still keeps the fix.

**Comment by pawelkontek** [comment] 2024-09-13 12:22
The bug still persists for me, even after disabling monitoring apps.

I am going to disable alt-tab and use macOS regular switcher, and see if it also gets stuck.

https://github.com/user-attachments/assets/516746d3-19b0-44a2-93ad-33dcc45ebed0

**Comment by albionselimaj** [comment] 2024-09-13 14:22
This is happening when the mouse cursor is positioned over the AltTab popup. Hiding window thumbnails in Appearance settings helps with this as it reduces the chances of the cursor being over the popup area.

**Comment by multi-io** [comment] 2024-09-13 19:03
> This happens constantly for me, to the point where AltTab becomes unusable.

Update: I had Karabiner Elements running, wasn't really using it anymore. Disabled it and restarted, and it looks like the problem is gone.
I still have Rectangle with a whole bunch of keyboard mappings running, and this would be much harder to replace or stop using, but so far it doesn't seem to interfere with AltTab.
I will report back if the issue reappears.

**Comment by ctrl-cheeb-del** [comment] 2024-09-13 19:50
just wanted to say, I was experiencing this issue but took @ILIAink  suggestion of downgrading to 6.63.0 seemed to fix it for me

**Comment by Yazi27** [comment] 2024-09-13 23:29
I don't have Karabiner, the issue does arise when my mouse is somewhere around where the windows appear as @albionselimaj mentioned, it would be nice to add a feature to disable entirely disable cursor as an easy fix, or maybe disable it when its not moving?

Would be nice if a dev answers

**Comment by lwouis** [comment] 2024-09-14 17:29
Hi,

A lot of cases in this threads have been confirmed to be caused not by AltTab having a bug, but by another app stealing a keyboard input.

It's hard to investigate more without being able to ever reproduce the issue on my machine. Soon, we'll add a logger to AltTab. It will allow for casual users to share logs here. These will help us investigate such issues that happen only on some people setups.

Thank you 🙇

**Comment by hikariatama** [comment] 2024-09-15 16:59
I was testing different versions trying to figure out, which one does not have the issue mentioned, because I had it. I tried all version starting from 6.63.0 up to the **latest** one. I do not have a slightest idea why, but the issue fixed itself and currently I am not experiencing it on the latest version. Weird.

**Comment by and-poulsen** [comment] 2024-09-23 22:37
> This is happening when the mouse cursor is positioned over the AltTab popup. Hiding window thumbnails in AltTab Appearance settings helps with this as it reduces the chances of the cursor being over the popup area.

Exactly what happens for me – most definitely this is what is causing it for me.
Disabled all input capturing apps, but still happens.

**Comment by d-lord** [comment] 2024-10-01 03:39
I've been experiencing this for a while. Setting `Apparition delay` to 0ms rather than 104ms seems to have resolved it. 🤞

Unable to reproduce by putting my cursor where AltTab will pop up.

**Comment by james-aus** [comment] 2024-10-04 05:24
I can reproduce as well with the mouse being over the switcher popup when it appears & have nothing like Karabiner installed. If I move my mouse to the side of the screen, I have no issue. If I have my mouse in the center, it happens every time. Wasn't actually aware this was the pattern until I found this thread, but experimenting now that I know to pay attention to where my mouse is that explanation fits perfectly :) I've got >16 windows open, so it takes up most of the screen.

**Comment by lordgrenville** [comment] 2024-10-08 09:16
I also have this issue, which is caused by the mouse cursor being over the AltTab window, as @albionselimaj said.

However, under controls, I have deselected "Also select windows using mouse hover" and "Cursor follows focus", so **this seems like a bug**.

**Comment by multi-io** [comment] 2024-10-10 21:01
> > This happens constantly for me, to the point where AltTab becomes unusable.
> 
> Update: I had Karabiner Elements running, wasn't really using it anymore. Disabled it and restarted, and it looks like the problem is gone. I still have Rectangle with a whole bunch of keyboard mappings running, and this would be much harder to replace or stop using, but so far it doesn't seem to interfere with AltTab. I will report back if the issue reappears.

Well...it did reappear. I did not reinstall Karabiner Elements. Restarting it seems to help, for a while at least.

**Comment by rcwmt** [comment] 2024-10-13 12:39
Would it help to give Alt-Tab a higher priority compared to BTT / Karabiner etc.? Could Alt-Tab become a "Input Monitoring App?"

**Comment by lwouis** [comment] 2024-10-13 13:41
@rcwmt as far as i know, there is no way to set the priority of input capture between macOS apps. It's not exposed to the user through some kind of list, and there is no API for the app to call to claim for themselves. Priority is decided by the order in which apps are launched, i believe.

**Comment by Longwelwind** [comment] 2024-10-14 10:04
> Any solution regarding the cursor being on the way of the windows making the cycle get stuck, even cycling by itself? I'll provide a video.
> 
>  Screen.Recording.2024-09-14.at.20.15.46.mov

I'm having the same issue. If I Alt+Tab and if the cursor is on the overlay when it appears, it will sometimes quickly cycle randomly through the open windows:

https://github.com/user-attachments/assets/749c8d60-01a2-4799-87c6-58d0cd5a2628

(Note that I only pushed on Alt+Tab once in the video)

I enabled `Hide window thumbnails` to make the overlay smaller so that the issue happens less. I disabled all `Input Monitoring` apps in `Privacy & Security` in MacOS settings.

Thanks for an otherwise great app!

**Comment by lwouis** [comment] 2024-10-15 08:41
Could everyone in this thread please update to the latest version of AltTab, and see if it has fixed the issue like [it did form some users](https://github.com/lwouis/alt-tab-macos/issues/3567#issuecomment-2351677989)?

Thank you 🙇

**Comment by Yazi27** [comment] 2024-10-18 15:41
@lwouis Latest update does fix it indeed. Thank you very much 😄

**Comment by kaiyihuo** [comment] 2024-11-01 09:50
Latest update fixes it for me too.

**Comment by lwouis** [comment] 2024-11-07 17:41
I'll close this ticket since there seems to be nothing to do on AltTab side.

Some issues were due to [external software interfering](https://github.com/lwouis/alt-tab-macos/issues/3567#issuecomment-2351070314)
Some issues seem fixed on the latest version of AltTab
Some issues already have tickets to track them (e.g. #3117)

Thank you 🙇

**Closed by lwouis** 2024-11-07 17:41 UTC
Labels: bug, unactionable, unreproducible
