### ISSUE TITLE
AltTab preference window is cut off and can't be resized.

### ISSUE THREAD

**Issue by imthenachoman** [lwouis/alt-tab-macos#1149] opened 2021-09-21 17:54 UTC
I am using an external monitor. When I open the preferences window on my main monitor it cuts the bottom of. If I drag it to my built-in MBP monitor then I can see it. Not a big issue but still wanted to report.

I am on a Macbook Pro 2019 with BigSur 11.6.

![image](https://user-images.githubusercontent.com/83817/134222482-7917b29b-6d74-4cc3-97b8-0303eaa710c6.png)

**Comment by lwouis** [comment] 2021-09-22 02:14
Duplicate of https://github.com/lwouis/alt-tab-macos/issues/936

**Closed by lwouis** 2021-09-22 02:14 UTC
Labels: bug
