### ISSUE TITLE
Number windows and switch to them using alt-<number>

### ISSUE THREAD

**Issue by kostyafarber** [lwouis/alt-tab-macos#2639] opened 2023-07-02 16:01 UTC
I would like to be able to switch to windows that with having to alt-tab all the way to them, if they are say, at the end of the list.

I don't want to use the mouse to get to it, similar to [this](https://chrome.google.com/webstore/detail/numbered-tabs/iocebdgkllilbhbekghlbpmhfeejgcgi) Google Chrome extension that numbers tabs and you can switch to them using: `cmd + number`

Perhaps numbering each window and allowing the user to switch pressing `alt + number` would be great. Thanks.

**Comment by lwouis** [comment] 2023-07-02 16:17
Duplicate of #210

**Closed by lwouis** 2023-07-02 16:17 UTC
Labels: enhancement
