### ISSUE TITLE
AltTab 3.6.x crashed

### ISSUE THREAD

**Issue by buttercrab** [lwouis/alt-tab-macos#216] opened 2020-04-08 08:06 UTC
AltTab 3.6.0 crashed on Macbook pro 2017, MacOS 10.15.4. I use Korean and AltTab opened with Korean at first time. Then, when I check the options of AltTab in settings, it crashed. Since then , it won't open.

What I've tried
- reinstall 3.6.0
- upgrade to 3.6.1
- downgrade to 3.5.0
- run `AltTab.app/Contents/MacOS/AltTab` and got result (zsh):
  ```
  [1]    4607 illegal hardware instruction  ./AltTab
  ```

**Comment by gingerr** [comment] 2020-04-08 08:08
Ive observe the same behavior #217 

Workaround: run `defaults delete com.lwouis.alt-tab-macos` in the terminal and dont change any of the dropdowns in the Preferences panel.

**Comment by buttercrab** [comment] 2020-04-08 08:13
@gingerr I think it's same issue. The command had an effect, but it doesn't fix the problem.

**Comment by lwouis** [comment] 2020-04-08 10:15
Closing as duplicate of #217. It happens with any non-English locale.

Let's have the discussion in #217 :)

**Closed by lwouis** 2020-04-08 10:15 UTC
Labels: bug, duplicate

**Comment by lwouis** [comment] 2020-04-08 16:25
@buttercrab Were you able to upgrade to 3.7.0+ and have it work?
