### ISSUE TITLE
Don't request Screen Recording if the user doesn't use the thumbnail feature

### ISSUE THREAD

**Issue by ivanvotti** [lwouis/alt-tab-macos#1639] opened 2022-06-01 12:19 UTC
**Is your feature suggestion related to a problem? Please describe.**
Here is what I see when I disable the screen recording:
<img width="538" alt="2022-06-01-at-19 08 15@2x" src="https://user-images.githubusercontent.com/106441558/171400903-15e5a652-7423-42cb-b128-8c06f0d8b622.png">

But I hided the window thumbnail, so I don't need the app to have the permission to record my screen:
<img width="247" alt="2022-06-01-at-19 09 40@2x" src="https://user-images.githubusercontent.com/106441558/171401200-a9eb16f4-5a55-4938-b34e-dfcab1427408.png">

**Describe the solution you'd like**
I should be able to use the AltTab app even after I disable the screen recording permission:
<img width="704" alt="2022-06-01-at-19 11 24@2x" src="https://user-images.githubusercontent.com/106441558/171401537-fc844668-600c-4bc2-9762-e39f29dd0027.png">

Thanks for the app.

**Comment by lwouis** [comment] 2022-06-01 13:34
Duplicate of #1082

**Closed by lwouis** 2022-06-01 13:34 UTC
Labels: enhancement
