### ISSUE TITLE
Discord window is always present even when "Hide apps with no open window:" is enabled

### ISSUE THREAD

**Issue by UltraHDR** [lwouis/alt-tab-macos#2082] opened 2022-11-04 20:40 UTC
**Describe the bug**

Discord window is always present even when "Hide apps with no open window:"  is enabled

**Steps to reproduce the bug**

1. Open Prefrences -> Go to Appearnce -> Tick "Hide apps with no open window:" 
2. Run Discord
3. Press the red x button or Command + W to close the window
4. In Expose the Discord window is not present
5. The Discord window is present in alt-tab-macos

**Comment by lwouis** [comment] 2022-11-04 21:07
Duplicate of https://github.com/lwouis/alt-tab-macos/issues/1412#issuecomment-1058765751

**Closed by lwouis** 2022-11-04 21:07 UTC
Labels: bug
