### ISSUE TITLE
cause matlab to freeze

### ISSUE THREAD

**Issue by Alex123425** [lwouis/alt-tab-macos#890] opened 2021-04-01 03:22 UTC
it causes Matlab to freeze when I try to close a plot window with a mouse click, even if I quit alt-tab, as long as it is selected in the accessibility in system preferences.

**Comment by lwouis** [comment] 2021-04-01 06:50
Hi @Alex123425! Could you please more details, especially a video showcasing the issue would be nice, and precise steps to reproduce

**Comment by Alex123425** [comment] 2021-04-01 08:39
Hi @lwouis,

This doesn't happen every time while alt-tab is not running, so I can not provide a video. 

However, when alt-tab is running, this happens 100 per cent. Attached is a sample video. I tried matlab alone first, everything is fine. I then opened alt-tab, and matlab lost response. I have to use option+command+esc to quit.

https://user-images.githubusercontent.com/58759217/113267138-96906900-9308-11eb-8165-9d148b20dc56.mp4

**Comment by lwouis** [comment] 2021-04-08 14:42
Thank you for the video, it's showing the issue very nicely.

Unfortunately, I can't access MatLab source code to debug what crashes inside of it. This reminds me of a similar ticket: https://github.com/lwouis/alt-tab-macos/issues/822. It was an issue in the Java/Swing/AWS stack on macOS. Wikipedia says Matlab is written in C/C++, and it's cross-platform as the UI shows (looks like Windows). I'm guessing they could have a bug in the cross-platform layer, in the way they handle macOS events.

I suggest you open a ticket to their customer service. If they have a public bug tracker, or you get a response, could you please share it here so we learn from it what they did wrong, or maybe so I can collaborate with them to help them debug their app 👍

**Comment by Alex123425** [comment] 2021-04-08 15:43
Hi, @lwouis, Thanks for your reply. 

I asked workers from Matlab for help before I opened this issue. They just told me to turn off the accessibility. I had a problem report after MatLab is freeze, could you find any reason from this? I attached the report in a .txt file.

[matlab_problem_report.txt](https://github.com/lwouis/alt-tab-macos/files/6279813/matlab_problem_report.txt)

**Comment by lwouis** [comment] 2021-04-08 16:00
> They just told me to turn off the accessibility

What does that mean? Remove the Accessibility permission of the MatLab app? Or maybe disable some of macOS Accessibility features in System Preferences?

> I had a problem report after MatLab is freeze, could you find any reason from this? I attached the report in a .txt file.

Oh! That's very interesting! Look at this section:

```
  22  -[NSWindow(NSWindowAccessibility) accessibilityFocusedUIElement] + 105 (AppKit + 9423907) [0x7fff23826c23]
  22  -[AWTView accessibilityFocusedUIElement] + 156 (libawt_lwawt.dylib + 31748) [0x13d37ec04]
  22  -[JavaComponentAccessibility accessibilityFocusedUIElement] + 110 (libawt_lwawt.dylib + 206154) [0x13d3a954a]
  22  JNFCallStaticObjectMethod + 176 (JavaNativeFoundation + 27465) [0x7fff6fa43b49]
  22  jni_CallStaticObjectMethodV + 268 (libjvm.dylib + 3270035) [0x11b803593]
  22  jni_invoke_static(JNIEnv_*, JavaValue*, _jobject*, JNICallType, _jmethodID*, JNI_ArgumentPusher*, Thread*) + 447 (libjvm.dylib + 3308741) [0x11b80ccc5]
  22  JavaCalls::call_helper(JavaValue*, methodHandle*, JavaCallArguments*, Thread*) + 1710 (libjvm.dylib + 3083550) [0x11b7d5d1e]
  22  ??? [0x1229d57a7]
  22  ??? [0x1229dd040]
  22  ??? [0x1229dd040]
  22  ??? [0x1229dd2bd]
  22  ??? [0x1229dd2bd]
  22  ??? [0x1229dd2bd]
  22  ??? [0x1229ed667]
  22  Java_sun_lwawt_macosx_LWCToolkit_doAWTRunLoopImpl + 256 (libawt_lwawt.dylib + 227631) [0x13d3ae92f]
  22  -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 212 (Foundation + 393121) [0x7fff214d5fa1]
  22  CFRunLoopRunSpecific + 563 (CoreFoundation + 521934) [0x7fff207486ce]
  21  __CFRunLoopRun + 1315 (CoreFoundation + 525002) [0x7fff207492ca]
  21  __CFRunLoopServiceMachPort + 316 (CoreFoundation + 531447) [0x7fff2074abf7]
  21  mach_msg_trap + 10 (libsystem_kernel.dylib + 3710) [0x7fff2061de7e]
 *21  ipc_mqueue_receive_continue + 0 (kernel + 573344) [0xffffff800029bfa0]
```

It's actually a stacktrace going into some AWT stack. You can see for instance: `AWTView accessibilityFocusedUIElement` and `Java_sun_lwawt_macosx_LWCToolkit_doAWTRunLoopImpl `

I was right in my previous guess above:

>  It was an issue in the Java/Swing/AWS stack on macOS

That's cool that I was able to guess such a thing haha! Even when Wikipedia said the app is written in C/C++, I was guessing there could be some Java stack at play here.

In the ticket I linked above, you can see how [me and someone else opened ticket with Sun to ask them to fix the Java issue](https://github.com/lwouis/alt-tab-macos/issues/822#issuecomment-784986240).

I still believe it's Matlab responsibility to fix their app. They use a Java dependency that has bugs. They are responsible for these bugs. They could replace the dependency with one that doesn't have such a bug. More realistically, they could raise the issue with AWT, and since MatLab is a big company, they could get priority support from Sun I imagine.

Let me know if there is a follow up 👍

**Comment by redmetz** [comment] 2021-04-09 08:32
Any idea, how I can add matlab to the blacklist in Alttab?

**Comment by lwouis** [comment] 2021-04-12 14:51
You can find which bundleId MatLab uses using this command here: https://github.com/lwouis/alt-tab-macos/issues/858

You can then input that bundleId in the Blacklist section in AltTab

**Comment by Last-Remote** [comment] 2021-05-24 03:38
> Any idea, how I can add matlab to the blacklist in Alttab? So which path I just add there?

Write the following path in the blacklist to block the matlab window:
com.mathworks.matlab

But I tried, it just block window and still can't solve the plot window problem, so you'd better close AltTab before running matlab

**Comment by lwouis** [comment] 2021-05-24 05:29
@Alex123425 @redmetz @Last-Remote Did any of you open a ticket with MatLab support to get a fix rolling? If yes, can you please share the developments from that ticket so everyone can know if there is hope to get a fix from MatLab, and a timeline maybe.

From my side I can't do anything since I don't have access to the app since it's a commercial app. If someone can share a license with me temporarily or something, let me know. Without that, the support has to come from MatLab. It's a bug on their side anyway, so they should fix it for sure. It impact AltTab but it probably breaks with screen-readers and other accessibility app.

I made a [local build with a workaround](https://github.com/lwouis/alt-tab-macos/files/6530021/AltTab.app.2.zip) I implemented for a few other broken apps. Maybe it could mitigate the issue. I have no way to test it, but you can. So could you please try to see if the bug is happening [with this local build](https://github.com/lwouis/alt-tab-macos/files/6530021/AltTab.app.2.zip)? Thanks 👍

**Comment by Alex123425** [comment] 2021-05-24 07:08
@lwouis I did not do that. I don't think the chance is much to let them fix it. They have known this issue for a long time, years longer than I open this one on Github, yet still remain unfixed. See their official website for reference, this happened in the year 2018: https://www.mathworks.com/matlabcentral/answers/421446-r2018b-r2019a-runs-very-slow-on-macos-10-14#answer_414410

**Comment by lwouis** [comment] 2021-05-24 08:09
@Alex123425 the link you shared seems to be some community forums. I don't know the kind of license you're using, but depending on how much you pay, I imagine you qualify for professional support with actual SLAs. Could you try opening up a ticket [on this page](https://www.mathworks.com/support/contact_us.html?s_tid=sp_ban_cs) perhaps?

**Comment by Alex123425** [comment] 2021-05-24 08:39
@lwouis I am only a student. I do not have the "Software Maintenance Service subscription" required. I submitted a request even though, hope they will respond.

**Comment by lwouis** [comment] 2021-05-26 11:09
I suggest you ask them for more clarity on the timeline. Either a concrete date, or an their planned/estimate release period. Something like Q3 2021 would be more useful than "soon"

**Comment by noirchen** [comment] 2021-12-06 12:40
Hi @lwouis I tested the local build and now matlab figure closes normally without freezing.

**Comment by lwouis** [comment] 2021-12-30 02:06
@noirchen so can we close this ticket, or is there work on AltTab side left over?

**Comment by richardso21** [comment] 2022-02-19 05:55
Not sure why this issue is closed, this problem is still happening at my end. I have AltTab 6.31.0 and MATLAB 2021b.

**Comment by richardso21** [comment] 2022-02-20 23:57
I found that **downgrading MATLAB to 2019b fixed it (I can still use AltTab 6.31.0)**. An older version of MATLAB works for me, but I am not sure if this is sustainable for the future. Personally, I think MathWorks should be the ones fixing this, but looking at their responses they aren't too keen on helping the community lol.

**Comment by lwouis** [comment] 2022-04-29 15:47
Closing this as it's unactionable:

* Can't debug with Matlab myself since I don't have a license
* Issue is clearly on their side, as the message above proves

**Closed by lwouis** 2022-04-29 15:47 UTC
Labels: bug, unactionable

**Comment by soppelmann** [comment] 2022-05-11 17:48
> @Alex123425 @redmetz @Last-Remote Did any of you open a ticket with MatLab support to get a fix rolling? If yes, can you please share the developments from that ticket so everyone can know if there is hope to get a fix from MatLab, and a timeline maybe.
> 
> From my side I can't do anything since I don't have access to the app since it's a commercial app. If someone can share a license with me temporarily or something, let me know. Without that, the support has to come from MatLab. It's a bug on their side anyway, so they should fix it for sure. It impact AltTab but it probably breaks with screen-readers and other accessibility app.
> 
> I made a [local build with a workaround](https://github.com/lwouis/alt-tab-macos/files/6530021/AltTab.app.2.zip) I implemented for a few other broken apps. Maybe it could mitigate the issue. I have no way to test it, but you can. So could you please try to see if the bug is happening [with this local build](https://github.com/lwouis/alt-tab-macos/files/6530021/AltTab.app.2.zip)? Thanks 👍

Are These patches available in some branch?
The local build works for me.

**Comment by lwouis** [comment] 2022-05-12 08:47
@soppelmann I couldn't remember exactly what I changed in the build I shared. I think I added `com.mathworks.matlab` to the list of app for which we shouldn't subscribe to `kAXFocusedUIElementChangedNotification`.

Can you please tell me if the issue happens or not with [this new build](https://github.com/lwouis/alt-tab-macos/files/8676450/AltTab.app.zip)? If it fixes it, I'll integrate the fix in the regard app/releases 👍

**Comment by noirchen** [comment] 2022-05-12 09:51
@lwouis this new build works fine with matlab.
