### ISSUE TITLE
Keynote when in display mode not showing up in AltTab

### ISSUE THREAD

**Issue by dyno** [lwouis/alt-tab-macos#636] opened 2020-10-04 17:16 UTC
Keynote shows up in CMD+Tab but not in Alt+Tab.

**Comment by lwouis** [comment] 2020-10-05 10:55
Thank you for sharing this issue @dyno!

Indeed I was able to reproduce. It turns out that Keynote is not using the standard fullscreen mode when in presentation mode. It is using a trick of having a fullscreen window cover the whole screen instead.

I will hardcode a workaround so Keynote shows in AltTab, in Presentation Mode. Note that there is a gap in the workaround: if you switch windows while presenting, you won't see the presentation window anymore after you switch. The reason is that Keynote destroys that window, so there is literally no way AltTab can show it. Then when you click on the Dock icon again, Keynote will re-create the window, showing it fullscreen again. At this point it shows again in AltTab.

The workaround will be in the next release 👍

**Closed** 2020-10-06 17:10 UTC
Labels: bug
