### ISSUE TITLE
Add ability to add direct access shortcuts to specific windows

### ISSUE THREAD

**Issue by samxyzabc** [lwouis/alt-tab-macos#178] opened 2020-03-14 03:14 UTC
Dear dev,
A great app better than any other ones I've ever met.
Can the shortcut be fully customized, other than fixed to Tab and another key?
Also can any window be assigned a letter to make it faster to switch to, rather than have to tab-through the list? Just like the way [HotSwitch](https://github.com/oniatsu/HotSwitch) works?

Thanks!

**Comment by lwouis** [comment] 2020-03-15 05:29
Hi @samxyzabc! Thank you for the feedback!

> Can the shortcut be fully customized, other than fixed to Tab and another key?

There are a [number of tickets already open about that](https://github.com/lwouis/alt-tab-macos/milestone/1). They are all going to be the focus of v4, the next release.

> Also can any window be assigned a letter to make it faster to switch to, rather than have to tab-through the list?

I feel this functionality plays at offs with what AltTab tries to accomplish. AltTab focuses on **showing** thumbnails so that you can visually identify and switch to a window. If we are no longer using the thumbnails, then what's the point of having them? What's HotSwitch not doing for you currently? It seems you should just use it since it does exactly what you want.

Another tool that may be better suited to the kind of workflow where windows are static would be [yabai](https://github.com/koekeishiya/yabai/). With yabai you can customize rich, keyboard-based, shortcuts and whole workflows.

**Comment by samxyzabc** [comment] 2020-03-15 11:47
Thumbnails are useful visible info to find the window to switch to, especially when there are multiple windows of the same app, such chrome, Firefox etc browsers, which is what HotSwitch lacks, IMHO. Thanks!

**Comment by lwouis** [comment] 2020-04-23 18:15
Closing this as duplicate of #210. I outlined there which steps need to happen for this feature to be developped

**Closed by lwouis** 2020-04-23 18:15 UTC
Labels: duplicate, enhancement
