### ISSUE TITLE
Few apps with no windows wont show up in switcher even if running in bg

### ISSUE THREAD

**Issue by ishaanrathodd** [lwouis/alt-tab-macos#3673] opened 2024-10-11 14:03 UTC
**Describe the bug**

Like other apps show up in switcher with a dash below them when no app window is open if u turn off the "Hide apps with no open window" feature, discord doesnt show up in switcher when no window from discord is open!

**Steps to reproduce the bug**

Turn off "Hide apps with no open window" feature and then just close all discord windows. The app does NOT show in the switcher whereas other app does show with no app windows open.

**Your environment**

* AltTab version: 7.0.1
* macOS version: 15.1 Beta (24B5070a)

**Comment by lwouis** [comment] 2024-10-11 14:48
Hi,

Discord is not a native macOS app. It's a cross-platform, Electron app. They do things a bit differently. When you close the last window, it actually **hides the app**. The app is still open, and the window is still open. The app is just hidden which hides all its windows. You'll find the window in the switcher. You won't find it on the right side since it's an app with a window. Just a hidden app.

Thank you 👍

**Comment by ishaanrathodd** [comment] 2024-10-12 07:49
> Hi,
> 
> Discord is not a native macOS app. It's a cross-platform, Electron app. They do things a bit differently. When you close the last window, it actually **hides the app**. The app is still open, and the window is still open. The app is just hidden which hides all its windows. You'll find the window in the switcher. You won't find it on the right side since it's an app with a window. Just a hidden app.
> 
> Thank you 👍

yea but when you look at vs code, that app even if closed all windows of it(but still running) wont show up in switcher at all, even if you turn on show hidden apps(though discord does).

**Comment by ishaanrathodd** [comment] 2024-10-12 07:58
@lwouis please do look into this bug, i was facing the same issue before too even with discord and other apps too but these apps not showing up is definitely a bug

**Comment by ishaanrathodd** [comment] 2024-10-12 08:39
I have been testing this bug on prev versions too and i can confirm even 6.73.0 has this bug and this kind of completely breaks the use of shortcut functionality in the switcher too. Pressing "W" to close window of an app in switcher closes the window but the switcher still shows that the window is open. Too many bugs when "Hide apps when no open window" is turned off.

**Comment by lwouis** [comment] 2024-10-12 16:35
Hi @ishaanrathodd,

I think I must have explained it poorly.

> Pressing "W" to close window of an app in switcher closes the window but the switcher still shows that the window is open.

This is what Discord wants. They implemented that when you click on the (x) icon, or send a shortcut to close the window, instead of closing it like other apps, they keep it open, and hide the entire app. So visually, you see the window go away. However, it's still very much open. You can right-click on the Dock, and see that the app is still open and that the window is still open.

AltTab is only reporting what's going on. It's not responsible for that UX decision from Discord. This issue has been [discussed many times before](https://github.com/lwouis/alt-tab-macos/issues?q=is%3Aissue+discord+is%3Aclosed), so I'm familiar with the situation. It's 100% Discord doing unintuitive things, and users getting confused. Nothing AltTab can change. Please address your feedback to the Discord Support.

Thank you 🙇

**Comment by ishaanrathodd** [comment] 2024-10-12 17:29
> Hi @ishaanrathodd,
> 
> I think I must have explained it poorly.
> 
> > Pressing "W" to close window of an app in switcher closes the window but the switcher still shows that the window is open.
> 
> **This is what Discord wants**. They implemented that when you click on the (x) icon, or send a shortcut to close the window, instead of closing it like other apps, they keep it open, and hide the entire app. So visually, you see the window go away. However, it's still very much open. You can right-click on the Dock, and see that the app is still open and that the window is still open.
> 
> AltTab is only reporting what's going on. It's not responsible for that UX decision from Discord. This issue has been [discussed many times before](https://github.com/lwouis/alt-tab-macos/issues?q=is%3Aissue+discord+is%3Aclosed), so I'm familiar with the situation. It's 100% Discord doing unintuitive things, and users getting confused. Nothing AltTab can change. Please address your feedback to the Discord Support.
> 
> Thank you 🙇

I understand that. Please see the video i attached, im not talking about discord at all, im talking about apps like notion and vscode. I understand what you say about discord, but im sure vscode is not an electron app, neither is it shown as a hidden app in the switcher app when no windows are open. I hope you understand what im saying

**Comment by lwouis** [comment] 2024-10-13 15:05
Hi @ishaanrathodd,

I checked the video, and indeed some apps have no windows showing. My best guess is that you're seeing the symptoms of #1324. I'm guessing that the missing windows are not on the active Space, and that you've not visited their Space since AltTab was opened.

Thank you 🙇

**Comment by ishaanrathodd** [comment] 2024-10-13 15:21
> Hi @ishaanrathodd,
> 
> I checked the video, and indeed some apps have no windows showing. My best guess is that you're seeing the symptoms of #1324. I'm guessing that the missing windows are not on the active Space, and that you've not visited their Space since AltTab was opened.
> 
> Thank you 🙇

Soooo, the apps that are not showing up in the switcher have no open windows, and the issue u referenced, is there any possible fix for this? Coz unfortunately this makes it very difficult to use the switcher 😔  Btw theres an app called 1Piece which is similar to alttab and it shows apps from all spaces. The only feature it doesnt have is displaying apps with no open windows. Maybe if that app has this functionality possible, it IS possible to integrate that in here too? unfortunately that app is not open source and i like to support open source apps so my primary switcher is alttab.

**Comment by lwouis** [comment] 2024-10-13 15:46
Could you please share a screenshot of your settings in `Preferences > Appearance > Customize Titles Style...`?

**Comment by ishaanrathodd** [comment] 2024-10-13 15:48
> Could you please share a screenshot of your settings in `Preferences > Appearance > Customize Titles Style...`?

<img width="542" alt="image" src="https://github.com/user-attachments/assets/dae6da4a-b184-4409-8180-6b927f6a2f7e">

**Comment by ishaanrathodd** [comment] 2024-10-13 15:50
> Could you please share a screenshot of your settings in `Preferences > Appearance > Customize Titles Style...`?

let me also tell you, this is not a consistent bug, the apps appear half the times and half the times it doesnt

**Comment by lwouis** [comment] 2024-10-13 16:25
Thank you. It's very surprising

Could you please show me a screenshot of these System Settings:

<img width="827" alt="image" src="https://github.com/user-attachments/assets/d5016ceb-b660-4dc5-beb8-e40043c0c702">

In the case in your video, could you show what shows when you right-click the VSCode icon in the Dock? Also, is it listed in Activity Monitor?

Thank you 🙇

**Comment by ishaanrathodd** [comment] 2024-10-13 17:15
> Thank you. It's very surprising
> 
> Could you please show me a screenshot of these System Settings:
> 
> <img alt="image" width="827" src="https://private-user-images.githubusercontent.com/106195/376051418-d5016ceb-b660-4dc5-beb8-e40043c0c702.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4Mzk4OTcsIm5iZiI6MTcyODgzOTU5NywicGF0aCI6Ii8xMDYxOTUvMzc2MDUxNDE4LWQ1MDE2Y2ViLWI2NjAtNGRjNS1iZWI4LWU0MDA0M2MwYzcwMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxM1QxNzEzMTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMWIwOTExYmE1MzY0N2JmOTg0YmU4M2RiM2Q5NTljNjdlNzUzNzRlYTljNDlkNzdmMmE1YjhkNjgyZDY2MmZlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.QU2y8UVwtKMUN8tn8XKI2my1rYQpWuAD4Ot_nWC3lik">
> In the case in your video, could you show what shows when you right-click the VSCode icon in the Dock? Also, is it listed in Activity Monitor?
> 
> Thank you 🙇

<img width="708" alt="image" src="https://github.com/user-attachments/assets/c2a78ae8-27c6-439b-bbcd-bad757312efa">

<img width="247" alt="image" src="https://github.com/user-attachments/assets/6972d78a-1b13-4c34-b886-6d71889157a1">

Yes VS Code is listed in the acrivity monitor even when no windows are open

**Comment by lwouis** [comment] 2024-10-13 20:30
Thank you for sharing these!

From all the data, I can't make sense of what's happening. This functionnality hasn't been touched in 4 years. It's pretty solid. I don't see why it works for everyone except just you. I don't have a clue what could be the root cause.

Could you please run this in Terminal.app and share the output?

`defaults read com.lwouis.alt-tab-macos`

Also could you please click on AltTab icon at the top, and `Send Feedback` then fill the form and send it. This way we can have the Debug Profile and look at it.

Thank you 🙇

**Comment by lwouis** [comment] 2024-10-15 16:46
Thank you for sharing this. In the preferences, I see `hideWindowlessApps = true` which explains instantly why you don't see the windowsless apps.

I think you can find your issue by toggling the setting here on then off again:

![image](https://github.com/user-attachments/assets/4592b1d7-0861-4cea-bedf-fd155d940aa9)

Now the golden question is: how can this setting by `true`, but the UI show `false`

The only scenario I can imagine is that you've updated the preferences with something like `defaults write [...]` or by replacing the preferences file **while AltTab was already running**. Because if you were to restart AltTab, it would read the value in the preferences, and the toggle would have been blue.

Do you remember doing anything like that?

Is you issue fixed now with a restart of AltTab or a toggling on then off?

Thank you 🙇

**Comment by ishaanrathodd** [comment] 2024-10-15 18:00
@lwouis I turned on "Hide apps with no open window" and then off again and restarted the app but still the problem exists.

https://github.com/user-attachments/assets/75b573e4-932a-4dda-a2a0-2d1b476676d3

As you can see in the video, i hover over apple mail app, press "W" to close the window and the app is open with no windows, but the apple mail app doesnt show up in the switcher whilst other apps with no windows does show. If i restart alttab again the switcher WILL show the apple mail in the switcher with no windows, but then again if i close an app window the app will disappear from switcher. The switcher essentially isnt refreshing apps with no windows until i restart alttab. Also, i do not have altered anything about the app or through terminal and im sure about it. Thank you for looking into this problem but i still cant seem to fix it.

**Comment by lwouis** [comment] 2024-10-15 18:40
What's the current value of `defaults read com.lwouis.alt-tab-macos hideWindowlessApps`?

I'm very surprised that when you clicked `w`, we still see the entry in AltTab for the window. Even though it's closed. that's not normal. The symptoms ressemble a bit https://github.com/lwouis/alt-tab-macos/issues/3589. However, after you close the switcher, and reopen it, the window is gone. Very weird stuff. I don't know how to explain it. I still don't know how you got the preference desync'd with the app UI.

@Allsochen any idea what could cause these things?

**Comment by ishaanrathodd** [comment] 2024-10-15 18:49
> defaults read com.lwouis.alt-tab-macos hideWindowlessApps

I have for now turned on the "Hide apps with no open window" feature because its very inconsistent, after turning it on, defaults read com.lwouis.alt-tab-macos hideWindowlessApps = true

Yes after i click "W" we still see the entry in AltTab for the window, however if i click "Q", the app quits and the entry disappears before closing the switcher. The problem is only with "W".

**Comment by lwouis** [comment] 2024-10-15 18:51
> I have for now turned on the "Hide apps with no open window" feature

If you turn it ON, it will hide the items you want to see. You need to turn it OFF. The value should be `false`.

Could you please try that and see if it works for you?

Thank you

**Comment by ishaanrathodd** [comment] 2024-10-15 18:53
> > I have for now turned on the "Hide apps with no open window" feature
> 
> If you turn it ON, it will hide the items you want to see. You need to turn it OFF. The value should be `false`.
> 
> Could you please try that and see if it works for you?
> 
> Thank you

Yes it was turned off, but because the behaviour is inconsistent for apps, i turned it on. If i turn it off, the value is false in terminal, so the settings are working perfectly.

**Comment by lwouis** [comment] 2024-10-15 18:59
Great! 🎉

**Comment by ishaanrathodd** [comment] 2024-10-15 19:01
> Great! 🎉

ehh lol the settings are working perfectly but the functionality is not being reflected in the switcher its buggy like i showed u in the video

**Comment by lwouis** [comment] 2024-10-15 19:24
I'm sorry I couldn't follow. I thought the setting was `true` in your video?

Could you please make the setting be `false`, then see if it works? If it doesn't could you please take a video showing the value of the setting in-app, in the Terminal, and showing the behavior?

Also, could you please check in Activity Monitor if you have only 1 instance of AltTab running? I'm thinking that this could explain the setting desync issue, if one app has a setting and the other another.

Thank you

**Comment by ishaanrathodd** [comment] 2024-10-16 04:56
Okay, there are too many problems but for now, i completely deleted the app and reinstalled the app again and ig rn things seem to work better than before. You can close the issue for now! Thank you!

**Closed** 2024-10-16 06:26 UTC
Labels: bug, unreproducible

**Comment by darthlite** [comment] 2024-12-31 14:36
Sorry to revive this, but I'm having the same issue and only noticed it recently (maybe new macOS update is responsible since it was working perfectly before). I have the setting set to off/false in both terminal and UI but I see apps running without windows (e.g., MS Word), but they do not appear in the switcher.

If I restart AltTab I see them appear, but the moment I close a window with a W, they disappear from the switcher.

**Comment by darthlite** [comment] 2025-01-11 12:04
Sorry, took a while, but done now!
