### ISSUE TITLE
Android emulator is missing from the applications list

### ISSUE THREAD

**Issue by Stokestack** [lwouis/alt-tab-macos#444] opened 2020-07-20 01:40 UTC
**Describe the bug**
I'm programming in Android Studio and running my app in the emulator. Although the emulator is its own application and shows up in Apple's Command-Tab list, it doesn't show up in Alt-Tab.

**Screenshots / video**
<img width="1274" alt="AndroidEmulator" src="https://user-images.githubusercontent.com/196304/87891521-1ed71400-c9ef-11ea-9488-6b068c99910e.png">

**Steps to reproduce the bug**

1. Download and install Android Studio:[]( https://developer.android.com/studio)
2. Install Java 8 runtime (I think; just going from memory here): https://www.java.com/en/download/
3. Download a sample project from their training course: [](https://github.com/udacity/andfun-kotlin-guess-it/tree/Step.02-Solution-Populate-the-GameViewModel)
4. Build and run the project in the emulator. I think the emulator is automatically installed.
5. Try to Alt-Tab between Android Studio & the emulator

There is something funky about the emulator. It frequently doesn't quit when told to, and it often prevents shutdowns.

**Comment by lwouis** [comment] 2020-07-20 04:54
Hi @Stokestack! Thanks for sharing this issue!

I already worked on this issue in the past in #376. I encourage you to check my comments there. I explain how the Android Emulator is a very unique app on the mac. It has no `bundleIdentifier` for example. It is a very weird app. If you want to keep it in your Dock for example, you will see a messy behavior with the icon changing when you close it.

I thought my workaround was working since the user confirmed it does. I guess you may be running a different version or some other variation that breaks my workaround.

Could you please run this command in your Terminal, and share the result?

```bash
ps -ef | grep qemu
```

Also could you please share which version of Android Studio, and which version of the emulator you're running?

**Comment by SoPat712** [comment] 2020-07-20 14:05
This looks like a difficult issue to address. I have no idea how MacOS themselves addresses this issue haha.

**Comment by Stokestack** [comment] 2020-07-20 19:11
Thanks for the reply. Here you go:
119:28.85 /Users/gavin/Library/Android/sdk/emulator/qemu/darwin-x86_64/qemu-system-x86_64 -netdelay none -netspeed full -avd Pixel_2_API_28_Android_9

Android Studio 4.0.  It's not a huge deal; as we've both noted, there's plenty funky about this app and even the OS can't manage it normally. It's probably not worth further effort, when we have that all-important "windowless apps" problem to solve!  🙂

**Comment by lwouis** [comment] 2020-07-20 20:37
The regex should match that path. I'm not sure what's going wrong in your case. I'll try to download the whole thing and try on my system

**Closed** 2020-07-20 22:10 UTC
Labels: bug, unreproducible

**Comment by Stokestack** [comment] 2020-07-21 00:21
Hey thanks for taking the time! This will make debugging easier.
