### ISSUE TITLE
Sonoma Caps-Lock indicator shows as a window in AltTab

### ISSUE THREAD

**Issue by shaoyihao** [lwouis/alt-tab-macos#2849] opened 2023-10-03 03:41 UTC
In the latest MacOS system 14.0 Sonoma, the uppercase and lowercase status of the current input method will be displayed (as a small icon), but in alttab, this small icon will be regarded as a window, which brings inconvenience to window switching.

<img width="301" alt="image" src="https://github.com/lwouis/alt-tab-macos/assets/74238076/492e74c7-6f68-461f-b79b-9c471924b3e6">

https://github.com/lwouis/alt-tab-macos/assets/74238076/ff35cd49-8c85-4a70-9189-8c72183aa0d1

**My environment**

* AltTab version:  6.59.0
* macOS version:  14.0

**Comment by lwouis** [comment] 2023-10-03 06:57
This is either an issue with Sonoma, or Chrome. I'll keep the issue up so I can check it out for myself, once I'm on Sonoma. But I can already tell you that this issue is not an AltTab bug.

**Comment by shaoyihao** [comment] 2023-10-03 08:55
Thank you for your reply!

Displaying the the uppercase and lowercase status as a small icon seems to be a new feature of the macOS 14.
I'm wondering is there any way for AltTab to ignore that "window"(the small icon) ?

**Comment by depleur** [comment] 2023-10-06 21:30
> This is either an issue with Sonoma, or Chrome. I'll keep the issue up so I can check it out for myself, once I'm on Sonoma. But I can already tell you that this issue is not an AltTab bug.

This seems to be an issue with Sonoma since the same issue is reproducible using Firefox, Sublime Text and a bunch of  other apps too.

**Comment by meako689** [comment] 2023-10-11 10:27
The same behavior appears when the input language indicator shows up.

I was trying to add it to the blacklist in the AltTab, but with no luck. The indicator seems to 'belong' to a parent window, of the focused application.

Another workaround would be to disable the indicator itself.

https://forums.macrumors.com/threads/caps-lock-icon.2391867/page
https://stackoverflow.com/questions/77248249/disable-macos-sonoma-text-insertion-point-cursor-caps-lock-indicator

**Comment by lwouis** [comment] 2023-10-12 09:07
I've updated to Sonoma today, and was able to look into this issue.

Sonoma adds a window to show the indicator. It creates the window, in the app which has the active input field.

1. macOS should obviously not use a window for that purpose. There are all sorts of panels and HUDS elements to use for that sorts of small UI. It should definitely not be a window. I hope Apple changes that implementation.
2. In the meantime, there is nothing AltTab can do to workaround it. The window has no unique signature which we could use to hardcore a workaround to filter out it out.

It's unfortunate that Apple keeps introducing new issues with each release. See the [second paragraph here](https://github.com/lwouis/alt-tab-macos/issues/1179#issuecomment-1755873877).

Closing this as unactionable

**Closed by lwouis** 2023-10-12 09:07 UTC
Labels: unactionable, macOS 14

**Comment by victorlin** [comment] 2023-11-13 21:29
I'm using macOS 14.1.1 + AltTab 6.64.0 and can't reproduce the issue with the caps lock indicator. The indicator is still shown by the system, but it doesn't show as a window in AltTab.

**Comment by victorlin** [comment] 2023-11-13 21:31
However, the indicator is not limited to caps-lock: it can also be shown when one has multiple input sources.

![A](https://github.com/lwouis/alt-tab-macos/assets/13424970/7d116d99-d3c3-4a52-8885-d64a00f1e81f) ![注](https://github.com/lwouis/alt-tab-macos/assets/13424970/e5fab3d4-7b43-40db-8f6f-6475b2df027a) 

So far I have seen it come up in specific situations:

1. When switching input sources.
2. When switching away from [iTerm](https://iterm2.com).

(1) isn't detected by AltTab, but (2) is. I can't find any other application that causes this when switching away from it (macOS's `Terminal.app` works fine).

**Comment by nskazki** [comment] 2024-03-15 03:16
@victorlin, you can disable the inline language indicator with 

```
defaults write kCFPreferencesAnyApplication TSMLanguageIndicatorEnabled 0
```
