### ISSUE TITLE
Alt-Tab Fullscreen bug

### ISSUE THREAD

**Issue by TonyL111** [lwouis/alt-tab-macos#1305] opened 2022-01-03 06:15 UTC
**Describe the bug**

Google Chrome disappears from alt-tab after exiting a fullscreen youtube video. I've tried disabling all chrome extensions and the problem still persists.

**Screenshots / video**

https://www.loom.com/share/62f7fa0c171447aabbf721fe72458d62

**Steps to reproduce the bug**

Fullscreen a youtube video and then exit the fullscreen. Then the google chrome will disappear from alt-tab.
By the way I am using a silicone mac.

**Comment by lwouis** [comment] 2022-01-03 06:21
@TonyL111 Which macOS version are you using? The fullscreen animation seems different to the one i see on Catalina.

i need to try and reproduce your scenario on my machine.

Also note that there are similar existing tickets like #471 #1173

**Comment by TonyL111** [comment] 2022-01-03 09:29
<img width="595" alt="Screen Shot 2022-01-03 at 1 24 08 AM" src="https://user-images.githubusercontent.com/46988378/147915529-3eb388df-1152-4ae4-bdf8-c8a2f95c16f6.png">

I can duplicate this every time with google chrome but it does not happen on safari. In addition I've noticed that the animation for the fullscreen transition is different in chrome than in safari.

**Comment by lwouis** [comment] 2022-01-06 02:12
I can't reproduce this issue on my Catalina laptop. I also tried in my Monterey VM, and it works fine.

Are you able to reproduce this issue every single time you try, or is it just happening sometimes?

**Comment by TonyL111** [comment] 2022-01-07 21:23
I tried to reproduce the bug and it appears that it happens when I have 2 windows of the google chrome open on two separate monitors. It doesn't happen instantly after restarting my computer but I can usually get the bug with about 3-5 alt tabs with fullscreenings in between.

**Comment by lwouis** [comment] 2022-04-28 17:14
Closing as there are already similar tickets

**Closed by lwouis** 2022-04-28 17:14 UTC
Labels: bug, unreproducible
