### ISSUE TITLE
Order window is fixed and by start time of the window

### ISSUE THREAD

**Issue by kdeberk** [lwouis/alt-tab-macos#2459] opened 2023-04-06 07:54 UTC
**Is your feature suggestion related to a problem? Please describe.**
I normally only have three or four windows open at a time. The constantly changing order between these windows confuses me to no end. I would like this order to be fixed always so that I can, for example, alt-tab from firefox twice to reach emacs and then shift-alt-tab twice from emacs to reach firefox again. 

**Describe the solution you'd like**
The solution is basically how the default alt-tab behavior worked on Mac OS X before Lion (or at least how I remember it; I've been missing it ever since). The windows are ordered by their start time.

**Describe alternatives you've considered**
No alternatives considered.

**Comment by lwouis** [comment] 2023-04-06 08:04
Duplicate of #515

**Closed by lwouis** 2023-04-06 08:04 UTC
Labels: enhancement
