### ISSUE TITLE
It automatically skips multiple tabs even though I only press once "Command + Tab" 

### ISSUE THREAD

**Issue by ugurkellecioglu** [lwouis/alt-tab-macos#3236] opened 2024-03-13 15:28 UTC
**Describe the bug**

It automatically skips multiple tabs even though I only press once "Command + Tab" .Let's say  I have 5 tabs, and when I do Command + Tab combo, expected behaviour is to select 2nd tab right, sometimes it just skips to 3-4-5 etc. 

**Screenshots / video**

https://www.loom.com/share/e971cf2afed14e82bb25fd05bc805779

**Steps to reproduce the bug**

1- Command + tab
2- Sometimes it skips some tabs. 

**Your environment**

* AltTab version: 6.65
* macOS version: Sonoma 14.2.1
* Other relevant info: it just my laptop.

**Comment by lwouis** [comment] 2024-03-13 18:02
Duplicate of https://github.com/lwouis/alt-tab-macos/issues/3117

**Closed by lwouis** 2024-03-13 18:02 UTC
Labels: bug
