### ISSUE TITLE
Some windows are occasionally missing

### ISSUE THREAD

**Issue by vthemelis** [lwouis/alt-tab-macos#2582] opened 2023-06-08 22:07 UTC
**Describe the bug**

I noticed that some times some of my open windows are completely missing from the AltTab stack. For example, the Safari window that I'm currently using is absent from my window stack (ie, I can AltTab away from it _but I cannot AltTab back to it_).

**Steps to reproduce the bug**

Unfortunately, I cannot offer a repro yet.

**Your environment**

* AltTab version: [6.58.0](https://github.com/lwouis/alt-tab-macos/compare/v6.57.0...v6.58.0)
* macOS version: 12.0.1 (21A559)

**Comment by lwouis** [comment] 2023-06-09 06:02
Hi,

i think you're seeing #1324 

closing the ticket. Let me know if it's not it

thank you

**Closed by lwouis** 2023-06-09 06:02 UTC
Labels: bug

**Comment by vthemelis** [comment] 2023-06-09 07:39
@lwouis not sure if it's the same as I don't use full screen mode, only expanded Windows through magnet.

**Comment by lwouis** [comment] 2023-06-09 08:28
Do you use multiple Spaces? The issue is with Spaces. Fullscreening a video for example will create a new Space. But spaces you manually create and use have the issue as well

**Comment by vthemelis** [comment] 2023-06-11 21:10
I double checked and I was not using any spaces. I'll try to run on a debugger and see what's going on.

**Comment by lwouis** [comment] 2023-06-12 06:59
Thank you @vthemelis. If you find a way to understand, and even better, reproduce the issue consistently, please share here, and I'll re-open the ticket 👍

**Comment by vthemelis** [comment] 2023-06-12 23:05
It seems like it got resolved after moving to the latest version. As an extra datapoint, it seemed to only be affecting Apple apps (Safari, Xcode, QuickTime).
