### ISSUE TITLE
Separating apps based on desktops they're on

### ISSUE THREAD

**Issue by kontramantra** [lwouis/alt-tab-macos#2033] opened 2022-10-20 16:17 UTC
I love the option of being able to command+tab across various desktops/visible spaces. However, the order the app thumbnails are currently shown while toggling seems to me to be random. In addition, app thumbnails are all clustered together, so it is pretty hard to clearly see on which desktop/visible space the app I'm command-tabbing is.

What I'm imagining one possible solution to be is having a horizontal line splitting apps in their corresponding desktops/visible spaces. That way, when pressing command+tab I could clearly see not only all open windows, but also on which desktop/visible space they are.

I can also imagine that for many open windows this would make the AltTab's window too big. But there already is Window min/max width in row slider, so that could mitigate the issue.

Wish I could donate to this project, it's saving my sanity.

**Comment by lwouis** [comment] 2022-10-20 21:25
Duplicate of #337

**Closed by lwouis** 2022-10-20 21:25 UTC
Labels: enhancement
