### ISSUE TITLE
quickly iterating through all windows

### ISSUE THREAD

**Issue by matthijsbro** [lwouis/alt-tab-macos#747] opened 2020-12-27 09:52 UTC
**Describe the bug**

When I open the switcher, it (somtimes) quickly iterates through all windows as if I was holding down the right arrow key. It stops at the last one. Macos Big Sur.

**Steps to reproduce the bug**

1. Go to > open with option+tab
2. Seer error

**Comment by vrnvorona** [comment] 2020-12-29 12:38
Have same, i use Cmd + Tab, sometimes it goes forward as if i hold Tab, but i hold only Cmd to select window i want.

Couldn't reproduce it with guarantee, but it happens quite often.

**Comment by lwouis** [comment] 2021-01-02 02:34
Duplicate of https://github.com/lwouis/alt-tab-macos/issues/719 and https://github.com/lwouis/alt-tab-macos/issues/633

**Closed by lwouis** 2021-01-02 02:34 UTC
Labels: bug
