### ISSUE TITLE
Group windows of same application

### ISSUE THREAD

**Issue by Kazuto** [lwouis/alt-tab-macos#1861] opened 2022-08-11 12:31 UTC
**Is your feature suggestion related to a problem? Please describe.**
As a developer, I have multiple windows of the same applications open at any given time. I switch those windows with `cmd+<`. I don't need to see N chrome browser thumbnails.

**Describe the solution you'd like**
An option to group windows of the same application, just like macOS.

**Describe alternatives you've considered**
macOS built-in switch functionality.

**Comment by lwouis** [comment] 2022-08-11 13:03
Duplicate of #337

**Closed by lwouis** 2022-08-11 13:03 UTC
Labels: enhancement

**Comment by Kazuto** [comment] 2022-08-12 11:44
Actually, it's not a duplicate. 

The mentioned issue was sorting in order `1(word)3(word),2(Powerpoint),3(Excel),3(Evernote),4(Facetime)`, not grouping all windows of one application as one item as macOS does.

**Comment by lwouis** [comment] 2022-08-12 14:39
@Kazuto it is a duplicate. I think you may have missed some info from the other ticket.

The title of the issue is about grouping then drilling down. Here's a [visual aid as to what it could look like](https://github.com/lwouis/alt-tab-macos/issues/337#issuecomment-639307626). Please also see my reply to that comment, and the overall thread for full context.
