### ISSUE TITLE
Mouse hover always selects window

### ISSUE THREAD

**Issue by vfilter** [lwouis/alt-tab-macos#3101] opened 2024-01-12 02:23 UTC
**Describe the bug**

Since a few weeks ago, unchecking "Mouse hover" under "Also select windows using" has no effect and windows get selected when the mouse is hovering and moving over them.

**Steps to reproduce the bug**

1. Start AltTab
2. Uncheck option
3. Press tabbing shortcut
4. Hover mouse over window

**Your environment**

* AltTab version: 6.64.0
* macOS version: 14.2.1
* Other relevant info: Using external mouse & keyboard

**Comment by lwouis** [comment] 2024-01-12 08:52
Hi,
I can't reproduce. Could you please share a video of the issue?
Thank you

**Comment by yawks** [comment] 2024-02-01 08:52
Hello,
Same issue here:

https://github.com/lwouis/alt-tab-macos/assets/4396128/6facfe6d-31d0-4f2d-bae9-de15fff764c9

**Comment by lwouis** [comment] 2024-02-01 08:57
Hi @yawks,

What the video shows is expected behavior.

* The white outline is mouse hover. It's used to indicate which preview you are interacting with, with the mouse. It's useful for drag-and-dropping files on top of previews for example
* The black background is the selected window. It's the one which will be focused if you release the keyboard shortcut.

If you select the `Suivi de la souris` (aka `Mouse hover`), the mouse will make both the white outline, and the black background follow the mouse.

I'll close this ticket for now

Thank you

**Closed by lwouis** 2024-02-01 08:57 UTC
Labels: bug, unreproducible

**Comment by yawks** [comment] 2024-02-01 09:03
ok, this is not a big deal (for me), but it sometimes occurs I unexpectedly move the mouse while "alt tabbing" with the keyboard and the rotation is interrupted by the mouse over

**Comment by lwouis** [comment] 2024-02-01 09:13
@yawks this is not what we see on your video though. Do you mean that you sometimes experience what we see in [this issue](https://github.com/lwouis/alt-tab-macos/issues/3117)?

**Comment by yawks** [comment] 2024-02-02 10:36
In my video I did not use the keys, only the mouse.
The situation I tried to describe does not occur a lot and is not really an issue.

And I did not experience what's mentionned in the #3117 issue.
