### ISSUE TITLE
After disconnecting external monitor some apps are lost from alt tab

### ISSUE THREAD

**Issue by llowinge** [lwouis/alt-tab-macos#765] opened 2021-01-06 09:38 UTC
**Describe the bug**

I have connected external monitor - with that alt tab works great. Then i disconnect from external monitor and i can see that some apps are missing from alt tab (eg. one of chrome window).

**Screenshots / video**

I will provide those later.

**Steps to reproduce the bug**

**Comment by lwouis** [comment] 2021-01-25 15:28
I think this is a duplicate of #656

**Closed by lwouis** 2021-01-25 15:28 UTC
Labels: bug, unclear, unreproducible
