### ISSUE TITLE
Permissions explanation

### ISSUE THREAD

**Issue by ris58h** [lwouis/alt-tab-macos#345] opened 2020-05-20 19:59 UTC
I couldn't find any explanation about required permissions in the app itself, nor on the site, nor on GitHub. I know there is a reason to ask 'Screen Recording' permission for example, but it's not obvious for an end user.

**Comment by lwouis** [comment] 2020-05-21 02:06
Hi @ris58h! Thank you for sharing this feedback!

I'm so intimately familiar with the app that I never considered that these permissions may not be obvious to users. It should indeed be explained *why* these are necessary for the app to work.

I'll close this ticket as a duplicate of the broader #127. Please follow progress in that ticket 👍

**Closed by lwouis** 2020-05-21 02:06 UTC
Labels: duplicate
