### ISSUE TITLE
[feature suggestion] one switch to "merge same windows"

### ISSUE THREAD

**Issue by keman5** [lwouis/alt-tab-macos#2066] opened 2022-11-01 06:50 UTC
**Is your feature suggestion related to a problem? Please describe.**
Open many windows in the same application, then switch apps, I will see two or three the same icons of an application, and I will be confused that which one is I want? I will press keys more times, this is a more troublesome way to open the less used window.

**Describe the solution you'd like**
I want to see one icon by a switch in the preferences to "merge windows" like the native switcher.

**Describe alternatives you've considered**
Using alt-tab show different apps will be more efficient for many windows.

<img width="1524" alt="image" src="https://user-images.githubusercontent.com/116868115/199171204-5b9cf774-665b-46e8-ad5c-abbe930c826a.png">

**Comment by lwouis** [comment] 2022-11-01 08:42
Duplicate of #337

**Closed by lwouis** 2022-11-01 08:42 UTC
Labels: enhancement
