### ISSUE TITLE
Fullscreen (other space) windows disappear

### ISSUE THREAD

**Issue by MrBaseMax** [lwouis/alt-tab-macos#471] opened 2020-07-28 12:34 UTC
**Describe the bug**

Hi. Could't find anything similar in known issues. Sorry if was there.

Sometimes fullscreen windows aren't shown in the list of alt+tab windows (to switch to) until switching to that window other way. And then it returns to list and works fine for a while. After a certain number of switches, the problem comes again. 

Thank you, the App is awesome!

**Comment by lwouis** [comment] 2020-07-28 12:50
Hi @MrBaseMax! Are you sure the issue doesn't involve restarting AltTab? Note that updating AltTab restarts it, so the symptom would appear after a restart.

I'm mentioning restarts because windows opened *before* AltTab is (re)started are known to not be visible by AltTab in some circumstances. The reason being that there is no public API to grab windows from other Spaces than the active one, so we use buggy private APIs to achieve a best-effort.

If you scenario does *not* involve restarting AltTab, then I think it could be linked to the way we try to detect tabs (think Finder tabs). In that case, could you please help us investigate by providing steps to reproduce? The best would be a [Loom recording](https://www.loom.com/) of your screen showing the problem happening and the steps to get there.

**Comment by MrBaseMax** [comment] 2020-07-28 18:02
https://youtu.be/Yechz9hOtQs

"Windows10" fullscreen Parallels window at the 2d Space disappeared after a few switches. Becomes visible again only after returning to this app via Mission Control

**Comment by lwouis** [comment] 2020-07-29 19:14
Thank you for the video! That helps a lot understand the issue. My first guess is that it's an issue with tab detection, and some timing. Either the transition to fullscreen animation, or Parallel being a large app, takes a bit longer to answer the AX call we make, and that result of AltTab mistakingly identifying the fullscreen window as a tabbed window.

I'll try to reproduce locally

**Comment by lwouis** [comment] 2020-08-06 03:24
@MrBaseMax at 00:06 in the video, the focus switches from AltTab preferences to the fullscreen Parallel window, but AltTab main window is not showing. What triggered that transition? Did you perhaps do a shortcut, or a multi-finger swipe to switch?

**Comment by MrBaseMax** [comment] 2020-08-06 07:50
I used BetterTouchTool shortcut. But it didn't matter, also happened when using AltTab trigger.
But i can't reproduce it now, maybe it was fixed with the regression bug #484

**Comment by lwouis** [comment] 2020-08-06 07:57
Well that's good news! I'll close the ticket for now. If you experience the issue again please let me know and i'll happily reopen this ticket 👍

**Comment by MrBaseMax** [comment] 2020-08-06 08:36
Sure! Thanks a lot

**Comment by MrBaseMax** [comment] 2020-10-04 15:27
Bug has returned with 6.7.1 (mb earlier, i didn't use recent releases due to other bugs). Experience with Parallels window. More often than it used to, when the current bug had been born.

**Comment by lwouis** [comment] 2020-10-05 10:35
I'm suspecting that this is the same root cause as #603. I'll re-open this issue in case they are not the same though

**Comment by MrBaseMax** [comment] 2020-10-05 10:37
yep, seems so

**Comment by lwouis** [comment] 2021-04-21 14:09
Closing this ticket, as I can't reproduce, and I'm thinking/hoping it should be gone after some recent fixes about fullscreen apps.

**Closed by lwouis** 2021-04-21 14:09 UTC
Labels: bug, unreproducible
