### ISSUE TITLE
Buttons not aligned.

### ISSUE THREAD

**Issue by Nimrod0901** [lwouis/alt-tab-macos#808] opened 2021-02-07 16:07 UTC
**Describe the bug**

version: Version 6.15.0
Buttons in Shortcut 1 and Shortcut2 are not aligned.

**Screenshots / video**

Shortcut 1         |   Shortcut 2
:-------------------------:|:-------------------------:
![image](https://user-images.githubusercontent.com/33589385/107152106-05a0af80-69a1-11eb-821f-7c6debcb829c.png) |  ![image](https://user-images.githubusercontent.com/33589385/107152090-fa4d8400-69a0-11eb-9999-7ff65ef865fc.png)

**Steps to reproduce the bug**
1. Go to `Controls`
2. Switch between `Shortcut 1` and `Shortcut 2` quickly.
3. You can see the two panes are not aligned...

I am glad to fix the code if you don't have the time.

**Comment by lwouis** [comment] 2021-02-08 14:23
Hi @Nimrod0901! Thanks for sharing this issue!

Let me tell you, it was like playing "Can you spot the differences?" on your screenshots. I couldn't tell the difference for the life of me. Then I started my Big Sur VM, and was able to see the issue by switching back-and-forth between shortcut 1 and 2.

For other people interested, the issue is the vertical position of the button on the right of "While open, press:". Only the buttons, not the labels on their right.

> I am glad to fix the code if you don't have the time.

That would be really cool! Let me know if you need help getting started! There is a [contribution guide here](https://alt-tab-macos.netlify.app/contributing).

**Comment by lwouis** [comment] 2021-02-17 17:34
Nice animation from https://github.com/lwouis/alt-tab-macos/issues/828:

https://user-images.githubusercontent.com/15688641/108237470-e6fd9e00-7182-11eb-8e5a-b4d78dbe1bc8.mp4

**Comment by decodism** [comment] 2022-04-13 11:34
I no longer see this issue.

**Comment by lwouis** [comment] 2022-04-13 12:55
@decodism it may be happening only on certain macOS versions

**Comment by lwouis** [comment] 2022-05-28 04:17
Closing this as subsumed by #351

**Closed by lwouis** 2022-05-28 04:17 UTC
Labels: bug, macOS 11
