### ISSUE TITLE
Visual artefacts while switching active tabs

### ISSUE THREAD

**Issue by shmileee** [lwouis/alt-tab-macos#1125] opened 2021-09-09 09:38 UTC
**Describe the bug**

After the latest app update when you switch between active applications there's a visual glitch / artefact presented to the user.

I'm on BigSur (11.5.2) running latest AltTab (6.24.0) version. The application configuration is default, with an exception to controls, which are as on the attached image.

![Screenshot 2021-09-09 at 11 37 05](https://user-images.githubusercontent.com/9083008/132662097-63c38873-66f5-4a77-b0d0-e21332835ae0.png)

**Screenshots / video**

This happens randomly, I wasn't able to find a reproducible way or pattern, neither I was able to get a screenshot since this disappears really quickly. I raise this issue hoping I'm not alone struggling with it.

**Steps to reproduce the bug**

See above.

**Comment by re1oaded** [comment] 2021-09-09 13:45
Me too

iMac 2020
macOS 10.15.7

**Comment by re1oaded** [comment] 2021-09-09 13:45
It appears often and cannot be reproduced.

**Comment by shmileee** [comment] 2021-09-09 13:52
I've downgraded app to version 6.22.1 and hasn't noticed any issue since 3 hours so far.

**Comment by limonte** [comment] 2021-09-09 17:54
Same here:

<img width="574" alt="CleanShot 2021-09-09 at 20 53 41@2x" src="https://user-images.githubusercontent.com/6059356/132737514-36f201e9-e44d-4916-a364-ada37efeef08.png">

**Comment by lwouis** [comment] 2021-09-10 05:25
This ticket is a duplicate of https://github.com/lwouis/alt-tab-macos/issues/563. Please see the gifs here for instance: https://github.com/lwouis/alt-tab-macos/issues/563#issuecomment-690654640. I think they are showing the symptoms that this ticket is talking about, right?

We've had this issue for around a year, as you can see from the other ticket creation date. It seems however that this glitch has been happening more frequently since either v6.23 or v6.24.

This may help us locate the root cause of this issue, since something that changed in the source code between v6.22 and now has increased the occurrence rate of the glitch.

That's for the good news. The bad news is that I can't reproduce the issue consistently, and thus it's pretty much impossible to debug. You can see in the original ticket that I was still lucky to have it happen during runs in Instruments, and still all the profiling data doesn't help. I believe this is because the issue happens within Apple's frameworks/code.

I think I've found some clues and ideas on how to maybe tackle this when working on https://github.com/lwouis/alt-tab-macos/issues/1096#issuecomment-912673340. However, it's really hard to even know if a change in code is working or not. How would I measure it? The issue is happening rarely, so to know that a change is useful I would have to prove that it happens less, over the course of a day maybe? But a day of using AltTab how many times exactly? Really hard to make a protocol to establish progress here.

So please follow progress/discussion in the other ticket. If you happen to know about macOS programming, please help find a breakthrough in the issue 👍

**Closed by lwouis** 2021-09-10 05:25 UTC
Labels: bug

**Comment by limonte** [comment] 2021-09-19 13:04
> This ticket is a duplicate of #563. Please see the gifs here for instance: [#563 (comment)](https://github.com/lwouis/alt-tab-macos/issues/563#issuecomment-690654640). I think they are showing the symptoms that this ticket is talking about, right?
> 
> We've had this issue for around a year, as you can see from the other ticket creation date. It seems however that this glitch has been happening more frequently since either v6.23 or v6.24.
> 
> This may help us locate the root cause of this issue, since something that changed in the source code between v6.22 and now has increased the occurrence rate of the glitch.
> 
> That's for the good news. The bad news is that I can't reproduce the issue consistently, and thus it's pretty much impossible to debug. You can see in the original ticket that I was still lucky to have it happen during runs in Instruments, and still all the profiling data doesn't help. I believe this is because the issue happens within Apple's frameworks/code.
> 
> I think I've found some clues and ideas on how to maybe tackle this when working on [#1096 (comment)](https://github.com/lwouis/alt-tab-macos/issues/1096#issuecomment-912673340). However, it's really hard to even know if a change in code is working or not. How would I measure it? The issue is happening rarely, so to know that a change is useful I would have to prove that it happens less, over the course of a day maybe? But a day of using AltTab how many times exactly? Really hard to make a protocol to establish progress here.
> 
> So please follow progress/discussion in the other ticket. If you happen to know about macOS programming, please help find a breakthrough in the issue 👍

While this **might be** the duplicate of this old issue, as you can see from the multiple issue reports for many users it started to happen **only with the latest release**. So please reconsider reopening and investigating what might cause the issue for users like me for whom issue started only with the latest release. 

Thank you.

**Comment by lwouis** [comment] 2021-09-19 13:21
> reopening and investigating what happened between v6.23.0 and v6.24.0

Reopening this ticket and investigating the issue are different things. I closed this ticket as i prefer the discussion happen in one place, as this issue has been happening forever, and has existing in-depth investigation in the original ticket. The comments/testimonies in this present tickets are not lost. They add to the material in the other ticket.

So to recap, let's focus the efforts in one place
