### ISSUE TITLE
AltTab size on my MacBook Pro 14" vs on LG UltraFine are way off

### ISSUE THREAD

**Issue by bradhs** [lwouis/alt-tab-macos#1816] opened 2022-07-25 23:15 UTC
The pixel size on the icons are significantly different between monitors even though the DPI is relatively similar.

**Comment by lwouis** [comment] 2022-07-26 07:07
@bradhs could you please share more info like screenshots on the various monitors, resolution and dpi of the monitors, etc?

Thank you

**Comment by lwouis** [comment] 2022-07-29 23:43
@bradhs any update?

**Comment by bradhs** [comment] 2022-07-29 23:55
How do I get a snapshot of it?  I can't seem to activate the snapshot shortcut while keeping Alt Tab open.

**Comment by bradhs** [comment] 2022-07-29 23:58
I**MacBook Pro 14"**
**Resolution:** 1512x982
**DPI:** 0.1972mm

**LG 27"**
**Resolution:** 2560x1440
**DPI:** 0.2335mm

**Comment by bradhs** [comment] 2022-07-30 04:53
Okay, I think I know what's up.  The Max height on screen is set to 65%.  On the LG 27" it's fine, but on the 14" MBP display it's squished.  The resolution is different enough to where it makes a difference.

Would it be better to specify pixels instead of percentages?


<img width="563" alt="image" src="https://user-images.githubusercontent.com/51719730/181875226-f90b1b0b-6c69-4e0a-9a96-73520ab973db.png">

**Comment by lwouis** [comment] 2022-07-31 15:19
I see. Then this ticket is a duplicate of #1107

**Closed by lwouis** 2022-07-31 15:19 UTC
Labels: bug, unactionable, unclear
