### ISSUE TITLE
App seems to make Control key sticky

### ISSUE THREAD

**Issue by ngocphamm** [lwouis/alt-tab-macos#175] opened 2020-03-12 13:00 UTC
When the app is set to using Control + Tab as the shortcut.

From macOS, it's kinda hard to tell but I constantly have to do RDP to a Windows machine and it's there I can see the effect. In Visual Studio Code in that Windows machine, once the Control key is pressed, every single click after that will add another cursor in the editor, just like when I hold down Ctrl key and click to create multiple cursors in VSC.

Please let me know if there's actually a better/easier way to test this within macOS. I wil gladly do and report more information.

Thanks!

**Comment by lwouis** [comment] 2020-03-13 00:16
Hi @ngocphamm! Thank you for your feedback!

The issue only happens when the main key is control or with command/alt too?

I'm adding this ticket to the [next milestone](https://github.com/lwouis/alt-tab-macos/milestone/1). I think that as soon as we adopt a shortcut library, these corner cases will go away

**Comment by ngocphamm** [comment] 2020-03-13 13:25
Hi @lwouis. I just tested and it only happend with the main key set to Control. I think I might set it to Command for now to avoid the issue, because I still need Alt-Tab for the Windows session.

Please let me know if I can do anything to debug this.

**Comment by lwouis** [comment] 2020-03-15 05:33
There are a [number of tickets centered around shortcut issues](https://github.com/lwouis/alt-tab-macos/milestone/1). They are all going to be the focus of v4, the next release. Unfortunately I'm a bit stuck by functional gap in ShortcutRecorder. You may want to [upvote the issue](https://github.com/Kentzo/ShortcutRecorder/issues/114) I opened to show that there is interest in that ticket getting implemented. Hopefully using an established library to handle shortcuts would also shut down this issue.

**Comment by lwouis** [comment] 2020-04-19 09:22
Closing this as duplicate of #239 where 2 other people have the issues with other apps. Let's follow the issue there!

**Closed by lwouis** 2020-04-19 09:22 UTC
Labels: bug, duplicate
