### ISSUE TITLE
Select previous window and

### ISSUE THREAD

**Issue by kodmanyagha** [lwouis/alt-tab-macos#942] opened 2021-05-07 14:29 UTC
Hello,

This app is so good app. Thanks to developer. I have a suggestion and I think this is an important suggestion. I can select next window with CMD+TAB keys. I want to select previous window with CMD+SHIFT+TAB keys too in first time. Current behaviour is that: Open window list with CMD+TAB and then push to CMD+SHIFT+TAB for selecting previous window. But I want to select previous tab directly pushing to CMD+SHIFT+TAB keys. 

![image](https://user-images.githubusercontent.com/3948692/117464847-b9dab380-af59-11eb-8cfe-9884e05eab4a.png)

**Comment by lwouis** [comment] 2021-05-08 04:53
Duplicate of #510

**Closed by lwouis** 2021-05-08 04:53 UTC
Labels: enhancement
