### ISSUE TITLE
AltTab hangs when launched from the Applications folder on Ventura beta 5

### ISSUE THREAD

**Issue by zacharee** [lwouis/alt-tab-macos#1852] opened 2022-08-09 19:30 UTC
**Describe the bug**

I updated to Ventura beta 5 today on my M1 Pro MBP and noticed that AltTab was hanging on launch.

After playing around with building my own version, I noticed that when run from the Applications folder it hangs. Otherwise (with the debug version that doesn't move itself to `/Applications`) it runs fine.

**Steps to reproduce the bug**

1. Update to Ventura beta 5 on an M1 Mac.
2. Try opening AltTab from the Applications folder and notice it hangs.
3. Try opening a debug version of AltTab from the Applications folder and notice it hangs.
4. Try opening a debug version of AltTab from elsewhere and notice it has no issues.

Note: I built my debug version with Xcode 14.0 beta 5.

**Comment by lwouis** [comment] 2022-08-09 19:52
Could you better describe what you mean by "hanging"? Does it spins with high CPU?

If you can build it locally, could you then launch it in debug mode locally? You could then pause the debug and see where the execution is spending cycles or where it's blocking.

Alternatively, a spin dump from Activity Monitor would help diagnose the issue.

**Comment by zacharee** [comment] 2022-08-09 19:59
> Could you better describe what you mean by "hanging"? Does it spins with high CPU?
> 
> If you can build it locally, could you then launch it in debug mode locally? You could then pause the debug and see where the execution is spending cycles or where it's blocking.
> 
> Alternatively, a spin dump from Activity Monitor would help diagnose the issue.

As soon as it launches, it's marked as "not responding" in Activity Monitor. The menu bar icon consistently appears and the settings window occasionally appears but will have a beach ball of death. CPU usage is low.

The problem is that it only hangs if the `.app` is in `/Applications`. If I do a direct launch from AppCode there are no issues.

I can't seem to launch the debug executable inside `/Applications` through the terminal to get a log, either. It doesn't see it has screen recording permissions.

Here's a spindump:

[Spindump.txt](https://github.com/lwouis/alt-tab-macos/files/9294180/Spindump.txt)

**Comment by zacharee** [comment] 2022-08-09 20:05
Even weirder: now the debug app only successfully launches if it's run through AppCode. Double-clicking in Finder causes it to hang no matter where the file is located.

**Comment by lwouis** [comment] 2022-08-09 20:16
> I can't seem to launch the debug executable inside /Applications through the terminal to get a log, either. It doesn't see it has screen recording permissions.

I think it will work if you give the permissions to Terminal.app. Could you try that?

> Here's a spindump

It's a bit unclear what the main thread is blocking on. It seems to be some internals from Apple, not code from AltTab. It could indicate a regression in macOS. After all AltTab works on the previous macOS version, and the one you're on is a beta, so that's possibly the root cause here.

**Comment by zacharee** [comment] 2022-08-09 20:19
That let me launch it through the terminal. This is the log:

```
zachary@zacharyMBP MacOS % ./AltTab 
"Current space" 1
"Adding app" 171 "com.apple.loginwindow"
"Adding app" 450 "com.apple.systemuiserver"
"Adding app" 446 "com.apple.dock"
"Adding app" 447 "com.apple.backgroundtaskmanagement.agent"
"Adding app" 449 "com.apple.controlcenter"
"Adding app" 455 "com.apple.WindowManager"
"Adding app" 445 "com.apple.talagent"
"Adding app" 451 "com.apple.finder"
"Adding app" 496 "com.apple.Spotlight"
"Adding app" 477 "com.apple.CoreLocationAgent"
"Adding app" 528 "com.google.Chrome"
"Adding app" 564 "com.apple.TextInputMenuAgent"
"Adding app" 527 "com.apple.notificationcenterui"
"Adding app" 555 "com.apple.AirPlayUIAgent"
"Adding app" 541 "com.apple.Siri"
"Adding app" 581 "com.apple.coreservices.uiagent"
"Adding app" 504 "com.apple.wifi.WiFiAgent"
"Adding app" 580 "com.apple.TextInputSwitcher"
"Adding app" 584 "com.BlueBubbles.BlueBubbles-Server"
"Adding app" 601 "com.microsoft.OneDrive"
"Adding app" 740 "com.spotify.client"
"Adding app" 741 "com.crowdcafe.windowmagnet"
"Adding app" 743 "com.IdeaPunch.ColorSlurp"
"Adding app" 744 "ai.krisp.krispMac"
"Adding app" 579 "com.teamviewer.Desktop"
"Adding app" 614 "com.apple.AppSSOAgent"
"Adding app" 553 "com.logi.cp-dev-mgr"
"Adding app" 746 "com.surteesstudios.Bartender"
"Adding app" 693 "com.apple.universalcontrol"
"Adding app" 550 "com.paragon-software.extfs.notification-agent"
"Adding app" 732 "com.google.chromeremotedesktop.me2me-host"
"Adding app" 538 "com.teamviewer.TeamViewer"
"Adding app" 729 "com.apple.security.Keychain-Circle-Notification"
"Adding app" 767 "com.google.drivefs"
"Adding app" 838 "com.apple.MobileSMS"
"Adding app" 847 "com.apple.SoftwareUpdateNotificationManager"
"Adding app" 881 "com.apple.locationmenu"
"Adding app" 1096 "com.hnc.Discord"
"Adding app" 1201 "com.apple.ActivityMonitor"
"Adding app" 1353 "com.apple.LocalAuthentication.UIAgent"
"Adding app" 1369 "com.apple.accessibility.universalAccessAuthWarn"
"Adding app" 2523 "com.apple.OSDUIHelper"
"Adding app" 3526 "ru.keepcoder.Telegram"
"Adding app" 4290 "com.apple.storeuid"
"Adding app" 4935 "com.apple.UserNotificationCenter"
"Adding app" 8993 "com.jetbrains.AppCode"
"Adding app" 9747 "com.apple.Family"
"Adding app" 10542 "com.apple.PowerChime"
"Adding app" 11831 "com.readdle.smartemail-Mac"
"Adding app" 13584 "com.apple.systempreferences"
"Adding app" 13623 "com.apple.Terminal"
"Adding app" 13943 "com.lwouis.alt-tab-macos"
2022-08-09 16:18:49.224 AltTab[13943:159378] It's not legal to call -layoutSubtreeIfNeeded on a view which is already being laid out.  If you are implementing the view's -layout method, you can call -[super layout] instead. Break on void _NSDetectedLayoutRecursion(void) to debug.  This will be logged only once.  This may break in the future.

```

**Comment by zacharee** [comment] 2022-08-09 20:22
Also, AltTab worked fine on beta 4, so whatever changed happened very recently.

**Comment by aliosmanyuksel** [comment] 2022-08-09 20:46
I've that problem. I upgraded to macOS Ventura Beta 5 today. It has working to beta 4.

**Comment by aliosmanyuksel** [comment] 2022-08-09 21:10
![Screenshot](https://i.ibb.co/0tpPhT1/Ekran-Resmi-2022-08-10-00-07-19.jpg)

**Comment by Write** [comment] 2022-08-09 23:53
Same here :)

**Comment by svk-works** [comment] 2022-08-10 03:40
> Also, AltTab worked fine on beta 4, so whatever changed happened very recently.

can confirm, this has been driving me crazy

**Comment by bradhs** [comment] 2022-08-10 05:42
Same problem. Upgraded to Beta 5 and now AltTab is stuck as Not Responding.

**Comment by bradhs** [comment] 2022-08-10 05:49
2022-08-09 22:48:38.563 AltTab[3654:40136] It's not legal to call -layoutSubtreeIfNeeded on a view which is already being laid out.  If you are implementing the view's -layout method, you can call -[super layout] instead. Break on void _NSDetectedLayoutRecursion(void) to debug.  This will be logged only once.  This may break in the future.

**Comment by GitSparTV** [comment] 2022-08-10 09:46
Same for MacBookPro16,1 on Ventura Public Beta 3

**Comment by MalwarePup** [comment] 2022-08-10 13:03
Same for MacBookPro 14 with M1 on Ventura Public Beta 3

**Comment by lwouis** [comment] 2022-08-10 13:24
Could anyone here follow the error message and put a breakpoint on `void _NSDetectedLayoutRecursion(void)`? I don't have a VM with Ventura beta 5, so I can't reproduce this. On my Catalina machine, and my other VMs, I don't get this warning when running AltTab.

**Comment by aliosmanyuksel** [comment] 2022-08-10 13:36
I can't build this project. If you wanna connect to me via AnyDesk or Teamviewer, i can send my connection code. @lwouis 
mail: aliosmanyuksel@outlook.com

![error](https://i.ibb.co/qsgjmnH/Ekran-Resmi-2022-08-10-16-34-16.jpg)

**Comment by samdenty** [comment] 2022-08-10 13:38
getting this as well, can do a teamviewer too if needed

**Comment by Write** [comment] 2022-08-10 13:47
> Could anyone here follow the error message and put a breakpoint on `void _NSDetectedLayoutRecursion(void)`? I don't have a VM with Ventura beta 5, so I can't reproduce this. On my Catalina machine, and my other VMs, I don't get this warning when running AltTab.

Could you use https://github.com/insidegui/VirtualBuddy ?

**Comment by zacharee** [comment] 2022-08-10 13:58
I'm not quite sure how to set a breakpoint on that function. I've tried `[void _NSDetectedLayoutRecursion]` and without brackets in AppCode's symbolic breakpoints menu but they don't catch it.

**Comment by Write** [comment] 2022-08-10 18:28
I'm willing to help too, I have a VM  Running beta 5, with anydesk, brew, and latest xcode installed.

**Comment by elijahchan2019** [comment] 2022-08-11 04:12
Same here. It seems like apple has changed some SDKs.

**Comment by Ashinch** [comment] 2022-08-11 14:56
I'm in Venture Beta 5 and can accept any test request

**Comment by lwouis** [comment] 2022-08-11 16:53
I was able to connect @Write's Ventura VM, and try and debug the issue. Thank you again @Write for trusting me to use your VM 👍 

I could reach the symbolic breaking by breaking on `_NSDetectedLayoutRecursion`:

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/106195/184189354-20b4c417-e6dc-44ff-bd32-567dc2747777.png">

However, it's pretty useful as it doesn't show which specific window or view is generating the log/issue.

I tried to manually remove the preferences window, feedback window, main window, etc, to try and guess where the issue is coming from, but I can't deduce anything.

Furthermore, I tried to google various pieces of the error message from Apple, but nothing comes up that's relevant.

I'm afraid my time is limited (please see #1179), so I'll wait until Ventura is out of beta to give it a second look.

**Comment by Write** [comment] 2022-08-11 17:21
I don't have any macOS coding knowledge, but I tried to look for what makes the app crash at launch, it seems to be in this function and has nothing to do with _NSDetectedLayoutRecursion since the error message is shown whether this line is commented out or not. But the app actually run when i comment out `Applications.list.append(Application($0))`

![Screenshot du 2022-08-11 à 19 19 37](https://user-images.githubusercontent.com/541722/184194587-a6a4a893-710b-479d-b24f-e09437148265.png)

**Comment by zaper4life** [comment] 2022-08-11 18:04
Hi,
I don't know if it counts as a solution, but it works for me,
Remove altTab from your login items,
Start your machine.
After a few minutes, usually around 10 for me, start altTab,
All is good now.

**Comment by lilbillybiscuit** [comment] 2022-08-12 02:44
> Hi,
> I don't know if it counts as a solution, but it works for me,
> Remove altTab from your login items,
> Start your machine.
> After a few minutes, usually around 10 for me, start altTab,
> All is good now.

This workaround worked for me too., but I didn't have to restart my machine.

**Comment by bradhs** [comment] 2022-08-12 05:59
> Hi, I don't know if it counts as a solution, but it works for me, Remove altTab from your login items, Start your machine. After a few minutes, usually around 10 for me, start altTab, All is good now.

Did not work for me.

**Comment by svk-works** [comment] 2022-08-12 06:11
> > Hi, I don't know if it counts as a solution, but it works for me, Remove altTab from your login items, Start your machine. After a few minutes, usually around 10 for me, start altTab, All is good now.
> 
> Did not work for me.

yup, same

**Comment by Write** [comment] 2022-08-12 09:46
> I don't have any macOS coding knowledge, but I tried to look for what makes the app crash at launch, it seems to be in this function and has nothing to do with _NSDetectedLayoutRecursion since the error message is shown whether this line is commented out or not. But the app actually run when I comment out `Applications.list.append(Application($0))`
> 
> ![Screenshot du 2022-08-11 à 19 19 37](https://user-images.githubusercontent.com/541722/184194587-a6a4a893-710b-479d-b24f-e09437148265.png)
> 
> EDIT : Guessing you already saw that so I'm certainly making you lose your time, I'm sorry.
> 
> EDIT 2 : I managed to make it compile & work with an ugly """fix"" (don't know any side-effect, except, my guess is AltTab won't show itself when AltTabing). It always crashed when AltTab was adding itself to the list of apps. ![Screenshot du 2022-08-11 à 19 48 03](https://user-images.githubusercontent.com/541722/184200211-3e17b3a0-0912-4e2f-a035-c1d231d236bc.png)
> 
> A video of AltTab somewhat working on Beta 5: https://share.socialspill.com/w/5890bb78635279715c3dc7b814ff3082

Here's a debug build with my ugly fix, I think it'll only run on ARM and you'll certainly have to remove / re-add AltTab permissions manually. **Please do not run it if you don't trust me.**

[AltTab.zip](https://github.com/lwouis/alt-tab-macos/files/9315383/AltTab.zip)

**Comment by svk-works** [comment] 2022-08-12 11:57
> > I don't have any macOS coding knowledge, but I tried to look for what makes the app crash at launch, it seems to be in this function and has nothing to do with _NSDetectedLayoutRecursion since the error message is shown whether this line is commented out or not. But the app actually run when I comment out `Applications.list.append(Application($0))`
> > ![Screenshot du 2022-08-11 à 19 19 37](https://user-images.githubusercontent.com/541722/184194587-a6a4a893-710b-479d-b24f-e09437148265.png)
> > EDIT : Guessing you already saw that so I'm certainly making you lose your time, I'm sorry.
> > EDIT 2 : I managed to make it compile & work with an ugly """fix"" (don't know any side-effect, except, my guess is AltTab won't show itself when AltTabing). It always crashed when AltTab was adding itself to the list of apps. ![Screenshot du 2022-08-11 à 19 48 03](https://user-images.githubusercontent.com/541722/184200211-3e17b3a0-0912-4e2f-a035-c1d231d236bc.png)
> > A video of AltTab somewhat working on Beta 5: https://share.socialspill.com/w/5890bb78635279715c3dc7b814ff3082
> 
> Here's a debug build with my ugly fix, I think it'll only run on ARM and you'll certainly have to remove / re-add AltTab permissions manually. **Please do not run it if you don't trust me.**
> 
> [AltTab.zip](https://github.com/lwouis/alt-tab-macos/files/9315383/AltTab.zip)

tysm, it's working perfectly fine for me

**Comment by lwouis** [comment] 2022-08-12 14:33
@Write this is very interesting. You narrowed the issue down to AltTab monitoring AltTab itself.

We had people complain in the past that AltTab's windows (preferences, feedback form, auto-update window) don't show up in AltTab. So I added it. We could remove that, if it's making the app unusable on Ventura, but I can't imagine why it's crashing, especially since it's been working on like 5 major macOS releases.

What I'll do is that if this issue persists when the beta is over, and Ventura goes live, then I'll consider some kind of workaround. I may dig deeper then also, and find a fix that doesn't involve blacklisting AltTab.

**Comment by ccarpiog** [comment] 2022-08-14 10:05
> > I don't have any macOS coding knowledge, but I tried to look for what makes the app crash at launch, it seems to be in this function and has nothing to do with _NSDetectedLayoutRecursion since the error message is shown whether this line is commented out or not. But the app actually run when I comment out `Applications.list.append(Application($0))`
> > ![Screenshot du 2022-08-11 à 19 19 37](https://user-images.githubusercontent.com/541722/184194587-a6a4a893-710b-479d-b24f-e09437148265.png)
> > EDIT : Guessing you already saw that so I'm certainly making you lose your time, I'm sorry.
> > EDIT 2 : I managed to make it compile & work with an ugly """fix"" (don't know any side-effect, except, my guess is AltTab won't show itself when AltTabing). It always crashed when AltTab was adding itself to the list of apps. ![Screenshot du 2022-08-11 à 19 48 03](https://user-images.githubusercontent.com/541722/184200211-3e17b3a0-0912-4e2f-a035-c1d231d236bc.png)
> > A video of AltTab somewhat working on Beta 5: https://share.socialspill.com/w/5890bb78635279715c3dc7b814ff3082
> 
> Here's a debug build with my ugly fix, I think it'll only run on ARM and you'll certainly have to remove / re-add AltTab permissions manually. **Please do not run it if you don't trust me.**
> 
> [AltTab.zip](https://github.com/lwouis/alt-tab-macos/files/9315383/AltTab.zip)

Mmm... I'm getting a "AltTab.app is damaged and can't be opened" when trying to run you version. Strange.

**Comment by svk-works** [comment] 2022-08-14 10:21
> > > I don't have any macOS coding knowledge, but I tried to look for what makes the app crash at launch, it seems to be in this function and has nothing to do with _NSDetectedLayoutRecursion since the error message is shown whether this line is commented out or not. But the app actually run when I comment out `Applications.list.append(Application($0))`
> > > ![Screenshot du 2022-08-11 à 19 19 37](https://user-images.githubusercontent.com/541722/184194587-a6a4a893-710b-479d-b24f-e09437148265.png)
> > > EDIT : Guessing you already saw that so I'm certainly making you lose your time, I'm sorry.
> > > EDIT 2 : I managed to make it compile & work with an ugly """fix"" (don't know any side-effect, except, my guess is AltTab won't show itself when AltTabing). It always crashed when AltTab was adding itself to the list of apps. ![Screenshot du 2022-08-11 à 19 48 03](https://user-images.githubusercontent.com/541722/184200211-3e17b3a0-0912-4e2f-a035-c1d231d236bc.png)
> > > A video of AltTab somewhat working on Beta 5: https://share.socialspill.com/w/5890bb78635279715c3dc7b814ff3082
> > 
> > 
> > Here's a debug build with my ugly fix, I think it'll only run on ARM and you'll certainly have to remove / re-add AltTab permissions manually. **Please do not run it if you don't trust me.**
> > [AltTab.zip](https://github.com/lwouis/alt-tab-macos/files/9315383/AltTab.zip)
> 
> Mmm... I'm getting a "AltTab.app is damaged and can't be opened" when trying to run you version. Strange.

You need to remove quarantine
 `xattr -d -r com.apple.quarantine `
and followed by the application path (just drag and drop the application)

**Comment by ccarpiog** [comment] 2022-08-14 11:23
> > > > I don't have any macOS coding knowledge, but I tried to look for what makes the app crash at launch, it seems to be in this function and has nothing to do with _NSDetectedLayoutRecursion since the error message is shown whether this line is commented out or not. But the app actually run when I comment out `Applications.list.append(Application($0))`
> > > > ![Screenshot du 2022-08-11 à 19 19 37](https://user-images.githubusercontent.com/541722/184194587-a6a4a893-710b-479d-b24f-e09437148265.png)
> > > > EDIT : Guessing you already saw that so I'm certainly making you lose your time, I'm sorry.
> > > > EDIT 2 : I managed to make it compile & work with an ugly """fix"" (don't know any side-effect, except, my guess is AltTab won't show itself when AltTabing). It always crashed when AltTab was adding itself to the list of apps. ![Screenshot du 2022-08-11 à 19 48 03](https://user-images.githubusercontent.com/541722/184200211-3e17b3a0-0912-4e2f-a035-c1d231d236bc.png)
> > > > A video of AltTab somewhat working on Beta 5: https://share.socialspill.com/w/5890bb78635279715c3dc7b814ff3082
> > > 
> > > 
> > > Here's a debug build with my ugly fix, I think it'll only run on ARM and you'll certainly have to remove / re-add AltTab permissions manually. **Please do not run it if you don't trust me.**
> > > [AltTab.zip](https://github.com/lwouis/alt-tab-macos/files/9315383/AltTab.zip)
> > 
> > 
> > Mmm... I'm getting a "AltTab.app is damaged and can't be opened" when trying to run you version. Strange.
> 
> You need to remove quarantine `xattr -d -r com.apple.quarantine ` and followed by the application path (just drag and drop the application)

Thanks, it worked.

**Comment by simyanliang** [comment] 2022-08-14 16:24
Running AltTab from the application on desktop (just not in Applications) seems to work for me on Ventura beta 5 on the latest version 6.46.1 in case anyone facing this issue wants to try to tide them over.

**Comment by zacharee** [comment] 2022-08-14 21:32
I have a PR up that lets AltTab still show its own windows while working around the freeze: https://github.com/lwouis/alt-tab-macos/pull/1865.

You can either pull the repo and merge in that PR to build yourself or you can download the prebuilt debug app: https://github.com/lwouis/alt-tab-macos/files/9334145/AltTab.app.zip.

If you use the debug app, you'll need to run `sudo xattr -cr /path/to/AltTab.app` in a terminal before you can open it.

**Comment by Write** [comment] 2022-08-14 21:55
> I have a PR up that lets AltTab still show its own windows while working around the freeze: #1865.
> 
> You can either pull the repo and merge in that PR to build yourself or you can download the prebuilt debug app: https://github.com/lwouis/alt-tab-macos/files/9334145/AltTab.app.zip.
> 
> If you use the debug app, you'll need to run `sudo xattr -cr /path/to/AltTab.app` in a terminal before you can open it.

Thanks, as such, I removed the link to my build, and replaced it with a link to your message instead.

**Comment by elijahchan2019** [comment] 2022-08-15 10:24
> I have a PR up that lets AltTab still show its own windows while working around the freeze: #1865.
> 
> You can either pull the repo and merge in that PR to build yourself or you can download the prebuilt debug app: https://github.com/lwouis/alt-tab-macos/files/9334145/AltTab.app.zip.
> 
> If you use the debug app, you'll need to run `sudo xattr -cr /path/to/AltTab.app` in a terminal before you can open it.

It worked perfectly.

**Comment by mrsnakeoil** [comment] 2022-08-15 17:31
> I have a PR up that lets AltTab still show its own windows while working around the freeze: #1865.
> 
> You can either pull the repo and merge in that PR to build yourself or you can download the prebuilt debug app: https://github.com/lwouis/alt-tab-macos/files/9334145/AltTab.app.zip.
> 
> If you use the debug app, you'll need to run `sudo xattr -cr /path/to/AltTab.app` in a terminal before you can open it.

Happy to state this worked for me. Many thanks @zacharee for the work and especially for the build. Saving me time.

Ventura beta 13.0 (22A5321d)

**Comment by KevinXC5** [comment] 2022-08-23 03:15
> I have a PR up that lets AltTab still show its own windows while working around the freeze: #1865.
> 
> You can either pull the repo and merge in that PR to build yourself or you can download the prebuilt debug app: https://github.com/lwouis/alt-tab-macos/files/9334145/AltTab.app.zip.
> 
> If you use the debug app, you'll need to run `sudo xattr -cr /path/to/AltTab.app` in a terminal before you can open it.

Can you help compile an Intel chip version package? Thank you very much!

**Comment by lwouis** [comment] 2022-08-23 08:24
@KevinXC5 the [build i shared on the PR](https://github.com/lwouis/alt-tab-macos/pull/1865#issuecomment-1214465729) should be universal.

**Comment by KevinXC5** [comment] 2022-08-23 12:55
> @KevinXC5 the [build i shared on the PR](https://github.com/lwouis/alt-tab-macos/pull/1865#issuecomment-1214465729) should be universal.
it can work, thks

**Comment by andylin2004** [comment] 2022-08-26 00:14
Seems to still be an issue on macOS Ventura beta 6

**Comment by bradhs** [comment] 2022-08-26 18:08
This is the only build that will work: https://github.com/lwouis/alt-tab-macos/pull/1865#issuecomment-1214465729

**Comment by ifsheldon** [comment] 2022-09-10 14:32
Beta 7 works well with the original 6.46.1 on my M1 Mac. So I guess the previous problem was macOS's internal bug.

**Comment by lwouis** [comment] 2022-09-10 18:50
@ifsheldon that's great news. It may mean that we won't need to do any patch to AltTab to work on Ventura, in the future.

**Comment by lwouis** [comment] 2022-10-14 21:09
Closing as Apple fixed their regression.

**Closed by lwouis** 2022-10-14 21:09 UTC
Labels: bug, unactionable, apple silicon, macOS 13
