### ISSUE TITLE
conflict with system service

### ISSUE THREAD

**Issue by zy-dys** [lwouis/alt-tab-macos#1257] opened 2021-11-27 05:06 UTC
---
Name: conflict with system service
About: when running, the open or save file dialog box will be delayed by about 2 seconds
Title: 'when running, the open or save file dialog box will be delayed by about 2 seconds'
labels: bug
assignees: ''
---
**Describe the bug**
At first, I thought it was a system problem. I went to Apple's customer service and they gave a bunch of useless solutions,
Then the system was reinstalled, and the problem still exists
Inadvertently found that after exiting the alttab, the problem disappeared by itself. It was very smooth to open the file dialog box
After trying all the configuration options without success, go to contexts, but contexts is really not easy to use
**Steps to reproduce the bug**
1. When running alttab, open the browser Command + s to save the web page, or open or save any software file, it will be stuck for about 2 seconds and 100% reproduced
2. This problem existed in the current system when it was 12 and in the previous 11
3. M1 chip

**Comment by nnemkin** [comment] 2021-11-27 16:54
This is a duplicate of #718.

**Closed** 2021-11-28 04:23 UTC
