### ISSUE TITLE
Switch to a different app, ignoring same app's windows

### ISSUE THREAD

**Issue by koterpillar** [lwouis/alt-tab-macos#3452] opened 2024-06-27 01:02 UTC
**Is your feature suggestion related to a problem? Please describe.**
I would like to reserve `` Alt-` `` to switch between the same application's windows, and `Alt-Tab` to always switch to a **different** application.

**Describe the solution you'd like**
Add a "Other apps" option to "Show windows from:" selector and perhaps make it default for `Alt-Tab`.

**Comment by lwouis** [comment] 2024-06-27 09:34
Hi,

It's an interesting idea. However, I think it's quite niche. No one has requested this in 4 years.

I'll close this issue, but please, if you are interested in it, upvote or comment here. This way, if we see an interest for many people here, we can reconsider adding the feature.

Thank you

**Closed by lwouis** 2024-06-27 09:34 UTC
Labels: enhancement

**Comment by koterpillar** [comment] 2024-06-27 11:50
Would you be open to a PR?

**Comment by lwouis** [comment] 2024-06-27 13:52
Hey @koterpillar,

The code change is quite easy, so the issue is not implementation effort. The issue is keeping the number of preferences low. If we add a preference for everyone preference a few users have, the preferences panel will become overwhelming. It is already the case actually.

Please see #351 for the direction we are ahead towards

Thank you

**Comment by koterpillar** [comment] 2024-06-30 06:29
For posterity: this is the default behaviour of Gnome, which I tried to replicate with this app. It is not the default behaviour of Windows 11, so unfortunately it is niche.
