### ISSUE TITLE
Checkboxes are not properly aligned in RTL

### ISSUE THREAD

**Issue by ShlomoCode** [lwouis/alt-tab-macos#3486] opened 2024-07-13 23:39 UTC
**Describe the bug**

In RTL languages ​​like Hebrew, Arabic the boxes should be to the right of the label text. In practice they remain to his left.

**Screenshots / video**

![CleanShot 2024-07-14 at 02 32 44@2x](https://github.com/user-attachments/assets/5771dc02-57ba-44f2-b6d6-4a4c8a26d1df)

**Steps to reproduce the bug**

1. Set the alt-tab application language to Hebrew in System Settings > Language & Region > Applications
2. Open the alt-tab Settings

**Your environment**

* AltTab version: 6.71.0
* macOS version: Sonoma 14.5

**Comment by lwouis** [comment] 2024-07-13 23:50
Hi,

Could you please clarify what the issue is? I'm not a native RTL language user. When I look at the screenshot, it looks correct to me. Could you perhaps provide visuals of how it should look like? Perhaps some other apps like first-party Apple apps doing this correctly, as a reference?

Thank you 🙇

**Comment by ShlomoCode** [comment] 2024-07-13 23:57
The logic (and Apple HIG as well) is that in RTL mode the entire interface should flip, just like a mirror, with specific exceptions like video controls, so the content flows right to left instead of left to right.
Here are some examples:
System Settings:
![CleanShot 2024-07-14 at 02 52 09@2x](https://github.com/user-attachments/assets/e3529c8b-2d75-4c1b-a4e9-0306fb48fcf5)
Safari settings:
![CleanShot 2024-07-14 at 02 53 14@2x](https://github.com/user-attachments/assets/84417441-18d6-4e10-87f1-a721b8b9a951)
iMessage settings:
![CleanShot 2024-07-14 at 02 54 57@2x](https://github.com/user-attachments/assets/47f48a67-8a59-4af7-9038-86ce31b3eb29)

**Comment by lwouis** [comment] 2024-07-14 00:14
AltTab does flip everything like a mirror. I think what may confuse you is that AltTab, even in it's LTR variant uses this type of UI:

```
Setting: [ ]
```

It doesn't use the alternative UI:

```
[ ] Setting
```

In the Safari screenshot you shared, we can see Apple using the same style, and it being mirrored like AltTab does, here in red:

![image](https://github.com/user-attachments/assets/a019bdec-235b-4bca-987d-c5e92ca135e0)

I think AltTab is doing it correctly, no?

**Comment by ShlomoCode** [comment] 2024-07-14 00:21
> AltTab does flip everything like a mirror. I think what may confuse you is that AltTab, even in it's LTR variant uses this type of UI:
> 
> 
> ```
> Setting: [ ]
> ```
> 
> It doesn't use the alternative UI:
> 
> 
> ```
> [ ] Setting
> ```

Hmmm... I didn't notice that. Yes you are right (although the example from Safari is incorrect, what misled you was the "category" text)
![348509097-a019bdec-235b-4bca-987d-c5e92ca135e0](https://github.com/user-attachments/assets/495ab637-943d-42bf-a68f-1c2135042295)

Why does alt-tab really do it like that? I think this is quite unusual

**Comment by lwouis** [comment] 2024-07-14 00:26
I think AltTab uses a neat variant. All labels are on the same side, and all values / interactive elements are on the other side.

Since there is no bug, I'll close this ticket.

Thank you 🙇

**Closed by lwouis** 2024-07-14 00:26 UTC
Labels: bug

**Comment by ShlomoCode** [comment] 2024-07-14 01:05
Sorry for false alarm!
