### ISSUE TITLE
Add setting to change app with no open window icon (high contrast/low contrast)

### ISSUE THREAD

**Issue by SoPat712** [lwouis/alt-tab-macos#1752] opened 2022-06-30 21:55 UTC
Is it possible to allow the user to customize the apps with no open window icon.

as mentioned in https://github.com/lwouis/alt-tab-macos/issues/1727, the new icon contrasts a bit too much for some people, and I don't like alt-tab burning my eyes when I choose to code at 4 in the morning. Can we add an appearance option for it instead?

**Comment by lwouis** [comment] 2022-06-30 22:04
I assume you use Dark Mode? I was thinking to have a dark variation for Dark Mode, and keep the current design for Light Mode.

**Comment by SoPat712** [comment] 2022-06-30 22:10
I use both, and I prefer the old variant on both, honestly.

Also, it's yellow now?

![image](https://user-images.githubusercontent.com/30350506/176787280-80908288-245e-4af6-801d-b1dd27747278.png)

**Comment by lwouis** [comment] 2022-06-30 22:13
> Also, it's yellow now?

What do you mean? I need more info to understand what's on the screenshot. Why is the right side yellow-ish?

**Comment by SoPat712** [comment] 2022-06-30 22:29
The app furthest to the right, regardless of how many apps there are, becomes yellow. I'll try quitting alt tab to see if that fixes it.

**Comment by XInTheDark** [comment] 2022-07-09 12:48
> The app with no windows furthest to the right, regardless of how many apps with no windows there are, becomes yellow. I'll try quitting alt tab to see if that fixes it.

Cannot reproduce.

**Comment by SoPat712** [comment] 2022-07-09 14:48
I think it might be an issue with my display. I was also unable to reproduce it consistently.

**Comment by lwouis** [comment] 2022-07-09 14:50
Ok i'll close it then. I have occasional issues when i open Chrome on my display. Display drivers definitely can have bugs. Closing until it's shown to be AltTab and we have ways to reproduce this consistently.

**Comment by lwouis** [comment] 2024-10-09 22:43
This issue should no longer be relevant since we don't have the icon anymore. Closing it 👍

**Closed by lwouis** 2024-10-09 22:43 UTC
Labels: enhancement
