### ISSUE TITLE
Option to display on "all displays"

### ISSUE THREAD

**Issue by flypenguin** [lwouis/alt-tab-macos#750] opened 2020-12-27 16:20 UTC
**Is your feature suggestion related to a problem? Please describe.**
I have multiple monitors. The monitor I look at never has a 100% (or even close) correlation to "active window", "mouse pointer", "menu bar". So the alt-tab display opens roughly 30% of the time on the wrong monitor.

**Describe the solution you'd like**
Add the option to display alt-tab on "all monitors" as fourth option.

**Describe alternatives you've considered**
none

**Comment by lwouis** [comment] 2021-01-02 02:41
duplicate of https://github.com/lwouis/alt-tab-macos/issues/535

**Closed by lwouis** 2021-01-02 02:41 UTC
Labels: enhancement
