### ISSUE TITLE
Keyboard combination with "Alt-^" doesn't work

### ISSUE THREAD

**Issue by stephansann** [lwouis/alt-tab-macos#1385] opened 2022-02-17 07:47 UTC
Hello

First of all thanks a lot for this amazing piece of software!

I have a small problem with my second shortcut.
I set up "Alt-^" as combination:

<img width="465" alt="Screen Shot 2022-02-17 at 10 40 14" src="https://user-images.githubusercontent.com/9678681/154428767-b540acf4-3542-4987-9e1f-2a108627f2aa.png">

However the keyboard shortcut does not work. MacOS will just output the sound it does for not configured shortcuts.
Happens both on the laptop keyboard and on my external keyboard.

I have macOS Monterey (12.2.1), MacBook Pro M1.

Thanks a lot in advance for any hint!

Best regards
Stephan

**Comment by lwouis** [comment] 2022-02-17 09:27
It seems to be a duplicate of https://github.com/lwouis/alt-tab-macos/issues/1190

**Closed by lwouis** 2022-02-17 09:27 UTC
Labels: bug
