### ISSUE TITLE
AltTab isn't triggered by command+tab after update to macOS 13.4.1 (c) (22F770820d)

### ISSUE THREAD

**Issue by danulqua** [lwouis/alt-tab-macos#2677] opened 2023-07-18 08:21 UTC
**Describe the bug**

After update to macOS 13.4.1 (c) (22F770820d) AltTab stopped working.
I tried to relaunch AltTab and restart my Mac.

**Screenshots / video**

https://github.com/lwouis/alt-tab-macos/assets/38916225/da707b90-b706-4dab-a1c1-d672939eeeb2

**Steps to reproduce the bug**

1. Update to last macOS version: 13.4.1 (c) (22F770820d)
2. Launch AltTab
3. Hit the shortcut and see that the native app switcher appears instead of AltTab

**Your environment**

* AltTab version: 6.61.0
* macOS version: macOS 13.4.1 (c) (22F770820d)
* Other relevant info: using external monitor (it doesn't matter)

**Comment by lwouis** [comment] 2023-07-18 08:25
Hi @danulqua,

This is surprising. I'm on 13.4 myself. I haven't updated to 13.4.1 yet.

Could you please try and change the shortcut to alt+tab or some other combination? This way we can check if the issue is specific to command+tab, or if it affects every shortcut.

Thank you 🙇

**Comment by danulqua** [comment] 2023-07-18 08:28
@lwouis tried with ⌥Tab - it works. It's specific to ⌘Tab.
I was always using it with ⌘Tab and my ⌥Tab is for other action in different app.

**Comment by lwouis** [comment] 2023-07-18 16:46
It's possible that Apple has broken the private API that AltTab uses to disable the system command+tab. In that case, we would need to forbid users from using the `command+tab` shortcut, as the system one would always show up first and absorb the shortcut.

I'll try out when I upgrade to 13.4.1.

It's also possible that something else is at play on your machine, like external keyboard, software key rebinders, etc. This possibility is not to be excluded because you're the only one to report this issue so far.

**Comment by danulqua** [comment] 2023-07-18 17:16
@lwouis I don't use either external keyboard or software key rebinders etc.

**Comment by sapoepsilon** [comment] 2023-07-18 20:05
Hey, I just checked alttab works on my end on 13.4.1(c)
<img width="475" alt="image" src="https://github.com/lwouis/alt-tab-macos/assets/47342870/6317db85-8b2c-4aec-913d-9d5d7dc16e80">

@danulqua check if cmd+tab will work if you disable thumbnails.

**Comment by danulqua** [comment] 2023-07-18 20:08
@sapoepsilon really, disabling and enabling thumbnails fixed the issue. So strange.

**Comment by sapoepsilon** [comment] 2023-07-18 20:17
As far as I remember 13.4.1(c) was an urgent security update. I wonder if Apple's fix can be bypassed as easily as this workaround.

**Comment by lwouis** [comment] 2023-07-18 20:33
Good news. I'll close this ticket 👍

**Closed by lwouis** 2023-07-18 20:33 UTC
Labels: bug, unreproducible

**Comment by danulqua** [comment] 2023-07-26 18:16
@lwouis the problem is back (seems like after a new macOS 13.5 update), and the tip provided by @sapoepsilon no longer works.
AltTab 6.61.0
macOS Ventura 13.5

**Comment by sapoepsilon** [comment] 2023-07-26 18:28
> @lwouis the problem is back (seems like after a new macOS 13.5 update), and the tip provided by @sapoepsilon no longer works. AltTab 6.61.0 macOS Ventura 13.5

I wonder if updates on your end rewriting permissions on your Mac. Try removing accessibility permissions for alttab 
<img width="470" alt="image" src="https://github.com/lwouis/alt-tab-macos/assets/47342870/b9a99290-dbff-4307-b60f-bf18788bd244">
Click on alttab, then click "-" icon at the bottom. 
Then delete the alttab, and reinstall it.

**Comment by sapoepsilon** [comment] 2023-07-26 18:38
@danulqua  just installed 13.5 on my end. The app works without an issue. I am pretty sure you have some kind of a setup, which is triggered on boot and it is preventing recognition of cmd + tab

**Comment by danulqua** [comment] 2023-07-26 18:41
@sapoepsilon I use Hyperkey to bind all modifiers to the right command. Seems like if it was started before AltTab, then it'll be a problem. I exited both apps, then started AltTab first and Hyperkey then, now everything is fine.

**Comment by wesgm** [comment] 2024-03-26 13:59
Also doesn't work for me. I have no other software that could be conflicting to my knowledge, on M1 MBP on 14.4.

**Comment by martikyan** [comment] 2024-12-21 21:40
Still reproducible on MBP 15.2 (24C101) and AltTab 7.12
