### ISSUE TITLE
Text is not displayed completely

### ISSUE THREAD

**Issue by LarkinZero** [lwouis/alt-tab-macos#814] opened 2021-02-10 15:56 UTC
**Describe the bug**

The top part of Chinese text is not displayed.

**Screenshots / video**
<img width="288" alt="Xnip2021-02-10_23-52-19" src="https://user-images.githubusercontent.com/6387162/107535003-514e9580-6bfb-11eb-888a-b39ad99d4931.png">

My settings
<img width="606" alt="Xnip2021-02-10_23-52-51" src="https://user-images.githubusercontent.com/6387162/107535028-57447680-6bfb-11eb-8f22-9c5593f6fc7d.png">

**Steps to reproduce the bug**

I tried to modify the font size, but no effect.

**Comment by lwouis** [comment] 2021-02-10 17:47
Hi @LarkinZero! Thanks for sharing this issue!

I'm not very familiar with Chinese hanzi. What is wrong exactly on your first screenshot? Is it that there are a few pixels shaved off to the top of the text? Is it on all rows like Chrome, Finder, etc, or is it just the very first row?

I need more details to really understand the scope of the issue

Thank you!

**Comment by LarkinZero** [comment] 2021-02-10 17:56
Yes,there are a few pixels shaved off to the top of the text.
It looks every row has this problem.
![](https://user-images.githubusercontent.com/6387162/107550488-0ee18480-6c0c-11eb-9ec9-108496aebbd2.png)

**Comment by LarkinZero** [comment] 2021-02-10 18:01
Not only Chinese characters, but also some symbols
Like `[]`
<img width="1564" alt="Xnip2021-02-11_01-59-22" src="https://user-images.githubusercontent.com/6387162/107551273-0473ba80-6c0d-11eb-846a-c5cd473918c6.png">

**Comment by LarkinZero** [comment] 2021-02-10 18:13
And it happening as well with the thumbnails visible
<img width="459" alt="Xnip2021-02-11_02-10-55" src="https://user-images.githubusercontent.com/6387162/107552476-89ab9f00-6c0e-11eb-9514-fe9bd38bb473.png">

**Comment by lwouis** [comment] 2021-02-16 01:30
@LarkinZero I can't seem to reproduce the issue. Could you please share the links to some of the websites on your screenshots? Or just write here the hanzi and I'll search them on Google. Thank you

**Comment by LarkinZero** [comment] 2021-02-16 02:39
https://www.google.com/search?q=%5B%5D&oq=%5B%5D&aqs=chrome..69i57.1055j0j7&sourceid=chrome&ie=UTF-8
Text is : []
<img width="2528" alt="Xnip2021-02-16_10-36-59" src="https://user-images.githubusercontent.com/6387162/108011878-fece0880-7042-11eb-920b-bd827f32c11b.png">

https://www.google.com/search?q=%E5%96%9C%E6%AC%A2&oq=%E5%96%9C%E6%AC%A2&aqs=chrome..69i57j69i61.386j0j9&sourceid=chrome&ie=UTF-8
Text is : 喜欢
<img width="1496" alt="Xnip2021-02-16_10-38-15" src="https://user-images.githubusercontent.com/6387162/108011969-27ee9900-7043-11eb-8493-76fbf23bc0cf.png">

**Comment by lwouis** [comment] 2021-02-17 01:50
I can't reproduce the issue on my macbook pro:

![image](https://user-images.githubusercontent.com/106195/108142982-2936c900-710a-11eb-9f80-c259c92cbf0c.png)

It seems like a layout bug where the text is 1 or 2 pixels off. When I compare yours and mine side by side, it seems like your font is rendered differently:

![image](https://user-images.githubusercontent.com/106195/108143462-2ab4c100-710b-11eb-9c0f-b963e4f74dd6.png)

There is more space between the `o`s of `Google` and the `[]` is wider than mine.

It could be a font issue? AltTab uses `NSFont.systemFont` for the titles, so it should be using macOS standard font.

I tried to adjust the preferences to match yours (font size 14px for instance, but also everything else on your screenshot above), and your font rendering still looks wider for instance:

![image](https://user-images.githubusercontent.com/106195/108144120-5ab09400-710c-11eb-871e-f2e7c42feaf2.png)

What's the default font on your system?

**Comment by LarkinZero** [comment] 2021-02-17 14:45
@lwouis I have no change with fonts.
And I don’t know what font the system defaults use.
But in Activity Monitor, I found some font which AltTab is in use.
Maybe this information can help you reproduce this problem.
```
/System/Library/Fonts/SFNS.ttf
/System/Library/Fonts/Helvetica.ttc
/System/Library/Fonts/LastResort.otf
/System/Library/Fonts/PingFang.ttc
/System/Library/Fonts/LucidaGrande.ttc
/System/Library/Fonts/ZapfDingbats.ttf
```

**Comment by LarkinZero** [comment] 2021-02-17 14:58
@lwouis After I change my system language to perferrd English. When the window title has no Chinese characters, the font list used is like this:
```
/System/Library/Fonts/SFNS.ttf
/System/Library/Fonts/Helvetica.ttc
/System/Library/Fonts/LastResort.otf
/System/Library/Fonts/LucidaGrande.ttc
/System/Library/Fonts/ZapfDingbats.ttf
```

`/System/Library/Fonts/PingFang.ttc`This font is not used, it seems to be the reason for this font.
When the system prefers to use Chinese, all window titles use this font. 
But when English is preferred, only Chinese characters are used, and this font will be used
<img width="1232" alt="Xnip2021-02-17_22-57-15" src="https://user-images.githubusercontent.com/6387162/108222230-8c107a80-7173-11eb-8237-8ef782f9aa93.png">

**Comment by lwouis** [comment] 2021-02-17 16:45
Thanks a lot for the help! I was able to reproduce the issue when forcing the font to PingFang programmatically.

I think this [thread discusses the exact same issue](https://stackoverflow.com/questions/36179012/nstextfield-non-system-font-content-clipped-when-usessinglelinemode-is-true). Sadly, none of the people discussing it found a solution. I'll try to think of one.

**Comment by lwouis** [comment] 2021-02-23 14:38
I've been trying to work around the layout issues that arise with the `PingFang SC` font. However, I can't get anything robust working. There are so many complications, and me changing 1px here 1px there is not robust enough, and I'm pretty sure it's going to look bad on various monitors, computers, font sizes, etc.

I'm thinking about going the other way around, and instead of picking the system font which can change depending on the system language, I could pick the same font for everyone. Now the issue is that Apple doesn't want developers to specify "San Francisco". They want them to ask for the "System font". So getting SFNS would be using the private name. The issue is that I'm not sure how that would work on earlier releases of macOS, and also on other systems like a Chinese install. Pre-installed fonts vary through time and geographies I think. Documentation is poor on this, so I would need to test on all these environments.

Either that, or we find a way to fix the layout bug on PingFang when the `NSTextView` is set to a single line. That would be ideal but I don't know how to.

**Comment by LarkinZero** [comment] 2021-02-24 06:28
@lwouis If users are allowed to customize fonts here, can this problem be resolved to a certain extent?

**Comment by lwouis** [comment] 2021-02-24 06:58
I thought about that. It's interesting to imagine users would customize with fun fonts. That being said, it would have these downsides:

* Default experience still has the issue, for Chinese users! Only a few percentage of users actually open the preferences I would bet, so most people still have the broken experience.
* More preferences = more complexity for end-users = more complexity to maintain the project
* I would bet that the layout would be broken with many fonts, due to the complexity of having a layout that works in all scenarios, in all languages, at all sizes, etc

**Comment by YashiroKirara** [comment] 2023-12-18 09:40
我也有同样的问题

**Comment by lwouis** [comment] 2024-12-25 22:01
This issue should be fixed in the latest release. If not, please share it here 👍 
Thank you

**Closed by lwouis** 2024-12-25 22:01 UTC
Labels: bug
