### ISSUE TITLE
Emacs windows not appearing in AltTab list

### ISSUE THREAD

**Issue by mjog** [lwouis/alt-tab-macos#810] opened 2021-02-07 23:18 UTC
**Describe the bug**

Emacs windows not appearing in AltTab list

**Steps to reproduce the bug**

1. Open an Emacs window
2. Press shortcut to invoke AltTab window
3. Notice Emacs window is not present

**Comment by lwouis** [comment] 2021-02-08 14:01
Hi @mjog!

Could you please clarify which Emacs app you're running? It seems that mac ports are various, and exhibits issues. I see here for instance that there are [flags specifically to get a version that has correct windows](https://github.com/koekeishiya/yabai/issues/86).

**Comment by mjog** [comment] 2021-02-09 03:40
I can't currently reproduce this either, may be intermittent? I restarted AltTab yesterday.

**Comment by lwouis** [comment] 2021-02-09 03:54
Could you still please share with emacs app/port/version you are using?

**Comment by mjog** [comment] 2021-02-09 06:53
Sure thing, this one: https://vigou3.gitlab.io/emacs-modified-macos/

**Comment by dsedivec** [comment] 2021-03-16 00:37
I think I can reproduce this:

1. Grab [Emacs 27.1](https://emacsformacosx.com/emacs-builds/Emacs-27.1-1-universal.dmg) from https://emacsformacosx.com
2. Run Emacs (I ran it from a shell a la `/Volumes/Emacs/Emacs.app/Contents/MacOS/Emacs -Q` because my Emacs config doesn't like multiple instances running; `-Q` tells Emacs not to load my config)
3. Type <kbd>⌥X</kbd> set-var <kbd>return</kbd> ns-use-native-fullscreen <kbd>return</kbd> nil <kbd>return</kbd>
4. Type <kbd>⌥X</kbd> toggle-frame-fullscreen <kbd>return </kbd>, which should make the window full screen but not in the standard macOS full screen way
5. Invoke AltTab

Expected result: You can see the Emacs window in the list of windows you can switch to

Observed result: You do not see the Emacs window, but instead only an icon which I think means something like "launch Emacs"

<img width="237" alt="Screen Shot 2021-03-15 at 19 26 18" src="https://user-images.githubusercontent.com/95333/111238078-57ea7700-85c4-11eb-86f0-7f9f7e64994b.png">

(I think it tried to start a brand new Emacs when I made the mistake of selecting it once.)

I am testing this on macOS 10.15.7, AltTab 6.17.0.

I am *guessing* that some of the most important code for "non-native full screen" is [here](https://github.com/emacs-mirror/emacs/blob/c4549d3b37f7f3b9a9b5376eebb39b1929c48bd1/src/nsterm.m#L8042), looks like setting [some kind of "full screen auxiliary window collection behavior"](https://developer.apple.com/documentation/appkit/nswindow/collectionbehavior/1419617-fullscreenauxiliary).  (Emacs users like me love this "non-native full screen" because you don't end up in a different Space™, you can have ordinary windows like terminals on top of Emacs's big window for code editing, etc.)

Thank you for AltTab. :)

**Comment by dsedivec** [comment] 2021-03-16 00:51
Maybe you're interested to see what Accessibility Inspector has to say about the non-native full screen Emacs window?  (Pardon the green veil added by Accessibility Inspector, I've just got the one screen.)

<img width="419" alt="image" src="https://user-images.githubusercontent.com/95333/111239338-f546aa80-85c6-11eb-9921-f41ff57f3256.png">
<img width="424" alt="image" src="https://user-images.githubusercontent.com/95333/111239388-10b1b580-85c7-11eb-8e59-83cb0fd0d63d.png">
<img width="422" alt="image" src="https://user-images.githubusercontent.com/95333/111239402-18715a00-85c7-11eb-8fa7-028786a941fa.png">

As you pointed out in [the yabai issue you linked to above](https://github.com/koekeishiya/yabai/issues/86), the Emacs's windows seem to have role AXTextField  This is true even when the Emacs window is not full screen.  However, in non-native full screen, the normal Emacs window's subrole is AXUnknown.  When that window is full screen, its subrole becomes AXStandardWindow, as you see above.

**Comment by lwouis** [comment] 2021-03-16 01:08
@dsedivec thank you for the nice detailed information!

I think it's the classic case of the window not being a real window (`AXUnknown`), and AltTab not showing it. AltTab avoids showing non standard windows because if it did, you would have all sorts of mini UI elements, large invisible windows, etc, polluting your view. The best heuristic I found over the years to detect what a window is, to the end-user, is to use the accessibility attributes `subrole` and `role`. There is an open ticket flagged with `Breakthrough needed`, where hopefully one day someone will suggest a better way: #456 

In the meanwhile, I have been hardcoding app-specific exceptions, after users reported issues with these apps.

**Comment by dsedivec** [comment] 2021-03-16 01:20
> The best of course, would be for the people behind emacs to use a window to do this non-native fullscreen window feature. Then it would simply work with AltTab. Have you opened a ticket with them?

Do you mean to just have them set the role to AXWindow?  [The patch to do that seems very simple](https://github.com/d12frosted/homebrew-emacs-plus/blob/master/patches/emacs-28/fix-window-role.patch).  I'm trying to compile Emacs with it now.  If it works out, I'll propose it upstream and see what they say.

If it works, I'm mostly mystified why they aren't already using it.  My first guess would be that it somehow impairs accessibility, and to do something like properly enclose the text area in a normal window would be too invasive of a change.  But I can ask.

**Comment by dsedivec** [comment] 2021-03-16 02:01
> Do you mean to just have them set the role to AXWindow? [The patch to do that seems very simple](https://github.com/d12frosted/homebrew-emacs-plus/blob/master/patches/emacs-28/fix-window-role.patch). I'm trying to compile Emacs with it now. If it works out, I'll propose it upstream and see what they say.

I just rebuilt Emacs HEAD with the patch for AXWindow and AltTab still doesn't list it, despite the role now showing AXWindow in Accessibility Inspector.  Is there something else that could be causing AltTab to ignore Emacs?

<img width="425" alt="image" src="https://user-images.githubusercontent.com/95333/111244708-6db26900-85d1-11eb-9774-2c30f0269da1.png">
<img width="420" alt="image" src="https://user-images.githubusercontent.com/95333/111244726-77d46780-85d1-11eb-983a-ad10119d2944.png">
<img width="423" alt="image" src="https://user-images.githubusercontent.com/95333/111244737-7d31b200-85d1-11eb-804c-ed35386b5fd6.png">

**Comment by lwouis** [comment] 2021-03-16 02:22
I see on your screenshot `Subrole: AXUnknown`. AltTab only shows windows with `subrole` being either `kAXStandardWindowSubrole` or `kAXDialogSubrole`.

You can see the [full logic to filter out windows from non-windows here](https://github.com/lwouis/alt-tab-macos/blob/5c7aa38312229f6fca5374d752667db0b1c88b06/src/api-wrappers/AXUIElement.swift#L83). It's pretty simple.

**Comment by dsedivec** [comment] 2021-03-29 21:01
> I see on your screenshot `Subrole: AXUnknown`. AltTab only shows windows with `subrole` being either `kAXStandardWindowSubrole` or `kAXDialogSubrole`. [...] Given the simplicity of the patch you shared, you may be able to do the same change to `subrole`. Something like:

And indeed that seems to work, with [this patch](https://gist.github.com/dsedivec/32a80446260eb9fd399ae36d96681e73) I can see "full screen" Emacs windows in AltTab.  I should probably suggest this upstream, or find out why Emacs doesn't already do this.

Thanks for your help!

**Comment by lwouis** [comment] 2021-03-30 04:31
Cool! I'll close this ticket then. Feel free to report here if it gets fixed upstream 👍

**Closed by lwouis** 2021-03-30 04:31 UTC
Labels: bug, unclear
