### ISSUE TITLE
Wrong window listing

### ISSUE THREAD

**Issue by kodmanyagha** [lwouis/alt-tab-macos#943] opened 2021-05-07 14:32 UTC
I'm using PHPStorm and it sometimes shows popup windows when developing. And alt-tab application is keeping this window in window list. Example screenshot is here:

This popup window is listing in window list:
![image](https://user-images.githubusercontent.com/3948692/117465192-1ccc4a80-af5a-11eb-81ae-0632f6c5a916.png)

![image](https://user-images.githubusercontent.com/3948692/117465235-281f7600-af5a-11eb-8719-0bcf03db6967.png)

**Comment by lwouis** [comment] 2021-05-08 04:55
Duplicate of #885

**Closed by lwouis** 2021-05-08 04:55 UTC
Labels: bug
