### ISSUE TITLE
Not able to access options at the bottom of the appearance tab

### ISSUE THREAD

**Issue by mlubej** [lwouis/alt-tab-macos#969] opened 2021-05-24 15:41 UTC
**Describe the bug**

I can't seem to access the very bottom of the appearance tab in preferences

**Screenshots / video**

![image](https://user-images.githubusercontent.com/37869250/119371738-ef500280-bcb6-11eb-9a87-c81b7b11e7a0.png)

**Steps to reproduce the bug**

This happens to me on macOS Big Sur 11.3.1 (20E241)

**Comment by lwouis** [comment] 2021-05-25 02:28
Duplicate of https://github.com/lwouis/alt-tab-macos/issues/936

**Closed by lwouis** 2021-05-25 02:28 UTC
Labels: bug
