### ISSUE TITLE
Terminal window: strange behavior

### ISSUE THREAD

**Issue by jsh9** [lwouis/alt-tab-macos#692] opened 2020-11-13 07:40 UTC
**Describe the bug**

When pressing Alt + Tab, the terminal window exhibits strange behaviors:

- Sometimes it does not show up in the lists of icons
- Sometimes it shows multiple terminal icons, if I have a single terminal window with multiple tabs

**Screenshots / video**

N/A

**Steps to reproduce the bug**

It's hard to tell when the issues above occur: sometimes AltTab behaves perfectly normal, but sometimes there are issues.

**Comment by lwouis** [comment] 2020-11-13 10:28
Thank you for reporting this issue @jsh9!

I'm affraid i can't do much with so little information. I really need steps to reproduce, video footage, or some hints like "i notice it happens after i plug my external display".

This issue doesn't happen on mine or other's machines so I need your help to investigate it and fix it 🙇

**Comment by SoPat712** [comment] 2020-11-18 03:10
@jsh9, the multiple terminal issues might be caused because you have this setting checked.

![image](https://user-images.githubusercontent.com/30350506/99477979-9a0af100-2921-11eb-9e34-aa298ddb5886.png)

Uncheck it, and see if that fixes the problem with the multiple terminal icons showing up.

**Comment by jsh9** [comment] 2020-12-09 09:24
Hi @SoPat712 , this option is unchecked on my computer, but the issue still persisted.

@lwouis is it possible for you to implement some logging functionality that logs keystrokes etc, so that you can better reproduce and/or diagnose issues?

**Comment by SoPat712** [comment] 2020-12-09 12:51
I believe @lwouis wishes not to implement those for performance reasons, and frankly, I agree with that.

**Comment by lwouis** [comment] 2020-12-09 14:14
Actually logging has OS infrastructure support, so I'm confident it would be low impact. The issue is more about taking time to add a logging framework, log lines at strategic place all over the codebase, etc. Also logging changed quite a lot over macOS versions, so supporting existing covered releases raises questions on how to do it.

On top of that, in that specific scenario, I'm not sure if would help us much if we had these logs. Let's say you see the keys pressed in the log, then what? Or let's say you don't see them, then what? It's really tricky to investigate these issues I've learned over the course of this project. It's all about being to reproduce with steps. Once a problem is reproduced, I'll come up with a fix quickly. 90% of the work is finding causes or correlations.

**Comment by jsh9** [comment] 2020-12-09 20:32
So what shall developers do if the problem can't be reproduced, or at least the problem is sporadic?  I cannot even reproduce the issue, because I can't predict when it would happen.

IMHO, if the app developers do not attempt to address such problems, the app quality will eventually decay to a hard-to-maintain state.

**Comment by lwouis** [comment] 2020-12-10 00:25
> So what shall developers do if the problem can't be reproduced, or at least the problem is sporadic? I cannot even reproduce the issue, because I can't predict when it would happen.

I don't know. Do you know? I'm really hoping for someone to help here because i don't have superpowers and here i'm literally stuck. The issue does not happen on my machine. Reading the code statically doesn't reveal a clear problem. Then what? What can i do?

> IMHO, if the app developers do not attempt to address such problems, the app quality will eventually decay to a hard-to-maintain state.

Of course it's a bad thing. I'm attempting hard to address all issues on this app though. It's not about motivation it's about hard problems being hard to deal with. If you come to a garage saying "my car makes a noise every month randomly. Not sure why not sure how. I couldn't record the sound cause i never expect it it's random, so sorry you can't hear it. Oh you inspected inside and found nothing wrong? Well if you don't attempt to fix it it's going to decay"

What's the garage technician going to do there? Probably in real life that's the end of that conversation, as he can't do much more. Notice that i'm still here everyday trying to continue conversations and discuss solutions. Notice that i'm doing on my personal free time when the garage technician is doing it to make a living.

**Comment by jsh9** [comment] 2020-12-10 02:56
You are right - in that particular case, there is nothing that the technician can do, exactly because there is insufficient logging.

But in many other occasions, if your car's dashboard light is on, a car mechanic would be able to read the error code using a handheld device, and tell you what went wrong.  And this is the benefit of implementing logging.

If performance is not an issue and you implement very detailed logging, would you be able to diagnose these sporadic issues?  If your answer is "yes", then maybe you can do this:

- Implement logging
- And then add a toggle of "debug mode": if it is on, then things are logged but the app runs slower, and if it is off, there is no logs but the performance isn't impacted

I don't know enough of your code base to assess the feasibility of my suggestion.  I'm just brainstorming : )

**Comment by lwouis** [comment] 2020-12-10 03:14
In your analogy, the error code from the car "blackbox" would either give an already understood error like "oil levels insufficient" or an unexpected error like "brake system failure". It would then merely locate the issue in an area where it expressed itself. Note that this can be a symptom and the cause could be far away in some cases.

Going back to AltTab: what would we log that could realistically help here?

Just to be clear, i would love to have nice logs in the app. That would be great. Now (a) that's a big task to implement it in a cross platform, robust way, and (b) logs won't solve things. They may help, maybe. I've added custom logs in local builds that i shared with other users on some previous tickets. I felt from these experiences that  issues resolution depends mostly, if not entirely, on the quality of user tickets (e.g. someone not mentioning that they use an external windows keyboard), as well as somebody eventually reporting a reproducible scenario that allows me to debug locally and finally understand what's at play.

Also keep in mind that there are 450 closed issues on this repo. The app is quite mature in that sense, and the remaining bugs are, as i tried to illustrate with my analogy with the car, very difficult to work on, as they happen only to a small subset of users, in a sporadic fashion.

I would love contributions from anyone by the way. It could be code, it could be researching logging frameworks and their tradeoffs, it could be experimenting on your machine to try exotic stuff to trigger the issue, etc

**Comment by lwouis** [comment] 2021-01-25 15:26
So there is the lack of logging infra that we discussed in this ticket, but the OP is about inconsistent windows being shown in AltTab. I'll close this ticket as a duplicate of #639. Let's focus the efforts in this ticket 👍

**Closed by lwouis** 2021-01-25 15:26 UTC
Labels: bug
