### ISSUE TITLE
Show windows in current active screen only?

### ISSUE THREAD

**Issue by xingheng** [lwouis/alt-tab-macos#953] opened 2021-05-14 07:25 UTC
I have this configuration for `Cmd` + `Tab` to switch all the windows from the current screen but it's not working, it always shows all the windows from all the screens.

I've no idea it's a bug or not supported, please help me clarify it, thanks!

![Screen Shot 2021-05-14 at 3 09 36 PM](https://user-images.githubusercontent.com/2891714/118234978-ac2bad80-b4c6-11eb-824b-70bd22ccfc57.png)

**Comment by lwouis** [comment] 2021-05-14 07:59
Could you please share more details? I need to understand your physical setup. How many screens do you use, when you trigger AltTab, what's the state of those screens (which screen has keyboard focus, which screen shows AltTab).

The best would be that you share a video you record from your phone for instance. Then we can really see what's going on.

**Comment by xingheng** [comment] 2021-05-14 11:03
I have two screens, one is mbp builtin (Screen1), another one is external (Screen2) which is the main screen (has the menu bar only, the right one in the bottom screenshot).

<img width="780" alt="Screen Shot 2021-05-14 at 6 49 44 PM" src="https://user-images.githubusercontent.com/2891714/118260872-6a5e2f80-b4e5-11eb-8f83-db470a1435f2.png">

<img width="780" alt="Screen Shot 2021-05-14 at 6 49 55 PM" src="https://user-images.githubusercontent.com/2891714/118260883-6df1b680-b4e5-11eb-864d-8dd7eb721644.png">

Applications:
* Screen1:
   * Chat
   * iTerm
   * Finder
* Screen2:
   * Xcode
   * Source Tree
   * Google Chrome

Case 1: When I move the cursor to screen2/Chrome (the menu bar changed to Chrome), press  `Cmd` + `Tab`, the `AltTab` window shows in screen2 with all the above applications, but I thought that ***Show windows from `Screen showing AltTab`*** should work as showing applications only in screen2, right?

Case 2: When I move the cursor to screen1/iTerm, press `Cmd` + `Tab`, the `AltTab` window shows in screen2 with all the above application list, too. How to make it show in the active screen1?

**Comment by xingheng** [comment] 2021-05-20 06:23
@lwouis ping... any other environments & configurations needed?

**Comment by lwouis** [comment] 2021-05-31 02:27
For **case 2**, there is a preference in AltTab to pick where the UI shows. What option have you selected there? It's not shared above.

![image](https://user-images.githubusercontent.com/106195/120131139-b528b880-c202-11eb-809b-edddc5407c98.png)

For **case 1**, it could be a bug. I notice you have `Displays have separate Spaces` off, which is very uncommon. I'll have to try to reproduce your setup and see if I can reproduce the issue. Again, I need to know the option you picked for `Appearance > Show on` to do that

**Comment by xingheng** [comment] 2021-06-02 02:41
I use the `Active screen` for `Show on` option always and I thought it means *the application window which current active application in*, right? This may cause by `Displays have separate Spaces` off.

BTW, I tried the `Show on` with `Screen including mouse` option just now, it shows in the right screen now, but it still shows all the applications from all the screens.

**Comment by lwouis** [comment] 2022-04-29 15:13
Closing as there hasn't been activity in a year. Could be a duplicate of #1324 as well

**Closed by lwouis** 2022-04-29 15:13 UTC
Labels: unreproducible, unclear
