### ISSUE TITLE
Add a option to visually group alt-tab thumbnails by Screen and/or Space

### ISSUE THREAD

**Issue by ppatel-gh** [lwouis/alt-tab-macos#1360] opened 2022-02-03 22:16 UTC
Hello, I saw a response from @Iwouis in issue no [1274](https://github.com/lwouis/alt-tab-macos/issues/1274#issue-1071282915) about adding workflows for showing windows based on apps, spaces and screens. I wanted to add a request on top of that, would it be possible to visually separate the alt-tab preview on the basis of screens and/or spaces.

For example, let's say I have two physical screens. Currently the options for showing windows are 'All Screens' and 'Screen showing AltTab'. I have selected the 'All Screens' options to make it easy to switch to a window on my second screen, but the problem with this option is that the Alt-Tab preview shows all the thumbnails from each screen together without any kind of order, so it becomes hard for me to tell which window is in which screen. The same issue applies for Spaces.

What I suggest is there be a option to visually group the thumbnail previews based on the screen and space. So that when I bring up the Alt-Tab preview, I can tell at a glance which windows are in which screen/space.

e.g like the following but as a grid of preview tiles -
<pre>
Screen 1 - 
    Space 1 -
        Browser, Calendar
    Space 2 - 
        Email
Screen 2 - 
    Music, PDF
</pre>

**Comment by lwouis** [comment] 2022-02-04 16:37
Duplicate of https://github.com/lwouis/alt-tab-macos/issues/337

**Closed by lwouis** 2022-02-04 16:37 UTC
