### ISSUE TITLE
Alt + Tab delay after show second window

### ISSUE THREAD

**Issue by kythuatwebso** [lwouis/alt-tab-macos#1116] opened 2021-09-04 02:33 UTC
Hello,

My issues when i'm press "alt + tab" switch between two windows it is delay (slow) fade before show windows second!

Thanks

**Comment by lwouis** [comment] 2021-09-04 03:14
I think this is a duplicate of https://github.com/lwouis/alt-tab-macos/issues/1096

**Closed by lwouis** 2021-09-04 03:14 UTC
Labels: bug
