### ISSUE TITLE
Alt-Tab constantly asks for access to screen-recording despite having permission

### ISSUE THREAD

**Issue by owenfiscus** [lwouis/alt-tab-macos#642] opened 2020-10-08 18:47 UTC
**Describe the bug**

Alt-Tab will randomly request access to screen recording despite already being granted the permission. Happens at random, Alt-Tab functions properly most of the time but not always.

Running Big Sur Developer Beta (20A5384c)

**Screenshots / video**

![Screen Shot 2020-10-08 at 11 43 43 AM](https://user-images.githubusercontent.com/8652398/95500486-b5b2cd00-095b-11eb-8e26-57ef0cf8aa46.png)

**Comment by lwouis** [comment] 2020-10-09 02:43
Hi @owenfiscus! Thanks for sharing this issue!

It's hard to know with so little information what's happening. The only factor I see at play here is that you are on a beta of macOS which may contain a bug regarding Screen Recording permission.

Could you please share a screenshot of the window when you click on the `Open Screen Recording Preferences...` button? Like is AltTab listed on that window?

Also, do you have multiple versions of AltTab that you installed, or just the current one? That includes the auto-updater which prompts you for updates once in a while by default: have you every updated? Normally it shouldn't impact anything since all versions are signed and notarized with Apple so they reuse the same permission grant since the app has the same `bundleIdentifier` between versions.

If it seems like everything is good, yet AltTab thinks the permission is not granted, then could you please open a ticket with Apple? Finding bugs or regressions such as this is literally the purpose of their beta program.

Finally, to potentially help you move on, you can try running this command in Terminal.app: `tccutil reset All com.lwouis.alt-tab-macos` to remove all permissions. You may then be able to give them back for good after that and un-glitch macOS.

**Comment by owenfiscus** [comment] 2020-10-09 03:46
![Screen Shot 2020-10-08 at 7 56 43 PM](https://user-images.githubusercontent.com/8652398/95539886-6644bf00-09a4-11eb-8411-358bc29eb636.png)

**Comment by owenfiscus** [comment] 2020-10-09 03:54
Yeah I agree it is likely a problem with the beta. I do have the auto-update tool installed and I am on the most recent update. My intention isn't to have you think I expect support for beta versions of an OS. I hope it didn't come off that way, you make this app for free and I appreciate that. I ran the `tccutil` command you suggested, so far so good, thanks for that suggestion. Thanks again for the thorough response. Have a great day!

**Comment by lwouis** [comment] 2020-10-09 04:10
No worries! I appreciate you sharing the issue. It could be a bug in AltTab. Nobody else reported such an issue, so I suspect the beta may be involved, but it may be something else.

The Screen Recording permission is terrible because Apple doesn't expose APIs to know if the app was granted permission or not. [Look at the code (at least the comment at the top) that AltTab uses](https://github.com/lwouis/alt-tab-macos/blob/7f64e18b1cefe23d2128bdf63eb41dd230c0d909/src/logic/SystemPermissions.swift#L23)... I wouldn't be surprised if macOS Big Sur breaks this workaround. At the same time there is no better way to do it, as far as I know, and I've spent hours online looking for a better way, and hours testing different workarounds with different trade-offs.

**Comment by owenfiscus** [comment] 2020-10-09 04:21
Thanks for the link, I took a look. I'm a just beginner coder so I won't pretend like I understand much of what's going on but just from hanging around in nerdy Apple circles on the internet I am aware of the unfortunate reality that is Apple APIs. Let's hope my issue is unique to me and the workaround remains in the Big Sur release! Again, not expecting anything from this bug report, just wanted to make you aware. I'll update here if the issue happens again. Thanks for your work on this project!

**Comment by lwouis** [comment] 2020-10-09 05:18
Thank you! I'll close this ticket. If you or other people face this issue again, please write here and i'll re-open the ticket 👍

**Closed by lwouis** 2020-10-09 05:18 UTC
Labels: bug

**Comment by owenfiscus** [comment] 2020-10-09 14:39
Unfortunately this issue is persistent. I've filed a Feedback with Apple. Maybe in a perfect world they'll create an API for this. Sorry about that.

**Comment by lwouis** [comment] 2020-10-09 15:40
Note that currently AltTab is only supported up to Catalina. When Big Sur releases, I'll start playing with it, and seeing what broke and trying to support the new OS. At that point, if I may be able to find a new workaround for that particular issue. I will only start that work when Big Sur is out of beta though. I'm quite overwhelmed by the number of open issues currently, unfortunately
