### ISSUE TITLE
After a quick Space change, AltTab shows windows from previous Space

### ISSUE THREAD

**Issue by arekk** [lwouis/alt-tab-macos#3792] opened 2024-10-31 10:18 UTC
**Describe the bug**

I'm using multiple spaces for separate workflows. Im switching between spaces using keyboard shortcut.

In Alt-Tab I'm using mode: "show widows from: space showing alt-tab" to see in Alt-Tab windows only from current  space. 

Every time when I switch to next/previous space and quickly run Alt-Tab I see in preview overlay windows from other spaces mixed with those from current space. When I perform it slowly, eg. I'll wait 1s after switch to new space it looks fine. 

**Screenshots / video**

What should I see (all windows opened on current space)

![IMG_20241031_110418_A](https://github.com/user-attachments/assets/b90bb6ea-79d7-4913-8d2c-6d6c90416df0)

What I see when I'll run Alt-Tab just after switching spaces:

![IMG_20241031_110448_B](https://github.com/user-attachments/assets/59a945db-097b-4d02-99e9-4b8ca650f1f9)

**Steps to reproduce the bug**

1. Set Alt-Tab settings: show widows from: space showing alt-tab
2. Define a Mac keyboard shortcut to switch between spaces
3. Spawn two separate spaces and run some applications on every space
4. Switch from space 1 to two and immediately press Alt-Tab - it must be done very quickly, just after space switch
5. See mixed windows in preview

**Your environment**

* AltTab version: 7.0.2
* macOS version: Sequoia 15.0.1 (24A348)
* Nothing additional, no additional monitors

**Comment by lwouis** [comment] 2024-10-31 10:42
Hi,

Could you please share a screenshot of your Controls and Appearance settings?
Could you please also share a video so we can see the issue in motion, in your workflow?

Thank you 🙇

**Comment by arekk** [comment] 2024-10-31 11:14
> Could you please share a screenshot of your Controls and Appearance settings? Could you please also share a video so we can see the issue in motion, in your workflow?

Sure, video here: https://streamable.com/dtfvyj
Screenshots only in polish - sorry - I have no idea how to change language settings to EN.

<img width="595" alt="bez nazwy" src="https://github.com/user-attachments/assets/13bfdeaa-b5dc-4337-af41-e274b74f3fd8">

**Comment by lwouis** [comment] 2024-11-06 22:00
I think this issue is a duplicate of https://github.com/lwouis/alt-tab-macos/issues/1254

**Closed by lwouis** 2024-11-06 22:00 UTC
Labels: bug, unreproducible, unclear
