### ISSUE TITLE
Show AltTab in all screens

### ISSUE THREAD

**Issue by sshresthaEG** [lwouis/alt-tab-macos#1613] opened 2022-05-23 14:16 UTC
**Is your feature suggestion related to a problem? Please describe.**
I have 2 displays and sometimes I am looking at a screen which may not be the active one. So, hitting alt-tab shortcut key only brings the alt-tab to the active screen and I have to turn around head to see where is it. 

**Describe the solution you'd like**
An option to `Show in all screens` that will replicate alt-tab in all screens would be awesome.

**Describe alternatives you've considered**
No alternative solution than just turning around to see where is it.

![image](https://user-images.githubusercontent.com/62610476/169838884-21ba74a6-0e7b-40e1-b13f-581d98ac978a.png)

**Comment by lwouis** [comment] 2022-05-23 15:52
Duplicate of https://github.com/lwouis/alt-tab-macos/issues/535

**Closed by lwouis** 2022-05-23 15:52 UTC
Labels: enhancement
