### ISSUE TITLE
Webex in-call window doesn't appear in window list

### ISSUE THREAD

**Issue by citruz** [lwouis/alt-tab-macos#1803] opened 2022-07-21 20:54 UTC
## Setup

- macOS Monterey 12.5 on M1
- AltTab 6.46.1
- Webex 42.7.0.22904

## Steps to reproduce

1. Download Webex from https://www.webex.com/downloads.html
2. Join a test call from https://www.webex.com/test-meeting.html
3. Switch away from the in-call window
4. Try to switch back using AltTab ➔ Windows is not visible

- The Webex signin window is visible, the in-call window not
- Switching via cmd-tab works

## Screenrecording

https://www.dropbox.com/s/yehtam1rrvl8e6g/Screen%20Recording%202022-07-21%20at%2022.47.40.mov?dl=0

<img width="1220" alt="Screenshot 2022-07-21 at 22 54 01" src="https://user-images.githubusercontent.com/3756270/180313430-ce940365-9e09-4bf6-b5a9-df23de682caf.png">

**Comment by keaukraine** [comment] 2022-07-22 09:03
Thank you for reporting this.
I will re-test release with fix on my work Mac.

**Comment by lwouis** [comment] 2022-07-22 10:47
@keaukraine are you working for WebEx? Or do you mean you have a patch for AltTab to fix this issue?

**Comment by lwouis** [comment] 2022-07-23 17:27
I just tested the steps in this ticket, and it works fine on my machine. All windows are shown.

I think it may be an issue with more recent versions of Webex? I noticed that my icon was not the same as in the video, and indeed when downloading a fresh version, it looks like the video now:

<img width="556" alt="image" src="https://user-images.githubusercontent.com/106195/180616032-c8306843-1be2-4b85-b995-3cf3700e653f.png">

Update: After installing the new version, it still works great:

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/106195/180616123-2e356b5e-646b-434c-b4bb-6397b032860a.png">

I removed the webcam, but it worked with it. The secondary app `Cisco Webex Meetings` shows its windows like `Webex`, and everything works fine. I'm confused what's different on the OP video.

**Comment by keaukraine** [comment] 2022-07-26 08:56
> > release with fix
> 
> @keaukraine are you working for WebEx? Or do you mean you have a patch for AltTab to fix this issue?

No, I meant I wanted to test a new release of Alttab with this issue fixed.

**Comment by citruz** [comment] 2022-07-26 09:22
> @citruz any idea why your Webex window has differences with mine? Maybe it's the Monterey version? Maybe it's the M1 version? Maybe something else I'm not seeing?

You are using Catalina? Yes I guess that could be the problem, at least I would say it is more likely than M1 vs. Intel. Yesterday, I noticed that the same issue also happens with FaceTime.

**Comment by lwouis** [comment] 2022-07-26 09:23
@keaukraine could you please share the code change you made that may fix the issue?

**Comment by keaukraine** [comment] 2022-07-27 08:49
To be clear: I neither work for Webex nor contribute to Alttab. I only use both apps.

**Comment by lwouis** [comment] 2022-07-27 08:50
@keaukraine you said you have a fix. What kind of fix is this? I thought you had made a change in AltTab in a local fork. If not, how did you implement the fix?

**Comment by keaukraine** [comment] 2022-08-02 16:26
I said that I will be able to test next release with this bug fixed. Sorry for possible confusion.

**Comment by wischnow** [comment] 2022-08-09 08:32
I've been having a similar problem with Webex in-call windows for quite some time (long enough that I don't recall when it started). For me, the in-call window appears in the list of windows but when I select it, the window is neither brought to the foreground nor focussed. This is with MacOS Monterey 12.5 on an Intel Mac.

**Comment by lwouis** [comment] 2022-11-02 22:24
Closing this. I think when people have issues, it's because of #1324. As I've shown above, I can't reproduce despite great efforts.

**Closed by lwouis** 2022-11-02 22:24 UTC
