### ISSUE TITLE
Chrome applications not shown after connecting external display

### ISSUE THREAD

**Issue by quantus** [lwouis/alt-tab-macos#656] opened 2020-10-19 22:16 UTC
**Describe the bug**

I have an external monitor configured to be my primary display. Almost every time after I connect an external display, the Chrome windows disappear from the AltTab. So this happens almost every day with my current usage.

**Screenshots / video**

[alttab-issue.mp4.zip](https://github.com/lwouis/alt-tab-macos/files/5405093/alttab-issue.mp4.zip)

At ~0:16 seconds I disconnect my external screen for a moment, and at ~0:23 it gets reconnected. At the end of the video I show all the settings I have configured in AltTab.

**Steps to reproduce the bug**

 1. Close all open Chrome and Firefox windows
 2. Move all open applications to other spaces. (So both the laptop's and external screen are empty)
 3. Open a Chrome window on the external display
 4. Open a Firefox window on the external display
 5. Disconnect the external display (this moves the Chrome and Firefox windows to the laptop's screen)
 6. Reconnect the external display (this moves the Chrome and Firefox windows back to the external screen)

After these steps the AltTab isn't showing the Chrome windows anymore, but it is showing the Firefox window. If I open any new Chrome windows, those new windows do appear in AltTab. Restarting AltTab fixes the issue.

So far I've seen these disappearing windows (randomly) from the following applications: Chrome, Sublime text, Firefox, Terminal. I don't use any applications in fullscreen mode, but I do use multiple spaces. Disabling "Show standard tabs as windows" option doesn't fix the issue. Both the Chrome and Firefox versions used in my testing are the latest stable versions.

I'm running AltTab version 6.7.3 on macos 10.15.7.

**Comment by lwouis** [comment] 2020-10-20 01:34
Thank you @quantus for sharing this issue! You made a very nice and clear ticket too. Most people just through a few lines of "it's not working please fix", so i do appreciate a quality ticket when i see one 👍

I'm thinking that this is the tabs detection acting incorrectly again. When a window changes Space, there is a small window of time where the workarounds and private APIs AltTab has to use may read the window as being tabbed onto another window.

Could you perhaps check the checkbox in the preferences "Show standard tabs as individual windows"? If after checking it, you then see a window like Chrome's, which was previously not visible, it would comfirm my theory.

I'll try to reproduce the issue as soon as my life gets less busy 👍

**Comment by quantus** [comment] 2020-10-20 07:34
> Thank you @quantus for sharing this issue! You made a very nice and clear ticket too. Most people just through a few lines of "it's not working please fix", so i do appreciate a quality ticket when i see one 👍

Thanks! I think it's the issues reporter's job to make the issue resolving as easy as possible.

> Could you perhaps check the checkbox in the preferences "Show standard tabs as individual windows"? If after checking it, you then see a window like Chrome's, which was previously not visible, it would comfirm my theory.

Enabling the preference after the Chrome window had disappeared didn't change anything. I also tried all the reproduction steps after the preference was enabled, but the window still went missing.

> I'll try to reproduce the issue as soon as my life gets less busy 👍

:+1:

Thanks for looking into this issue!

**Comment by lwouis** [comment] 2020-10-20 14:29
I tried to reproduce the issue today but couldn't. I followed your steps exactly, but after reconnecting to the external monitor, the windows go back on that monitor, and AltTab lists them correctly.

Could you possibly film your setup with your phone? There are small ambiguities like do you have both the external and the internal monitors turned on at the same time when plugged to the external monitor for example. These would be made more clear if I see the end-to-end setup and reproduction. Otherwise I'm a bit stuck as I can't reproduce, and your latest test seems to indicate that my speculation regarding the root cause was incorrect.

**Comment by quantus** [comment] 2020-10-20 19:22
I've been testing this a bit more. This time I closed all the software from the background, and closed all the extra spaces (the external display has just space "Desktop 1", and the laptop has just "Desktop 2" . I also restarted the laptop to make sure there was less things that could mess up my testing.

Here is the video (with a bit bad encoding) from my testing:
[2020-10-20 22-05-11.mp4.zip](https://github.com/lwouis/alt-tab-macos/files/5411028/2020-10-20.22-05-11.mp4.zip)

This time I experienced something bit different than what I initially reported. When I reconnected the external monitor, neither applications were visible in the AltTab. After I moved the application windows, they appeared there. This is shown in the video. 

My configuration is like this:
![Screenshot 2020-10-20 at 21 12 48](https://user-images.githubusercontent.com/671419/96633681-1d84f280-1322-11eb-969d-35aa3c717874.png)
![Screenshot 2020-10-20 at 21 12 52](https://user-images.githubusercontent.com/671419/96633669-19f16b80-1322-11eb-90bc-433a33dd6128.png)
![Screenshot 2020-10-20 at 22 18 41](https://user-images.githubusercontent.com/671419/96633767-41e0cf00-1322-11eb-9bfa-dd178f6fa40b.png)

Thanks again for looking in to this.

**Comment by lwouis** [comment] 2020-10-21 04:35
Thanks for the video. It's very intriguing! I'm wondering what's at play here

**Comment by CreaaZ** [comment] 2020-12-04 15:19
I have a similar behaviour on my machine as well with Chrome windows are not showing up in Alt-Tab - happens once a day at minimum. New Chrome windows are available in Alt-Tab, but existing windows won't show up. 
In difference to what @quantus mentioned, I never work with other spaces on my Mac. So using different spaces might not be the root cause or a necessary step to reproduce the issue. I will closely monitor under which circumstances the bug will show up and update the issue when I have new information.

One additional thing I observed - don't know whether this helpful:
I have configured CMD + ^ to switch between windows of the active application (so switching among all Chrome windows for example). When I am in the situation that my current Chrome window does not show up on Alt-Tab and I open a new window I can use CMD + ^ to switch to the affected Chrome window. So somehow Alt-Tab recognises that window when looking for windows of the same application, but not when looking for all windows.

**Comment by lwouis** [comment] 2020-12-05 03:07
@CreaaZ from your last remark, i can deduct that it's the tab detection having issues, [as i suspected](https://github.com/lwouis/alt-tab-macos/issues/656#issuecomment-712532793). At least in your case. You say you don't use other Space. Do you really not? What about fullscreen windows? These create other Spaces on macOS. Fullscreening a Youtube video for example creates a new Space. These are the scenarios where AltTab could mistakenly think that you tabbed a window, because the window stop showing in results of APIs because windows on other Space are not listed in most API results

**Comment by CreaaZ** [comment] 2020-12-07 11:34
@lwouis Of course, I cannot completely rule out that I don't use spaces at all - but I definitely don't work actively with fullscreen windows or dedicated spaces, because I use Magnet App to manage my windows. Agree that fullscreen videos cause a space in the background, but I rarely watch videos (and even more rarely in fullscreen).
This morning I observed the exact same behaviour with the Microsoft OneNote app. And with that app I can say with more than 99,9% confidence, that this app has never been in another space or fullscreen since my last boot.
So far I unfortunately could not identify any usage pattern that would explain that behaviour.

**Comment by lwouis** [comment] 2020-12-07 13:53
I'm sorry to hear that the issue is happening to many people. I'm a bit overwhelmed between work and moving houses recently. I hope next year I can start going deeper on this issue and others that have accumulated. The problem being the vast amount of time needed for these hard-to-reproduce issues which happen on other people machines, and never on mine, and even on their machine, not on a clear pattern. These are really though to deal with, but I'll try my best to look into it again soon!

**Comment by lwouis** [comment] 2021-03-08 14:45
@CreaaZ @quantus Could you please try out the local build in https://github.com/lwouis/alt-tab-macos/issues/824#issuecomment-792431409? It may fix the issue in this ticket.

Please let me know if it fixes the issue for you!

**Comment by quantus** [comment] 2021-03-08 17:54
After hitting this issue I've kept my laptop more connected the the external display, and so haven't seen this issue that often. Now that I tested this, it seems can't even reproduce this issue in the latest release (6.17.0). I tested the previous releases and the version 6.14.0 was the one where this issue got fixed. So at least for me this issue has already been resolved.

Thanks!

**Comment by lwouis** [comment] 2021-03-09 15:06
Cool! Thanks a lot for testing all these different versions to confirm when it was fixed!

I'll close this ticket now then 👍

**Closed by lwouis** 2021-03-09 15:06 UTC
Labels: bug, unreproducible
