### ISSUE TITLE
Constant freezing when alt-tabbing on latest OS update.

### ISSUE THREAD

**Issue by DD-09** [lwouis/alt-tab-macos#1286] opened 2021-12-14 15:13 UTC
**Describe the bug**

Since I've updated to MacOS Monterey 12.1, AltTab has been acting up whenever I alt-tab. It sometimes freezes, the selection window stays on screen, and it generally becomes unresponsive. 

**Screenshots / video**

N/A

**Steps to reproduce the bug**

No way of reproducing the bug. Happens at irregular times.

**Comment by lwouis** [comment] 2021-12-14 15:39
I've worked on https://github.com/lwouis/alt-tab-macos/issues/563 for more than a year. The symptoms you describe are similar.

Performance issues like this are a nightmare because they can't be reproduced consistently. Worse than this, i've reproduced these issues while the profiler was running (different kind of profilers in Instruments actually). Yet the profiles don't point to causes within AltTab code

Without steps to repro, i'll close this ticket. A year of working on the other one had me look at the issue up down and sideways, and i simply did all i could i'm afraid.

Could also be something specific to Monterey. I know that #718 is a direct bug Apple introduced from BigSur that i've no idea how to work around. These may be related who knows

**Closed by lwouis** 2021-12-14 15:39 UTC
Labels: bug

**Comment by DD-09** [comment] 2021-12-14 15:41
Damn, makes sense. Thanks for the response. Wish I could help you more!
