### ISSUE TITLE
setup_local.sh fails without -legacy in generate_selfsigned_certificate.sh

### ISSUE THREAD

**Issue by gabekus** [lwouis/alt-tab-macos#3170] opened 2024-02-11 18:39 UTC
**Describe the bug**

When running `scripts/codesign/setup_local.sh` I get this error `MAC verification failed during PKCS12 import (wrong password?)`. Adding `-legacy` to the final `openssl` command in `generate_selfsigned_certificate.sh` fixes this error. I'm not sure which OS versions need this flag, as I assume older versions worked just fine without it, but it's possible new Mac versions going forward may need this.

**Screenshots / video**
<img width="796" alt="image" src="https://github.com/lwouis/alt-tab-macos/assets/122312713/c3dd93ad-d729-48be-8e7a-406f5b72600f">
<img width="828" alt="image" src="https://github.com/lwouis/alt-tab-macos/assets/122312713/f75bf2d9-13de-47a8-82cb-b5e23255a3c1">
<img width="829" alt="image" src="https://github.com/lwouis/alt-tab-macos/assets/122312713/fbfa080e-8404-4f1e-9f4d-bdc43c0980ac">

**Steps to reproduce the bug**

1. Run `scripts/codesign/setup_local.sh` on Sonoma 14.2.1

**Your environment**

* AltTab version: 6.65.0
* macOS version: 14.2.1
* Other relevant info: e.g. using external keyboard, multiple monitors, etc
This is a work MacBook Pro with custom configuration, may not happen on a personal machine

**Comment by lwouis** [comment] 2024-02-12 16:00
Hi,

I was not able to reproduce the issue:

```sh
$ openssl version
LibreSSL 3.3.6

$ scripts/codesign/setup_local.sh
+ certificateFile=codesign
++ openssl rand -base64 12
+ certificatePassword=iJ0RNAf4eKtpS9gC
+ scripts/codesign/generate_selfsigned_certificate.sh codesign iJ0RNAf4eKtpS9gC
+ certificateFile=codesign
+ certificatePassword=iJ0RNAf4eKtpS9gC
+ cat
+ openssl genrsa -out codesign.key 2048
Generating RSA private key, 2048 bit long modulus
..........................................................................................................................................................................................................................+++++
...............................................................................+++++
e is 65537 (0x10001)
+ openssl req -x509 -new -config codesign.conf -nodes -key codesign.key -extensions extensions -sha256 -out codesign.crt
+ openssl pkcs12 -export -inkey codesign.key -in codesign.crt -out codesign.p12 -passout pass:iJ0RNAf4eKtpS9gC
+ scripts/codesign/import_certificate_into_main_keychain.sh codesign iJ0RNAf4eKtpS9gC
+ certificateFile=codesign
+ certificatePassword=iJ0RNAf4eKtpS9gC
+ security import codesign.p12 -P iJ0RNAf4eKtpS9gC -T /usr/bin/codesign
1 identity imported.
+ security add-trusted-cert -d -r trustRoot -p codeSign codesign.crt
```

I'm wondering if perhaps you have installed a custom version of openssl, or some other dependency used by the `setup_local.sh` script.

Thank you

**Comment by GabeKuslansky** [comment] 2024-02-13 04:02
> I'm wondering if perhaps you have installed a custom version of openssl, or some other dependency used by the `setup_local.sh` script.

There may very well be something else at play as you suggested, since this is happening on a pre-configured work machine. I just checked:

```
openssl -v
OpenSSL 3.2.1 30 Jan 2024 (Library: OpenSSL 3.2.1 30 Jan 2024)
```

I'm unsure how to check the version of `security`, that's the only other dep I'm seeing.

**Comment by Allsochen** [comment] 2024-06-13 12:10
I had this problem too. this problem depends on the version of openssl.

https://stackoverflow.com/questions/70431528/mac-verification-failed-during-pkcs12-import-wrong-password-azure-devops

**Comment by lwouis** [comment] 2024-07-06 10:49
Closing this ticket for now. If too many people encounter the issue, or simply with time passing by, we may have to add en if/else around the openssl call, to add the `-legacy` flag if needed.

**Closed by lwouis** 2024-07-06 10:49 UTC
Labels: bug, unreproducible
