### ISSUE TITLE
Cmd-Tab doesn't work on Ventura Beta

### ISSUE THREAD

**Issue by leehauser** [lwouis/alt-tab-macos#1878] opened 2022-08-17 03:28 UTC
I realize this may not be reproducible, and Ventura is in beta -- but after the most recent public beta update (22A5321d), Cmd-Tab does nothing. I eliminated other login items before finally arriving at AltTab. The Cmd key does other things as usual, including launching Spotlight. Without AltTab, Cmd-Tab works fine again.

**Comment by lwouis** [comment] 2022-08-17 05:37
Duplicate of #1852

**Closed by lwouis** 2022-08-17 05:37 UTC
