### ISSUE TITLE
AltTab makes the Open/Save dialog have 1s delay to popup

### ISSUE THREAD

**Issue by painty** [lwouis/alt-tab-macos#1155] opened 2021-09-24 02:52 UTC
**Describe the bug**

Macbook Pro M1, BigSur 11.6
When AltTab is running, the system's file dialog will have about 1s delay to show.

**Steps to reproduce the bug**

1. Make sure AltTab is running (in the background)
2. In any app, chrome, for example
3. Press cmd+o to show the open file dialog
4. Will get a noticeable 1s delay before the popup dialog
5. Exit AltTab
6. Replay step 2-3
7. The popup dialog appears much faster

**Comment by lwouis** [comment] 2021-09-24 07:25
Duplicate of #718

**Closed by lwouis** 2021-09-24 07:25 UTC
Labels: bug
