### ISSUE TITLE
Zim.app not shown as window

### ISSUE THREAD

**Issue by andredasilvapinto** [lwouis/alt-tab-macos#367] opened 2020-06-05 10:40 UTC
**Describe the bug**

Zim app (GTK) isn't detected as an option while switching between windows.

Not sure what information AltTab uses to detect the presence of a window but it might be that there is either something wrong with the way the Zim wrapper is reporting the existance of the window or AltTab is missing some of the windows when doing the lookup. Zim shows up in the native application list from OSX (Cmd+Tab).

**Steps to reproduce the bug**

1. Install Zim and its wrapper ( https://zim-wiki.org/ https://github.com/jaap-karssenberg/zim-wiki/wiki/Mac-OSX-App-%28wrapper%29 )
2. Open Zim
3. Press Option+Tab
4. See that the Zim window is not there.

**Comment by lwouis** [comment] 2020-06-08 01:50
Hi @andredasilvapinto! Thank you for sharing this issue!

I installed Zim and tested, and could reproduce the issue. I'm afraid the issue is with Zim. I don't know how the zim app is built, but looking at the wrapper wiki, it seems to be 100% foreign to the mac platform. I imagine the UI is drawn using GTK which is using OpenGL directly, as opposed to use macOS UI libraries (e.g. Cocoa, AppKit).

The app identifies as "python":

![image](https://user-images.githubusercontent.com/106195/83985512-7c019380-a974-11ea-8874-68a2c42cfd3e.png)

When using APIs to get the app object, it has `bundleIdentifier` = `org.python.python`. And when calling `AXObserverAddNotification` on the app, which is the way we get to know about an app window, it returns `AXError.cannotComplete`.

Some other apps like Gimp return that error while starting, so we have a retry-loop in place to attempt again for 2 min. Here however, Zim just never let us subscribe to it. I've seen similar behavior from #182 in the past. I think an app should have a macOS event loop to be able to respond to things like accessibility subscription from the outside. I imagine Zim doesn't have that, so it never responds, and thus we can never sub and get its windows.

I thought I would open a ticket on their github, but I realized they have more than 400 open tickets already. Also it seems that macOS is in a messy situation, [being worked on right now](https://github.com/zim-desktop-wiki/zim-desktop-wiki/issues/990).

I imagine you're more familiar with Zim than me. Could you possibly reach out to the right community members, and reference this issue here? They may be able to give Zim a proper bundleID, and make it compatible with the macOS Accessibility API.

I'll close this ticket as there is no work on AltTab side that can fix this, unfortunately.

**Closed by lwouis** 2020-06-08 01:50 UTC

**Comment by andredasilvapinto** [comment] 2020-06-08 08:17
Hi @lwouis 

First of all thanks for looking into this and investigating the issue.
Yes, mac support for Zim is still quite poor. The wrapper was introduced here: https://github.com/zim-desktop-wiki/zim-desktop-wiki/issues/262

I will create a ticket with Zim.

**Comment by jovarela** [comment] 2020-07-26 20:03
On alt-tab Version 4.9.1 blacklist functionality has been introduced... it will be a nice workaround to blacklist zim windows to reduce CPU consumption. I've used "org.python.python" into the black list but it didn't helped... alt-tab is looking for a different identifier? is this approach feasible?

**Comment by lwouis** [comment] 2020-07-27 01:59
@jovarela I can't test it locally right now, so I'm just guessing:

The Zim wrapper is missing a `bundleIdentifier`. That means you blacklisting `org.python.python` is not helpful. I think a simple fix for the Zim wrapper on mac would be to add a `bundleIdentifier` in the `Info.plist` ([last file on this page](https://github.com/jaap-karssenberg/zim-wiki/wiki/Mac-OSX-App-%28wrapper%29)). You could then blacklist that identifier.

You would need to add something like this:

```
<key>CFBundleIdentifier</key>
<string>org.zim-wiki.zim/</string>
```

That's a change you could both ask the maintainer of the mac release to do, but also do locally right now to get it working on your system immediately.

Hope that helps!

**Comment by jovarela** [comment] 2020-07-28 08:29
Thanks a lot for the quick answer! It doesn't work since the CPU consumption still goes to 10% until I close zim and it goes to 0%... If I have the time I'll try to go deep on that. Thanks anyway!

**Comment by pushkarajthorat** [comment] 2022-08-08 05:48
> @jovarela I can't test it locally right now, so I'm just guessing:

> ```
> <key>CFBundleIdentifier</key>
> <string>org.zim-wiki.zim/</string>
> ```
> 
This worked for me, in my case the string was 'org.zim-wiki.Zim' I changed it to 'org.zim-wiki.zim'
