### ISSUE TITLE
Overlapping & missing thumbnails

### ISSUE THREAD

**Issue by MTCoster** [lwouis/alt-tab-macos#255] opened 2020-04-20 11:23 UTC
This issue is best described by these two screenshots:

![Alt-Tab Screenshot](https://user-images.githubusercontent.com/2152582/79745739-bcdc1500-8300-11ea-894f-fc5de9f77b24.png)
![Mission Control Screenshot](https://user-images.githubusercontent.com/2152582/79746010-31af4f00-8301-11ea-99c3-02e2a0cc1e9d.png)

In the first image, Alt-Tab shows 11 thumbnails (9 windows + 1 full-screen + 1 minimised), but with one of them shown behind some of the others.

The second image shows Mission Control with 10 windows and 1 full-screen app (plus the minimised window if you look closely).

For some reason, Alt-Tab is not showing one of the windows (Spark.app).

Please let me know if there's any additional information you require or testing steps you'd like me to take.

**Comment by lwouis** [comment] 2020-04-20 13:05
Hi @MTCoster! Thank you for sharing these issues! Let's go 1 by 1:

> Alt-Tab is not showing one of the windows (Spark.app)

I installed Spark.app and right off the bat I noticed the onboarding window is not standard. Yet I can still see it in AltTab:

| <img src="https://user-images.githubusercontent.com/106195/79754051-dce7f480-8351-11ea-8d6e-30f516e35857.jpg" width=45% /> | <img src="https://user-images.githubusercontent.com/106195/79754039-d8bbd700-8351-11ea-9dd5-470982f210d0.jpg" width=45% /> |

I thought "ok maybe the onboarding windows are ok, but the main inbox window is different. So I loged in with my gmail account, and again it just shows correctly in AltTab:

| <img src="https://user-images.githubusercontent.com/106195/79754126-fdb04a00-8351-11ea-815e-cbd326cd9dc1.jpg" width=45% /> | <img src="https://user-images.githubusercontent.com/106195/79754142-01dc6780-8352-11ea-8690-e5a429915ebe.jpg" width=45% /> |

> One of them shown behind some of the others.

That's very surprising! Does it always do that? Is it consistently happening, or could it be a fluke? What if you play with the preferences:

![image](https://user-images.githubusercontent.com/106195/79754546-b1193e80-8352-11ea-9748-e1af2a939171.png)

Especially the `Align windows` preference. What happens if you change values there? Also number of rows, etc.

By poking around at these things, it may help understand what's wrong. You can also send a debug profile by using the built-in feedback form. This way we can see things like macOS version, locale, darkmode, etc.

![image](https://user-images.githubusercontent.com/106195/79754758-ff2e4200-8352-11ea-8a6c-d72f623becea.png)

**Comment by lwouis** [comment] 2020-04-27 17:37
@MTCoster any update?

**Comment by MTCoster** [comment] 2020-04-27 17:39
@lwouis All appears to be working now, must have had something in a funny state before.

**Comment by lwouis** [comment] 2020-04-28 00:32
That's weird! Oh well, i guess we can't reproduce so let's close this ticket and move on. Hopefully it was just a rare fluke and won't affect anyone else

**Closed by lwouis** 2020-04-28 00:32 UTC
Labels: bug, unreproducible
