### ISSUE TITLE
The icon of iTerm2 is small then restore to normal size.

### ISSUE THREAD

**Issue by zhaoxuan** [lwouis/alt-tab-macos#3376] opened 2024-05-23 03:32 UTC
**Describe the bug**

See the video

**Screenshots / video**

https://github.com/lwouis/alt-tab-macos/assets/1038132/14134a96-705c-4302-bee4-267ad3772705

**Your environment**

* AltTab version: latest
* macOS version: 14.5

**Comment by ianrobrien** [comment] 2024-05-27 08:19
iTerm2 got a new update (3.5.0) just a few days ago with some new settings. It could be one of those that's conflicting with alt-tab.

**Comment by lwouis** [comment] 2024-05-27 09:06
This looks like a duplicate of https://github.com/lwouis/alt-tab-macos/issues/1279

I think there is a workaround shared towards the bottom of that thread 👍

**Closed by lwouis** 2024-05-27 09:06 UTC
Labels: bug
