### ISSUE TITLE
AltTab doesn't ask for ScreenRecording permission on 10.15.4

### ISSUE THREAD

**Issue by vansickle** [lwouis/alt-tab-macos#340] opened 2020-05-18 19:17 UTC
**Describe the bug**

Mac OS 10.15.4

***AltTab 3.23.1 release***

* On start app asked to give accessibility permission. After it was given - nothing happened when app restarted, it just silently finished.
* When tried to run via Terminal received ""Before using this app, you need to give permission in System Preferences > Security & Privacy > Privacy > Screen Recording."
"Please authorize and re-launch."
"See https://dropshare.zendesk.com/hc/en-us/articles/360033453434-Enabling-Screen-Recording-Permission-on-macOS-Catalina-10-15-"
* But the problem is - AltTab never asked me for "Screen Recording" permission. It doesn't appear in ' Security & Privacy > Privacy > Screen Recording' and this 'Screen Recording' doesn't have an option to manually add an app.

***master***

The same results as 3.23.1 when compiled and run latest master

***Other similar apps***

Tried how similar apps handle this:

* TeamViewer, it has useful dialog to show given permissions, but effectively has the same problem - no request for screen recording from app, doesn't appear in System Preferences
* QuickTime - works fine, when tried screen record it asked me for permissions and appeared in SysPrefs where I could check the checkbox for it

***AltTab 1.14.1***

When searching through issues found that initial Screen Recording support in AltTab was made differently, tried it and it worked fine - asked me for permission, appeared in System Preferences and worked.

**Comment by lwouis** [comment] 2020-05-19 06:13
Hi @vansickle! Thanks a lot for sharing this nicely documented bug report!

The System Permissions situation on macOS is a hot mess unfortunately. Just to give you an idea, there is no public API from Apple to check if Screen Recording permission was granted, so we use a private API called `SLSRequestScreenCaptureAccess` for that.

I will close this ticket as a duplicate of #127 as I documented a lot of things there already on how we could tackle all the issues with macOS System Permissions. I also shared [a very in-depth post](https://github.com/lwouis/alt-tab-macos/issues/127#issuecomment-606383564) I found outlying the issues with the OS not showing the user the permission grant popup after the first time, which may be the issue you faced here.

I'm wondering for instance, if the fact that it worked for you with 1.14.1 is not due to the fact that it's a different app technically. Maybe any version other than 3.23.1 would work for you as it would be the first time, and trigger the OS prompt?

In any case, i have already explored the issue quite a bit in #127, so let's continue the conversation there.

Of course, any PR would be accepted and merged promptly. Any technical pointers would help also, as this area is undocumented by Apple and any insight would help. Pointing to another OSS project that does it well would be a big thumbs up also 👍

**Comment by vansickle** [comment] 2020-06-05 15:42
I know the issue is closed, but still one share solution to the problem I had.

`tccutil reset ...` didn't help me, but `PRAM reset` did
So if AltTab permission request to screen recording doesn't appear for you - try reset PRAM/NVRAM (describe [here](https://support.apple.com/en-us/HT204063)) - after that latest AltTab finally asked for permission properly.

Why it happened to me? My guess is that it may be connected to the fact that I had System Integrity Protection disabled

**Comment by kissge** [comment] 2020-09-19 08:30
I suppose the OP's problem was misread.
I'm having the same issue, although this is my first time install.
Under this situation, it's impossible to use AltTab at all...

![image](https://user-images.githubusercontent.com/4177010/93662774-88ca7300-fa9d-11ea-8700-1760a98a558c.png)

**Comment by lwouis** [comment] 2020-09-25 15:50
Note: experiment with https://github.com/egoist/Shortcut/blob/6b64cb17b6d83c7ab7b2a17c5b5b5a7e51a23677/Shortcut/ActiveWin.swift#L30

**Comment by lwouis** [comment] 2021-01-25 15:23
I implemented the above new workaround to detect Screen Recording permission (see https://github.com/lwouis/alt-tab-macos/issues/704#issuecomment-762935477) in the just released v6.13.0. Hopefully it fixes this issue. Please let me know if you still face it on the latest version, and I'll re-open this issue 👍

**Closed by lwouis** 2021-01-25 15:23 UTC
Labels: bug, duplicate
