### ISSUE TITLE
Hidden badge not updated

### ISSUE THREAD

**Issue by decodism** [lwouis/alt-tab-macos#971] opened 2021-05-25 20:04 UTC
**Describe the bug**

In some cases, the badge indicating that a window is hidden does not disappear when the window is unhidden.

**Steps to reproduce the bug**

In AltTab :
- Hide an application
- Minimize a window of this application (which unhides the application)

**Comment by lwouis** [comment] 2021-05-26 02:12
Hi @decodism

Actually, minimizing a window doesn't unhide its app. You can confirm this by right-clicking the Dock icon of the app, and it will say "Show" or "Hide" depending on if the app is hidden of not.

* Hide the app
* => reads "Show" since the app is hidden
* Minimize the window with AltTab
* => reads "Show" still, confirming that for the OS, the app is hidden
* Deminimize the window
* => reads "Show" still, confirming that for the OS, the app is hidden. Interestingly, a user can visually see the window at this point

This situation is complex. It's not a bug in AltTab, because at the OS level, the app is hidden still, in all the scenarios above. It is not possible, without AltTab, to minimize/deminimize a hidden window. How would you do it? There is no icon to click, or menu to use to select the window to be minimized/deminimized once the app is hidden.

In other words, AltTab is putting the OS in a state that's not meant to be possible. Thus the OS is incoherent.

Now should AltTab follow that state, and also report that the app is hidden? I think yes. If we did our own thing like "ok after deminiaturizing the window, I know for a fact that visually, the window is visible, so I will force AltTab to ignore the OS state, and instead display that it's not hidden, then we could get inconsistencies, as now AltTab and the OS are desync'd.

I'll close this for now, as I think the way we currently deal with it shows the user the reality of the situation, as understood by the OS. For example, if another app needs an app to be not hidden to display its contents, then that app would work when AltTab says it's not hidden, and would not work when AltTab says it's hidden. That contradicts direct observation with the eyes, since the user can see the window, but again, technically the app is still hidden for the OS, so better notify the user of that reality.

**Closed by lwouis** 2021-05-26 02:12 UTC
Labels: bug

**Comment by decodism** [comment] 2021-05-26 15:01
I agree that AltTab should stay synchronized with the OS. However, why not notify the OS of the desired display state after minimizing a hidden window? It would remain to be determined whether one wants the application to remain hidden or to be displayed.
