### ISSUE TITLE
Disable automatic rearangement of windows based on most recent use

### ISSUE THREAD

**Issue by orlovorlov** [lwouis/alt-tab-macos#1386] opened 2022-02-17 11:51 UTC
**Is your feature suggestion related to a problem? Please describe.**

When the user has a lot of windows open and wants to find a particular one it becomes a time-consuming task to locate it because the windows are in constant motion depending on how recently they've been switched to. 

**Describe the solution you'd like**

Please add a check-box to allow keeping the windows in the order that they've been opened so their position is permanently assigned based on when they were opened and not when they were switched to last.  Would also be beneficial to have a sub-option that automatically groups windows based on which app they belong to and adds the newly opened windows to that group while still maintaining the global order for the rest of the windows.

**Comment by lwouis** [comment] 2022-02-17 14:38
Duplicate of https://github.com/lwouis/alt-tab-macos/issues/515#issuecomment-678993323

**Closed by lwouis** 2022-02-17 14:38 UTC
Labels: enhancement
