### ISSUE TITLE
Alt-tab'ing to the Preferences window doesn't focus it, and may cause crashes

### ISSUE THREAD

**Issue by jukrb0x** [lwouis/alt-tab-macos#871] opened 2021-03-18 17:16 UTC
**Describe the bug**
I wish I could upload videos to present this _bug_ comprehensively (maybe later), but limited to some issues I only express in words as clearly as I can.

> AltTab Version 6.17.0
> macOS Big Sur 11.2.2 (20D80)

### Prob 1
I have an external Bluetooth keyboard, the strange thing is AltTab don't react to Shortcut 2 ( **Cmd + \`** ) on the external keyboard, meanwhile the **\`** is shared the same key with **Esc** on the keyboard, so actually I press **Cmd + Fn + \`** to perform the Shortcut 2. The windows (under the same application) switched if I did so by this external keyboard, but it went with the old way (macOS default windows switch) instead of AltTab doing so, at the same time I tried to use the in-build keyboard of macbook the AltTab Shortcut 2 working as expected.

The second problem occurs with the idea of changing Shortcut 2.

### Prob 2
I want to change the shortcut key of Shortcut 2 to test if the **Fn** key produces the issue, so I click the key-holder button to record a new key, noticing that the first screenshot below that traffic lights on the top left corner is _activated_ while the second screenshot performs in contrast.

That is I pulled up the AltTab settings window by opening the AltTab, and I switched to some else window and **switched back to AltTab**, **in two means**, Cmd + Tab as Shortcut 1 to switch back and **the traffic lights were off (2nd Screenshot), and the key-holder buttons didn't react when clicking them**, but I still can visit other tabs (General, Appearance, etc.) while the traffic lights were grey, **it appeared like the focus is not on the AltTab settings window**; 

And I tried to activate the settings window by _Mission Control_ (or just mouse clicking between two windows) and it worked with the traffic lights colored, as expected they should be colored when the window is activated (focused on). 

![p2-1](https://user-images.githubusercontent.com/15688641/111662880-4797fd80-884b-11eb-8dd8-0dc9a9b5426f.png)

![p2-2](https://user-images.githubusercontent.com/15688641/111662957-54b4ec80-884b-11eb-91ff-ea159b5e6c55.png)

### Conclusion to Prob 1
I successfully assigned a different key to shortcut 2 skipping **Fn** key on the external keyboard, it performed OK as AltTab expected instead of macos in-built windows switching, so I guess AltTab reading the keydown of each key pressed so it detected **Cmd + Fn + Esc** other than **Cmd + \`**, (I've tested if I assign **Cmd + Esc** to Shortcut 2, it works as expected on the external keyboard).

While I assigned different keys to test out the bug the AltTab crashed many times and I've sent the crash reports with prompt), I guess it's _Prob 2_ related bug.

**Steps to reproduce the bug**

1. Press **Cmd + \`** on macbook inbuilt keyboard, working as expected
2. Press **Cmd + Fn + Esc(\`)** on external keyboard, not working as AltTab
3. Set **Cmd + 1** as Shortcut 2
4. Press **Cmd + 1** on external keyboard, working as expected
5. Set **Cmd + Esc** as Shortcut 2
6. Press **Cmd + Esc** on external keyboard, working as expected

During Steps 3 - 6, AltTab crashes many times, possible causes are mentioned above.

**Comment by lwouis** [comment] 2021-03-19 00:53
Hi @jukrb0x! Can you please share a picture of your keyboard from above, so i can see the keys layout?

Regarding the second issue and the crashes, AltTab is not supported on Big Sur yet. There are some known issues there:

**Comment by jukrb0x** [comment] 2021-03-19 08:05
> Hi @jukrb0x! Can you please share a picture of your keyboard from above, so i can see the keys layout?
> 
> 
> 
> Regarding the second issue and the crashes, AltTab is not supported on Big Sur yet. There are some [known issues](https://github.com/lwouis/alt-tab-macos/labels/big%20sur) there:

The keyboard:

![image](https://user-images.githubusercontent.com/15688641/111749148-5b377880-88cc-11eb-85f7-b5807c935e3f.jpeg)

The **Esc** is bind with **`**

**Comment by lwouis** [comment] 2021-03-21 10:22
Oh I see, it's a custom Windows keyboard. I think you could potentially manage to do what you are trying to, but not with the `Fn` key. The `Fn` key is not supported as a modifier in AltTab. You can read the [rationale behind this on this ticket on ShortcutRecorder](https://github.com/Kentzo/ShortcutRecorder/issues/132), which is the library we use to capture shortcuts.

So if you bind ``` ` ``` to something else like `command-escape` instead of `fn-escape`, you may get success.

I'll keep this ticket open, and rename it to focus on Prob 2, which seems like it's not already covered by an existing ticket.

**Comment by lwouis** [comment] 2021-04-21 13:19
I tried to reproduce the issue with focusing the preferences window, but couldn't reproduce it. I'm closing this ticket. Please let me know if this issue still persists, and I'll re-open it. If that's the case, please share a video to showcase the issue, and steps to repro 👍

**Closed by lwouis** 2021-04-21 13:19 UTC
Labels: big sur, bug

**Comment by lilyball** [comment] 2021-09-21 18:50
I re-filed this as #1151 as it occurs on latest macOS 11 but this issue's description is a bit confusing.
