### ISSUE TITLE
I have to restart AltTab several times after restart/login to make it work as intended.

### ISSUE THREAD

**Issue by qns7** [lwouis/alt-tab-macos#3682] opened 2024-10-12 08:47 UTC
**Describe the bug**

As the title describes: After a login AltTab is running and I can go to the settings and all, but my hotkeys for switching aren't working: So in my case it just shows the stock apple app switcher when using cmd-tab.
I have to restart AltTab at least two times including waiting for a few seconds to make it work.
After that, so once it runs, it runs without hickups.
I tried to "regrant" the two permissions and clicking "later", as I read in another thread, but that didn't help.
This bug was present for a while in Sonoma and now on Sequoia is still there even after the recent/newest update.

**Screenshots / video**

I think my description is enough.

**Steps to reproduce the bug**

I don't know if it's just on my machine, but at pretty much every login it's the case. So reproducing it might be difficult for other people. 

**Your environment**

* AltTab version: 7.0.1
* macOS version: Sequoia 15.0.1
* Other relevant info: I'm using an external keyboard and an external monitor, but it happens also on it's own. 
* The below screenshot shows all my login items: _custom_start_ automatically re/starts AltTab three times including `sleep 3` after the three `osascript -e 'tell application "AltTab" to activate'` and before the two `killall "AltTab"`s, which hopefully is a functioning but janky workaround (I will test this later). In this scenario I deactivated the startup login inside AltTab.

![Screenshot 2024-10-12 at 10 33 13](https://github.com/user-attachments/assets/3b6b1419-54f9-4265-8987-0cd513c07f3e)

Best regards Q

**Comment by Mx-Iris** [comment] 2024-10-12 13:08
I have this issue too, all of a sudden he doesn't work, restart app many times and wait for a while before it works, the old 6.x version didn't have this issue.

**Comment by qns7** [comment] 2024-10-12 15:42
The workaround doesn't work reliably. I hope there will be a fix soon or someone who can tell me where to look for a solution.

**Comment by lwouis** [comment] 2024-10-12 16:25
Duplicate of https://github.com/lwouis/alt-tab-macos/issues/3665

**Closed by lwouis** 2024-10-12 16:25 UTC
Labels: bug
