### ISSUE TITLE
Please allow a command + tab option for the previous window as well.

### ISSUE THREAD

**Issue by cocoonkid** [lwouis/alt-tab-macos#1032] opened 2021-07-14 07:01 UTC
![CleanShot 2021-07-14 at 08 58 53@2x](https://user-images.githubusercontent.com/43231640/125577623-168bbd81-cf84-4844-b481-6eb0bd2270ac.jpg)

Please allow a command + tab option for the *previous window* as well.

The original switch somehow seems not possible. I always have to use an additional shift press to switch to the previous app.

Otherwise this is the perfect tool. Thanks so much!

**Comment by lwouis** [comment] 2021-07-14 10:00
Duplicate of https://github.com/lwouis/alt-tab-macos/issues/510

**Closed by lwouis** 2021-07-14 10:00 UTC
Labels: enhancement

**Comment by cocoonkid** [comment] 2021-07-14 20:37
Thx :)
