### ISSUE TITLE
Unusable

### ISSUE THREAD

**Issue by Fischmuetze** [lwouis/alt-tab-macos#219] opened 2020-04-08 09:41 UTC
I tried it out for some weeks and it ran more or less ok. But in this time I wondered why I had again and again spooky behavior of apps regarding spaces (Mission control). So I got apps - like the Finder which was configured to appear on all spaces but a click on it switched also the space. I take a long time since I realized that this behavior was affected by alt-tab. Until version 3.5 (the last version that stable ran here) there was a lot of layout problems inside the preferences dialog. After updating to version 3.6 it crashed direct after trying to use it or trying to open the preferences. Also a downgrade to the last known version isn't help anymore. Overall it seems to be to sloppy programmed. I know this is a open source project and the author spent a part of his lifetime voluntary to programming this. Thank you very much for that!  But for my opinion it isn't usable currently and I have to switch back to HyperSwitch.

**Comment by lwouis** [comment] 2020-04-08 10:28
> spooky behavior of apps regarding spaces (Mission control). So I got apps - like the Finder which was configured to appear on all spaces but a click on it switched also the space. I take a long time since I realized that this behavior was affected by alt-tab.

It's hard for me to understand what you're talking about here. Could you attach a video from your phone perhaps? I don't understand how you "configured" the Finder to appear on all Spaces. How is this done exactly? Then you say "A click on it switched also the space". A click on what, the window thumbnail in AltTab, or the Finder window in the Dock? If you click on a window thumbnail in AltTab, and that window is in another space, then it will focus the window and the new space. This is logical to me. What would you expect? Again, the best would be a video to demonstrate what you think is a bug.

> there was a lot of layout problems inside the preferences dialog

Could you please give us more details so that we can try to understand and fix these layout problems? Screenshots or videos would help a lot here. Also submitting from the "Send feedback..." button in the menubar would share a Debug Profile which would help by showing us your macOS version and other important details we need to know to reproduce/fix the issues you face.

> Also a downgrade to the last known version isn't help anymore

Please try to run `defaults delete com.lwouis.alt-tab-macos` in your terminal. This will remove your old preferences. Hopefully that helps. Please note that there is currently a bug on non-English locales that crashes even if you do this. I'm releasing a fix in a few minutes to address it.

> Overall it seems to be to sloppy programmed

May I suggest you look at the source code yourself, and share with us what could be improve? That would be more useful than a dismissive statement. Also consider that not many apps have support for downgrades. It is quite complex to support preferences of older versions.

**Comment by Fischmuetze** [comment] 2020-04-08 13:12
Hello,
thank you fro your quick response.

> May I suggest you look at the source code yourself, and share with us what could be improve? That would be more useful than a dismissive statement.


Sorry, but this is a very stupid, but typical reaction of some open source developers. So what does you mean with it: Only developers are allowed to communicate their criticism and dissatisfaction? In this case I suggest that you announce this kind of your point of view in the description of the software. 

I meant sloppy as I followed your project for several versions and each version came with new or already existing bugs - and now finally it doesn't run anymore (also if preference file was deleted). That's totally ok but you have to accept that you have not only dev bros rather "normal" users and they will have impressions of the app if the app is harm the working with the computer. So I try to work wit my computer and it's not only a playground. Publish your project as beta and all will be fine. 

Sincerely

**Comment by lwouis** [comment] 2020-04-08 13:59
@Fischmuetze can you please watch your language when you interact with strangers? Saying "sloppy" talking about someone else work, or saying "it is very stupid" about someone else response is considered rude.

> Sorry, but this is a very stupid, but typical reaction of some open source developers. So what does you mean with it: Only developers are allowed to communicate their criticism and dissatisfaction? In this case I suggest that you announce this kind of your point of view in the description of the software.

This was never my intention. Most tickets are discussed by non-developers here. There are hundreds of tickets.

I said "suggest you look at the source code yourself" because you said "overall it seems to be to sloppy programmed". I assumed you looked at the code since you had an opinion on it. If you're not a programmer, then why are you judging the code? You don't know. Personally I don't think that this codebase is sloppy. I think the app we are trying to make is very difficult to make and have work on thousands of computers with different settings, displays, OS versions, etc. Also we heavily use private APIs, and undocumented code, because Apple doesn't care for these kind of apps to exist, and provide no support for it, so we have to be creative and retro-engineer their system basically.

> I followed your project for several versions and each version came with new or already existing bugs 

This project has 114 closed tickets. Meaning either bugs or new features. The amount of features that were added in the past few months is huge. Adding support for Spaces, multi-displays, big performance improvements, custom shortcuts, etc. Yes there are bugs. Not that many I think. You need to realize that this is hard to do. We are using undocumented, private APIs from Apple. It is extremely to work and make software when you use code that has no documentation. In that context, I'm very proud of what we achieved. Regarding bugs, you're the first person to complain about the app not working at all, after deleting the preferences.

Finally, you have ignored all my other questions, as to what exactly is happening on your machine. How do you want us to fix the issues if you don't even take time to describe them in details. Do you expect customer support to help if you say "my tv is not working"? No of course they will ask for more details to understand what's wrong. Also it doesn't help if you call them stupid while asking for support, and they are volunteer and you're not a customer.

**Comment by Fischmuetze** [comment] 2020-04-08 14:31
> @Fischmuetze can you please watch your language when you interact with strangers? Saying "sloppy" talking about someone else work, or saying "it is very stupid" about someone else response is considered rude.


Regarding "sloppy" it might be a translation issue of the kind of the power of words and its meaning. Sorry for that ... 
Regarding "stupid", that's my understanding for your "argument" to force me to check the code by self. This is in my experiences a typical reaction in parts of the open source scene in sense of software quality criticism. I heard it to often ... If I would cooperate for each open source project that I use I could quit any other thing in my life.


> Finally, you have ignored all my other questions, as to what exactly is happening on your machine. How do you want us to fix the issues if you don't even take time to describe them in details. 

I haven't ignored your questions but I could only answer if it would be possible to run your program again, but it isn't. 

Yes the TV is not working since your app doesn't longer run. What should I do in your opinion as to say that it crashed after the first alt-tab switch or by click on the app icon in the menu bar (3.5). For 3.6 it crashed direct after the start. Crash logs for both version as attachment.

defaults delete com.lwouis.alt-tab-macos
2020-04-08 16:19:52.646 defaults[11123:2471053]
Domain (com.lwouis.alt-tab-macos) not found.
Defaults have not been changed.

Cheers

**Comment by lwouis** [comment] 2020-04-08 15:26
> Yes the TV is not working since your app doesn't longer run.

What do you mean "the TV"? Do you mean a TV app on you mac?

> What should I do in your opinion

If it crashes at startup, the only thing you can do is to get the crash report from Console.app, and attach it here. You could also run the project locally in XCode. When you run it and there is an uncaught exception, it will show you the line that threw. This is immensely helpful, but maybe you can't run XCode locally, which of course I understand. These are the only 2 things that would help investigate, that I know of.

> Crash logs for both version as attachment.

There are no attachments in your message. I think you used email to reply and I guess github doesn't support attachments from emails

**Comment by lwouis** [comment] 2020-04-18 19:36
@Fischmuetze any update?

**Comment by lwouis** [comment] 2020-04-27 17:31
It seems the OP is not following up to help understand the issue they faced. I'm closing this ticket

**Closed by lwouis** 2020-04-27 17:31 UTC
Labels: unclear, unreproducible
