### ISSUE TITLE
Show standard tabs as windows does not turn off

### ISSUE THREAD

**Issue by ishaanrathodd** [lwouis/alt-tab-macos#2601] opened 2023-06-22 02:50 UTC
**Describe the bug**
I do not want to see all windows of a specific app in the switcher panel and for that, an option to turn off standard tabs as windows is given in the preferences of the app. But unfortunately, it does not work. All windows are still being shown

**Screenshots / video**

https://github.com/lwouis/alt-tab-macos/assets/90642857/12e39023-3198-4134-a089-daf513a1e532

**Your environment**

* AltTab version: version 6.58.0
* macOS version: Monteray 12.6.6

**Comment by lwouis** [comment] 2023-06-23 07:57
I just tested this scenario on my setup, and I wasn't able to reproduce the issue. It works correctly for me.

* AltTab version: 6.59.0
* macOS version: Ventura 13.4

**Comment by lwouis** [comment] 2023-06-23 14:31
Unfortunately, there is little chance to fix an issue which can't be reproduced. Other users don't seem to have the issue, and I can't reproduce the issue on my machine.

I don't know what could be happening on your system that's different. I tested this many times when I was still on Monterey, and it works correctly.

There are know issues with fullscreen windows and Spaces for instance (see #1324), but from your video, it's not what's going on.

I'm afraid without a way to reproduce, I can't do anything 🙇

**Comment by ishaanrathodd** [comment] 2023-06-23 17:36
Okay i’ll see to it, thanks for looking into it👍Sent from my iPhoneOn 23-Jun-2023, at 8:01 PM, lwouis ***@***.***> wrote:﻿
Unfortunately, there is little chance to fix an issue which can't be reproduced. Other users don't seem to have the issue, and I can't reproduce the issue on my machine.
I don't know what could be happening on your system that's different. I tested this many times when I was still on Monterey, and it works correctly.
There are know issues with fullscreen windows and Spaces for instance (see #1324), but from your video, it's not what's going on.
I'm afraid without a way to reproduce, I can't do anything 🙇

**Comment by jasondm007** [comment] 2023-06-30 19:13
@ishaanrathodd I've long had the same problem (re: tabs treated as windows). Live yourself, I'm running Monterey. I suspect it's related to the same issues noted here #2017

**Comment by lwouis** [comment] 2023-07-01 18:52
Thank you @jasondm007. This ticket is indeed the root cause. I'll close this ticket here as duplicate 👍

**Closed by lwouis** 2023-07-01 18:52 UTC
Labels: bug, unreproducible
