### ISSUE TITLE
Telegram not showing

### ISSUE THREAD

**Issue by elgirafo** [lwouis/alt-tab-macos#2092] opened 2022-11-08 08:06 UTC
**Describe the bug**

I installed the recent update, and my telegram thumbnail shows as if it is to open a new window of the app, I tried checking if something is wrong in the settings, but everything seems standard.

**Screenshots/video**

![Screenshot 2022-11-08 at 16 03 55](https://user-images.githubusercontent.com/80516439/200508837-3d03fe3c-ffa5-43d5-91ba-8236f7b32404.jpg)

**Comment by lwouis** [comment] 2022-11-08 08:13
Telegram is on another Space, right? This is most likely #1324

**Comment by elgirafo** [comment] 2022-11-08 08:51
hey @lwouis, it is all on the same desktop.

**Comment by lwouis** [comment] 2022-11-08 08:55
@elgirafo Can you please share a video showing every single step you take, including opening Telegram and opening AltTab?

Also what version of macOS do you have? Do you have all apps on the same Space or multiple? Do you fullscreen apps?

**Comment by elgirafo** [comment] 2022-11-08 10:05
here is a recording, I have macOS 13.0 venture, and I am using 1 desktop, no fullscreen apps.


https://user-images.githubusercontent.com/80516439/200535857-f5c9d2c9-a18d-4097-b651-161f1d0036db.mov

**Comment by lecodeski** [comment] 2022-11-08 15:11
same here issue here (preview missing) with:
- 6.49.0
- macOS Ventura (13.0)
- today released macOS Telegram (9.1.238857 from AppStore)
- fullscreeen apps
- multiple spaces
- multiple screens

**Comment by aquasov** [comment] 2022-11-08 15:53
same here:
- macos: 13.0 (22A380)
- telegram: 9.1.238859 Stable

**Comment by lwouis** [comment] 2022-11-08 17:58
I downloaded Telegram (non-MAS version), and was able to reproduce with the first window. Indeed it's not shown in AltTab.

I debugged, and Telegram doesn't return any window from the Accessibility API:

![image](https://user-images.githubusercontent.com/106195/200640085-d5404c08-be86-4449-8ef6-2889495e8cc5.png)

![image](https://user-images.githubusercontent.com/106195/200640111-a7fb9351-bb92-4ab7-9e0e-e3beed37d945.png)

Not only does Telegram not return windows from the AX call, but it doesn't trigger a `kAXWindowCreatedNotification` event.

I'm not sure what's wrong with Telegram, but it seems to be nothing AltTab can deal with. AltTab can only display what OS APIs tell it exist.

**Comment by lecodeski** [comment] 2022-11-08 18:05
Thanks for the debugging! Is it okay to cross-post this issue in the app's repo?

**Comment by lwouis** [comment] 2022-11-08 20:08
XCode Accessibility Inspector is also not listing the window:

<img width="710" alt="image" src="https://user-images.githubusercontent.com/106195/200664549-36ba06c8-20ae-4972-ae90-0e5c5ced156c.png">

@lecodeski yes, please share the data with them. It's definitely an issue on their side. It must affect other accessibility apps like screen readers. I'll close this as there is no action on AltTab's side.

**Closed by lwouis** 2022-11-08 20:08 UTC
Labels: bug

**Comment by lwouis** [comment] 2022-11-08 20:21
Interestingly, it's the same symptoms as https://github.com/lwouis/alt-tab-macos/issues/481#issuecomment-679234953.

I think these apps override some core event-sending methods, which prevents windows from listing from an accessibility standpoint.

**Comment by pasquale95** [comment] 2022-11-09 08:45
Opened the issue on Telegram Desktop repo.

**Comment by stingusss** [comment] 2022-11-12 21:14
I suffer from this as well. Hope it gets fixed soon.

**Comment by lwouis** [comment] 2022-11-12 23:49
@stingusss please post on the Telegram ticket linked above, not here. AltTab is unrelated to the issue.

**Comment by stingusss** [comment] 2022-11-13 11:29
@lwouis Yep, I understand that it's not AltTab's problem. I made a post on the Telegram ticket you mentioned.
BTW, I'd like to use the opportunity and say thank you for developing and supporting such a great app. You're amazing!

**Comment by stingusss** [comment] 2022-11-19 17:18
I'm happy to report that Telegram team has fixed this problem in the beta Version 9.1 (239780)
from Nov 18, 2022 at 21:11!

**Comment by bellerofonte** [comment] 2022-12-09 09:25
Just discovered that the latest (at 12 Dec 22) AppStore's version on Telegram (9.1.xxx) has this issue, but Telegram's website version (9.2.xxx) hasn't.

**Comment by change-agent** [comment] 2023-02-24 00:44
> Just discovered that the latest (at 12 Dec 22) AppStore's version on Telegram (9.1.xxx) has this issue, but Telegram's website version (9.2.xxx) hasn't.

Yes, thank you! This issue still occurs in the latest version of the Mac App Store build ("9.4"), but downloading the website build (9.4.243050 Stable) fixed it for me.
