### ISSUE TITLE
Add option to keep the order of windows upon switching

### ISSUE THREAD

**Issue by XInTheDark** [lwouis/alt-tab-macos#1805] opened 2022-07-22 10:21 UTC
Right now, the order of the windows change after I switch to another window, and this can be very confusing/time-wasting, especially when I select windows with mouse hover. If I do not look carefully at the order of windows, it is likely that I will be directed to the wrong window.

What I am suggesting is basically an option to retain the order of windows upon switching;

For example, if I am currently focused on `Window 1`, the current order is `Window 1, Window 2, Window 3`.
Upon switching to `Window 2`, the default (and current) behaviour would be to change the order to `Window 2, Window 1, Window 3`; hence always keeping the current window at the first position of the tab switcher.

While there is nothing wrong with this, I would prefer that the order does not change (upon switching to `Window 2`, the order is _still_ `Window 1, Window 2, Window 3`.

I wonder if an option could be added for this in preferences. Thanks.

**Comment by lwouis** [comment] 2022-07-22 10:46
Duplicate of #515 #378

**Closed by lwouis** 2022-07-22 10:46 UTC
Labels: enhancement
