### ISSUE TITLE
On Sequoia beta 3 (Mac os 15.0), it keeps says screen recording is not allowed even it's allowed , and don't have popup like before

### ISSUE THREAD

**Issue by hyungchulc** [lwouis/alt-tab-macos#3477] opened 2024-07-10 18:23 UTC
**Describe the bug**

On Sequoia beta 3 (Mac Os 15.0), it keeps says screen recording is not allowed even it's allowed , and don't have popup like before, which asks if I want to keep give the permission.

**Screenshots / video**

![Screenshot 2024-07-11 at 03 21 59 AM@2x](https://github.com/lwouis/alt-tab-macos/assets/64293163/194dd77a-d207-4df4-a94d-ff3dcfd64df5)

**Steps to reproduce the bug**

1. Open AltTab in beta 3
2. Doesn't work

**Your environment**

* AltTab version: Latest, 6.71.0
* macOS version: 15.0

**Comment by falchion10** [comment] 2024-07-10 18:30
Having this issue as well. Just updated to 15.0 Developer Beta 3

**Comment by UnknownCrafts** [comment] 2024-07-10 19:13
I would like to confirm this issue and also give a workaround. Unfortunately the workaround does not persist during restarts but it is still better than being able to use AltTab, ofc you can redo the steps after each restart.

Workaround:

https://github.com/lwouis/alt-tab-macos/assets/65975222/2808010e-d600-4f00-be03-82b080629368

**Comment by UnknownCrafts** [comment] 2024-07-10 19:40
> > Edit: just for extra clarification I am also on MacOS 15 dev beta 3
> > I would like to confirm this issue and also give a workaround. Unfortunately the workaround does not persist during restarts but it is still better than not being able to use AltTab, ofc you can redo the steps after each restart.
> > Workaround:
> > video.mp4
> 
> Removing + adding back didn't fix it for me. I had to add it without removing it and it fixed itself. Seems more like a MacOS issue though

I will add that as an alternative to the original comment.

**Comment by Ethansev** [comment] 2024-07-11 00:56
> > Edit: just for extra clarification I am also on MacOS 15 dev beta 3
> > I would like to confirm this issue and also give a workaround. Unfortunately the workaround does not persist during restarts but it is still better than not being able to use AltTab, ofc you can redo the steps after each restart.
> > Workaround:
> > video.mp4
> 
> Removing + adding back didn't fix it for me. I had to add it without removing it and it fixed itself. Seems more like a MacOS issue though

Not working for me unfortunately but worth a shot. I'll play with it a bit and see what I can do. Also on MacOS 15 dev beta 3.

**Comment by hyungchulc** [comment] 2024-07-11 03:11
Made it work with just clicking "Later" in the pop-up...!!

**Comment by andogq** [comment] 2024-07-11 03:18
This worked for me too! Remove AltTab from the list in Screen & System Audio Recording, and close the AltTab warning window. Re-open AltTab, and follow the prompts to give it screen recording permissions in settings. When it says that the program must be quit and re-opened, then click Later and it will work.

**Comment by UnknownCrafts** [comment] 2024-07-11 03:21
> Made it work with just clicking "Later" in the pop-up...!!

I was afraid that people would not be able to see the options due to the video compression, but in the video I am clicking the "Later" option instead of "quit and restart"

I will add a disclaimer in my original comment.

**Comment by tiankaima** [comment] 2024-07-11 03:52
Reinstalling with Homebrew fixed this for me. Another macOS beta issue I‘m afraid, the upgrade process might break stuff.

```sh
brew uninstall --cask alt-tab
brew install --cask alt-tab
```

**Comment by jhaemin** [comment] 2024-07-11 05:47
> This worked for me too! Remove AltTab from the list in Screen & System Audio Recording, and close the AltTab warning window. Re-open AltTab, and follow the prompts to give it screen recording permissions in settings. When it says that the program must be quit and re-opened, then click Later and it will work.

@andogq It works. Thanks.

**Comment by BossscoLeung** [comment] 2024-07-11 09:29
> Workaround:
> 
> NOTE: Please click the "Later" option instead of "quit and restart", this might not be obvious in the video due to compression.

@UnknownCrafts Thanks for the temporarily workaround, it works!

**Comment by Anastandstealb** [comment] 2024-07-11 14:09
I also am facing the same issue and later is not working for me

**Comment by judge2020** [comment] 2024-07-11 16:13
andogq's suggestion is what worked for me.

**Comment by lwouis** [comment] 2024-07-11 21:57
Related: https://github.com/lwouis/alt-tab-macos/issues/3427

**Comment by XicoMontalvao** [comment] 2024-07-12 18:58
Here I have already tested everything that was said above and it did not work again, neither this nor the Shottr

**Comment by pauldvu** [comment] 2024-07-12 21:50
Okay, so I think I kind of figured out why the workaround may not be working for some people. Let me go ahead and share with you some things you can try.


Okay, so the first thing you want to do is reset the consent control prompts, which is different from resetting the privacy and security entry. Rather, ensure that you reset the entire consent prompt.

```zsh
tccutil reset ScreenCapture com.lwouis.alt-tab-macos && 
tccutil reset Microphone com.lwouis.alt-tab-macos && 
tccutil reset Camera com.lwouis.alt-tab-macos && 
tccutil reset Accessibility com.lwouis.alt-tab-macos
```
 
 
 This is important because it will allow you to see the prompts again in order to do the next steps.
 
 
 
<img width="1261" alt="image" src="https://github.com/user-attachments/assets/c66dbe16-c76b-45cc-86a1-00f9c2616cce">
Okay, here. You want to go ahead and open system settings and then add it.
 
![image](https://github.com/user-attachments/assets/bc771001-cf6b-4b34-a690-39103c7e7389)

Okay. It's at this point, where this is the checkpoint. You want to make sure that you see the screen recording? It's green and set to allowed.


<img width="1160" alt="image" src="https://github.com/user-attachments/assets/706ff8a6-f517-438a-933d-78316daa46d9">

Okay. And then after that, you want to go ahead and press, later.


Lastly, you simply want to do that for accessibility.




What's important to note is that you want to make sure. That. You're seeing both go green, essentially. When you're hitting the later button, so you have to reset. your control cassette props hope it helps

**Comment by UnknownCrafts** [comment] 2024-07-12 22:10
> Okay, so I think I kind of figured out why the workaround may not be working for some people. Let me go ahead and share with you some things you can try.
> 
> Okay, so the first thing you want to do is reset the consent control prompts, which is different from resetting the privacy and security entry. Rather, ensure that you reset the entire consent prompt.
> 
> ```shell
> tccutil reset ScreenCapture com.lwouis.alt-tab-macos && 
> tccutil reset Microphone com.lwouis.alt-tab-macos && 
> tccutil reset Camera com.lwouis.alt-tab-macos && 
> tccutil reset Accessibility com.lwouis.alt-tab-macos
> ```
> 
> This is important because it will allow you to see the prompts again in order to do the next steps.
> 
> <img alt="image" width="1261" src="https://private-user-images.githubusercontent.com/93230643/348403212-c66dbe16-c76b-45cc-86a1-00f9c2616cce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA4MjIzNjYsIm5iZiI6MTcyMDgyMjA2NiwicGF0aCI6Ii85MzIzMDY0My8zNDg0MDMyMTItYzY2ZGJlMTYtYzc2Yi00NWNjLTg2YTEtMDBmOWMyNjE2Y2NlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEyVDIyMDc0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdhNGRhYWRhMzg2YWJhYThkYmVjYmM1OTNkYTI3YTE4NjFhM2U2YWI2OGNmNmQyZTZjNzg3OGMwYTIwYzkyMDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mVKxxPjSwMK3DteQjZnvXMu85-RoEzBJLbWhjtWTFJ0"> Okay, here. You want to go ahead and open system settings and then add it.
> ![image](https://private-user-images.githubusercontent.com/93230643/348403761-bc771001-cf6b-4b34-a690-39103c7e7389.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA4MjIzNjYsIm5iZiI6MTcyMDgyMjA2NiwicGF0aCI6Ii85MzIzMDY0My8zNDg0MDM3NjEtYmM3NzEwMDEtY2Y2Yi00YjM0LWE2OTAtMzkxMDNjN2U3Mzg5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEyVDIyMDc0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFjMzUzZTBiMDJmNWY4NDA4ZmNmMzgwNGY4ZGY3NWY2MjQ0ZjA2Yjc4ODBhMTBiOTFiZTU5NjYzMDFmNzcwODImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.A3sAv07xG-Kml4aeLP_fLm5YgKvFAJOticDnhqiNc1A)
> 
> Okay. It's at this point, where this is the checkpoint. You want to make sure that you see the screen recording? It's green and set to allowed.
> 
> <img alt="image" width="1160" src="https://private-user-images.githubusercontent.com/93230643/348403916-706ff8a6-f517-438a-933d-78316daa46d9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA4MjIzNjYsIm5iZiI6MTcyMDgyMjA2NiwicGF0aCI6Ii85MzIzMDY0My8zNDg0MDM5MTYtNzA2ZmY4YTYtZjUxNy00MzhhLTkzM2QtNzgzMTZkYWE0NmQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEyVDIyMDc0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlM2YyY2ZmMDQyZThkNWE2YjRiN2YwZjdjZTU3NDE1OGUzMTY5NDc2YWNkNjc5YjdhMzM1NDg1NzlhMTllMDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3jvIcGTTPAxO2Yk_vkB_pv_vbGF0Z40l0pcd7eBEZFM">
> Okay. And then after that, you want to go ahead and press, later.
> 
> Lastly, you simply want to do that for accessibility.
> 
> What's important to note is that you want to make sure. That. You're seeing both go green, essentially. When you're hitting the later button, so you have to reset. your control cassette props hope it helps

This works perfectly.

**Comment by XicoMontalvao** [comment] 2024-07-12 23:13
![Captura de Tela 2024-07-12 às 20 13 00](https://github.com/user-attachments/assets/625c67ab-cf98-4fb9-b507-e258f2583c92)
 not

**Comment by UnknownCrafts** [comment] 2024-07-12 23:23
> ![Captura de Tela 2024-07-12 às 20 13 00](https://github.com/user-attachments/assets/625c67ab-cf98-4fb9-b507-e258f2583c92)
>  not
> 

Just give the accessibility permission again by clicking the button and then it should work perfectly

**Comment by YousufSSyed** [comment] 2024-07-13 17:06
Having this issue as well

**Comment by IsaacBraydon** [comment] 2024-07-13 18:19
> > Edit: just for extra clarification I am also on MacOS 15 dev beta 3
> > I would like to confirm this issue and also give a workaround. Unfortunately the workaround does not persist during restarts but it is still better than not being able to use AltTab, ofc you can redo the steps after each restart.
> > Workaround:
> > video.mp4
> 
> Removing + adding back didn't fix it for me. I had to add it without removing it and it fixed itself. Seems more like a MacOS issue though

You can try these steps:
1. Run AltTab until it showed permission is required.
2. Switch to the permission settings and disable AltTab's permission that you're troubling with. (Use 'Later' instead of 'Restart&Reopen', and do not remove it from the list right now).
3. Use Command+Q close AltTab.
4. Reopen AltTab manually after confirmed AltTab's permission is disabled & not removed from the permission list.
5. AltTab would still require permission at this run.
6. REMOVE AltTab's permission from the list & add AltTab again to the list & grant the permission.
7. AltTab can be used during this login session but you might do it again after restart.
* Seems like something wrong with Sequoia's permission management system while updated to Beta 3. Apple might repair this after next update.

**Comment by engageintellect** [comment] 2024-07-13 21:09
+1 😢

**Comment by HTA86** [comment] 2024-07-14 09:19
> **Ignore my instructions, please check this:** [#3477 (comment)](https://github.com/lwouis/alt-tab-macos/issues/3477#issuecomment-2226400338)
> 
> Edit: just for extra clarification I am also on MacOS 15 dev beta 3
> 
> I would like to confirm this issue and also give a workaround. Unfortunately the workaround does not persist during restarts but it is still better than not being able to use AltTab, ofc you can redo the steps after each restart.
> 
> Workaround:
> 
> NOTE: Please click the "Later" option instead of "quit and restart", this might not be obvious in the video due to compression.
> 
>  video.mp4 
> 
> Edit: If the workaround does not work then, add AltTab without removing it in the privacy and security settings.

Thank you for sharing the workaround! I can confirm that I am also experiencing the same issue on macOS 15.0 Beta 3. The suggested workaround works for me.

**Comment by hahayupgit** [comment] 2024-07-15 01:54
> This worked for me too! Remove AltTab from the list in Screen & System Audio Recording, and close the AltTab warning window. Re-open AltTab, and follow the prompts to give it screen recording permissions in settings. When it says that the program must be quit and re-opened, then click Later and it will work.

+1 had this same issue and this worked! Thank you!

**Comment by Bleushift** [comment] 2024-07-17 03:44
Same issue here. Updated to later Beta on Mac. Unfortunately, none of the suggestions here have worked.

**Comment by XicoMontalvao** [comment] 2024-07-17 22:19
Same issue here. Updated to later Beta on Mac. Unfortunately, none of the suggestions here have worked.

**Comment by IZKEER** [comment] 2024-07-18 16:17
> This worked for me too! Remove AltTab from the list in Screen & System Audio Recording, and close the AltTab warning window. Re-open AltTab, and follow the prompts to give it screen recording permissions in settings. When it says that the program must be quit and re-opened, then click Later and it will work.

worked, cheers

**Comment by castdrian** [comment] 2024-07-19 08:29
to fix this with most screenshot applications, take a full screen screenshot and then it'll work until reboot

**Comment by todd-gallant** [comment] 2024-07-19 13:31
its not just alt-tab, other apps are doing the same thing, like Displaylink Manager..

**Comment by lwouis** [comment] 2024-07-19 13:56
I'm guessing that the root cause of this issue is the way AltTab checks if the permission is granted.

AltTab doesn't use the official API for this. Instead it uses a workaround that consist in making a call to another API, and seeing if we get a result. If we don't, we assume that the permission is not granted. If we do, we assume that it is granted.

The reason we use this workaround instead of the official API is that the official API has a big downside: when you call it, it returns how the permission was **at the time when AltTab was launched**, not at the time we are calling to ask. This means that we know the permission state when AltTab was launched. If it's changed after that, we have no idea.

This made the onboarding experience as it is today in the app impossible. Indeed, the first time, we ask the user to provide permissions. Of course at this point the permissions are not granted since it's the first launch. The user then grants it. At this point, we would have no way to confirm that they granted it since the official API would return `false` until AltTab is restarted.

We wanted a good UX, so we implemented the workaround I mentioned. It's possible that Apple messed with the API used in the workaround in this Beta, which would break it. I don't see why they would update it, or how they could do it without breaking the API functionality, but maybe they did.

[More specifics in this PR](https://github.com/lwouis/alt-tab-macos/pull/3497).

Again, this is my guess. I don't have a machine with the Beta to debug things. As usual, I plan on waiting for the Beta to finish, and the release to be made public and official. Only then, we will know if we have things to fix or not. It's usual of Apple to fix things before the end of betas. It has happened for the last 2 betas for instance. So from my perspective, we shouldn't rush hotfixes or what not. Let's wait for something stable. These betas are moving targets.

**Comment by eachann1024** [comment] 2024-07-22 05:25
> I'm guessing that the root cause of this issue is the way AltTab checks if the permission is granted.
> 
> AltTab doesn't use the official API for this. Instead it uses a workaround that consist in making a call to another API, and seeing if we get a result. If we don't, we assume that the permission is not granted. If we do, we assume that it is granted.
> 
> The reason we use this workaround instead of the official API is that the official API has a big downside: when you call it, it returns how the permission was **at the time when AltTab was launched**, not at the time we are calling to ask. This means that we know the permission state when AltTab was launched. If it's changed after that, we have no idea.
> 
> This made the onboarding experience as it is today in the app impossible. Indeed, the first time, we ask the user to provide permissions. Of course at this point the permissions are not granted since it's the first launch. The user then grants it. At this point, we would have no way to confirm that they granted it since the official API would return `false` until AltTab is restarted.
> 
> We wanted a good UX, so we implemented the workaround I mentioned. It's possible that Apple messed with the API used in the workaround in this Beta, which would break it. I don't see why they would update it, or how they could do it without breaking the API functionality, but maybe they did.
> 
> [More specifics in this PR](https://github.com/lwouis/alt-tab-macos/pull/3497).
> 
> Again, this is my guess. I don't have a machine with the Beta to debug things. As usual, I plan on waiting for the Beta to finish, and the release to be made public and official. Only then, we will know if we have things to fix or not. It's usual of Apple to fix things before the end of betas. It has happened for the last 2 betas for instance. So from my perspective, we shouldn't rush hotfixes or what not. Let's wait for something stable. These betas are moving targets.

Every time Apple releases a major update, it challenges the rules of the old version.

**Comment by DominicVonk** [comment] 2024-07-23 22:35
The issue is fixed with beta 4

**Comment by UnknownCrafts** [comment] 2024-07-23 23:05
> The issue is fixed with beta 4, remove all old permissions and quit the app. And allow them again. It keeps them preserved between reboots now.

Time to go back to dev beta from public beta, at least it's only 2.88gb

**Comment by jhaemin** [comment] 2024-07-24 03:09
Confirmed it is fixed in Beta 4.

**Comment by jhaemin** [comment] 2024-07-24 08:52
@dexxa05 Preview is working fine for me.

**Comment by dexxa05** [comment] 2024-07-24 12:07
> @dexxa05 Preview is working fine for me.

Yes you right everything is working properly :)

**Comment by dew912** [comment] 2024-07-25 23:45
Any luck with Public Beta 2?

**Comment by Imolos** [comment] 2024-07-26 07:26
> Any luck with Public Beta 2?

Just Installed Beta 2 on my Mac Studio with M1 Max
And after reboot system asked me if I still want to allow usage of screen recording.
It starts working
I try also just quit the app and launch it again and the permisions are still allowed
So I guess for some this could work
Mileage may vary

**Comment by ThomasWaldmann** [comment] 2024-07-30 09:38
https://github.com/lwouis/alt-tab-macos/issues/3477#issuecomment-2226400338 <- this only worked for me after changing the binary to `/usr/bin/tccutil`.

Otherwise I only got some "Usage: ..." output.

**Comment by Larsen2k4** [comment] 2024-08-05 22:11
A little update with Sequoia Beta 5: Apple finally eased the constant nagging on permissions by allowing access for one week before asking again.

**Comment by danielskowronski** [comment] 2024-08-16 22:44
This still happens on macOS 15.0 beta 6 (`624A5320a`) and I have an open FB ticket with them since early July. The issue is both with AltTab spamming macOS API with requests and macOS allowing message storm to annoy users by running any executable calling that API.

Even with the latest change from Apple that introduces 1 month whitelist option, AltTab triggers the same pattern (it doesn't start showing just after AltTab gets launched on login, rather when the computer is in Power Nap or just left with the screen turned off):

![AltTab](https://github.com/user-attachments/assets/fe072c14-15c1-4dea-88ee-4574812c745b)

Anyone who's using macOS Beta should file a feedback ticket with Apple so they get enough system diagnostics to figure out what's allowing this behaviour.

**Comment by Larsen2k4** [comment] 2024-08-16 22:49
Not happening here on Sequoia Beta 6 (PowerNap turned off) - AltTab requests have been completely silent for me after the first allowance.

**Comment by danielskowronski** [comment] 2024-08-18 13:41
After two days, I can confirm that issue seems to be gone `after the first allowance`. 

I have AltTab installed since Sonoma, so it seems that on Sequoia Beta 6 the problem lies only with AltTab being persistent in requesting permission it partially had been granted (and macOS allowing it to annoy user).

**Comment by ejbills** [comment] 2024-09-09 19:58
> I'm guessing that the root cause of this issue is the way AltTab checks if the permission is granted.
> 
> AltTab doesn't use the official API for this. Instead it uses a workaround that consist in making a call to another API, and seeing if we get a result. If we don't, we assume that the permission is not granted. If we do, we assume that it is granted.

Hi there @lwouis, DockDoor has a similar permissions page which works on macOS 15 Sequoia without issues
<img width="630" alt="Screenshot 2024-09-09 at 12 56 50 PM" src="https://github.com/user-attachments/assets/b981c85f-d3ca-4bd2-8027-9256645335ef">
.

Feel free to port the logic to AltTab:
Observable object: https://github.com/ejbills/DockDoor/blob/539ef09e72e0ff24b2bf722704b84523bc4d1f08/DockDoor/Components/PermissionsView/PermissionsChecker.swift#L4
Used in a view: https://github.com/ejbills/DockDoor/blob/539ef09e72e0ff24b2bf722704b84523bc4d1f08/DockDoor/Components/PermissionsView/PermissionsView.swift#L6

Hope this helps. 👍

**Comment by lwouis** [comment] 2024-09-09 20:27
Hi @ejbills,

Thank you for sharing your implementation to help us!

I think we use the same exact implementation. In other words, I think yours will suffer from the same problems:

* Sequoia issues from this thread
* https://github.com/lwouis/alt-tab-macos/issues/3253

Thank you 🙇

**Comment by ejbills** [comment] 2024-09-09 22:47
> I think we use the same exact implementation. In other words, I think yours will suffer from the same problems:

Oh man... thanks for the heads up! hahaha

**Comment by lwouis** [comment] 2024-09-19 13:11
I've updated to Sequoia today, and on first login was greeted with the new dialog:

<img width="372" alt="image" src="https://github.com/user-attachments/assets/dd92a068-5ce2-44eb-bd9a-68dc00b1e507">

**Comment by lwouis** [comment] 2024-09-19 14:03
I see that Snagit has the same issue They [posted this 3 days ago](https://support.techsmith.com/hc/en-us/articles/30302332343693-Snagithelper-2024-Is-Requesting-to-Bypass-the-System-Private-Window-Picker-and-Directly-Access-Your-Screen-and-Audio).

**Comment by lwouis** [comment] 2024-09-19 14:59
Indeed, I got it with Google Chrome doing window sharing with Google Meet.

I'll close this ticket as the beta is over, and it's just now the way things are on macOS. Nothing we can do about it on our side. Apple decides the UX.

**Comment by danielskowronski** [comment] 2024-10-09 10:08
@lwouis so do I get it right that no changes to address this were made between 6.72.0 and 6.73.0 ? I've missed the update of AltTab, but macOS is on latest version - Sequoia 15.1 Beta (24B5070a). Overnight the below happened:

![image](https://github.com/user-attachments/assets/fd90a58d-70b7-44fd-835e-aecf6ab7f655)

I'll bump AltTab, leave the system the same way and let you know if anything changed. I still treat this as issue in both macOS which allows spam (FB ticket is still open_ and AltTab, because of the way how it requests permissions. I have other software which uses the same APIs, and it's able to recognize that consent wasn't given, so it does not re-request it until user goes to system settings and grants it.

**Comment by lwouis** [comment] 2024-10-09 20:01
Hi @danielskowronski 

Sorry to hear you're facing this issue. I can confirm that v6.73.0 didn't do anything about this. As I mentioned when I closed this issue, it's the new macOS UX. Nothing our app can do about it.

Your screenshot looks pretty crazy. There shouldn't be anything AltTab can do to cause this. Thus I think it's a bug in the Beta you're on. I'm on the public release of Sequoia 15.0 and I've never seen this with any app. All apps now ask this dialog, but only once.

> I have other software which uses the same APIs, and it's able to recognize that consent wasn't given, so it does not re-request it until user goes to system settings and grants it.

AltTab is not requested consent. It's not asking for this dialog to show up. MacOS is doing that on their own. AltTab asks permission initially to access. Once you grant permissions, it just does its job. MacOs added its own layer on top of that, and pops its own dialog without AltTab asking for anything. We can't control when it pops and how many dialogs. That's purely on macOS side, unfortunately.

Thank you

**Comment by danielskowronski** [comment] 2024-10-09 20:25
That starts to be an interesting case - it only shows when I'm away from machine and never when I actually trigger AltTab by keyboard. Could you please point me to the line in code which should be triggering this behaviour? It's either some background loop in AltTab or macOS runs periodic checks and triggers this warning.

Maybe it's something about app manifest or package signature? I have bunch of other apps that are actively using "Screen & System Audio Recording" APIs and so far, those requests show only for AltTab (although I'm not sure when I started using AltTab - there's a chance it was on early days of Sequoia and something got stuck in a weird way; BTW - already tried to remove AltTab from settings and re-adding it). 

For reference, here are other apps from the same category on my machine - Alfred 5, Bartender, CleanShot X, DDPM, Chrome, Logitech G HUB, PixelSnap, Step Two and TeamViewer Host. 

Looking at the latest release notes (https://developer.apple.com/documentation/macos-release-notes/macos-15_1-release-notes#New-Features) it seems like maybe macOS thinks I don't use AltTab often so that's why it shows warning randomly. But to confirm that, someone would need to compile an app that requests ScreenCaptureKit normally and then never does anything with it...

**Comment by lwouis** [comment] 2024-10-09 20:59
AltTab takes screenshot of the window anytime it gets notified by macOS that a window was changed. For example, when a window is resized, minimized, title changes, etc. It's not on a timer. It's when a window thumbnail should be refreshed.

**Comment by danielskowronski** [comment] 2024-10-10 10:44
I left my system with VM running overnight and both host (with 7.0.0) and VM (with 6.73.0) experienced the issue yet again, but this time I have crucial hint why system prompt is show for AltTab while it's supposed to be idle in background. It's crashing and forking hard - when I came back, there were 20-30 instances of `AltTab.app` running and closing system prompt spawned more.

![image](https://github.com/user-attachments/assets/dfe5ebc1-e39e-4eec-aa7f-ce8f23ed0f30)

Both permissions were "green" before it started crashing and are after restarting app, so it looks like after crash, new instance is not recognized by macOS TCC as legitimate one.

It can be easily reproduced by running VM (I used [VirtualBuddy](https://github.com/insidegui/VirtualBuddy) with macOS 15.1 beta 6 and having just AltTab left running for several hours. My host has normal PowerNap settings, but I can rerun this with something in background that would keep it awake.

https://github.com/lwouis/alt-tab-macos/issues/3653 seems to describe similar behaviour in 7.0.0 specifically

**Comment by lwouis** [comment] 2024-10-10 13:49
Hey @danielskowronski,

Thank you for the exhaustive report. It's very useful!

I'm surprised to see all these instances. We have a ticket about multiple instances #1840, however it's for 2-3 instances, when the user inadvertently sets up multiple Login Items for AltTab for instance. It's not AltTab opening itself.

The way AltTab can open itself does exist. It will open a new instance of the same app (same location), then terminate the current instance. You can see implementation here: https://github.com/lwouis/alt-tab-macos/blob/8abb9b435899f6767243f3ba0116fc01e1defe0b/src/ui/App.swift#L117

When does this happen and why? It happen generally when AltTab has already validated that macOS permissions are granted, then somehow it seems to lose these permissions. This can happen for instance if the user grants permissions, uses AltTab for a while, then decide to remove permissions while AltTab is still open. If that happens, AltTab will restart, and show the permissions screen to let the user know that permissions are required to operate.

Looking at the implementation again, I'm confused how there could be multiple instances. The code clearly creates a new instance, then immediately terminates.

I wonder if perhaps the [new macOS dialog](https://private-user-images.githubusercontent.com/106195/369003652-dd92a068-5ce2-44eb-bd9a-68dc00b1e507.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1Njc3NjksIm5iZiI6MTcyODU2NzQ2OSwicGF0aCI6Ii8xMDYxOTUvMzY5MDAzNjUyLWRkOTJhMDY4LTVjZTItNDRlYi1iZDlhLTY4ZGMwMGIxZTUwNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMFQxMzM3NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNWY2YWFlMThmMTI2MzQ4MmIzYWNkNmZlMDBlNDU5ODhkNTU1MDgwMWZkZTdkZDBiNGRlYTc0NmY2MTMzODFkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.YOF8n4EWNygY6FcgJ3HXzIPH5oWO8eyJAOOgCiX_6KI) prevents termination, if it's open? Maybe it pops up, then AltTab tries to restart, is blocked because this pop-up is open, and then the new instance has the same thing happen, etc?

I don't know how to test this, as the new dialog randomly appears. I don't know of a way to force it to happen.

**Comment by sinkr** [comment] 2024-10-23 02:33
Having the same issue on Sequoia and have tried everything above to no avail.  I get the permissions happy, then the app never loads again.

**Comment by lwouis** [comment] 2024-11-06 21:51
Hi,

This ticket has become too big, with too many different discussions happening inside.
Furthermore, the issues seem unactionable, and due to macOS.
Finally, they seem to only happen on Beta versions of macOS, which is Apple's responsibility to fix when they break things.

I'll close the ticket for now. Please open a new one if you face an issue on a stable macOS release 👍 

Thank you 🙇

**Closed by lwouis** 2024-11-06 21:51 UTC
Labels: bug, unactionable, macOS 15

**Comment by sinkr** [comment] 2024-11-06 21:58
I doubt this will change your mind and I am resolved to having lost the money paid for the license and the lesson learned therein, however I **am not on a beta** and I am unable to use Alt-Tab consistently across 3 MacBooks all running Sequoia 15.1.

**Comment by lwouis** [comment] 2024-11-06 22:36
> I am resolved to having lost the money paid for the license and the lesson learned therein

I'm don't understand. What are you refering to?

Your previous post indicates different symptoms than this thread. You seem to face https://github.com/lwouis/alt-tab-macos/issues/3819
