### ISSUE TITLE
` (Grave accent) Key not working when used in shortcut. 

### ISSUE THREAD

**Issue by apotenza92** [lwouis/alt-tab-macos#1377] opened 2022-02-12 03:00 UTC
Hi I'm on Monterey, all use of the ` key is not working for shortcuts using AltTab. Is this a known issue? For me the grave key is just typed with a weird underline, if I use alt-grave it looks like this:

<img width="8" alt="image" src="https://user-images.githubusercontent.com/53612685/153694115-919e5488-e8d0-44c9-a8ff-fbe92c790ef0.png">

The underlined part disappears when I press space bar. It's all very strange. I've tried uninstalling AltTab and clearing caches etc. No luck.

**Comment by lwouis** [comment] 2022-02-12 03:16
Could you please share a video of the issue? It's hard to tell from the little image.

Also could you please share:

* Photo of your physical keyboard
* Which language you have macOS in
* Does it happen with the internal keyboard (if you use external)? Does it happen if you plug another keyboard? Did it happen before Monterey?

Maybe related: #1278

**Comment by apotenza92** [comment] 2022-02-15 01:12
Hi, it's just a new 2021 M1 Pro MacBook Pro 14", using the normal laptop keyboard (I'm in Australia so it's a US keyboard). Hasn't had any other OS on it. Keyboard language is Australia however I've tried using it on US and the same issue happens.

**Comment by lwouis** [comment] 2022-02-17 09:27
It seems to be a duplicate of https://github.com/lwouis/alt-tab-macos/issues/1190

**Closed by lwouis** 2022-02-17 09:27 UTC
