### ISSUE TITLE
Apple Silicon build?

### ISSUE THREAD

**Issue by ngocphamm** [lwouis/alt-tab-macos#767] opened 2021-01-08 15:13 UTC
Do you think it'd be possible to have a native build of the app for Apple Silicon?

I have a new mac mini to test it if you want. Please let me know.

Thank you for making such a great app!

Best,
Ngoc

**Comment by lwouis** [comment] 2021-01-09 09:26
Another user said something similar on Discord:

> Just dropping by to thank @lwouis for the awesome app. Have been using with Apple Silicon for the past 3 weeks without any issues. I look forward to when the app will support arm natively!

I replied:

> Glad to hear this! I've no idea how the new arch impact the ecosystem. Is there some kind of universal app, or would we need to release 2 separate apps going forward? If you have a good link for what's involved, I'm interested. I may also interact and be combined with this issue: https://github.com/lwouis/alt-tab-macos/issues/158

**Comment by lwouis** [comment] 2021-01-09 09:29
I'm guessing that building a native Apple Silicon app is as easy as flipping a switch in XCode. The issues are around distribution. See the reason #158 is not already implemented. Many problems arise when we go from 1 universal release to multiple releases for multiple platforms.

I've interested in hearing proposals though

**Comment by ngocphamm** [comment] 2021-01-09 15:11
I honestly have no idea either as I don't do iOS/macOS dev. I was just curious if you know what it takes to have the universal build for this app. Currently, it's running just fine (so far) on the M1 I have. I was just thinking the universal build would probably somewhat faster, just like almost any other apps when they moved to support Apple Silicon natively.

**Comment by PolCPP** [comment] 2021-01-15 14:19
@lwouis Just got an m1 and tried to build locally. It compiles fine on my mbp 16 but the m1 seems to have linker problems on app center. 

```ld: warning: ignoring file /Users/polcpp/Downloads/alt-tab-macos-master-2/Pods/AppCenter/AppCenter-SDK-Apple/macOS/AppCenter.framework/AppCenter, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
ld: warning: ignoring file /Users/polcpp/Downloads/alt-tab-macos-master-2/Pods/AppCenter/AppCenter-SDK-Apple/macOS/AppCenterCrashes.framework/AppCenterCrashes, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
ld: warning: ignoring file /Users/polcpp/Downloads/alt-tab-macos-master-2/Pods/Sparkle/Sparkle.framework/Sparkle, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
```
Seems to be related to this (TLDR app center pod is not working, you need to get the framework as a GitHub asset, which I guess makes distribution harder)

https://github.com/microsoft/appcenter-sdk-apple/issues/2111

**Comment by lwouis** [comment] 2021-01-15 14:43
@PolCPP Have you seen [the PR](https://github.com/lwouis/alt-tab-macos/pull/771)? It bumps AppCenter's version to get support for ARM.

Note that other pods are not ready for ARM, thus blocking us from delivering a Universal App: https://github.com/lwouis/alt-tab-macos/pull/771#issuecomment-760973320

**Comment by PolCPP** [comment] 2021-01-19 17:21
``` 
% lipo -archs /Applications/AltTab.app/Contents/MacOS/AltTab
x86_64 arm64
```

**Comment by lwouis** [comment] 2021-01-20 00:32
Ok so it's universal. Normally when you build in Debug, it creates a native build. Another way to make sure is to change the Architecture setting in XCode, build again, comfirm with lipo that there is only arm and run 👍

**Comment by lwouis** [comment] 2021-03-21 11:05
Closing this as duplicate of https://github.com/lwouis/alt-tab-macos/pull/771. Let's keep the conversation there 👍

**Closed by lwouis** 2021-03-21 11:05 UTC
Labels: enhancement
