### ISSUE TITLE
Window selection sometimes automatically jump or scrolls.

### ISSUE THREAD

**Issue by Element9** [lwouis/alt-tab-macos#3466] opened 2024-07-05 09:51 UTC
**Describe the bug**

When the mouse cursor is where AltTab appears when triggered, it sometimes skips to the next window by itself. And sometimes it even starts scrolling through windows without any input from mouse and keyboard. I am not touching the mouse at all for this to happen. It just needs to be positioned in the "right" place. This never happens when mouse is not over AltTab.

**Screenshots / video**

https://github.com/lwouis/alt-tab-macos/assets/1780265/c39a5b43-ae23-4a10-b719-7a3cdb1c8da3

<img width="588" alt="Screenshot 2024-07-05 at 11 48 54" src="https://github.com/lwouis/alt-tab-macos/assets/1780265/b9a0a94d-7176-4686-b622-a90ca30b8d53">

<img width="1098" alt="Screenshot 2024-07-05 at 11 49 28" src="https://github.com/lwouis/alt-tab-macos/assets/1780265/7b292a8c-fb59-4ecb-9a7d-18b4f31d6cda">

**Steps to reproduce the bug**

1. Set up AltTab to be triggered with Command+Tab (for instance)
2. Position the mouse where AltTab will appear when triggered. I can't be 100% sure, but I think the position of the mouse is important, though I can't say how to position it exactly in order to reproduce the problem. I can't reproduce it every time, but it's pretty easy for me to reproduce after few tries.
3. Press Command+Tab, release Tab and keep holding Command

Expected: Next windows is selected
Observed: After a moment, the selection jumps to the next window or starts auto-scrolling through the windows before stopping again. Auto scrolling is what you can see in the attached video.

**Your environment**

* AltTab version: 6.70.1
* macOS version: 14.5
* Other relevant info: Using external keyboard and running Karabiner with only two rules.

**Comment by Element9** [comment] 2024-07-05 09:54
If it really is caused by mouse position, a potentially easy workaround that would work for me would be to have an option to completely disable mouse interactions with AltTab.

**Comment by iamkevindu** [comment] 2024-07-06 07:10
This app is fantastic and this is really the only "issue" I have with it. Issue is in air quotes because it is pretty rare that it happens (about once every 20 alt-tab's).

**Comment by Dimezis** [comment] 2024-07-06 08:41
I'm having the same issue occasionally.
AltTab might be working fine for a month and then just start doing this without a clear pattern.

**Comment by markkkkas** [comment] 2024-07-08 07:49
I have this issue as well and can't actually reproduce it constantly.

**Comment by stampycode** [comment] 2024-07-08 19:48
I'm having this issue nearly every time I use alt-tab, and it's very frustrating! I'm tempted to stop using it just because of this....
I wonder if it's because of system load? I'm a pretty heavy user and have a lot of stuff open, but it's not rendering thumbnails or anything....

**Comment by markkkkas** [comment] 2024-07-08 20:15
I've unchecked everything from here and it looks fine now
<img width="440" alt="image" src="https://github.com/lwouis/alt-tab-macos/assets/48568793/0f165543-da34-4a6e-b4aa-13123e4c23c6">

**Comment by lwouis** [comment] 2024-07-08 20:23
Duplicate of https://github.com/lwouis/alt-tab-macos/issues/3117

**Closed by lwouis** 2024-07-08 20:23 UTC
Labels: bug
