### ISSUE TITLE
altTab not cycling when inside a vscode editor

### ISSUE THREAD

**Issue by cpnvr** [lwouis/alt-tab-macos#992] opened 2021-06-11 20:18 UTC
**Describe the bug**

Ever since a recent update (not sure if vscode or altTab), I've noticed that altTab fails to cycle to and from vscode on a regular (but not entirely consistent) basis. I have never encountered this behavior before and was wondering if it's a known issue.

Note: the bug occurs whether or not extensions are disabled on vscode

Also interesting: while cycling from within vscode, if you go to another window, it will pop it to the front of the stack of windows from within that program but it still won't change to that application itself

**Screenshots / video**

https://www.loom.com/share/27bc61d2bcd94d3b8a49f78e82edfe62

**Steps to reproduce the bug**

1. Open vscode
2. altTab around to different programs for a bit. it will probably work at first
3. try writing some text and saving it, then alt-tab again
4. repeat 2 and 3 until behavior described in the bug is reproduced

**Comment by s0rl0v** [comment] 2021-06-12 08:37
I have encountered this too right after 1.57 vscode update. Dunno, maybe vscode team changed somthing.

**Comment by ipeluffo** [comment] 2021-06-12 11:32
In case it helps, here is the changelog of version 1.57

**Comment by HarriPinter** [comment] 2021-06-12 12:35
same here, I am facing the same when using Visual Studio Code. Other Apps are working (switching) fine, just from VSC it is not switching anymore.

**Comment by chunfeilung** [comment] 2021-06-12 15:08
[Could this be the cause](https://github.com/microsoft/vscode/issues/126025)?

**Comment by lwouis** [comment] 2021-06-13 03:13
Thanks @chunfeilung for sharing this ticket. I see an issue with yabai (a macOS window manager) on that issue, which makes me pretty confident this VSCode version introduced the bug from the OP.

It's a VSCode but which impacts many apps. Working around the issue in AltTab wouldn't fix the other impacted apps, so it's not very satisfying.

I advise people to downgrade VSCode until they release a new version which reverts their changes. See the ticket linked above for more details

**Comment by alk-sdavid** [comment] 2021-06-14 14:10
Hello 👋 there is an issue talking about this on vscode repo here: https://github.com/microsoft/vscode/issues/126013

**Comment by rbajaj1997** [comment] 2021-06-14 14:54
vscode team is aware of this issue and it is related to electron. I had raised the exact same [issue](https://github.com/microsoft/vscode/issues/126005) 2 days back.

**Comment by simondemeule** [comment] 2021-06-14 14:54
This bug also occurs using [Contexts](https://contexts.co/). Downgrading to 1.56.2 avoids this issue. Workflow-wise, the current release is a massive headache to use.

**Comment by AgilentGCMS** [comment] 2021-06-15 16:06
I have this issue too.

**Comment by alk-sdavid** [comment] 2021-06-18 07:52
Issue fixed in vscode v1.57.1 👍

**Comment by gquittet** [comment] 2021-06-18 15:26
Perfect, we can't close this issue ! 🥳 

As I said here: https://github.com/lwouis/alt-tab-macos/issues/992#issuecomment-863321748

Nothing related to AltTab but only related to VSCode 👍

**Closed** 2021-06-18 18:01 UTC
Labels: Support/Question, bug
