### ISSUE TITLE
macOS 10 Catalina how to use version

### ISSUE THREAD

**Issue by kythuatwebso** [lwouis/alt-tab-macos#3107] opened 2024-01-15 01:56 UTC
Hi guys,

I am using macOS Catalina (v10.15) , i am try some latest version but not working.
So which version should I use to make it work?

Thank you

**Comment by lwouis** [comment] 2024-01-15 07:32
Hi,

The latest version should run on Catalina.

Exactly how does it not work? What happens when you open the app?

Thank you

**Comment by kythuatwebso** [comment] 2024-01-15 07:34
Hi,

Status is:
The app can still be installed but it doesn't work as expected. "minimized" or "windowless" applications that are not hidden from "cmd + tab" still show full applications, not as neat as default

Thanks !

**Comment by lwouis** [comment] 2024-01-15 07:57
Have you set the right preferences in Preferences > Controls to hide minimized windows and Preferences > Appearance to hide windowless apps?

Thank you

**Comment by kythuatwebso** [comment] 2024-01-15 08:00
> Have you set the right preferences in Preferences > Controls to hide minimized windows and Preferences > Appearance to hide windowless apps?
> 
> Thank you

Yes, I am setting same, but not working.
A while ago used on macOS Ventura working ok,

Thanks !

**Comment by lwouis** [comment] 2024-01-15 08:03
I'm afraid i can't reproduce on my side since i don't have a mac on Catalina, and old VMs don't work with M2 macs.

I find it surprising that this functionality would break on older releases. It hasn't been updated in a long time. Also for windowless apps, it's pretty stable code, unlike some other OS-dependent tricks.

Could you please share a video of the issue?

Thank you

**Comment by kythuatwebso** [comment] 2024-01-15 08:10
> I'm afraid i can't reproduce on my side since i don't have a mac on Catalina, and old VMs don't work with M2 macs.
> 
> I find it surprising that this functionality would break on older releases. It hasn't been updated in a long time. Also for windowless apps, it's pretty stable code, unlike some other OS-dependent tricks.
> 
> Could you please share a video of the issue?
> 
> Thank you

Hi, 

This is Video: https://youtu.be/1eGIuWKe5BY

**Comment by lwouis** [comment] 2024-01-15 09:02
On your video, i see that you're not using AltTab. You're using the default app switcher from macOS.

By default, AltTab is trigger with alt+tab. You can see it on the video actually.

You can either use alt+tab, or you can remap to command+tab in Preferences > Controls, if you want to replace the built-in switcher.

I'll close the issue as it was not a bug in the end 👍

**Closed by lwouis** 2024-01-15 09:02 UTC

**Comment by kythuatwebso** [comment] 2024-01-15 09:25
Oh, 
just like you said

Sorry for this mistake 😓
