### ISSUE TITLE
Allow up and down arrows

### ISSUE THREAD

**Issue by mbikovitsky** [lwouis/alt-tab-macos#64] opened 2019-10-29 08:38 UTC
Similar to #53, but this time allow the up and down arrow keys to move between rows. Currently these keys are sent to the application that was last active.

**Comment by lwouis** [comment] 2019-10-29 09:49
This is significantly harder than left/right as it involves understanding what is up and down visually and the complex `NSCollectionView` that I customized with `CollectionViewCenterFlowLayout`.
`
Also, I'm thinking about maybe using the arrow keys for #9

**Comment by lwouis** [comment] 2020-04-23 19:26
Closing as duplicate of #270

**Closed by lwouis** 2020-04-23 19:26 UTC
Labels: duplicate, enhancement
