### ISSUE TITLE
App is not responsive when JetBrains Goland license window appears

### ISSUE THREAD

**Issue by przprz** [lwouis/alt-tab-macos#1140] opened 2021-09-16 08:54 UTC
**Describe the bug**

Given I have AltTab running
When I install and open Goland (https://www.jetbrains.com/go/download) and it shows license window
And I switch to some other application window
Then AltTab becomes unresponsive and I can't change windows anymore.

**Steps to reproduce the bug**

1. run `brew install goland` in terminal to install Goland
2. run `open -a goland` to start Goland
3. wait for the license window, but don't click anything within this window
4. switch to some other application
5. try to switch back to Goland - it's not possible, the app becomes unresponsive
6. run `pkill -if goland` to kill Goland and make AltTab responsive again

**Screen recording**
https://user-images.githubusercontent.com/1318450/137028515-063a1936-9442-4a34-93e4-5c612f13d811.mov

**Comment by lwouis** [comment] 2021-09-18 02:18
[Similar issues have already been reported with Jetbrains apps](https://github.com/lwouis/alt-tab-macos/issues?q=jetbrains) (Java apps; not using standard macOS GUI frameworks like AppKit). To be clear, these issues are from the apps themselves, so they should fix it. You should open a ticket with Jetbrains so they do a proper fix. They have a whole maintenance crew and budget. I'm basically 1 dev here working on my weekends. That's the overall context.

Now because I'm practical, and I know large companies move slow (sometimes never) on these minor issues. We have [hardcoded exceptions in AltTab](https://github.com/lwouis/alt-tab-macos/search?q=jetbrains) to workaround the issues in these product. The hardcoded string is part of the `bundleIdentifier` in the apps. We made it a catch-all for Jetbrains product, instead of individual products like IntelliJ, PyCharm, etc. So I'm surprise that the workaround wouldn't apply to GoLand.

I just downloaded GoLand, and checked the `bundleIdentifier` is `com.jetbrains.goland`. Our catch-all pattern is `^com\\.jetbrains\\..+?$` which should catch it.

I also own a license, so I didn't get any license prompt. I was able to reproduce any issue. GoLand windows show up correctly in AltTab for me.

Could you please share which `bundleIdentifier` you have? You can get it by running this command in Terminal.app: `mdls -name kMDItemCFBundleIdentifier /Applications/GoLand.app`. Furthermore, could you please share a video of the issue, so we see all the details/steps, how the window looks like, etc.

Thank you!

**Comment by BrumeSenya** [comment] 2021-11-27 09:48
In fact, my PyCharm had the same problem today

**Comment by lwouis** [comment] 2021-11-27 10:39
@przprz 

> I attached a short screen recording with similar behaviour reproducing with RubyMine.

i think you forgot to attach it. I don't see it. Could you please share it?

@BrumeSenya could you please share a video of the issue with step by step to reproduce?

**Comment by przprz** [comment] 2021-11-29 21:30
@lwouis My bad, should've mentioned that I attached the video to the description of the issue (the first post).

**Comment by lwouis** [comment] 2022-04-29 15:17
I think this may be fixed in recent versions. I'm closing the ticket since it's been a year. Please let me know if it happens still today

**Closed by lwouis** 2022-04-29 15:17 UTC
Labels: bug, unreproducible
