### ISSUE TITLE
Grouping of a single app with large amount of windows

### ISSUE THREAD

**Issue by jukrb0x** [lwouis/alt-tab-macos#789] opened 2021-01-28 18:53 UTC
**Is your feature suggestion related to a problem? Please describe.**
Some Apps could have a large number of windows, which keeps the consistency of the app. For example, Stickies, the original app of macOS. The user could have multiple and many sticky notes at the same time, then AltTab displays lots of windows, which is not necessary since _stickies.app_ put all separated notes in the same space as it started. In this case, I would like only one icon to switch to the _stickies.app_ instead displaying all windows, making lots of troubles.

![image](https://user-images.githubusercontent.com/15688641/106184833-084f1800-61dd-11eb-9b10-70f125112c33.png)

sorry for the miserable mosaic 

**Describe the solution you'd like**
It can be grouped into one icon of multiple windows, i.e., sharing a part of the style of macOS default window management. But at the same time, I love the AltTab way to manage windows as it's more efficient. (paradox, in a general situation the efficiency is elevated, but it can be decreased sharply since unnecessary windows come up.)

**Describe alternatives you've considered**
The current workaround, I use the blacklist to disappear the app in AltTab, however, it cannot be located using AltTab.

![blacklist](https://user-images.githubusercontent.com/15688641/106183577-52cf9500-61db-11eb-8cca-b4b743752a06.png)

**Comment by lwouis** [comment] 2021-01-29 01:53
Hi @jukrb0x! Thanks for sharing this feedback.

AltTab shows windows. If you have a lot of them, yes it can be an issue. I would suggest, as a workaround, that you organize your windows differently. For instance you could minimize some of them, and customize AltTab shortcut1 to only show non-minimized windows. You could also put less relevant stickies on other Spaces, and set AltTab to not show these Spaces's windows, etc.

If you think that's not workable, then what would you propose we implement to handle your use-case? You described the issue you face, but I would be interested in a *solution* with precise explanations on how the feature would work, be customized, etc.

**Comment by jukrb0x** [comment] 2021-02-02 17:47
Thank @lwouis for responding.

The solution in my mind is to group different windows into one single card like system default Cmd+Tab, but i'd rather not to use the default Cmd+Tab since applying AltTab as the default switcher (replacing Cmd+Tab shortcut).

So here's my thoughts, can add a section so called grouping or bundling, for user adding apps such as _Stickies_, then AltTab only display one card for the app. But even in this case can be a problem: how AltTab determines which window should be focused on when switching, I'd suggest the most recent one and I suppose that's what macOS does by the default switcher(Cmd+Tab).

This function can be a rough one, now I only encountered only this one app _Stickies_(which logically designed in a fashion using many windows, and it happens to use many many windows in a need, can up to 10 or 20 for me), as discussed many windows could lead to inconvenient.

**Comment by lwouis** [comment] 2021-02-03 00:54
> I suppose that's what macOS does by the default switcher(Cmd+Tab).

I think the built-in switcher activates the app, which brings **all** its windows forwards. If we did the same then in AltTab you would see all 20 stickies windows listed first since all of them were interacted with recently. Unlike the built-in switcher, we could bring only the most recent one up though.

Still some unsolved issues:

* how do we know which app to pack into 1 app-card? Based on a threshold like 20 windows? Based on a list like the current blacklists?
* What if AltTab is packing 20 windows into 1 icon, and you decide you want to explore the 20 windows to find 1 in particular. Now you're stuck, you can't access them individually. What now?

**Comment by MuhammedZakir** [comment] 2021-02-03 17:36
> Still some unsolved issues:
> 
>     * how do we know which app to pack into 1 app-card? Based on a threshold like 20 windows? Based on a list like the current blacklists?

Grouping by app or grouping by a user-given list. Latter is more flexible.

>     * What if AltTab is packing 20 windows into 1 icon, and you decide you want to explore the 20 windows to find 1 in particular. Now you're stuck, you can't access them individually. What now?

Can't we expand a "group"? That is, if a "group" is focused/clicked using `tab`/mouse, it will expand into a list of windows. To distinguish a "group" from a "window", an icon should be shown.

**Comment by jukrb0x** [comment] 2021-02-03 18:16
> - I think the built-in switcher activates the app, which brings all its windows forwards. 

How to deal with many windows if they are scattered in different spaces?

> - how do we know which app to pack into 1 app-card? Based on a threshold like 20 windows? Based on a list like the current blacklists?

I agree with @MuhammedZakir , grouping by a user-given list like Blacklists does.

> - What if AltTab is packing 20 windows into 1 icon, and you decide you want to explore the 20 windows to find 1 in particular. Now you're stuck, you can't access them individually. What now?

So far, the Shortcut 2 for the active app does not work if the app added in Blacklists, so if we add an app like Stickies into the user-given list for _grouping_, then Shortcut 1(AltTab) will not display all windows of the app but only one window-card, but Shortcut 2 still working while this app is active, we can use Shortcut 2 to switch between these windows.

**Comment by lwouis** [comment] 2021-03-08 13:19
Closing this ticket as duplicate of https://github.com/lwouis/alt-tab-macos/issues/337#issuecomment-673304578. Let's keep the discussion in one place

**Closed by lwouis** 2021-03-08 13:19 UTC
Labels: enhancement
