### ISSUE TITLE
A way to skip the currently focused window if hidden

### ISSUE THREAD

**Issue by matteocontrini** [lwouis/alt-tab-macos#2297] opened 2023-02-06 11:06 UTC
**Is your feature suggestion related to a problem? Please describe.**
When an app is hidden through Alt-Tab and the app is in focus, Alt-Tab by default selects the first app of the list, when invoked. If the hidden app was actually shown, that app would be the second one of the list, as expected.

However, when using software like CleanShot X, the currently focused window is often a small overlay in the corner of the screen. In those cases, you don't expect that small overlay to play a role since it's like a notification. So when invoking Alt-Tab, I would expect to be able to switch to the second app, ignoring that the hidden app is in focus.

**Describe the solution you'd like**
There could be a global option that allows to "skip" windows that are hidden. Or it could also be a per-app option.

**Comment by lwouis** [comment] 2023-02-06 18:35
I'm sorry but I couldn't understand what the issue is for you. Could you please provide a video with explanations, or some screenshots?

You can already hide apps-with-no-window in the preferences, or hide hidden or minimized windows. Is your use-case not handled by changing these settings?

**Comment by matteocontrini** [comment] 2023-02-06 19:41
Hi, thanks for the reply! Sorry, it's hard to explain with words. I'll try with screenshots.

An example of a "normal" case: the focused window is currently Firefox, I press Alt-Tab and AltTab immediately selects the next window, which is Spotify in this case.

<img width="512" alt="image" src="https://user-images.githubusercontent.com/2164763/217066663-b6693109-162e-43d1-943e-118089849175.png">

Now, when I take a screenshot with CleanShot there's a feature called Quick Access which shows this popup in the corner of the screen:

<img width="264" alt="image" src="https://user-images.githubusercontent.com/2164763/217067653-da5c0063-0df3-471a-a12f-1aab84c71c1d.png">

That thing is a window of the app, and appears in Alt-Tab:

<img width="498" alt="image" src="https://user-images.githubusercontent.com/2164763/217067778-5a673505-b890-4260-b6ab-a054e9d5ed6e.png">

I don't really want it there since it's a bit useless, so I add CleanShot X to the "Hide in AltTab" blacklist.

<img width="544" alt="image" src="https://user-images.githubusercontent.com/2164763/217068001-426c9d0a-7e16-48af-93ed-0f8da6efbc0b.png">

Let's go back to the first example: I'm in Firefox, I take a screenshot, and I want to Alt-Tab to the next window. This is what I see:

<img width="532" alt="image" src="https://user-images.githubusercontent.com/2164763/217068210-9ad1a27c-7c07-43ee-b665-837c52a4027b.png">

The problem is that since CleanShot X is in focus, even if hidden, Alt-Tab selects Firefox (where I took the screenshot) instead of the next app which is Spotify in this case.

I realize this is probably a very narrow use case, but it's something I do all the time: I take quick screenshots with CleanShot and then alt-tab to apps like Telegram or Slack to paste the screenshot. And that popup gets a bit in the way, I expect it to be "transparent", but unfortunately it's not, even if hidden.

Thanks again! :)

**Comment by lwouis** [comment] 2023-02-06 20:21
Thank you. I understand the use-case now.

It's a bit tricky. Should AltTab, when told to ignore windows of an app, also ignore that the app itself is focused? I think some use-cases like this one would answer "yes", while others would answer "no".

Since it's a 50/50 to improve it (it will create bad flows for some users, while improving flows for other users), I think status quo is equally good as making a change.

The root cause of your issue is that when you invoke CleanShot X, it steals focus away from the current app. Notice that AltTab itself is an example of a utility app that can be called, and never alters focus of the current app and current window. It's "on top of everything" and doesn't alter your business. I think CleanShot X is failing at being "invisible" to the user.

This app seems to be commercial, so I suggest you contact them and ask that they improve the Quick Access window so that it doesn't register as a window for apps like AltTab. It's very easy to do for them, technically. They just need to create the window as a `NSPanel` instead of a `NSWindow`. There are other ways to do it, but essentially this "window" should really be a floating panel, a HUD, etc. It's clearly a helper, not a full window that the user would expect to AltTab to.

I'll close this ticket as I don't see a possible improvement on AltTab side, and because the root cause is an issue in the coding of CleanShot X 🙇

**Closed by lwouis** 2023-02-06 20:21 UTC
Labels: enhancement, unclear

**Comment by matteocontrini** [comment] 2023-02-06 21:33
That makes sense, I'll give it a try, thanks a lot!
