### ISSUE TITLE
Prevents Alt+Tab functionality for Citrix Workspace

### ISSUE THREAD

**Issue by skupfer** [lwouis/alt-tab-macos#291] opened 2020-05-04 10:43 UTC
If AltTab is running, I cannot switch windows in Citrix Workspace / Citrix Viewer using Alt+Tab. Would it be possible to add whitelist/blacklist for applications?

**Comment by lwouis** [comment] 2020-05-04 16:20
Closing this as duplicate of #239. Please check there. We have already listed multiple other virtualization apps where the issue happen, and detailed why at the technical level, and drafts at what could be done.

Also interesting is the discussion around the UI of blacklisting, discussed in #164

**Closed by lwouis** 2020-05-04 16:20 UTC
Labels: duplicate
