### ISSUE TITLE
Conflict with an App called 'protege'

### ISSUE THREAD

**Issue by Whatsmine** [lwouis/alt-tab-macos#314] opened 2020-05-09 14:31 UTC
Hello!

Your app is my favorite one and I have already recommend it to my friends and colleagues who use Mac.

But I'm having problem with it. One of my research tools, which is called protege, can't be used normally these days. Protege is used to create ontology document that is based on XML. When I create a ontology and click 'save' to save it, the save window can't be popped up. I have spent three days to find a way to deal with it and I tried so many ways, even reinstall my system. But it doesn't work.

So today I decide to find problem in the error code of protege. A statement caught my attention: NSApplication runModalForWindow. I think maybe it's a window management problem? So I tried to close Alt-tab. And protege gets back to normal!

Now I have to close Alt-tab to use protege. It's a little troubled. And I think maybe other apps also could conflict with alt-tab? And I want to learn why this could happen.

Besides, protege is a Java program. This is its download page: https://protege.stanford.edu/products.php#desktop-protege. 
It needs JRE and I run it on JRE-1.8.

Thank you very much! Have a nice day!

**Comment by lwouis** [comment] 2020-05-10 01:05
Hi @Whatsmine! Thank you for reporting this issue!

I'm sorry you had to reinstall your system, and dig into Protege's source code! That sounds like a lot of troubles!

I'm surprised at how AltTab would prevent an app from displaying a window. AltTab only listen to the keyboard, so I could imagine some shortcut issues within Protege (see #239 for example). However you said the issue is:

> When I create a ontology and click 'save' to save it, the save window can't be popped up.

You used the mouse, clicked a button, and the window failed to appear?

I'll download Protege and see if I can reproduce. This is peculiar

**Comment by Whatsmine** [comment] 2020-05-10 01:32
Thank you. I'm not sure if other app results in this issue. But after I quit AltTab protege indeed works.
oh, besides, when AltTab is running and I open a ontology document with protege, protege will open two windows at one time. One window is the document which I want to open, another window is a blank document like automatically creating a new windows  that I don't expect.

**Comment by lwouis** [comment] 2020-05-10 02:33
@Whatsmine there are many buttons in this app. I'm not sure exactly what to press.

Could you possibly install [Loom](https://www.loom.com/) and record the issue? Using Loom is very easy and let's you share a link of a screen recording without worrying about where to upload, and other technical things.

That would make it way more clear what steps I need to do to reproduce both scenarios (clicking save, and opening an existing document)

**Comment by Whatsmine** [comment] 2020-05-10 02:37
OK, I will do it later.

**Comment by lwouis** [comment] 2020-05-10 02:39
@Whatsmine oh I managed to reproduce the save button scenario!

**Comment by Whatsmine** [comment] 2020-05-10 02:53
Yeah! 
And please click tab 'Entities'. Then you can see 'owl:Thing'. Please right click on it and click 'Add subclass'. In 'Name' you can write anything, such as 'test', and directly click ‘submit’. Then you can save this document.
Please quit protege and open this document outside. Maybe you will see two windows open and the blank window can't be operated?

**Comment by lwouis** [comment] 2020-05-10 03:58
I tried to:

* Disable subscribing to keyboard events: still interfere with Protege
* Disable subscribing to workspace events: still interfere with Protege
* Disable subscribing to windows AX events: still interfere with Protege
* Disable subscribing to apps AX events: doesn't interfere! 👍

I have no clue why there would be interaction here, but at least I narrowed the scope of the issue. I'll dig deeper.

**Comment by Whatsmine** [comment] 2020-05-10 04:03
✌️ Great!

**Comment by lwouis** [comment] 2020-05-10 14:15
I investigated more today. It's pretty wild. For every app running in the system, we subscribe to these notifications:

```
kAXApplicationActivatedNotification,
kAXMainWindowChangedNotification,
kAXWindowCreatedNotification,
kAXApplicationHiddenNotification,
kAXApplicationShownNotification,
kAXFocusedUIElementChangedNotification,
```

For some reason, subscribing to specifically `kAXFocusedUIElementChangedNotification`, breaks Protégé. I can't begin to understand how subscribing to it would affect it, as as far as I know, apps can't even be aware that other apps are subscribing to their accessibility events. Let alone being affected by another app subscribing to it.

Since Protégé doesn't seem to use standards tabs, as a workaround, I will avoid subscribing to that 1 notification for Protégé. I will hardcore this exception to make the app usable. I wish I could draw a lesson here, or fix something in AltTab, but it looks like either a bug in macOS, or some craziness coming from complex interaction with Protégé or perhaps the JVM on macOS.

**Comment by lwouis** [comment] 2020-05-10 14:19
> And please click tab 'Entities'. Then you can see 'owl:Thing'. Please right click on it and click 'Add subclass'. In 'Name' you can write anything, such as 'test', and directly click ‘submit’. Then you can save this document.
> Please quit protege and open this document outside. Maybe you will see two windows open and the blank window can't be operated?

Also I haven't been able to reproduce that issue. I only reproduced the "click save and nothing shows up" issue, so that's the only one I'm confident I have a workaround for. The other may or may not be fixed with the workaround. Unfortunately if I can't reproduce it, there is no way to know for me

**Closed** 2020-05-10 14:36 UTC
Labels: bug

**Comment by lwouis** [comment] 2020-05-10 15:45
I opened a [ticket on Protégé's issue tracker](https://github.com/protegeproject/protege/issues/956), so that they are aware that accessibility apps may be breaking their app on macOS.

**Comment by Whatsmine** [comment] 2020-05-10 23:56
It works! Two issues both have disappeared in my Mac. Thank you too much!!!
