### ISSUE TITLE
CMD+tab not working after pressing CMD+tab in Parallels Windows installation

### ISSUE THREAD

**Issue by stidch** [lwouis/alt-tab-macos#613] opened 2020-09-17 09:44 UTC
**Describe the bug**

AltTab v6.5.0

When pressing CMD+tab in a virtual Windows, running in Parallels, the CMD+tab does not work afterwards anymore. Only restarting AltTab helps.

**Screenshots / video**

[Screen Recording 2020-09-17 at 11.38.30.mp4.zip](https://github.com/lwouis/alt-tab-macos/files/5238077/Screen.Recording.2020-09-17.at.11.38.30.mp4.zip)

**Steps to reproduce the bug**

1. Start AltTab
2. Press CMD+tab --> works
3. Move to the second Desktop with Windows running in Parallels
4. Press CMD+tab
5. Move back to the first Desktop
6. Press CMD+tab --> does not work

**Comment by lwouis** [comment] 2020-09-17 10:44
Hi @stidch! Thank you for sharing this issue!

The video is very nice to see the issue in action, thanks!

I've reworked the whole keyboard events code for another ticket. Could you [please try out the build I shared on this ticket](https://github.com/lwouis/alt-tab-macos/issues/556#issuecomment-693428704)? Let me know if the issue is still present in that build, or not 👍

**Comment by stidch** [comment] 2020-09-17 13:29
Hey @lwouis 
Thanks for the very quick response. You're doing a very, very, very good job. Thanks a lot for this nice tool!
I've tested your linked build and the issue above is gone. Have not tested much if there are some side-effects or some new issues, but so far it looks perfect.

**Comment by lwouis** [comment] 2020-09-25 10:30
The [new release 6.7.0](https://github.com/lwouis/alt-tab-macos/releases/download/v6.7.0/AltTab-6.7.0.zip) should fix this issue. Closing this ticket. Let me know if the issue is not gone and I'll re-open it 👍

**Closed by lwouis** 2020-09-25 10:30 UTC
Labels: bug
