### ISSUE TITLE
Version 3.22.0 won't open

### ISSUE THREAD

**Issue by buttercrab** [lwouis/alt-tab-macos#326] opened 2020-05-10 02:40 UTC
**Describe the bug**

AltTab version [3.22.0](https://github.com/lwouis/alt-tab-macos/releases/tag/v3.22.0) won't open.
I've reinstalled many times, but it won't open.

**Screenshots / video**

It won't open, no images :)

**Steps to reproduce the bug**

1. Install 3.22.0
2. Open AltTab

**Comment by gitgetgot** [comment] 2020-05-10 02:44
I can reproduce that on Mojava.

either via update from an earlier version, or downloaded and installed directly.
configs removed or not.

AltTab shortly flashes, then crashes or quits or exits itself.

The Update screen shows this:
<img width="621" alt="Bildschirmfoto 2020-05-10 um 04 25 05" src="https://user-images.githubusercontent.com/974980/81489695-daa1f780-9278-11ea-9500-5456215bb5af.png">

**Comment by lwouis** [comment] 2020-05-10 03:06
Hi @buttercrab and @gitgetgot! Thank you so much for your reports!

I made a lot of changes by releasing a [new website for AltTab](https://alt-tab-macos.netlify.app). I tried to avoid breaking things, but it's incredibly hard because some of these things need to go live to be testable basically (same merge on master will release the website, and update the app to point to it, for instance). These kinds of issues should have safeguards for the future, but on the initial setup, there was some risk.

There are 2 distincts issues here:

* The crash on startup is due to me renaming a file `ACKNOWLEGDMENTS.md` to `Acknowledgments.md` and missing one place in the code where it's mentioned. Unfortunately it is triggers a crash as it fails to find the file.
* The 404 auto-update window. I was originally planning on using Github Pages, so I put the anticipated url here. Later on, I chose to use Netlify as it provides a way to test changes to the website before going live. Going forwards, making a PR that updates the website will auto-deploy a staging website, so we can safely check the changes before merging the PR. Once again, this nice safety will only come to play from now on. I missed the URL this time though.

I made fixes for both issues, and CI will release a new version in a few minutes.

Again, I'm very sorry about these issues!

**Comment by gitgetgot** [comment] 2020-05-10 03:07
Maybe [this issue](https://github.com/lwouis/alt-tab-macos/issues/269) causes the problem ?

> @gitgetgot I released a new version of AltTab which quits if you the permission is removed during runtime. It's a first quick win, as the app doesn't swallow keyboard inputs now. A more advanced UX can now be discussed in #127.
> 
> Also I'm still curious about your use-case of disabling permissions during runtime. Why do you need to do such a thing?

Accidentially, or on purpose, because I want to see what happens. Maybe I don't know what I'm doing, or just disable it temporarely. ;-)
In my personal case, it was because of the switching between the app versions of AltTab.

**Comment by lwouis** [comment] 2020-05-10 03:27
The new release with the fixes is available. I tested to upgrade to that release, and everything seems to work great, so I'm closing this ticket.

Please let me know if it's not fixed for you somehow! 👍

**Closed by lwouis** 2020-05-10 03:27 UTC
Labels: bug

**Comment by gitgetgot** [comment] 2020-05-10 03:34
AltTab starts now, but the strange flashing on start still remains.
It looks like a task is coming very shortly in front and then vanishes to the place it was before, but its too fast to recognize.

**Comment by lwouis** [comment] 2020-05-10 03:46
@gitgetgot this flashing has been there since v2 I believe. It's the only way I could find to deal with a specific situation: The user starts AltTab, but they have already multiple Spaces opened.

macOS has no public API to get windows from other Spaces than the active one. This means that we have to use private APIs. The trick I found, which is the only way I could manage to do it, is to teleport all windows to the current space (this is "the flash"), tag them so we can follow them later, and send them back.

It only happens if you have multiple spaces **and** you open AltTab later. These 2 conditions are fortunately not frequent I think, especially since I expect most users to have AltTab start at login, which means it can then get the windows without the hack, as they get created while AltTab is already listening to the OS.

If anyone knows a way to avoid this dirty teleport hack, I would **love** to hear it 🙉

**Comment by gitgetgot** [comment] 2020-05-10 04:10
> It only happens if you have multiple spaces **and** you open AltTab later.

Ah :-) 
Thank you, I just put some Apps on different spaces the last weeks, I thats the reason, I did not see it before. Ok, if it is a feature, I surely will live with it, as I don't start AltTab often in normal life. It was just for the testing...
