### ISSUE TITLE
Screen capture dialog on every AltTab launch

### ISSUE THREAD

**Issue by ProjectTermina** [lwouis/alt-tab-macos#3183] opened 2024-02-16 17:55 UTC
**Describe the bug**

On macOS Sonoma 14.4 Beta, macOS displays a dialog box on **every** AltTab startup that says "Allow screen capture in AltTab?" Apps using ScreenCaptureKit will not receive these additional prompts in macOS 14.4.

**Screenshots / video**

<img width="283" alt="Screenshot 2024-02-16 at 11 41 56 AM" src="https://github.com/lwouis/alt-tab-macos/assets/6645684/842485e7-3781-46c0-8497-faff925f9187">

video: https://uofi.box.com/s/s9erpblmg2g89jgt5d7k4vtos6emek85

**Steps to reproduce the bug**

1. Launch AltTab on affected OS version

**Your environment**

* AltTab version: 6.60.0
* macOS version: 14.4 Beta 4 23E5196e

**Comment by lwouis** [comment] 2024-02-16 18:14
Hi @ProjectTermina,

Thank you for reporting this issue.

I'm not sure what can be done about this. It's a terrible news. Apple is going to create frustrated users [once again](https://github.com/lwouis/alt-tab-macos/issues/2606).

> Apps using ScreenCaptureKit will not receive these additional prompts in macOS 14.4.

Could you please clarify exactly which API triggers the prompt? Maybe there is reference material from Apple you could share?

We use various APIs to grab screenshots of window, but also window titles, etc. I'm not sure which calls we would need to replace. For instance, using ScreenCaptureKit to list windows and get their titles [has big limitations I reviewed](Apps using ScreenCaptureKit will not receive these additional prompts in macOS 14.4.).

Thank you 🙇

**Comment by ProjectTermina** [comment] 2024-02-16 18:34
The [WWDC presentation of ScreenCaptureKit specifically called out CGDisplayStream and CGWindowList](https://developer.apple.com/videos/play/wwdc2022/10156/?time=896). Unfortunately there is no official communication from Apple on the upcoming 14.4 release. @lwouis

**Comment by ProjectTermina** [comment] 2024-02-16 18:57
The Core Graphics docs, specifically under Quartz Display Services and Quartz Window Services, might be helpful: https://developer.apple.com/documentation/coregraphics/

There is also a possibility that Apple will change their mind about enforcing this in 14.4. A lot of IT people are very unhappy about this. But I wouldn't count on it, of course.

**Comment by lwouis** [comment] 2024-02-16 21:47
Thank you for sharing these resources!

Let's wait for the beta to end, and let's see if we have to adapt the app or not. Hopefully they backpedal on this idea 🙏

**Comment by tails618** [comment] 2024-06-20 01:23
I see a similar but differently worded prompt on macOS 15.0 Sequoia; I can't reproduce it at the moment but I've seen it a number of times. I suspect it's the same issue and Apple modified the prompt slightly, but I'll try to remember to post a screenshot next time I see it.

**Comment by tails618** [comment] 2024-06-21 17:13
<img width="270" alt="image" src="https://github.com/lwouis/alt-tab-macos/assets/22648713/50743498-3ccc-4829-b067-bae646bd8645">
I get this on macOS startup, and sometimes upon just opening my laptop.

**Comment by bedesv** [comment] 2024-06-25 06:06
@tails618 I'm having the same issue on Sequoia. I get about 3-5 popups every time I open my laptop and it's very annoying having to close them all.

**Comment by tails618** [comment] 2024-06-25 14:43
> I get about 3-5 popups every time I open my laptop

Yup, same. 3-5 prompts. Not every time I open my laptop, though. It happens every time I boot up, and *sometimes* waking from sleep.

**Comment by enzofrnt** [comment] 2024-07-02 16:31
Same issue here.

**Comment by ejbills** [comment] 2024-07-03 19:12
Hi there, there is now some official word from Apple which at least acknowledges the popup's existence. See: https://developer.apple.com/documentation/macos-release-notes/macos-15-release-notes#ScreenCaptureKit

> Applications utilizing deprecated APIs for content capture such as CGDisplayStream & CGWindowListCreateImage can trigger system alerts indicating they might be able to collect detailed information about the user. Developers need to migrate to ScreenCaptureKit and SCContentSharingPicker. (120910350)

Looks like there is no option BUT to transition to 100% ScreenCaptureKit, which is restricted to the current-desktop space only. This is obviously a huge PITA and will have major ramifications for AltTab, I would imagine.

**Comment by lwouis** [comment] 2024-07-11 21:56
Apple reverted this change in macOS 14. They seem to be pushing it again in the macOS 15 beta. Closing this ticket in favor of the relevant https://github.com/lwouis/alt-tab-macos/issues/3477

**Closed by lwouis** 2024-07-11 21:56 UTC
Labels: enhancement, macOS 14
