### ISSUE TITLE
"Background Items Added" alert even after removing the app

### ISSUE THREAD

**Issue by miskelma** [lwouis/alt-tab-macos#2156] opened 2022-11-24 17:59 UTC
**Describe the bug**

1. I've installed the app
2. Used it for a while, and then deleted
3. Still get the macOS alerts about Background Items Added (about 10 times per day)

**Screenshots / video**

Screenshot: https://cln.sh/U3pwObxA6kXpzdGTKbzw
But there are no Alttab app in the Login Items: https://cln.sh/2jvJRykfhyDy5GdG7p5R

**Steps to reproduce the bug**

1. Work and wait

**Your environment**

* AltTab version: —
* macOS version: 13.0.1
* Other relevant info: External kb/mouse + display

**Comment by lwouis** [comment] 2022-11-24 18:57
I don't know how you got to that situation. Maybe you have multiple versions/apps on your system?

When the app is not running, it's obviously not capable of adding itself to the Login Items. It's capable of nothing, since it's not running. But you mention "about 10 times a day". Are you sure there is no AltTab in the top menubar when you see one of those alerts?

**Comment by iliakukharev** [comment] 2022-11-24 19:18
yeah, that's a bug surprise for me as well, especially when the app is deleted
created this issue to confirm that this is not a well-known bug, and it seems there is something on my side. will investigate

thank you 👍

**Comment by tajdien** [comment] 2022-11-30 19:03
I have to report that i am facing the same issue.
I receive the same message even after deleting the app.

I also used a software called AppZapper to try do really remove everything but with no success

**Comment by danisicos** [comment] 2022-11-30 19:23
Same, and with a lot of notifications

**Comment by lwouis** [comment] 2022-11-30 20:50
Please share more info. I can't debug on thin air. It doesn't happen on my machine, and most people's machine. So we need info from the people who get the issue. See my previous post above.

**Comment by tomershukhman** [comment] 2022-12-04 17:17
Facing the same issue
I am running macos ventrua and installed the sofftware using brew an removed it with brew.
There are no visable residues from alt-tab besides this notification (no file in the system containing "louis","alt-tab" etc...)

**Comment by Zoomatik** [comment] 2022-12-08 12:58
Exactly the same issue on my end.
Tried the software, deleted it and then multiple times a day this startup item gets added.

**Comment by lwouis** [comment] 2022-12-14 17:22
@tomershukhman my previous reply still stands: https://github.com/lwouis/alt-tab-macos/issues/2156#issuecomment-1332720704

I need more data. I've never seen the behavior on my machine, and have no clue as to what's going on. For all we know, this is a macOS bug.

**Comment by trestent2** [comment] 2022-12-14 17:46
Try this in Terminal: `rm ~/Library/LaunchAgents/com.lwouis.alt-tab-macos.plist`

**Comment by tomershukhman** [comment] 2022-12-14 17:52
Tnx @trestent2 , let's see if this solves it

**Comment by gosk8** [comment] 2022-12-15 05:53
> Try this in Terminal: `rm ~/Library/LaunchAgents/com.lwouis.alt-tab-macos.plist`

It works for me, Thanks!

**Comment by LvlAndFarm** [comment] 2023-02-06 23:04
I believe this issue is caused by Ventura, as many people have been complaining about a constant barrage of background app notifications despite the apps getting deleted. I would say this is mainly an OS bug as so many other apps have it, and it only started after Ventura's release.

**Comment by tajdien** [comment] 2023-02-20 11:18
Thanks to @trestent2 

Removing it solved the issue for me too.

**Comment by mayeths** [comment] 2023-03-28 16:52
Yes, it must be something wrong with macOS Ventura. Just starting from Nov 2022, [many similar issues were posted on the Apple forum](https://www.google.com/search?q=macos+allow+in+the+background+pop+up+site%3Adiscussions.apple.com&rlz=1C5CHFA_enCN979CN979&oq=macos+allow+in+the+background+pop+up+site%3Adiscussions.apple.com). All of them are related to Ventura.

**Comment by lwouis** [comment] 2023-03-28 18:58
Closing this issue since it's not actionable. If you have new data, please share and I will re-open it 👍

**Closed by lwouis** 2023-03-28 18:58 UTC
Labels: bug, unactionable, unreproducible

**Comment by lwouis** [comment] 2023-05-10 07:17
[macOS release notes for Ventura 13.3](https://developer.apple.com/documentation/macos-release-notes/macos-13_3-release-notes) seem to confirm that the issue was on macOS side:

<img width="599" alt="image" src="https://github.com/lwouis/alt-tab-macos/assets/106195/35f71275-8406-4656-9b44-99b7baba4662">
