### ISSUE TITLE
Stop opening the release notes automatically in the browser

### ISSUE THREAD

**Issue by GregOriol** [lwouis/alt-tab-macos#3933] opened 2024-12-02 20:49 UTC
**Describe the bug**

AltTab seems to like to open the release notes in a browser when there is a new version. This is annoying and not a common behavior at all in mac apps. It should be removed: the user should be able to display release notes if the user wants to, not be forced with a new window.

**Your environment**

* AltTab version: 7.6.0
* macOS version: 14.7.1
* Other relevant info: e.g. using external keyboard, multiple monitors, etc

**Comment by lwouis** [comment] 2024-12-02 21:17
Hi,

This is definitely not normal behavior. Normal behavior is that AltTab shows a popup asking if you'd like to update. It also offers the option to never be asked again.

Could you please share a video of what happens on your side?

Also, do it happen with other apps like BetterDisplay? Most mac apps use Sparkle for auto-update. AltTab uses it as well. Since it's a library, you should see the issue in all apps using Sparkle, if it happens in one of them.

Thank you

**Comment by GregOriol** [comment] 2024-12-02 21:23
@lwouis I only get this behavior when a new version is available, like today. So I can't reproduce it again until the next new version sadly. I see the Sparkle popup too, and it updated the app. I have never seen any other app with this behavior and I've been a macOs user/developer for >10 years, I don't use BetterDisplay though. I'll try to gather some more feedback when it happens next, but it is happening by surprise so I most likely won't be able to record a video...

**Comment by lwouis** [comment] 2024-12-02 21:29
To reproduce the issue, you can download for instance [v7.5.0 here](https://github.com/lwouis/alt-tab-macos/releases/download/v7.5.0/AltTab-7.5.0.zip). Then upon opening it, it should suggest to update.

Same thing with BetterDisplay. Here's an [older version](https://github.com/waydabber/BetterDisplay/releases/download/v3.1.1/BetterDisplay-v3.1.1.dmg). You can download and open it and it should prompt.

Could you please open both and record it in video?

**Comment by GregOriol** [comment] 2024-12-02 21:40
Well, that went better than I expected: I downgraded and it actually happens every time the Sparkle popup shows up.

Here is a video: https://www.gregoriol.net/tmp/alt-tab-macos-3933.mov

**Comment by lwouis** [comment] 2024-12-02 23:14
Thank you for sharing these videos!

I can't reproduce this. It's also the first time someone has this issue in 3-4 years that we've been using Sparkle. I'm not sure what could be triggering this only on your setup. Perhaps an adblocker plugging into the OS webviews? I'm really not sure.

It's hard to move forward from here. I can't reproduce, and updating Sparkle would be a very tough and risky task.

**Comment by GregOriol** [comment] 2024-12-03 08:46
@lwouis Thanks for your feedback. Indeed it's strange, I hoped some others had it too. I'm really intrigued by AltTab being the only app to have this, I'll look into it then.

**Comment by GregOriol** [comment] 2024-12-03 10:33
@lwouis Some new information on this issue: this has something to do with the Google Translate trick you use on the changelog page. My macOs is in French, the translate code you have on the page is executed and the page gets translated and the issue happens. If I change my macOs to be in English, the translate code you have is not executed (and the page stays in english and the issue does not happen!

Code being this at the bottom of `https://alt-tab-macos.netlify.app/changelog-bare`:
```
const userLanguage = getUserLanguage()
if (userLanguage !== "en") {
    let script = document.createElement("script")
    script.src = "https://translate.google.com/translate_a/element.js?cb=googleTranslateElementInit"
    document.head.appendChild(script)
}
```

**Comment by lwouis** [comment] 2024-12-04 21:47
Thank you @GregOriol 

Could you please go to https://alt-tab-macos.netlify.app/changelog-bare, and open Chrome's Network panel, clear it, then share a screenshot of what is listed when you load the page? For me, it looks like this:

![image](https://github.com/user-attachments/assets/87c91e40-1752-41d5-b269-5770c1940067)

I notice that google translate JS is making a call for the page itself (https://alt-tab-macos.netlify.app/changelog-bare). It's canceled in my case. Perhaps it's not in yours, and there is a call to open a new window, which results in the bug you see?

Thank you

**Comment by GregOriol** [comment] 2024-12-05 09:13
Here it is:
![Capture d’écran 2024-12-05 à 10 02 48](https://github.com/user-attachments/assets/72db3315-8a66-4d6a-95bb-d9ce03bb6eb6)

I also have the canceled request in the log.

Another interesting thing: I can right click and inspect in the changelog displayed inside the Sparkle window. Then if in the console I type `location.reload();`, it doesn't reload inside the Sparkle window: it opens in a browser window. I tried to replicate this in BetterDisplay's Sparkle window but there is no inspect option and I can't find it through Safari's developer menu either.

**Comment by lwouis** [comment] 2024-12-05 09:42
I ran `defaults write NSGlobalDomain WebKitDeveloperExtras -bool true` and was able to Inspect within the Sparkle window as well. Interestingly, the Network is different. There is indeed a call to load the page again, which is not cancelled.

I guess Google Translate has its heuristics and sometimes it decides to reload the page to apply translation. And when it goes through that path, it triggers a new page on your particular setup. Since it doesn't happen on my setup, and no one else seems to have the issue, I wonder if it's not due to some developer-focused flag your turned on your machine.

The only path forward I can see would be that we update Sparkle, and that's way too risky I would say. I know that they had a rewrite in the next major version. That was years ago. It's too risky for AltTab to update such an impactful library. If anything goes wrong, it could leave users bricked with no way to auto-update to the next fixed version.

I'll close this issue now. If it happens to more people, we can try and investigate more for a workaround 👍 

Thank you

**Closed by lwouis** 2024-12-05 09:42 UTC
Labels: bug, unreproducible

**Comment by lwouis** [comment] 2024-12-05 18:09
@GregOriol please see https://github.com/lwouis/alt-tab-macos/issues/3120#issuecomment-1900871951

**Comment by GregOriol** [comment] 2024-12-05 19:09
Well, I don't agree with the comment: I believe real/precise/expert english is better than any approximate translation.

I've switched the app to "en" with the trick from that comment: `defaults write -app AltTab AppleLanguages -array en` and the problem disappeared. Disables the fake translations too, so even better.
