### ISSUE TITLE
Quick switcher via a number or letter shortcut next to the window

### ISSUE THREAD

**Issue by MikeHanSolo** [lwouis/alt-tab-macos#1314] opened 2022-01-09 04:05 UTC
Each window could be assigned a number or letter key which would let you bring it into focus without having to click the "next window" key multiple times. Also the ability to customize if the shortcuts could come from just the right side of the keyboard would be fantastic, since it would make it more ergonomic to hit cmd + tab with the left hand and select the window with the right

**Comment by lwouis** [comment] 2022-01-09 05:05
Duplicate of #210

**Closed by lwouis** 2022-01-09 05:05 UTC
