### ISSUE TITLE
Appearance Tab is cutting off some settings

### ISSUE THREAD

**Issue by AbirRazzak** [lwouis/alt-tab-macos#936] opened 2021-04-28 18:44 UTC
**Describe the bug**

Open the preferences setting and navigate to the appearance tab. The settings panel is cutting off the last checkbox setting and the settings window is not resize-able to allow the user to see it, or scrollable to be able to scroll down. Expected behavior is that the settings window size is large enough to be able to properly display all the text.

**Screenshots / video**

![image](https://user-images.githubusercontent.com/26943377/116456204-fa3a8300-a82f-11eb-95ff-c300b13e4be2.png)

**Steps to reproduce the bug**

1. Go to preferences
2. Click on appearance tab
3. See error

**Comment by AbirRazzak** [comment] 2021-04-28 18:46
```
Alt-Tab Version 6.21.2
MacOS Version 11.3
```

**Comment by imthenachoman** [comment] 2021-09-22 02:17
FWIW for me this only happens when the preferences is open on external monitors.

**Comment by lwouis** [comment] 2021-09-22 02:25
I'm guessing that it's something like a rounding error on a pixel count, or some other precision layout bug. That would explain why it happens to few people, on external monitors. These can have various ratios, pixel density, etc. Some of the combinations must fall into the unlucky scenarios where the maths don't end up exact and this overflow happens.

Ideally this would all be resolved during #351. We would probably want to add vertical scrolling to the sections. That would solve this, as well as make the window more usable on smaller screens.

**Comment by imthenachoman** [comment] 2021-09-22 02:27
Yeah. Makes sense. It might have something to do with the retina screen and scaling too...

**Comment by lwouis** [comment] 2021-11-13 02:56
Closing as duplicate of #1062

**Closed by lwouis** 2021-11-13 02:56 UTC
Labels: bug, macOS 11
