### ISSUE TITLE
Having more than two shortcuts

### ISSUE THREAD

**Issue by daniel-zeng** [lwouis/alt-tab-macos#1458] opened 2022-03-31 07:42 UTC
Hello,

Currently, it seems that there's only two customizable shortcuts, and I've searched the Github issues but I don't seem to find anything to add additional shortcuts. 

Specifically, I wanted to have a way to have different types of release behavior, but using the two shortcuts for ("All Apps" and "Active App") for "Focus selected" takes up these two slots and I also wanted similar for the other option as well.

Thank you!

**Comment by PrayagS** [comment] 2022-04-08 13:37
+1 on this.

**Comment by GJRobert** [comment] 2022-04-10 02:59
I have also suggested in #1064

**Comment by lwouis** [comment] 2022-04-10 04:23
Closing as duplicate of #1064

**Closed by lwouis** 2022-04-10 04:23 UTC
Labels: enhancement
