### ISSUE TITLE
AltTab always shows tabs as separate window, when the window is hidden/minimized, on Monterey

### ISSUE THREAD

**Issue by jasondm007** [lwouis/alt-tab-macos#2017] opened 2022-10-13 18:11 UTC
**Describe the bug**

When the (1) "Show Standard tabs as windows" option is disabled in the Appearance options, and (2) the user has elected to show "Hidden windows" from the Control options, AltTab ignores the first option. In other words, it still shows standard tabs as windows. To be clear, this only occurs when the window is hidden. Otherwise, AltTab performs as expected, and only shows windows.

**Screenshots / video**

When the window isn't hidden, AltTab performs exactly as it should—displaying only the window. This is illustrated in the screenshot below using a Finder window with two tabs.

![Not Hidden](https://user-images.githubusercontent.com/14279767/195672549-45c7a58e-1227-4592-95fc-c939494aa36d.png)

However, once you hide the window, AltTab will now show both of Finder's tabs as windows—effectively ignoring the disabled option to "Show Standard tabs as windows".

![When Hidden copy](https://user-images.githubusercontent.com/14279767/195673467-266dc1bf-1850-4994-88ff-18bb10c42506.png)

**Steps to reproduce the bug**

1. Controls > Hidden windows > Show
2. Appearance > Show Standard tabs as windows > Uncheck/Disable
3. Minimize an app that uses standard tabs, like Finder, and then trigger AltTab. You'll notice that its tabs are being treated like windows.

**Comment by frypf** [comment] 2022-10-14 12:20
I've noticed this too, but only on Monterey.

**Comment by lwouis** [comment] 2022-10-14 18:49
Yes, I think Monterey broke our tab detection. I was able to reproduce with minimized and hidden windows. They show separately even with the preference unchecked.

I also noticed that if you check the preference, then bring a window with 2 tabs on another Space, then go back to the first Space, then AltTab to another tab of that window, it will teleport it on the current Space. It seems like a new macOS bug...

**Comment by decodism** [comment] 2022-10-14 20:20
This seems like it could do the trick on the latest OS:

```diff
+++ src/logic/Windows.swift
@@ -162,8 +162,8 @@
     static func detectTabbedWindows() {
-        let cgsWindowIds = Spaces.windowsInSpaces(Spaces.idsAndIndexes.map { $0.0 }, [])
+        let cgsWindowIds = Spaces.windowsInSpaces(Spaces.idsAndIndexes.map { $0.0 }, [.minimizedAndTabbed /* or .minimized2 */])
         list.forEach {
             if let cgWindowId = $0.cgWindowId {
-                $0.isTabbed = !$0.isMinimized && !$0.isHidden && !cgsWindowIds.contains(cgWindowId)
+                $0.isTabbed = !cgsWindowIds.contains(cgWindowId)
             }
         }
     }

+++ src/logic/Spaces.swift
@@ -70,5 +70,5 @@
     static func windowsInSpaces(_ spaceIds: [CGSSpaceID], _ options: CGSCopyWindowsOptions) -> [CGWindowID] {
         var set_tags = ([] as CGSCopyWindowsTags).rawValue
         var clear_tags = ([] as CGSCopyWindowsTags).rawValue
-        return CGSCopyWindowsWithOptionsAndTags(cgsMainConnectionId, 0, spaceIds as CFArray, 2, &set_tags, &clear_tags) as! [CGWindowID]
+        return CGSCopyWindowsWithOptionsAndTags(cgsMainConnectionId, 0, spaceIds as CFArray, options.rawValue, &set_tags, &clear_tags) as! [CGWindowID]
     }
```

or:

```diff
+++ src/logic/Windows.swift
@@ -162,8 +162,7 @@
     static func detectTabbedWindows() {
-        let cgsWindowIds = Spaces.windowsInSpaces(Spaces.idsAndIndexes.map { $0.0 }, [])
         list.forEach {
             if let cgWindowId = $0.cgWindowId {
-                $0.isTabbed = !$0.isMinimized && !$0.isHidden && !cgsWindowIds.contains(cgWindowId)
+                $0.isTabbed = cgWindowId.spaces().count == 0
             }
         }
     }
```

@lwouis

> I also noticed that if you check the preference, then bring a window with 2 tabs on another Space, then go back to the first Space, then AltTab to another tab of that window, it will teleport it on the current Space. It seems like a new macOS bug...

Is it different from the comment below?

```diff
+++ src/logic/Window.swift
@@ -200,4 +200,4 @@
     func updatesWindowSpace() {
         // macOS bug: if you tab a window, then move the tab group to another space, other tabs from the tab group will stay on the current space
         // you can use the Dock to focus one of the other tabs and it will teleport that tab in the current space, proving that it's a macOS bug
         // note: for some reason, it behaves differently if you minimize the tab group after moving it to another space
```

**Comment by lwouis** [comment] 2022-10-14 20:33
> This seems like it could do the trick on the latest OS:

Thank you for sharing this. I need to test it carefully now.

> Is it different from the comment below?

You're totally right. It's the same bug I re-"discovered" today I guess. You're very good with the codebase!

**Comment by lwouis** [comment] 2022-10-31 16:53
Could you guys please test out [this build](https://github.com/lwouis/alt-tab-macos/files/9903176/AltTab.app.zip)? It seems to fix tabs issues on my machine

**Comment by jasondm007** [comment] 2022-10-31 17:48
Hi @lwouis - Thanks for working on this issue! I really appreciate it. 

Unfortunately, the build didn't solve the problem on my end. But perhaps others will have more luck?

Using the build, I'm still seeing minimized tabs, as windows (when testing with Finder using Monterey 12.6.1). Except now I'm also seeing its tabs, as windows, when they're not minimized, too.

PS - When I reverted back to 6.48, however, the problem went back to just impacting minimized windows/tabs.

**Comment by frypf** [comment] 2022-10-31 18:06
Still on Monterey 12.5.1 here and it's working as intended for me.

**Comment by lwouis** [comment] 2022-10-31 20:51
@jasondm007 I can't reproduce the issue. Could you please share a video with that build and showcase the exact steps you take?

**Comment by jasondm007** [comment] 2022-10-31 23:19
@lwouis I'm not sure if this is what you're looking for, but after reinstalling that build, and restarting my computer, I created a video for you detailing everything. 

The video starts by showing the relevant Alt-Tab preferences, and then it illustrates the behavior using a Finder window with three open tabs. As you'll see in the video, each tab is treated like a window whether or not it's minimized. 

To be clear, however, when I revert back to 6.48, the problem only occurs when the window is minimized (i.e., tabs are not treated like windows, unless they're minimized).

Hope this helps clarify things. Thanks again!

https://user-images.githubusercontent.com/14279767/199127470-6d1aa82f-9a7b-441b-9bd8-1af738de475c.mp4

**Comment by lwouis** [comment] 2022-11-01 10:23
Thank you @jasondm007 for the video. I'm missing the steps prior: how did you create the Finder window with 3 tabs, and when did you launch AltTab (before or after setting the 3-tabs Finder window?).

Furthermore, what happens from the point at the end of the video, if you restart AltTab?

Also, do you use multiple monitors? And do you have multiple Spaces?

**Comment by frypf** [comment] 2022-11-01 14:43
Actually after testing a bit further, I've realised that after restarting AltTab while a multi-tabbed Finder window was already minimised, I'm now experiencing the same behaviour as in @jasondm007's video. I restarted AltTab again with the window de-minimized, which at first appeared to fix the behaviour. But then every time I focus another tab within the Finder window, it shows again as a separate window within the list. I've tried various different combos of relaunching AltTab / Finder / the whole computer since, but always the same result.

Also, I have `Minimized windows: Show at the end` set and I've noticed that directly after minimising the window, it does appear in the correct position within AltTab's switcher window, but is always highlighted/focused next (instead of whatever is second in the list).

**Comment by lwouis** [comment] 2022-11-01 17:13
@jasondm007 @frypf I can't reproduce your scenarios on my machine (M2, Ventura). When I launch AltTab before or after I make a 3-tabs Finder window, AltTab always shows 1 window. If I move to other tabs, it shows that 1 tab correctly.

What I can reproduce is when the window is hidden or minimized, then I see all tabs as separate windows.

I'm not sure what I can do here. I'll try to set up a VM with Monterey to test it out there. Tab detection has been a nightmare for years now. I know [other window management projects as well](https://github.com/koekeishiya/yabai/issues/199#issuecomment-519152388).

**Comment by frypf** [comment] 2022-11-01 17:30
12.5.1 / M1 here. I didn't have any issue until I quit & relaunched AltTab while my Finder window was minimised, but nothing I've tried since has managed to revert the behaviour back to normal.

**Comment by jasondm007** [comment] 2022-11-01 18:28
> When I launch AltTab before or after I make a 3-tabs Finder window, AltTab always shows 1 window. If I move to other tabs, it shows that 1 tab correctly.
> 
> What I can reproduce is when the window is hidden or minimized, then I see all tabs as separate windows. 

Yes - this is exactly how 6.48 performs on my computer. Tabs are only errantly shown as windows when minimized, but are otherwise displayed correctly when they are not minimized.

When using your test build from above, however, _all_ tabs were always treated as windows.

> Which exact version of macOS are you running?

12.6.1 / Intel
MacBook Air (13-inch, Early 2015)
2.2 GHz Dual-Core Intel Core i7

**Comment by lwouis** [comment] 2022-11-01 21:58
I moved from an Intel to an M2 macbook. I used to have nice VMs to test retro-compat of AltTab all the way down to macOS 10.12. Now on Apple Silicon, I can't virtualize anything. In theory I could have a Monterey VM at best. In practice, I tried Parallels, Virtual Buddy, and UTM, and I only get a black screen when trying to boot Monterey.

It's a big issue going forwards, how I should work on AltTab, and QA changes, if I can't test on previous OS myself. Sharing this here so you know the situation.

**Comment by frypf** [comment] 2022-11-18 10:08
Hi @lwouis, I hadn't realised you'd be rolling this change out with 6.50 given your last comment about being unable to QA the change or reproduce the issue. I've just updated (to 6.51) but had to roll back to 6.49 as I'm experiencing
> all tabs were always treated as windows

again - on both my Monterey and Mojave machines. Any chance of reverting to the old tabs logic for pre-Ventura installations please? At least then the tabs are only shown separately when the window is minimised, which is infinitely more usable than the current behaviour. I'm guessing this could be also be related to #2136.

**Comment by frypf** [comment] 2022-11-18 10:36
Actually I just did some quick version testing, as I distinctly remember the issue as reported in the title was never originally a problem on Mojave, only Monterey.

Monterey seems to have always had the problem with showing minimised tabs as windows regardless of AltTab's version. However on Mojave, the behaviour changed with 6.39.1 - prior to this there was no issue with tabs detection for minimised windows, then from 6.39.1 > 6.49 it's showed minimised tabs as windows. 6.50 > 6.51 are showing tabs as windows regardless of minimised/hidden status.

**Comment by lwouis** [comment] 2022-11-18 10:59
Hi @frypf,

I don't know how to handle this to be honest. I've writen about [the limitations I have](https://github.com/lwouis/alt-tab-macos/issues/2017#issuecomment-1299277033) above, in regards to being able to dev/test these scenarios.

I could make some kind of blind change that does different behavior for different macOS versions, but that would be:

* Blind work. I can't test it. I have to trust you entirely, and make a theoritical fix based on your version-specific statements above
* Creating complexity in the codebase. Today we have very few version flag. We have kept code mostly the same for all macOS versions.

I'm not sure what I can do here, since I don't have access to older macOS version now.

**Comment by frypf** [comment] 2022-11-18 11:45
I appreciate your frustrations, I know Apple have never made migrating software between OS versions particularly easy - even more so given the move to their own chips and when you're using private / undocumented APIs. I hadn't actually noticed the change I mentioned for Mojave at all until today, which shows how often I minimise a tabbed window. That being said, from my own point of view I can cope pretty easily with minimised/hidden tabs showing as windows, whereas this new behaviour just completely overpopulates the AltTab switcher and makes using it overall a pretty frustrating experience.

I know you're reticent to start adding version flags, but given that the code changes for 0965a78d469ef04113726f756d00e72757eafcfe seem fairly minimal, I'd be really appreciative if it was possible to do so in this instance at least. As far as Mojave is concerned, I'm happy enough living with the behaviour being the same as Monterey as it has been post-6.39.1, rather than adding yet another flag. The fact that there are so few issues reported previously regarding this problem is perhaps testament to how few people are experiencing / noticing it, albeit the fact that #2136 has been added so recently maybe shows that the new behaviour is likely to be more obvious.

I can fully understand that this may just start a slow drip of further complexity down the line. My only other option is to stay with 6.49 for now and hope that there's no further must-have features added in the future, but obviously this further reduces your own test-base for new features and fixes on older versions given the issues with doing so on M2/Ventura you mentioned above. I'm only one voice among many who seem keen enough to do such testing and reporting on issues more generally though, and I notice for instance that yabai has recently made the move to stop supporting older OS versions. I really appreciate that you've kept struggling against the tide to provide support for older OS versions, and none of these decisions are easy!

**Comment by lwouis** [comment] 2022-11-18 12:01
>  I really appreciate that you've kept struggling against the tide to provide support for older OS versions, and none of these decisions are easy!

If I can, I will never stop caring about older macOS versions. The deciding factor here may be that I'm no longer able to experience those versions. I didn't realize this when moving to an M2, and now I find myself a bit trapped as there is essentially no support for any older OS on the machine. I won't buy another Intel macbook just to test AltTab. It feels like I'm at a deadend :/

**Comment by frypf** [comment] 2022-11-18 12:50
> I won't buy another Intel macbook just to test AltTab.

I'm curious if this is from the point of view of the practicality of running a separate machine, or cost (if it's not too impertinent to ask!? - apologies if so). I know you've always had an altruistic vision for AltTab, but there are _many_ issues you've closed asking about setting up a means of donating for all the time you spend finessing it. Would you maybe reconsider this if working specifically towards a modest goal of purchasing a secondhand Intel machine for testing purposes? Just an idea - I'm also aware you're looking to pass the baton to someone else for continued development going forward. I'd guess that for me at least, AltTab is objectively the app I use most often day-to-day. It just works so well in the background that I never even have to think about it most of the time.

I wish I was better with Swift / programming in general so that I could actually help drill down into the meat of some of the issues, but my coding experience is very much limited to cludging together little ad-hoc CLI tools to solve issues that no-one else seems to have. Even then, as I've now switched to an M1 Macbook for my main machine, I'd still experience the same issues as you do with regard to easily testing for Intel and older OS versions. I only keep my Mojave machine going to run a few bits of old 32-bit software that will never be updated - and even on a consumer-level that's something I'm finding increasingly difficult going forward. So much for the supposedly seamless transition over to Apple Silicon 🤷‍♂️.

**Comment by lwouis** [comment] 2022-11-18 21:41
> I'm curious if this is from the point of view of the practicality of running a separate machine, or cost
> I'm also aware you're looking to pass the baton

It's the fact that I don't want to invest myself that much (buying a second computer just to work on this project) + the cost + the environmental symbolism of having a second computer (reminds me of households with 2 cars). The feeling I get from #1324 is also demotivating. It's a mix of things. I also think about the future, and get sad at what the IPCC is telling us that future will be like. I don't think we'll be discussing AltTab on Github in 20 years. I think we will have more necessary things to worry about.

This project is pretty symbolic to me of the end of my innocence. Barely a few years ago, I used to think humanity was going to go more complex, with more technology, that I could make a wonderful career in tech having fun with these abstract puzzles. Now I look at [all the science](https://photos.app.goo.gl/9jyMJ8ksyyR8kNvR9), and I've buried that dream. I'm currently working on a more realistic dream involving living in a small town, of some craftmanship.

I realize this answer goes a bit further than was probably expected. Sorry about that.

Regarding this specific issue, maybe I could use [some Cloud](https://checkout.macincloud.com/) rental for a few hours to try out a build with version-specific branches. Maybe I could just build it based on what you wrote above, and you could test it? Maybe it's enough, and better than status-quo on Monterey/Mojave if we add the special cases.

**Comment by frypf** [comment] 2022-11-19 13:23
> I realize this answer goes a bit further than was probably expected. Sorry about that.

No need to apologise - it's interesting to hear the specific motivations behind the project, even if said motivation has understandably taken a dent over the past few years. I only wish I could disagree with you. Either way, your efforts to support old OS versions are admirable and speak to my own frustrations with obsolescence and the rarely considered knowledge / monetary / environmental tradeoffs of relentless progress.

> Regarding this specific issue

I'm always happy to test out any builds although obviously as you've found, everyone seems to use AltTab differently, and even with regular day-to-day use a problem may only present itself under some pretty esoteric circumstances. As the tab detection problem as originally posted has moved on slightly, is it worth bringing in #2136 to add some additional viewpoints?

**Comment by probablykasper** [comment] 2023-01-04 05:32
I'm a bit confused about this issue. Is there some bugfix in v6.50 that can't be rolled back?

For me as well v6.49 works great, except minimized/hidden windows (x64 macOS Catalina)

**Comment by lwouis** [comment] 2023-01-04 07:46
@probablykasper the complexity here is that we need different internal implementations for the various macOS versions, because Apple has changed their undocumented APIs in very subtle ways with the last 2 releases. So we need 3 implementations, and i'm no longer able to test them to develop them because on my new macbook, I can no longer run my collection of VMs i was using to test the app on various macOS versions.

**Comment by probablykasper** [comment] 2023-01-04 09:22
I see, thanks for explaining

**Closed** 2023-07-12 19:25 UTC
Labels: bug, macOS 12

**Comment by frypf** [comment] 2023-07-14 08:40
Just noticed this in the changelog so I've finally updated from 6.49. Wanted to follow up and say thanks for implementing - seems to have fixed tab detection for unminimized / unhidden apps, which works for my workflow 👍.

**Comment by lwouis** [comment] 2023-07-14 10:21
I'm glad it helped! All the credit goes to @decodism's great work 🙇‍♂️

**Comment by jasondm007** [comment] 2023-07-18 16:44
Yeah, this is great! Thanks a ton, @lwouis & @decodism!!
