### ISSUE TITLE
PhpStorm weird windows in switcher

### ISSUE THREAD

**Issue by ibrahimabdo** [lwouis/alt-tab-macos#660] opened 2020-10-22 08:40 UTC
**Describe the bug**
After the last update of AltTab, I am starting to get weird windows in switcher when I press Alt + Tab while using PhpStorm 2020.3. 

I think it could be related to #652

**Screenshots / video**
https://a.cl.ly/qGuv7Eeb

**Comment by lwouis** [comment] 2020-10-22 11:51
Hi @ibrahimabdo! I see that you are using the EAP. The EAP indeed has some unique problems that the stable release doesn't. You mentioned #652. In that ticket I did a change so that AltTab ignores one of the accessibility notification from EAP products from Jetbrains. This notification is used to detect if a window becomes tabbed into another window. Jetbrains products don't use native AppKit tabs in the first place, so it's safe to not get this notification.

What I'm saying is, yes it is related to #652 because this ticket was also about an issue in an EAP product. However, the issue is quite different, and I don't think the [recent code change](https://github.com/lwouis/alt-tab-macos/commit/7c171c26cb8dc865b8a076cc35930093602bba60#diff-45acb5e8fb8c3382ebc34954179b288dd6f23b96745d43c3c6c519f729ac2527R28) can be responsible for new windows appearing.

I think the issue you're facing is exactly the same as https://github.com/lwouis/alt-tab-macos/issues/562 so I will close this ticket as a duplicate. Maybe you could ask @mfn if they are seeing the issue these days. Last time we discussed it, they said the issue is gone now, but you seem to be facing it still.

Another thing to consider is the broader story of #456. I'm still looking for someone to help me devise a better heuristic to avoid showing things that are not windows.

**Closed by lwouis** 2020-10-22 11:51 UTC
Labels: bug

**Comment by mfn** [comment] 2020-10-22 19:48
After #652 was fixed, I did not notice further or other anomalies but yes, #562 _sometimes_ occurs for me, but _very rarely_. And also did before the EAP and I saw it once since the EAP.
