### ISSUE TITLE
The windows of Adobe Arobat (2021.001.20145) windows often not shown on alt-tab

### ISSUE THREAD

**Issue by whlinaa** [lwouis/alt-tab-macos#887] opened 2021-03-29 11:08 UTC
**Describe the bug**

The windows of Adobe Arobat (2021.001.20145) windows often not shown on alt-tab

**Screenshots / video**

![image](https://user-images.githubusercontent.com/59403078/112828244-0bbe2d00-90c2-11eb-826d-53581c20cb8a.png)

**Steps to reproduce the bug**

1. Open Adobe Arobat
2. Sometimes the window of Adobe Arobat will be shown, but not always. Also, multiple windows of Adobe Arobat are often not shown.

**Comment by lwouis** [comment] 2021-04-08 14:49
I can't reproduce the issue. Could you help me figure out clear steps to reproduce the issue?

There is a very similar ticket already here: https://github.com/lwouis/alt-tab-macos/issues/851

I'll close this ticket as a duplicate. Let's keep the conversation going in the other ticket, and let's try to figure out what's happening, and fix the issue.

**Closed by lwouis** 2021-04-08 14:49 UTC
Labels: bug
