### ISSUE TITLE
More color customization

### ISSUE THREAD

**Issue by nguyenhimself** [lwouis/alt-tab-macos#118] opened 2020-01-19 17:31 UTC
This is almost perfect for my need *except* for one thing: The dark-gray-on-light-gray colorscheme means that sometimes it can be a bit hard to quickly see which thumbnail is being activated.

Especially now that macOS has dark mode, so most of the times it's "dark grey on a dark app window on slightly-lighter gray background"

If a colorscheme customization tab is too much, maybe just another theme where the activating background is the familiar macOS blue (you know the one).

Thanks!

**Comment by lwouis** [comment] 2020-01-20 03:16
Hi @nguyenhimself! Thank you for sharing this.

This is kind of a duplicate of #82 . I will close yours here in favor of the other ticket since it had already some interesting discussion about what could be done. Also it contain pointers from me for anyone that would like to implement it. Basically it can be done in 1h. Very easy to add a new theme to the app! :)

**Closed by lwouis** 2020-01-20 03:16 UTC
Labels: duplicate
