### ISSUE TITLE
Alttab is sharing your screen

### ISSUE THREAD

**Issue by borisborat** [lwouis/alt-tab-macos#2600] opened 2023-06-22 01:51 UTC
I have this Alert. Alttab is sharing your screen

<img width="595" alt="SCR-20230621-qlpe-2" src="https://github.com/lwouis/alt-tab-macos/assets/19535366/3a657cf1-e783-4db5-b0b0-b76ff322b2ab">

* AltTab version: Version 6.59.0
* macOS version: 14.0 Beta (23A5276g) Sonoma

**Comment by Bentheminernz** [comment] 2023-06-22 02:05
<img width="1440" alt="Screenshot 2023-06-22 at 2 05 18 PM" src="https://github.com/lwouis/alt-tab-macos/assets/65065992/e028842f-6451-46af-8c5c-4cfdc8050144">
Same here! AltTab: Version 6.59.0
macOS: 14.0 dev beta 2 Sonoma

**Comment by jessedelira** [comment] 2023-06-22 02:22
Yup, this and the deprecated api message seem to be happening because of the Sonoma beta release.

**Comment by lwouis** [comment] 2023-06-22 06:16
Closing this ticket for now. We can review issues once it goes live 👍

**Closed by lwouis** 2023-06-22 06:16 UTC
Labels: bug

**Comment by scottaw66** [comment] 2023-09-20 06:53
It's live and it's definitely still happening

**Comment by peeranat-dan** [comment] 2023-09-27 01:44
I also got the message "Alt tab is capturing your screen" too.
Here's a screenshot. It's from the topbar in the stable macos sonoma.

<img width="303" alt="image" src="https://github.com/lwouis/alt-tab-macos/assets/85337926/d0c58bc8-fd55-471e-b790-e296e048188c">

**Comment by benmotyka** [comment] 2023-09-27 06:20
Just updated to Sonoma, I confirm this issue exists

**Comment by justinsijbolts** [comment] 2023-09-27 06:49
> Just updated to Sonoma, I confirm this issue exists

Same here

**Comment by leobartowski** [comment] 2023-09-27 08:36
Same here

**Comment by dagema1** [comment] 2023-09-27 08:38
yeah it only appears for like 14 seconds after altTabing

**Comment by Jonomir** [comment] 2023-09-27 11:24
Same here, really annoying.
Do you think there is something you can do about this @lwouis ? :)

**Comment by Duc-NSH** [comment] 2023-09-27 11:44
just updated the Sonoma, and have the same issue, it disappears after about 10 seconds but really annoying

**Comment by dfinley** [comment] 2023-09-27 16:24
I too can confirm that this is occurring.  It happens every so often without using alttab and everytime that I use alttab the screen sharing icon appears.

**Comment by bacqueyrisses** [comment] 2023-09-27 21:22
Same here, any way to tweak the alert in the mac settings ?

**Comment by Astimus** [comment] 2023-09-28 15:48
Just updated to Sonoma and issue exists

**Comment by tbr** [comment] 2023-09-29 07:35
It's a security feature of Sonoma. All apps that capture screen will trigger this. Same happens for audio (microphone). I suppose there is no way to "work around" as it is working as designed by Apple.

One way would be have the (user) option to have Alttab working without capturing the window contents (and just show icons and window titles/names or something)?

**Comment by DanielDimitrov5** [comment] 2023-09-29 10:00
Same issue here

**Comment by od45pv** [comment] 2023-09-29 10:07
Same issue here

**Comment by bacqueyrisses** [comment] 2023-09-29 10:09
You can disable alt-tab window preview so it's not triggered.

**Comment by dgh06175** [comment] 2023-10-01 23:58
same issues here. sonoma updated

**Comment by schoesa** [comment] 2023-10-05 08:30
> You can disable alt-tab window preview so it's not triggered.

How?

**Comment by benmotyka** [comment] 2023-10-05 08:34
> > You can disable alt-tab window preview so it's not triggered.
> 
> How?

AltTab -> Preferences -> Appearance -> Tick "Hide window thumbnails" on

However, I noticed that with Sonoma update, there's no need to use AltTab: all of the programs show up correctly when I use command+tab

**Comment by dgh06175** [comment] 2023-10-05 09:53
> > > You can disable alt-tab window preview so it's not triggered.
> > 
> > 
> > How?
> 
> AltTab -> Preferences -> Appearance -> Tick "Hide window thumbnails" on
> 
> However, I noticed that with Sonoma update, there's no need to use AltTab: all of the programs show up correctly when I use command+tab

Solved. thank you

**Comment by schoesa** [comment] 2023-10-05 18:05
> Still here, and I want to keep the window preview option :D

You are right @StephaneJuban, this did not solve the problem. The preview window is one reason why I use AltTab.

**Comment by lutel** [comment] 2023-10-09 07:05
Could you reach out to Apple to work on how to solve this issue? This is the one thing which prevents me to update to Sonoma.

**Comment by tbr** [comment] 2023-10-09 07:33
> Could you reach out to Apple to work on how to solve this issue? This is the one thing which prevents me to update to Sonoma. Could you reopen this issue?

It blocks you to update because of an icon showing in the menu bar? This issue is about Alttab, not about MacOS. The icon is a privacy feature, I understand it is annoying, but get used to it or don't update/find another way. Alttab cannot fix this.

I personally disable the preview and just use alttab without the rendered thumbnails...

**Comment by c-daniele** [comment] 2024-06-07 06:54
Why is the application needing screen capturing for Alt-Tabbing? It looks to me a little bit unsafe

**Comment by metuuu** [comment] 2024-06-07 07:04
> Why is the application needing screen capturing for Alt-Tabbing? It looks to me a little bit unsafe

I believe it's for window thumbnails. But it seems to capture the screen even though "Hide window thumbnails" setting is set to true.

**Comment by lwouis** [comment] 2024-06-07 07:16
The purple screen capture UI is shown when AltTab calls an a system API to get window thumbnails and window titles. Please see #1082 for more details.
