### ISSUE TITLE
Spark email windows are not recognized by AltTab

### ISSUE THREAD

**Issue by shockey** [lwouis/alt-tab-macos#873] opened 2021-03-21 19:33 UTC
**Describe the bug**

[Spark](https://sparkmailapp.com) windows don't appear in the window switcher on Big Sur 11.0.1 (20B50) with AltTab 6.18.1.

**Screenshots / video**

Screencast [here](https://recordit.co/nL0mXt8Uj7). I've shown the main app window as an example, but other windows (e.g. email compose) have the same issue.

**Steps to reproduce the bug**

1. Open a Spark window
2. Cue AltTab (I use Cmd+Tab), whether Spark is a focused window or now
3. Observe that the Spark window is not detected by AltTab

## Related issues

- https://github.com/lwouis/alt-tab-macos/issues/698 is very similar.

**Comment by lwouis** [comment] 2021-03-22 00:58
Hi @shockey!

Have you contacted Spark for support? If not, i suggest you do, as the issue is likely on their side.

**Comment by lwouis** [comment] 2021-04-21 15:07
Hi @shockey, any update?

**Comment by lwouis** [comment] 2022-04-28 17:37
No reply. Closing

**Closed** 2022-04-28 17:37 UTC
Labels: bug, macOS 11

**Comment by CeleritasCelery** [comment] 2022-05-19 21:35
I am seeing this issue on Monterey 12.3.1 and AltTab 6.37.1. When I contact Spark support, what should I tell them (since spark works fine with the stock app switcher)?

**Comment by lwouis** [comment] 2022-05-20 00:45
@CeleritasCelery maybe you're seeing #1324? If not then it's on Spark side indeed.

you can tell them that accessibility apps are broken with their app. You say it works fine with the default app switcher but that switcher doesn't work at window level. Also it has access to internal APIs AltTab doesn't.

If AltTab can't see Spark windows then other accessibility apps (screen readers for blind people for example) can't either.
