### ISSUE TITLE
Apparition delay bug

### ISSUE THREAD

**Issue by johanan-daniel** [lwouis/alt-tab-macos#604] opened 2020-09-13 15:03 UTC
**Apparition delay bug**

When an "Apparition delay" is set that is longer than how fast it takes the user to 'alt + tab' (for me more than 50 ms), the AltTab window stays on the screen even after the keys are let go. 

**Zipped video recording**

[Apparition delay bug recording.mov.zip](https://github.com/lwouis/alt-tab-macos/files/5214361/Apparition.delay.bug.recording.mov.zip)

**Recreating the issue**

1. Set "Apparition delay" to a value faster than you can press (try 200 ms). 
2. When the 'alt + tab' combination is hit fast enough, the AltTab window stays after keys are released (first half of video).
3. When the same combination is held down longer than the set delay, the AltTab window disappears after keys are released (as expected, shown in second half of video).

**Comment by johanan-daniel** [comment] 2020-09-16 14:32
From my limited testing, when I set it to a value longer than it takes me to press the keys, it seems to work as expected!

**Comment by Cnly** [comment] 2020-09-17 03:22
On 6.6.0, alt-<kbd>tab</kbd> works as expected for me and the window goes away when the keys are pressed fast. But alt-<kbd>`</kbd> doesn't. Is this also the same bug?

**Comment by lwouis** [comment] 2020-09-17 10:40
I'm not sure @Cnly. Could you please try out the build in my message above, and tell us if that issue is fix in the build? If yes, then your issue will be gone in the next release 👍

**Comment by Cnly** [comment] 2020-09-17 11:39
@lwouis Just tested. Can confirm the bug is gone. Thanks!

**Comment by lwouis** [comment] 2020-09-25 10:30
The [new release 6.7.0](https://github.com/lwouis/alt-tab-macos/releases/download/v6.7.0/AltTab-6.7.0.zip) should fix this issue. Closing this ticket. Let me know if the issue is not gone and I'll re-open it 👍

**Closed by lwouis** 2020-09-25 10:30 UTC
Labels: bug
