### ISSUE TITLE
Window max/min width in a row: provide alternative for ultrawide monitors

### ISSUE THREAD

**Issue by singalen** [lwouis/alt-tab-macos#1506] opened 2022-04-20 17:12 UTC
**Is your feature suggestion related to a problem? Please describe.**
I have an ultrawide monitor that I use on and off.
The switcher either too big on one of them, or too small on the other.

**Describe the solution you'd like**
Maybe an alternative way to specify a window size would help? In pixels or points, or somehow else taking screen DPI into account? Maybe take screen height into account too?

**Describe alternatives you've considered**
Only manually changing the settings each time I disconnect/reconnect the monitor.

**Comment by lwouis** [comment] 2022-04-28 15:04
I'm a bit confused with the premise. If you have a very wide monitor, that's in order to make use of this space, right? So I'm surprised you don't want AltTab to expand and make use of it? I imagine if you play a movie or a game you set it up to fill the screen, no?

Could you maybe clarify what the problem is? Screenshots would help illustrate I think

**Comment by lwouis** [comment] 2023-01-16 21:13
Yes, the answer is most likely either per-screen configuration (fancy) and/or pixel max-size (easy/practical). There is already a ticket for fixed-sized: https://github.com/lwouis/alt-tab-macos/issues/1107

Closing as duplicate

**Closed by lwouis** 2023-01-16 21:13 UTC
Labels: enhancement, unclear
