### ISSUE TITLE
Windows 10 like 3 finger swipe to switch app using trackpad.

### ISSUE THREAD

**Issue by behlharsh4** [lwouis/alt-tab-macos#1176] opened 2021-10-18 06:37 UTC
In windows 10 it very simple and easy to open app switcher and navigate through it using just 3 finger left swipe. If that could be implimented here will be a great addition as I do not like to press keyboard button to switch betweeen the apps.

**Comment by lwouis** [comment] 2021-10-18 23:10
Duplicate of #756

**Closed by lwouis** 2021-10-18 23:10 UTC
Labels: enhancement
