### ISSUE TITLE
How do you get the domain/package name of an application for a blacklist?

### ISSUE THREAD

**Issue by Luckey-Elijah** [lwouis/alt-tab-macos#912] opened 2021-04-13 13:16 UTC
Simply, could you provide an example of how to get the package name (or reverse domain?) of an application in order to add it to the black list?

Would it be a command or something of the sort?

Possibly add this to docs as well, if there is a way to get it.

**Comment by meiser79** [comment] 2021-04-14 08:24
duplicate of #858

**Closed** 2021-04-14 08:57 UTC
Labels: duplicate
