### ISSUE TITLE
Windows 10 - Parallels Desktop - Same application windows

### ISSUE THREAD

**Issue by Yunustuzun** [lwouis/alt-tab-macos#1067] opened 2021-08-05 19:06 UTC
Hello, 
I am using Parallels Desktop - Windows 10 in coherence mode. When I try to switch between the same applications. Sometimes It doesn't reflect. 
Could you help, please? 

Below is the video, when I tried to switch between Document1 ( Office Word Application ) to Document2. Sometimes It doesn't change.

https://drive.google.com/file/d/1_OvKqr45YEGKjBeqO2WhnByzxL6savr6/view?usp=sharing

**Comment by lwouis** [comment] 2021-08-06 03:21
Hi @Yunustuzun,

The issue happens only between windows of the same Windows app? It doesn't happen if the windows are from different Windows apps?

**Comment by Yunustuzun** [comment] 2021-08-07 08:53
Hi @lwouis , 

Of course, It only happens in between the same apps.

**Comment by lwouis** [comment] 2021-08-10 06:39
I was not able to reproduce the issue with 2 Notepad documents. I'm wondering if the issue is not with "2 windows of the same apps" but rather an issue with Word itself.

Could you please try to reproduce with a free app bundled with Windows 10? That way I can reproduce on my VM which doesn't have Word? Thank you

**Comment by lwouis** [comment] 2021-08-29 08:29
I was able to reproduce once today. I can't get consistent steps though. It seems random and rare.

**Comment by Yunustuzun** [comment] 2021-09-04 21:23
> I was able to reproduce once today using the Photos app. I can't get consistent steps though. It seems random and rare.

Of course, it is random. But when you are all-time using the same applications and switch between them. It happens not rarely. Do you have any idea about the problem? And how we can solve this problem? Thanks for your contribution.

**Comment by lwouis** [comment] 2022-04-29 15:19
It may be fixed in recent versions? In any case, this seems to be unactionable at the moment. Please let me know if it's still an issue. We need more data like a way to reproduce consistently. Also if it's only happening with Parallels Desktop, you should contact them as it seems to indicate the issue is with their software, not AltTab

**Closed by lwouis** 2022-04-29 15:19 UTC
Labels: bug, unreproducible
