### ISSUE TITLE
Chrome doesn't show as a window - intermittent.

### ISSUE THREAD

**Issue by 1Mark** [lwouis/alt-tab-macos#1574] opened 2022-05-13 20:44 UTC
When I press alt + tab, sometimes it doesn't show chrome. This issue is intermittent and closing alt tab and reopening fixes it but it's annoying.

![PXL_20220513_204153325.jpg](https://user-images.githubusercontent.com/15360245/168386668-3b4ec99b-dabe-4899-be01-e5504d64dd58.jpg)

I'm using v 6.36.1

**Comment by lwouis** [comment] 2022-05-14 02:47
Does it happen when you open Chrome during your session, or does it happen when you start the session and maybe Chrome is started automatically or maybe restored from the previous session?

**Comment by 1Mark** [comment] 2022-05-14 09:13
> Does it happen when you open Chrome during your session, or does it happen when you start the session and maybe Chrome is started automatically or maybe restored from the previous session?

I think it was when chrome was restored from a previous session but I have to retest. I never thought about it.

**Comment by lwouis** [comment] 2022-05-14 09:52
Ok then i think it's a duplicate of #1317

**Closed by lwouis** 2022-05-14 09:52 UTC
Labels: bug

**Comment by 1Mark** [comment] 2022-05-14 15:30
@lwouis just retested, had two tabs open then closed the window. Pressed CMD + SHIFT + T.
Alt-tab worked fine.

Tried with one tab again worked fine. This doesn't look related to the issue you tagged.

**Comment by lwouis** [comment] 2022-05-14 17:17
The ticket I shared above is a placeholder for me to close the constant flow of tickets like this one. Please see discussion from here: https://github.com/lwouis/alt-tab-macos/issues/447#issuecomment-1112805183 to understand the broader issue that's going on, if you're interested. In short, I know that some apps don't show, but it's titanic work to come out with a breakthrough new solution that *may* fix that. All because macOS doesn't have API to do what AltTab needs to do, so we have to workaround limitations constantly using private APIs and what not.
