### ISSUE TITLE
Doesn't work with IDEA Intellij

### ISSUE THREAD

**Issue by mugenishere** [lwouis/alt-tab-macos#1332] opened 2022-01-18 06:13 UTC
**Describe the bug**

I'm alt-tabbing using option+tab key. It works for all other windows except Intellij. If you have Intellij open (doesn't matter full screen or normal window) alt-tab will simply refuse to switch to Intellij.

Note: When you press hotkey for AltTab and hold, don't release it, it'll show you an overview of all windows that you can switch to. Use the mouse and scroll through all these windows. You'll notice that Intellij window is not present in this list. There's no way to switch to an Intellij window.

I'm using Intellij community edition 2021.3. 

**Screenshots / video**

I don't have a video currently because I need to blur a number of regions and that functionality isn't provided in any free video recorder.

**Steps to reproduce the bug**

1. Go to Intellij. Then use the AltTab shortcut (I'm using Option+Tab) to switch to any other window
2. Click on AltTab shortcut and hold  OR try to switch back to Intellij

Actual results:
There's no way to switch back to Intellij. This is very frustrating because you need to break the muscle memory and keep using the conventional mac switch (Command + tab) which works fine.

**Comment by PlanksShapesTrumpeters** [comment] 2022-01-18 09:17
I experience the same behaviour for PyCharm. Android Studio oddly enough, shows up as expected.

**Comment by lwouis** [comment] 2022-01-18 09:40
Duplicate of #1249

**Closed by lwouis** 2022-01-18 09:40 UTC
Labels: bug
