### ISSUE TITLE
Does not work when opened from .app

### ISSUE THREAD

**Issue by Janhouse** [lwouis/alt-tab-macos#25] opened 2019-10-15 10:23 UTC
Switching works fine when I open it from terminal `/Applications/alt-tab-macos.app/Contents/MacOS/alt-tab-macos` but it doesn't show the switching popup when I open the app from Finder or `open /Applications/alt-tab-macos.app/`
It runs in status bar and binds to ctlr + tab shortcut because I can not longer switch between Firefox tabs but nothing happens. I have given the app Accessibility permission.
Tested on latest macOS Catalina version.

**Comment by kristofferR** [comment] 2019-10-15 11:17
Same issue here.

**Comment by hdiass** [comment] 2019-10-15 11:40
Same here..

**Comment by lwouis** [comment] 2019-10-15 11:51
I don't know how I could investigate this. It doesn't happen on my machine.

Maybe one of you guys could share the system logs for the process, or maybe even run the project locally with XCode and see if it crashes or if you can print useful logs to understand where it gets stuck

**Comment by hdiass** [comment] 2019-10-15 11:52
Couldn't it be because i am on catalina already ?

lwouis <notifications@github.com> escreveu no dia terça, 15/10/2019 à(s)
12:51:

**Comment by lwouis** [comment] 2019-10-15 11:54
> Couldn't it be because i am on catalina already ?

It's possible. I can't test on Catalina for the moment though, so can't really investigate deeper on that hypothesis

**Comment by hdiass** [comment] 2019-10-15 11:55
I'll be waiting for the other reporters to check if it's a catalina issue.

lwouis <notifications@github.com> escreveu no dia terça, 15/10/2019 à(s) 12:54:

**Comment by jfdhuiz** [comment] 2019-10-15 12:01
Same issue (Catalina)

**Comment by jjr2527** [comment] 2019-10-15 14:02
Same issue (Catalina)

**Comment by russelldc** [comment] 2019-10-15 14:42
Same issue (also on Catalina)

**Comment by JeremyCottontail** [comment] 2019-10-16 06:02
Same issue (Catalina)

**Comment by lwouis** [comment] 2019-10-16 16:49
https://github.com/lwouis/alt-tab-macos/pull/33

**Comment by lwouis** [comment] 2019-10-17 10:45
It seems that the OP issue root cause was the new Screen Recording permission in Catalina. I'm closing this ticket as support for Catalina is tracked in ticket #29 which will likely be closed soon thanks to PR #33.

**Closed by lwouis** 2019-10-17 10:45 UTC
Labels: L size, bug, help wanted
