### ISSUE TITLE
Sporadic delay when being activated

### ISSUE THREAD

**Issue by jsh9** [lwouis/alt-tab-macos#845] opened 2021-02-26 09:32 UTC
**Describe the bug**

Sometimes I experience a slight delay (about 0.5 to 1 second) between pressing alt + tab and the windows grid showing up, but sometimes the is no perceptible delay.

**Steps to reproduce the bug**

I cannot predict exactly when this is happening.  I can only say that it happens roughly 30% of the time.

**Comment by lwouis** [comment] 2021-02-26 10:18
Duplicate of https://github.com/lwouis/alt-tab-macos/issues/563

**Closed by lwouis** 2021-02-26 10:18 UTC
Labels: bug
