### ISSUE TITLE
Live Previews

### ISSUE THREAD

**Issue by jozhtn** [lwouis/alt-tab-macos#2407] opened 2023-03-12 00:29 UTC
**_Is your feature suggestion related to a problem? Please describe._**
Kind of? In Windows 10/11, when you press alt + tab you get to see a live preview of the app while it's open, but in AltTab it only shows a static image. Would be a nice feature to have to make it more similar to what Windows offers. 

An example of this would be to press alt + tab on macOS while a youtube video is playing, you won't see the video playing in the preview, you'll just see a static image from when you pressed alt + tab. In Windows if you press alt + tab while a youtube video is playing, the video will continue to play in the alt + tab preview.

**_Describe the solution you'd like_**
I'm not sure if this is possible, or if there is some sort of restriction in macOS permissions, but this would be a great feature for people coming from Windows, like myself.

**_Describe alternatives you've considered_**
None, the app pretty much has everything the Windows alt + tab has except this.

**Comment by lwouis** [comment] 2023-03-12 01:50
Duplicate of #122

**Closed by lwouis** 2023-03-12 01:50 UTC
Labels: enhancement
