### ISSUE TITLE
iOS simulator does not appear in the switcher

### ISSUE THREAD

**Issue by mykolaharmash** [lwouis/alt-tab-macos#657] opened 2020-10-20 09:37 UTC
It's not possible to focus on iOS simulator windows using AltTab, they are not listed in the switcher. At the same time system's Cmd+Tab has them.

Please see the video:
https://cln.sh/bmv7t4

**Comment by lwouis** [comment] 2020-10-20 13:33
Hi @mykolaharmash! Thanks for sharing this issue!

I'm not able to reproduce it locally. See:

![image](https://user-images.githubusercontent.com/106195/96587830-cc72ff80-131d-11eb-926a-d23c87dd1573.png)

I notice that at the top of your simulator you have a different UI than me. I also notice that your windows have more rounded corners, so I assume that you're on Big Sur. Maybe that's the issue? Have you tried on another mac on Catalina? If you can it would be nice to have another data point to understand if it's indeed a Big Sur specific issue.

**Comment by mykolaharmash** [comment] 2020-10-21 07:44
Hi, thank you for the response. Turns out it's indeed a Big Sur issue, on Catalina simulator is in the switcher.

<img width="1439" alt="CleanShot 2020-10-21 at 09 38 36@2x" src="https://user-images.githubusercontent.com/793851/96688913-0118a280-1382-11eb-95e1-33926c733dce.png">

**Comment by lwouis** [comment] 2020-10-21 08:01
There are a few issues people have reported with Big Sur. Big Sur is not officially supported at the moment (see website or brew spec). Big Sur is in beta still and can change anytime.

My current plan is to wait until release, the run it in a VM and see how AltTab works there. I will then also work on fixing issues such as this one, if they are still present after the beta.

It would be great if you notified Apple about this regression also as it's the very goal of the beta programme 👍

**Comment by mykolaharmash** [comment] 2020-10-21 08:47
Thank you, makes sense completely, will report this to Apple.

As a side note, besides this minor issue, I did not have any problems with AltTab on Big Sur, thank you for the great app 👍

**Comment by net** [comment] 2022-04-11 03:45
Still an issue on 12.3.1. Does not happen consistently. Not yet sure what triggers it.

**Comment by lwouis** [comment] 2022-04-29 15:10
If it's not consistent it's the general issue of #1317 

I'll close this ticket as it's not actionable at the moment.

**Closed by lwouis** 2022-04-29 15:10 UTC
Labels: bug, unreproducible, macOS 11
